//! A data-access shim for a trace.
//!
//! Port of `ghidra.pcode.exec.trace.data.PcodeTraceDataAccess`.

use std::sync::Arc;

use crate::pcode::exec::trace::data::pcode_trace_property_access::PcodeTracePropertyAccess;
use crate::program::model::address::{Address, AddressRange, AddressSetView};
use crate::program::model::lang::language::Language;
use crate::trace::model::memory::trace_memory_state::TraceMemoryState;

/// A data-access shim for a trace.
///
/// See [`PcodeTraceAccess`](crate::pcode::exec::trace::data::PcodeTraceAccess).
pub trait PcodeTraceDataAccess: Send + Sync {
    /// Get the language of the associated platform.
    fn get_language(&self) -> Box<dyn Language>;

    /// Set the memory state of an address range.
    ///
    /// The state is set only for the destination snapshot. It is *not* effective for the
    /// indefinite future.
    fn set_state(&mut self, range: &AddressRange, state: TraceMemoryState);

    /// Get the composite state of an address range, using the snapshot's viewport.
    ///
    /// Typically, the viewport is at most 2 snapshots deep. When reading from a captured
    /// snapshot, the viewport includes only the source snapshot. When reading from a scratch
    /// snapshot (usually generated by emulation), the viewport includes that scratch snapshot
    /// and the original source snapshot. The [`TraceMemoryState::Known`] address set is the
    /// union of known address sets among all snapshots in the viewport. If all addresses in the
    /// given range are `Known`, then the composite state is known. Otherwise, the composite
    /// state is [`TraceMemoryState::Unknown`].
    fn get_viewport_state(&self, range: &AddressRange) -> TraceMemoryState;

    /// Compute the intersection of the given address set and the set of `Known` or `Error`
    /// memory.
    ///
    /// `use_full_spans` controls how to treat the viewport: `true` for ever known, `false` for
    /// known now.
    fn intersect_view_known(&self, view: &dyn AddressSetView, use_full_spans: bool) -> Box<dyn AddressSetView>;

    /// Write bytes into the trace.
    ///
    /// Each written byte is effective for future snapshots up to but excluding the next
    /// snapshot where another byte is written at the same address.
    ///
    /// Returns the number of bytes written.
    fn put_bytes(&mut self, start: &Address, buf: &[u8]) -> usize;

    /// Read bytes from the trace into `buf`.
    ///
    /// Returns the number of bytes read.
    fn get_bytes(&self, start: &Address, buf: &mut [u8]) -> usize;

    /// Translate the given emulator address to a host/overlay address.
    fn translate(&self, address: &Address) -> Address;

    /// Get a property-access shim for the named property.
    ///
    /// `T` is the type of the property's values. Java selects `T` via a runtime `Class<T>`
    /// argument; here the caller supplies it via turbofish/inference instead, so this method
    /// requires `Self: Sized` and is not available through `dyn PcodeTraceDataAccess`.
    fn get_property_access<T>(&self, name: &str) -> Box<dyn PcodeTracePropertyAccess<T>>
    where
        T: 'static,
        Self: Sized;
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::program::model::address::{AddressSet, AddressSpace, AddressSpaceType};
    use std::collections::HashMap;

    /// A minimal in-memory shim mirroring `AbstractPcodeTraceDataAccess`'s per-address byte
    /// storage and state tracking, enough to exercise the trait's default-free wiring.
    struct FakeDataAccess {
        space: Arc<AddressSpace>,
        bytes: HashMap<i64, u8>,
        states: HashMap<i64, TraceMemoryState>,
    }

    impl FakeDataAccess {
        fn new(space: Arc<AddressSpace>) -> Self {
            FakeDataAccess { space, bytes: HashMap::new(), states: HashMap::new() }
        }
    }

    impl PcodeTraceDataAccess for FakeDataAccess {
        fn get_language(&self) -> Box<dyn Language> {
            unimplemented!("not exercised by these tests")
        }

        fn set_state(&mut self, range: &AddressRange, state: TraceMemoryState) {
            for addr in range.addresses() {
                self.states.insert(addr.offset(), state);
            }
        }

        fn get_viewport_state(&self, range: &AddressRange) -> TraceMemoryState {
            // Mirrors Java: composite state is Known only if every address in the range is
            // Known; otherwise Unknown.
            let all_known = range
                .addresses()
                .all(|addr| self.states.get(&addr.offset()) == Some(&TraceMemoryState::Known));
            if all_known {
                TraceMemoryState::Known
            } else {
                TraceMemoryState::Unknown
            }
        }

        fn intersect_view_known(
            &self,
            view: &dyn AddressSetView,
            _use_full_spans: bool,
        ) -> Box<dyn AddressSetView> {
            let mut result = AddressSet::new();
            for addr in view.addresses(true) {
                if self.states.get(&addr.offset()) == Some(&TraceMemoryState::Known) {
                    result.add_address(&addr);
                }
            }
            Box::new(result)
        }

        fn put_bytes(&mut self, start: &Address, buf: &[u8]) -> usize {
            for (i, b) in buf.iter().enumerate() {
                self.bytes.insert(start.offset() + i as i64, *b);
            }
            buf.len()
        }

        fn get_bytes(&self, start: &Address, buf: &mut [u8]) -> usize {
            let mut n = 0;
            for (i, slot) in buf.iter_mut().enumerate() {
                if let Some(b) = self.bytes.get(&(start.offset() + i as i64)) {
                    *slot = *b;
                    n += 1;
                }
            }
            n
        }

        fn translate(&self, address: &Address) -> Address {
            address.clone()
        }

        fn get_property_access<T>(&self, _name: &str) -> Box<dyn PcodeTracePropertyAccess<T>>
        where
            T: 'static,
        {
            unimplemented!("not exercised by these tests")
        }
    }

    fn ram_space() -> Arc<AddressSpace> {
        AddressSpace::new("ram", 64, 1, AddressSpaceType::Ram, 0)
    }

    #[test]
    fn test_put_get_bytes_round_trip() {
        let space = ram_space();
        let mut access = FakeDataAccess::new(space.clone());
        let start = space.address(0x1000);

        let written = access.put_bytes(&start, &[1, 2, 3, 4]);
        assert_eq!(written, 4);

        let mut out = [0u8; 4];
        let read = access.get_bytes(&start, &mut out);
        assert_eq!(read, 4);
        assert_eq!(out, [1, 2, 3, 4]);
    }

    #[test]
    fn test_viewport_state_known_only_when_whole_range_known() {
        let space = ram_space();
        let mut access = FakeDataAccess::new(space.clone());
        let a0 = space.address(0x1000);
        let a1 = space.address(0x1001);
        let range = AddressRange::new(a0.clone(), a1.clone());

        // Nothing marked yet: composite state is Unknown.
        assert_eq!(access.get_viewport_state(&range), TraceMemoryState::Unknown);

        // Only part of the range known: still Unknown.
        access.set_state(&AddressRange::new(a0.clone(), a0.clone()), TraceMemoryState::Known);
        assert_eq!(access.get_viewport_state(&range), TraceMemoryState::Unknown);

        // Whole range known: Known.
        access.set_state(&range, TraceMemoryState::Known);
        assert_eq!(access.get_viewport_state(&range), TraceMemoryState::Known);
    }

    #[test]
    fn test_intersect_view_known_filters_to_known_addresses() {
        let space = ram_space();
        let mut access = FakeDataAccess::new(space.clone());
        let a0 = space.address(0x1000);
        let a1 = space.address(0x1001);

        access.set_state(&AddressRange::new(a0.clone(), a0.clone()), TraceMemoryState::Known);

        let view = AddressSet::from_range(AddressRange::new(a0.clone(), a1.clone()));
        let known = access.intersect_view_known(&view, false);

        assert!(known.contains(&a0));
        assert!(!known.contains(&a1));
    }

    #[test]
    fn test_translate_is_identity_by_default_shim() {
        let space = ram_space();
        let access = FakeDataAccess::new(space.clone());
        let addr = space.address(0x2000);
        assert_eq!(access.translate(&addr), addr);
    }
}
