//! PowerPC ELF relocation types.
//!
//! Ported from `ghidra.app.util.bin.format.elf.relocation.PowerPC_ElfRelocationType`.

use super::elf_relocation_type::ElfRelocationType;

/// PowerPC ELF relocation types.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
#[allow(non_camel_case_types)]
pub enum PowerPcElfRelocationType {
    R_PPC_NONE,
    R_PPC_ADDR32,
    R_PPC_ADDR24,
    R_PPC_ADDR16,
    R_PPC_ADDR16_LO,
    R_PPC_ADDR16_HI,
    R_PPC_ADDR16_HA,
    R_PPC_ADDR14,
    R_PPC_ADDR14_BRTAKEN,
    R_PPC_ADDR14_BRNTAKEN,
    R_PPC_REL24,
    R_PPC_REL14,
    R_PPC_REL14_BRTAKEN,
    R_PPC_REL14_BRNTAKEN,
    R_PPC_GOT16,
    R_PPC_GOT16_LO,
    R_PPC_GOT16_HI,
    R_PPC_GOT16_HA,
    R_PPC_PLTREL24,
    R_PPC_COPY,
    R_PPC_GLOB_DAT,
    R_PPC_JMP_SLOT,
    R_PPC_RELATIVE,
    R_PPC_LOCAL24PC,
    R_PPC_UADDR32,
    R_PPC_UADDR16,
    R_PPC_REL32,
    R_PPC_PLT32,
    R_PPC_PLTREL32,
    R_PPC_PLT16_LO,
    R_PPC_PLT16_HI,
    R_PPC_PLT16_HA,
    R_PPC_SDAREL16,
    R_PPC_SECTOFF,
    R_PPC_SECTOFF_LO,
    R_PPC_SECTOFF_HI,
    R_PPC_SECTOFF_HA,
    R_PPC_ADDR30,
    R_PPC_RELAX,
    R_PPC_RELAX_PLT,
    R_PPC_RELAX_PLTREL24,
    R_PPC_16DX_HA,
    R_POWERPC_TLS,
    R_POWERPC_DTPMOD,
    R_POWERPC_TPREL16,
    R_POWERPC_TPREL16_LO,
    R_POWERPC_TPREL16_HI,
    R_POWERPC_TPREL16_HA,
    R_POWERPC_TPREL,
    R_POWERPC_DTPREL16,
    R_POWERPC_DTPREL16_LO,
    R_POWERPC_DTPREL16_HI,
    R_POWERPC_DTPREL16_HA,
    R_POWERPC_DTPREL,
    R_POWERPC_GOT_TLSGD16,
    R_POWERPC_GOT_TLSGD16_LO,
    R_POWERPC_GOT_TLSGD16_HI,
    R_POWERPC_GOT_TLSGD16_HA,
    R_POWERPC_GOT_TLSLD16,
    R_POWERPC_GOT_TLSLD16_LO,
    R_POWERPC_GOT_TLSLD16_HI,
    R_POWERPC_GOT_TLSLD16_HA,
    R_POWERPC_GOT_TPREL16,
    R_POWERPC_GOT_TPREL16_LO,
    R_POWERPC_GOT_TPREL16_HI,
    R_POWERPC_GOT_TPREL16_HA,
    R_POWERPC_GOT_DTPREL16,
    R_POWERPC_GOT_DTPREL16_LO,
    R_POWERPC_GOT_DTPREL16_HI,
    R_POWERPC_GOT_DTPREL16_HA,
    R_PPC_TLSGD,
    R_PPC_TLSLD,
    R_PPC_EMB_NADDR32,
    R_PPC_EMB_NADDR16,
    R_PPC_EMB_NADDR16_LO,
    R_PPC_EMB_NADDR16_HI,
    R_PPC_EMB_NADDR16_HA,
    R_PPC_EMB_SDAI16,
    R_PPC_EMB_SDA2I16,
    R_PPC_EMB_SDA2REL,
    R_PPC_EMB_SDA21,
    R_PPC_EMB_MRKREF,
    R_PPC_EMB_RELSEC16,
    R_PPC_EMB_RELST_LO,
    R_PPC_EMB_RELST_HI,
    R_PPC_EMB_RELST_HA,
    R_PPC_EMB_BIT_FLD,
    R_PPC_EMB_RELSDA,
    R_POWERPC_PLTSEQ,
    R_POWERPC_PLTCALL,
    R_PPC_VLE_REL8,
    R_PPC_VLE_REL15,
    R_PPC_VLE_REL24,
    R_PPC_VLE_LO16A,
    R_PPC_VLE_LO16D,
    R_PPC_VLE_HI16A,
    R_PPC_VLE_HI16D,
    R_PPC_VLE_HA16A,
    R_PPC_VLE_HA16D,
    R_PPC_VLE_SDA21,
    R_PPC_VLE_SDA21_LO,
    R_PPC_VLE_SDAREL_LO16A,
    R_PPC_VLE_SDAREL_LO16D,
    R_PPC_VLE_SDAREL_HI16A,
    R_PPC_VLE_SDAREL_HI16D,
    R_PPC_VLE_SDAREL_HA16A,
    R_PPC_VLE_SDAREL_HA16D,
    R_POWERPC_REL16DX_HA,
    R_POWERPC_IRELATIVE,
    R_POWERPC_REL16,
    R_POWERPC_REL16_LO,
    R_POWERPC_REL16_HI,
    R_POWERPC_REL16_HA,
    R_POWERPC_GNU_VTINHERIT,
    R_POWERPC_GNU_VTENTRY,
    R_PPC_TOC16,
}

impl PowerPcElfRelocationType {
    /// Returns the numeric relocation type identifier, matching the Java `typeId` field.
    pub const fn type_id_value(self) -> i32 {
        use PowerPcElfRelocationType::*;
        match self {
            R_PPC_NONE => 0,
            R_PPC_ADDR32 => 1,
            R_PPC_ADDR24 => 2,
            R_PPC_ADDR16 => 3,
            R_PPC_ADDR16_LO => 4,
            R_PPC_ADDR16_HI => 5,
            R_PPC_ADDR16_HA => 6,
            R_PPC_ADDR14 => 7,
            R_PPC_ADDR14_BRTAKEN => 8,
            R_PPC_ADDR14_BRNTAKEN => 9,
            R_PPC_REL24 => 10,
            R_PPC_REL14 => 11,
            R_PPC_REL14_BRTAKEN => 12,
            R_PPC_REL14_BRNTAKEN => 13,
            R_PPC_GOT16 => 14,
            R_PPC_GOT16_LO => 15,
            R_PPC_GOT16_HI => 16,
            R_PPC_GOT16_HA => 17,
            R_PPC_PLTREL24 => 18,
            R_PPC_COPY => 19,
            R_PPC_GLOB_DAT => 20,
            R_PPC_JMP_SLOT => 21,
            R_PPC_RELATIVE => 22,
            R_PPC_LOCAL24PC => 23,
            R_PPC_UADDR32 => 24,
            R_PPC_UADDR16 => 25,
            R_PPC_REL32 => 26,
            R_PPC_PLT32 => 27,
            R_PPC_PLTREL32 => 28,
            R_PPC_PLT16_LO => 29,
            R_PPC_PLT16_HI => 30,
            R_PPC_PLT16_HA => 31,
            R_PPC_SDAREL16 => 32,
            R_PPC_SECTOFF => 33,
            R_PPC_SECTOFF_LO => 34,
            R_PPC_SECTOFF_HI => 35,
            R_PPC_SECTOFF_HA => 36,
            R_PPC_ADDR30 => 37,
            R_PPC_RELAX => 48,
            R_PPC_RELAX_PLT => 49,
            R_PPC_RELAX_PLTREL24 => 50,
            R_PPC_16DX_HA => 51,
            R_POWERPC_TLS => 67,
            R_POWERPC_DTPMOD => 68,
            R_POWERPC_TPREL16 => 69,
            R_POWERPC_TPREL16_LO => 70,
            R_POWERPC_TPREL16_HI => 71,
            R_POWERPC_TPREL16_HA => 72,
            R_POWERPC_TPREL => 73,
            R_POWERPC_DTPREL16 => 74,
            R_POWERPC_DTPREL16_LO => 75,
            R_POWERPC_DTPREL16_HI => 76,
            R_POWERPC_DTPREL16_HA => 77,
            R_POWERPC_DTPREL => 78,
            R_POWERPC_GOT_TLSGD16 => 79,
            R_POWERPC_GOT_TLSGD16_LO => 80,
            R_POWERPC_GOT_TLSGD16_HI => 81,
            R_POWERPC_GOT_TLSGD16_HA => 82,
            R_POWERPC_GOT_TLSLD16 => 83,
            R_POWERPC_GOT_TLSLD16_LO => 84,
            R_POWERPC_GOT_TLSLD16_HI => 85,
            R_POWERPC_GOT_TLSLD16_HA => 86,
            R_POWERPC_GOT_TPREL16 => 87,
            R_POWERPC_GOT_TPREL16_LO => 88,
            R_POWERPC_GOT_TPREL16_HI => 89,
            R_POWERPC_GOT_TPREL16_HA => 90,
            R_POWERPC_GOT_DTPREL16 => 91,
            R_POWERPC_GOT_DTPREL16_LO => 92,
            R_POWERPC_GOT_DTPREL16_HI => 93,
            R_POWERPC_GOT_DTPREL16_HA => 94,
            R_PPC_TLSGD => 95,
            R_PPC_TLSLD => 96,
            R_PPC_EMB_NADDR32 => 101,
            R_PPC_EMB_NADDR16 => 102,
            R_PPC_EMB_NADDR16_LO => 103,
            R_PPC_EMB_NADDR16_HI => 104,
            R_PPC_EMB_NADDR16_HA => 105,
            R_PPC_EMB_SDAI16 => 106,
            R_PPC_EMB_SDA2I16 => 107,
            R_PPC_EMB_SDA2REL => 108,
            R_PPC_EMB_SDA21 => 109,
            R_PPC_EMB_MRKREF => 110,
            R_PPC_EMB_RELSEC16 => 111,
            R_PPC_EMB_RELST_LO => 112,
            R_PPC_EMB_RELST_HI => 113,
            R_PPC_EMB_RELST_HA => 114,
            R_PPC_EMB_BIT_FLD => 115,
            R_PPC_EMB_RELSDA => 116,
            R_POWERPC_PLTSEQ => 119,
            R_POWERPC_PLTCALL => 120,
            R_PPC_VLE_REL8 => 216,
            R_PPC_VLE_REL15 => 217,
            R_PPC_VLE_REL24 => 218,
            R_PPC_VLE_LO16A => 219,
            R_PPC_VLE_LO16D => 220,
            R_PPC_VLE_HI16A => 221,
            R_PPC_VLE_HI16D => 222,
            R_PPC_VLE_HA16A => 223,
            R_PPC_VLE_HA16D => 224,
            R_PPC_VLE_SDA21 => 225,
            R_PPC_VLE_SDA21_LO => 226,
            R_PPC_VLE_SDAREL_LO16A => 227,
            R_PPC_VLE_SDAREL_LO16D => 228,
            R_PPC_VLE_SDAREL_HI16A => 229,
            R_PPC_VLE_SDAREL_HI16D => 230,
            R_PPC_VLE_SDAREL_HA16A => 231,
            R_PPC_VLE_SDAREL_HA16D => 232,
            R_POWERPC_REL16DX_HA => 246,
            R_POWERPC_IRELATIVE => 248,
            R_POWERPC_REL16 => 249,
            R_POWERPC_REL16_LO => 250,
            R_POWERPC_REL16_HI => 251,
            R_POWERPC_REL16_HA => 252,
            R_POWERPC_GNU_VTINHERIT => 253,
            R_POWERPC_GNU_VTENTRY => 254,
            R_PPC_TOC16 => 255,
        }
    }

    /// Returns the variant name, matching the Java enum constant name.
    pub const fn name_str(self) -> &'static str {
        use PowerPcElfRelocationType::*;
        match self {
            R_PPC_NONE => "R_PPC_NONE",
            R_PPC_ADDR32 => "R_PPC_ADDR32",
            R_PPC_ADDR24 => "R_PPC_ADDR24",
            R_PPC_ADDR16 => "R_PPC_ADDR16",
            R_PPC_ADDR16_LO => "R_PPC_ADDR16_LO",
            R_PPC_ADDR16_HI => "R_PPC_ADDR16_HI",
            R_PPC_ADDR16_HA => "R_PPC_ADDR16_HA",
            R_PPC_ADDR14 => "R_PPC_ADDR14",
            R_PPC_ADDR14_BRTAKEN => "R_PPC_ADDR14_BRTAKEN",
            R_PPC_ADDR14_BRNTAKEN => "R_PPC_ADDR14_BRNTAKEN",
            R_PPC_REL24 => "R_PPC_REL24",
            R_PPC_REL14 => "R_PPC_REL14",
            R_PPC_REL14_BRTAKEN => "R_PPC_REL14_BRTAKEN",
            R_PPC_REL14_BRNTAKEN => "R_PPC_REL14_BRNTAKEN",
            R_PPC_GOT16 => "R_PPC_GOT16",
            R_PPC_GOT16_LO => "R_PPC_GOT16_LO",
            R_PPC_GOT16_HI => "R_PPC_GOT16_HI",
            R_PPC_GOT16_HA => "R_PPC_GOT16_HA",
            R_PPC_PLTREL24 => "R_PPC_PLTREL24",
            R_PPC_COPY => "R_PPC_COPY",
            R_PPC_GLOB_DAT => "R_PPC_GLOB_DAT",
            R_PPC_JMP_SLOT => "R_PPC_JMP_SLOT",
            R_PPC_RELATIVE => "R_PPC_RELATIVE",
            R_PPC_LOCAL24PC => "R_PPC_LOCAL24PC",
            R_PPC_UADDR32 => "R_PPC_UADDR32",
            R_PPC_UADDR16 => "R_PPC_UADDR16",
            R_PPC_REL32 => "R_PPC_REL32",
            R_PPC_PLT32 => "R_PPC_PLT32",
            R_PPC_PLTREL32 => "R_PPC_PLTREL32",
            R_PPC_PLT16_LO => "R_PPC_PLT16_LO",
            R_PPC_PLT16_HI => "R_PPC_PLT16_HI",
            R_PPC_PLT16_HA => "R_PPC_PLT16_HA",
            R_PPC_SDAREL16 => "R_PPC_SDAREL16",
            R_PPC_SECTOFF => "R_PPC_SECTOFF",
            R_PPC_SECTOFF_LO => "R_PPC_SECTOFF_LO",
            R_PPC_SECTOFF_HI => "R_PPC_SECTOFF_HI",
            R_PPC_SECTOFF_HA => "R_PPC_SECTOFF_HA",
            R_PPC_ADDR30 => "R_PPC_ADDR30",
            R_PPC_RELAX => "R_PPC_RELAX",
            R_PPC_RELAX_PLT => "R_PPC_RELAX_PLT",
            R_PPC_RELAX_PLTREL24 => "R_PPC_RELAX_PLTREL24",
            R_PPC_16DX_HA => "R_PPC_16DX_HA",
            R_POWERPC_TLS => "R_POWERPC_TLS",
            R_POWERPC_DTPMOD => "R_POWERPC_DTPMOD",
            R_POWERPC_TPREL16 => "R_POWERPC_TPREL16",
            R_POWERPC_TPREL16_LO => "R_POWERPC_TPREL16_LO",
            R_POWERPC_TPREL16_HI => "R_POWERPC_TPREL16_HI",
            R_POWERPC_TPREL16_HA => "R_POWERPC_TPREL16_HA",
            R_POWERPC_TPREL => "R_POWERPC_TPREL",
            R_POWERPC_DTPREL16 => "R_POWERPC_DTPREL16",
            R_POWERPC_DTPREL16_LO => "R_POWERPC_DTPREL16_LO",
            R_POWERPC_DTPREL16_HI => "R_POWERPC_DTPREL16_HI",
            R_POWERPC_DTPREL16_HA => "R_POWERPC_DTPREL16_HA",
            R_POWERPC_DTPREL => "R_POWERPC_DTPREL",
            R_POWERPC_GOT_TLSGD16 => "R_POWERPC_GOT_TLSGD16",
            R_POWERPC_GOT_TLSGD16_LO => "R_POWERPC_GOT_TLSGD16_LO",
            R_POWERPC_GOT_TLSGD16_HI => "R_POWERPC_GOT_TLSGD16_HI",
            R_POWERPC_GOT_TLSGD16_HA => "R_POWERPC_GOT_TLSGD16_HA",
            R_POWERPC_GOT_TLSLD16 => "R_POWERPC_GOT_TLSLD16",
            R_POWERPC_GOT_TLSLD16_LO => "R_POWERPC_GOT_TLSLD16_LO",
            R_POWERPC_GOT_TLSLD16_HI => "R_POWERPC_GOT_TLSLD16_HI",
            R_POWERPC_GOT_TLSLD16_HA => "R_POWERPC_GOT_TLSLD16_HA",
            R_POWERPC_GOT_TPREL16 => "R_POWERPC_GOT_TPREL16",
            R_POWERPC_GOT_TPREL16_LO => "R_POWERPC_GOT_TPREL16_LO",
            R_POWERPC_GOT_TPREL16_HI => "R_POWERPC_GOT_TPREL16_HI",
            R_POWERPC_GOT_TPREL16_HA => "R_POWERPC_GOT_TPREL16_HA",
            R_POWERPC_GOT_DTPREL16 => "R_POWERPC_GOT_DTPREL16",
            R_POWERPC_GOT_DTPREL16_LO => "R_POWERPC_GOT_DTPREL16_LO",
            R_POWERPC_GOT_DTPREL16_HI => "R_POWERPC_GOT_DTPREL16_HI",
            R_POWERPC_GOT_DTPREL16_HA => "R_POWERPC_GOT_DTPREL16_HA",
            R_PPC_TLSGD => "R_PPC_TLSGD",
            R_PPC_TLSLD => "R_PPC_TLSLD",
            R_PPC_EMB_NADDR32 => "R_PPC_EMB_NADDR32",
            R_PPC_EMB_NADDR16 => "R_PPC_EMB_NADDR16",
            R_PPC_EMB_NADDR16_LO => "R_PPC_EMB_NADDR16_LO",
            R_PPC_EMB_NADDR16_HI => "R_PPC_EMB_NADDR16_HI",
            R_PPC_EMB_NADDR16_HA => "R_PPC_EMB_NADDR16_HA",
            R_PPC_EMB_SDAI16 => "R_PPC_EMB_SDAI16",
            R_PPC_EMB_SDA2I16 => "R_PPC_EMB_SDA2I16",
            R_PPC_EMB_SDA2REL => "R_PPC_EMB_SDA2REL",
            R_PPC_EMB_SDA21 => "R_PPC_EMB_SDA21",
            R_PPC_EMB_MRKREF => "R_PPC_EMB_MRKREF",
            R_PPC_EMB_RELSEC16 => "R_PPC_EMB_RELSEC16",
            R_PPC_EMB_RELST_LO => "R_PPC_EMB_RELST_LO",
            R_PPC_EMB_RELST_HI => "R_PPC_EMB_RELST_HI",
            R_PPC_EMB_RELST_HA => "R_PPC_EMB_RELST_HA",
            R_PPC_EMB_BIT_FLD => "R_PPC_EMB_BIT_FLD",
            R_PPC_EMB_RELSDA => "R_PPC_EMB_RELSDA",
            R_POWERPC_PLTSEQ => "R_POWERPC_PLTSEQ",
            R_POWERPC_PLTCALL => "R_POWERPC_PLTCALL",
            R_PPC_VLE_REL8 => "R_PPC_VLE_REL8",
            R_PPC_VLE_REL15 => "R_PPC_VLE_REL15",
            R_PPC_VLE_REL24 => "R_PPC_VLE_REL24",
            R_PPC_VLE_LO16A => "R_PPC_VLE_LO16A",
            R_PPC_VLE_LO16D => "R_PPC_VLE_LO16D",
            R_PPC_VLE_HI16A => "R_PPC_VLE_HI16A",
            R_PPC_VLE_HI16D => "R_PPC_VLE_HI16D",
            R_PPC_VLE_HA16A => "R_PPC_VLE_HA16A",
            R_PPC_VLE_HA16D => "R_PPC_VLE_HA16D",
            R_PPC_VLE_SDA21 => "R_PPC_VLE_SDA21",
            R_PPC_VLE_SDA21_LO => "R_PPC_VLE_SDA21_LO",
            R_PPC_VLE_SDAREL_LO16A => "R_PPC_VLE_SDAREL_LO16A",
            R_PPC_VLE_SDAREL_LO16D => "R_PPC_VLE_SDAREL_LO16D",
            R_PPC_VLE_SDAREL_HI16A => "R_PPC_VLE_SDAREL_HI16A",
            R_PPC_VLE_SDAREL_HI16D => "R_PPC_VLE_SDAREL_HI16D",
            R_PPC_VLE_SDAREL_HA16A => "R_PPC_VLE_SDAREL_HA16A",
            R_PPC_VLE_SDAREL_HA16D => "R_PPC_VLE_SDAREL_HA16D",
            R_POWERPC_REL16DX_HA => "R_POWERPC_REL16DX_HA",
            R_POWERPC_IRELATIVE => "R_POWERPC_IRELATIVE",
            R_POWERPC_REL16 => "R_POWERPC_REL16",
            R_POWERPC_REL16_LO => "R_POWERPC_REL16_LO",
            R_POWERPC_REL16_HI => "R_POWERPC_REL16_HI",
            R_POWERPC_REL16_HA => "R_POWERPC_REL16_HA",
            R_POWERPC_GNU_VTINHERIT => "R_POWERPC_GNU_VTINHERIT",
            R_POWERPC_GNU_VTENTRY => "R_POWERPC_GNU_VTENTRY",
            R_PPC_TOC16 => "R_PPC_TOC16",
        }
    }
}

impl ElfRelocationType for PowerPcElfRelocationType {
    fn name(&self) -> &str {
        self.name_str()
    }

    fn type_id(&self) -> i32 {
        self.type_id_value()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn none_has_type_id_zero() {
        assert_eq!(PowerPcElfRelocationType::R_PPC_NONE.type_id(), 0);
        assert_eq!(PowerPcElfRelocationType::R_PPC_NONE.name(), "R_PPC_NONE");
    }

    #[test]
    fn common_relocations_match_java_ids() {
        assert_eq!(PowerPcElfRelocationType::R_PPC_ADDR32.type_id(), 1);
        assert_eq!(PowerPcElfRelocationType::R_PPC_ADDR16.type_id(), 3);
        assert_eq!(PowerPcElfRelocationType::R_PPC_COPY.type_id(), 19);
        assert_eq!(PowerPcElfRelocationType::R_PPC_JMP_SLOT.type_id(), 21);
    }

    #[test]
    fn non_contiguous_id_gap_is_preserved() {
        // Java skips typeIds 38-47 (between R_PPC_ADDR30 at 37 and R_PPC_RELAX at 48).
        assert_eq!(PowerPcElfRelocationType::R_PPC_ADDR30.type_id(), 37);
        assert_eq!(PowerPcElfRelocationType::R_PPC_RELAX.type_id(), 48);
    }

    #[test]
    fn high_range_reserved_constants_match_java_ids() {
        assert_eq!(PowerPcElfRelocationType::R_PPC_VLE_REL8.type_id(), 216);
        assert_eq!(PowerPcElfRelocationType::R_POWERPC_GNU_VTENTRY.type_id(), 254);
        assert_eq!(PowerPcElfRelocationType::R_PPC_TOC16.type_id(), 255);
    }

    #[test]
    fn implements_elf_relocation_type_trait_object() {
        let r: &dyn ElfRelocationType = &PowerPcElfRelocationType::R_PPC_GLOB_DAT;
        assert_eq!(r.type_id(), 20);
        assert_eq!(r.name(), "R_PPC_GLOB_DAT");
    }
}
