use crate::framework::plugintool::tool_event_name::ToolEventName;

/// Name of the event source used when a plugin event is passed to another tool as a
/// cross-tool event.
///
/// Mirrors `PluginEvent.EXTERNAL_SOURCE_NAME`.
pub const EXTERNAL_SOURCE_NAME: &str = "External Tool";

/// Behavior a concrete plugin event may supply.
///
/// Mirrors the two ways a Java subclass of `PluginEvent` customizes it: overriding the
/// protected `getDetails()` hook (default `null`), and carrying a `@ToolEventName`
/// annotation that the final `getToolEventName()`/`isToolEvent()` methods look up via
/// reflection on `getClass()`. Rust has no inheritance or reflection, so a concrete event
/// supplies both directly through this trait, which [`PluginEvent`] delegates to.
pub trait PluginEventBehavior {
    /// Extra details to append to [`PluginEvent`]'s `Display` output.
    ///
    /// Returns `None` by default, matching `getDetails()` returning `null`.
    fn details(&self) -> Option<String> {
        None
    }

    /// The event's cross-tool event name, mirroring the class's `@ToolEventName` annotation.
    ///
    /// Returns `None` by default, matching a class with no `@ToolEventName` annotation.
    fn tool_event_name(&self) -> Option<&ToolEventName> {
        None
    }
}

/// Event generated by a plugin.
///
/// A `PluginEvent` should supply a [`PluginEventBehavior`] whose `tool_event_name()` returns
/// `Some` if it may be passed between multiple tools via a
/// [`ToolConnection`](crate::framework::model::ToolConnection).
///
/// Port of `ghidra.framework.plugintool.PluginEvent`, an abstract base class. Rust has no
/// inheritance, so the fields and `final` methods live directly on this struct, and the
/// overridable behavior is supplied by an optional [`PluginEventBehavior`], following the same
/// base-struct-plus-behavior-trait composition used by
/// [`AbstractCreateStructureCmd`](crate::app::cmd::data::abstract_create_structure_cmd::AbstractCreateStructureCmd).
/// A concrete event that overrides neither hook can simply omit the behavior (see
/// [`PluginEvent::new`]).
pub struct PluginEvent {
    event_name: String,
    source_name: String,
    trigger_event: Option<Box<PluginEvent>>,
    behavior: Option<Box<dyn PluginEventBehavior>>,
}

impl PluginEvent {
    /// Constructs a plugin event with no custom [`PluginEventBehavior`]; `details()` returns
    /// `None` and `tool_event_name()` returns `None`, matching a Java subclass that overrides
    /// neither `getDetails()` nor carries a `@ToolEventName` annotation.
    ///
    /// Mirrors the protected `PluginEvent(String sourceName, String eventName)` constructor.
    pub fn new(source_name: impl Into<String>, event_name: impl Into<String>) -> Self {
        Self {
            event_name: event_name.into(),
            source_name: source_name.into(),
            trigger_event: None,
            behavior: None,
        }
    }

    /// Constructs a plugin event whose `details()`/`tool_event_name()` are supplied by
    /// `behavior`, mirroring a Java subclass that overrides `getDetails()` and/or carries a
    /// `@ToolEventName` annotation.
    pub fn with_behavior(
        source_name: impl Into<String>,
        event_name: impl Into<String>,
        behavior: Box<dyn PluginEventBehavior>,
    ) -> Self {
        Self {
            event_name: event_name.into(),
            source_name: source_name.into(),
            trigger_event: None,
            behavior: Some(behavior),
        }
    }

    /// Get the plugin event name.
    ///
    /// Mirrors the final `getEventName()`.
    pub fn event_name(&self) -> &str {
        &self.event_name
    }

    /// Returns the name of the plugin immediately responsible for firing this event.
    ///
    /// Mirrors the final `getSourceName()`.
    pub fn source_name(&self) -> &str {
        &self.source_name
    }

    /// Mirrors the final `setSourceName(String)`.
    pub fn set_source_name(&mut self, source_name: impl Into<String>) {
        self.source_name = source_name.into();
    }

    /// Mirrors the final `getTriggerEvent()`.
    pub fn trigger_event(&self) -> Option<&PluginEvent> {
        self.trigger_event.as_deref()
    }

    /// Mirrors the final `setTriggerEvent(PluginEvent)`.
    pub fn set_trigger_event(&mut self, trigger_event: Option<Box<PluginEvent>>) {
        self.trigger_event = trigger_event;
    }

    /// Get the optional cross-tool event name which has been established via this event's
    /// [`PluginEventBehavior`], making it available for passing as an external tool event via
    /// a [`ToolConnection`](crate::framework::model::ToolConnection). This name may differ
    /// from [`PluginEvent::event_name`].
    ///
    /// Mirrors the final `getToolEventName()`.
    pub fn tool_event_name(&self) -> Option<&ToolEventName> {
        self.behavior.as_ref().and_then(|b| b.tool_event_name())
    }

    /// Determine if this event is available for passing to another tool via a
    /// [`ToolConnection`](crate::framework::model::ToolConnection).
    ///
    /// Mirrors the final `isToolEvent()`.
    pub fn is_tool_event(&self) -> bool {
        self.tool_event_name().is_some()
    }

    fn details(&self) -> Option<String> {
        self.behavior.as_ref().and_then(|b| b.details())
    }
}

impl std::fmt::Display for PluginEvent {
    /// Mirrors the `toString()` override.
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "Event: {}  Source: {}", self.event_name, self.source_name)?;
        if let Some(details) = self.details() {
            write!(f, "\n\tDetails: {details}")?;
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    struct MockBehavior {
        details: Option<String>,
        tool_event_name: Option<ToolEventName>,
    }

    impl PluginEventBehavior for MockBehavior {
        fn details(&self) -> Option<String> {
            self.details.clone()
        }

        fn tool_event_name(&self) -> Option<&ToolEventName> {
            self.tool_event_name.as_ref()
        }
    }

    #[test]
    fn external_source_name_matches_java_constant() {
        assert_eq!(EXTERNAL_SOURCE_NAME, "External Tool");
    }

    #[test]
    fn new_stores_names() {
        let e = PluginEvent::new("MyPlugin", "MyEvent");
        assert_eq!(e.source_name(), "MyPlugin");
        assert_eq!(e.event_name(), "MyEvent");
    }

    #[test]
    fn no_behavior_defaults_match_java_defaults() {
        let e = PluginEvent::new("MyPlugin", "MyEvent");
        assert!(!e.is_tool_event());
        assert_eq!(e.tool_event_name(), None);
        assert_eq!(e.details(), None);
    }

    #[test]
    fn set_source_name_mutates() {
        let mut e = PluginEvent::new("Orig", "MyEvent");
        e.set_source_name("Updated");
        assert_eq!(e.source_name(), "Updated");
    }

    #[test]
    fn trigger_event_defaults_to_none() {
        let e = PluginEvent::new("MyPlugin", "MyEvent");
        assert!(e.trigger_event().is_none());
    }

    #[test]
    fn set_and_get_trigger_event() {
        let mut e = PluginEvent::new("MyPlugin", "MyEvent");
        let trigger = PluginEvent::new("OtherPlugin", "OtherEvent");
        e.set_trigger_event(Some(Box::new(trigger)));

        let got = e.trigger_event().expect("trigger event should be set");
        assert_eq!(got.source_name(), "OtherPlugin");
        assert_eq!(got.event_name(), "OtherEvent");

        e.set_trigger_event(None);
        assert!(e.trigger_event().is_none());
    }

    #[test]
    fn behavior_supplies_details_and_tool_event_name() {
        let behavior = MockBehavior {
            details: Some("extra info".to_string()),
            tool_event_name: Some(ToolEventName::new("My Tool Event")),
        };
        let e = PluginEvent::with_behavior("MyPlugin", "MyEvent", Box::new(behavior));

        assert!(e.is_tool_event());
        assert_eq!(e.tool_event_name(), Some(&ToolEventName::new("My Tool Event")));
        assert_eq!(e.details(), Some("extra info".to_string()));
    }

    #[test]
    fn behavior_with_no_tool_event_name_is_not_a_tool_event() {
        let behavior = MockBehavior { details: None, tool_event_name: None };
        let e = PluginEvent::with_behavior("MyPlugin", "MyEvent", Box::new(behavior));
        assert!(!e.is_tool_event());
    }

    #[test]
    fn display_without_details_matches_java_format() {
        let e = PluginEvent::new("MyPlugin", "MyEvent");
        assert_eq!(e.to_string(), "Event: MyEvent  Source: MyPlugin");
    }

    #[test]
    fn display_with_details_matches_java_format() {
        let behavior = MockBehavior {
            details: Some("extra info".to_string()),
            tool_event_name: None,
        };
        let e = PluginEvent::with_behavior("MyPlugin", "MyEvent", Box::new(behavior));
        assert_eq!(e.to_string(), "Event: MyEvent  Source: MyPlugin\n\tDetails: extra info");
    }
}
