use std::any::Any;
use std::fmt;

use crate::framework::model::DomainObjectChangeRecord;
use super::vt_event::VtEvent;

/// Event data for a DomainObjectChangeEvent generated by Version Tracking.
///
/// Port of `ghidra.feature.vt.api.impl.VersionTrackingChangeRecord`.
pub struct VersionTrackingChangeRecord {
    change_record: DomainObjectChangeRecord,
    affected: Option<Box<dyn Any + Send + Sync>>,
}

impl VersionTrackingChangeRecord {
    /// Construct a new VersionTrackingChangeRecord.
    ///
    /// # Arguments
    /// * `event_type` - event type
    /// * `affected` - the object that is the subject of this change record; may be None.
    /// * `old_value` - the original value; may be None.
    /// * `new_value` - the new value; may be None.
    pub fn new(
        event_type: VtEvent,
        affected: Option<Box<dyn Any + Send + Sync>>,
        old_value: Option<Box<dyn Any + Send + Sync>>,
        new_value: Option<Box<dyn Any + Send + Sync>>,
    ) -> Self {
        Self {
            change_record: DomainObjectChangeRecord::with_values(
                Box::new(event_type),
                old_value,
                new_value,
            ),
            affected,
        }
    }

    /// Return the object that is the subject of this change record.
    ///
    /// # Returns
    /// Option containing the affected object or None if this change record does not have the
    /// affected object
    pub fn object(&self) -> Option<&(dyn Any + Send + Sync)> {
        self.affected.as_deref()
    }

    /// Returns a reference to the underlying DomainObjectChangeRecord.
    pub fn change_record(&self) -> &DomainObjectChangeRecord {
        &self.change_record
    }
}

impl fmt::Display for VersionTrackingChangeRecord {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.change_record)?;
        if self.affected.is_some() {
            write!(f, ", affected = <object>")?;
        }
        Ok(())
    }
}

impl fmt::Debug for VersionTrackingChangeRecord {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.debug_struct("VersionTrackingChangeRecord")
            .field("has_change_record", &true)
            .field("affected", &self.affected.is_some())
            .finish()
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn new_with_no_affected() {
        let record = VersionTrackingChangeRecord::new(
            VtEvent::MatchSetAdded,
            None,
            None,
            None,
        );
        assert!(record.object().is_none());
    }

    #[test]
    fn new_with_affected_object() {
        let affected = Box::new("test_object".to_string());
        let record = VersionTrackingChangeRecord::new(
            VtEvent::MatchAdded,
            Some(affected),
            None,
            None,
        );
        assert!(record.object().is_some());
        assert_eq!(
            record.object().unwrap().downcast_ref::<String>(),
            Some(&"test_object".to_string())
        );
    }

    #[test]
    fn new_with_old_and_new_values() {
        let old = Some(Box::new(42i32) as Box<dyn Any + Send + Sync>);
        let new = Some(Box::new(100i32) as Box<dyn Any + Send + Sync>);
        let record = VersionTrackingChangeRecord::new(
            VtEvent::MatchTagChanged,
            None,
            old,
            new,
        );
        assert!(record.object().is_none());
    }

    #[test]
    fn new_with_affected_and_values() {
        let affected = Box::new("target".to_string());
        let old = Some(Box::new("old_state".to_string()) as Box<dyn Any + Send + Sync>);
        let new = Some(Box::new("new_state".to_string()) as Box<dyn Any + Send + Sync>);
        let record = VersionTrackingChangeRecord::new(
            VtEvent::AssociationStatusChanged,
            Some(affected),
            old,
            new,
        );
        assert!(record.object().is_some());
        assert_eq!(
            record.object().unwrap().downcast_ref::<String>(),
            Some(&"target".to_string())
        );
    }

    #[test]
    fn display_without_affected() {
        let record = VersionTrackingChangeRecord::new(
            VtEvent::MatchSetAdded,
            None,
            None,
            None,
        );
        let s = format!("{}", record);
        assert!(!s.contains("affected"));
    }

    #[test]
    fn display_with_affected() {
        let affected = Box::new("object".to_string());
        let record = VersionTrackingChangeRecord::new(
            VtEvent::MatchDeleted,
            Some(affected),
            None,
            None,
        );
        let s = format!("{}", record);
        assert!(s.contains("affected"));
    }

    #[test]
    fn debug_format() {
        let affected = Box::new(42i32);
        let record = VersionTrackingChangeRecord::new(
            VtEvent::TagAdded,
            Some(affected),
            None,
            None,
        );
        let s = format!("{:?}", record);
        assert!(s.contains("VersionTrackingChangeRecord"));
        assert!(s.contains("affected"));
    }

    #[test]
    fn multiple_event_types() {
        let events = vec![
            VtEvent::MatchSetAdded,
            VtEvent::AssociationStatusChanged,
            VtEvent::MatchDeleted,
            VtEvent::AssociationMarkupStatusChanged,
            VtEvent::MarkupItemStatusChanged,
        ];

        for event in events {
            let record = VersionTrackingChangeRecord::new(event, None, None, None);
            assert!(record.object().is_none());
        }
    }
}
