// This file is @generated by prost-build.
/// For testing: cause the server to report an unrecognized request error
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ErrorRequest {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ErrorReply {
    #[prost(enumeration = "ErrorCode", tag = "1")]
    pub code: i32,
    #[prost(string, tag = "2")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PingRequest {
    #[prost(string, tag = "1")]
    pub content: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PingReply {
    #[prost(string, tag = "1")]
    pub content: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FullExportRequest {
    #[prost(string, tag = "1")]
    pub ns: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FullExportReply {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LookAddrRequest {
    #[prost(string, tag = "1")]
    pub ns: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LookAddrReply {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LookTypeRequest {
    #[prost(string, tag = "1")]
    pub ns: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LookTypeReply {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EnumTypesRequest {
    #[prost(string, tag = "1")]
    pub ns: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EnumTypesReply {
    #[prost(string, tag = "1")]
    pub ns: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LookSymRequest {
    #[prost(string, tag = "1")]
    pub ns: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LookSymReply {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EnumSymsRequest {
    #[prost(string, tag = "1")]
    pub ns: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EnumSymsReply {
    #[prost(string, tag = "1")]
    pub value: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RootAddedEvent {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RootMessage {
    #[prost(int32, tag = "1")]
    pub sequence: i32,
    #[prost(
        oneof = "root_message::Msg",
        tags = "100, 200, 101, 201, 102, 202, 103, 203, 104, 204, 105, 205, 106, 206, 107, 207"
    )]
    pub msg: ::core::option::Option<root_message::Msg>,
}
/// Nested message and enum types in `RootMessage`.
pub mod root_message {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Msg {
        #[prost(message, tag = "100")]
        ErrorRequest(super::ErrorRequest),
        #[prost(message, tag = "200")]
        ErrorReply(super::ErrorReply),
        #[prost(message, tag = "101")]
        PingRequest(super::PingRequest),
        #[prost(message, tag = "201")]
        PingReply(super::PingReply),
        #[prost(message, tag = "102")]
        FullExportRequest(super::FullExportRequest),
        #[prost(message, tag = "202")]
        FullExportReply(super::FullExportReply),
        #[prost(message, tag = "103")]
        LookTypeRequest(super::LookTypeRequest),
        #[prost(message, tag = "203")]
        LookTypeReply(super::LookTypeReply),
        #[prost(message, tag = "104")]
        LookSymbolRequest(super::LookSymRequest),
        #[prost(message, tag = "204")]
        LookSymbolReply(super::LookSymReply),
        #[prost(message, tag = "105")]
        LookAddressRequest(super::LookAddrRequest),
        #[prost(message, tag = "205")]
        LookAddressReply(super::LookAddrReply),
        #[prost(message, tag = "106")]
        EnumTypesRequest(super::EnumTypesRequest),
        #[prost(message, tag = "206")]
        EnumTypesReply(super::EnumTypesReply),
        #[prost(message, tag = "107")]
        EnumSymbolsRequest(super::EnumSymsRequest),
        #[prost(message, tag = "207")]
        EnumSymbolsReply(super::EnumSymsReply),
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ErrorCode {
    EcUnknown = 0,
    EcBadRequest = 1,
    EcNotSupported = 2,
}
impl ErrorCode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::EcUnknown => "EC_UNKNOWN",
            Self::EcBadRequest => "EC_BAD_REQUEST",
            Self::EcNotSupported => "EC_NOT_SUPPORTED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EC_UNKNOWN" => Some(Self::EcUnknown),
            "EC_BAD_REQUEST" => Some(Self::EcBadRequest),
            "EC_NOT_SUPPORTED" => Some(Self::EcNotSupported),
            _ => None,
        }
    }
}
