use std::collections::HashSet;

/// Helper for allocating unique string names.
///
/// "Reserved names" are names that will be used by later calls to the de-duper.
///
/// "Used names" are names that are already allocated and are in use.
///
/// Reserved names only prevent re-use of a name when a name is being generated because of a
/// collision with a "used name".
#[derive(Debug, Default)]
pub struct NameDeduper {
    used_names: HashSet<String>,
    reserved_names: HashSet<String>,
}

impl NameDeduper {
    /// Create a new name de-duper.
    pub fn new() -> Self {
        Self::default()
    }

    /// Add names that have already been used.
    pub fn add_used_names<I, S>(&mut self, names: I)
    where
        I: IntoIterator<Item = S>,
        S: Into<String>,
    {
        self.used_names.extend(names.into_iter().map(|s| s.into()));
    }

    /// Add names that will be used in a future call. These do not block uniqueness checks but
    /// prevent the name from being chosen when auto-generating a collision-free alternative.
    pub fn add_reserved_names<I, S>(&mut self, names: I)
    where
        I: IntoIterator<Item = S>,
        S: Into<String>,
    {
        self.reserved_names.extend(names.into_iter().map(|s| s.into()));
    }

    /// Returns `true` if the specified name has not been allocated yet. A `None` name is always
    /// considered unique.
    pub fn is_unique_name(&self, name: Option<&str>) -> bool {
        name.map_or(true, |n| !self.used_names.contains(n))
    }

    /// Confirms that the specified name is unique, or returns a generated name that is unique.
    ///
    /// Returns `None` if the name was already unique (and marks it as used), or returns a new
    /// unique name generated by appending `_1`, `_2`, … until no collision exists. A `None`
    /// input passes through unchanged without modifying any state.
    pub fn get_unique_name(&mut self, name: Option<&str>) -> Option<String> {
        let name = name?;

        if self.used_names.insert(name.to_string()) {
            return None;
        }

        let original = name;
        let mut try_num: u32 = 0;
        let candidate = loop {
            try_num += 1;
            let c = format!("{}_{}", original, try_num);
            if !self.used_names.contains(&c) && !self.reserved_names.contains(&c) {
                break c;
            }
        };
        self.used_names.insert(candidate.clone());
        Some(candidate)
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn new_name_is_unique() {
        let mut d = NameDeduper::new();
        assert_eq!(d.get_unique_name(Some("foo")), None);
    }

    #[test]
    fn duplicate_name_gets_suffix() {
        let mut d = NameDeduper::new();
        d.get_unique_name(Some("foo"));
        assert_eq!(d.get_unique_name(Some("foo")), Some("foo_1".to_string()));
    }

    #[test]
    fn multiple_duplicates_increment_suffix() {
        let mut d = NameDeduper::new();
        d.get_unique_name(Some("foo"));
        d.get_unique_name(Some("foo"));
        assert_eq!(d.get_unique_name(Some("foo")), Some("foo_2".to_string()));
    }

    #[test]
    fn none_name_is_always_unique() {
        let mut d = NameDeduper::new();
        assert_eq!(d.get_unique_name(None), None);
        assert_eq!(d.get_unique_name(None), None);
    }

    #[test]
    fn is_unique_name_none_is_true() {
        let d = NameDeduper::new();
        assert!(d.is_unique_name(None));
    }

    #[test]
    fn is_unique_name_after_use() {
        let mut d = NameDeduper::new();
        d.get_unique_name(Some("bar"));
        assert!(!d.is_unique_name(Some("bar")));
        assert!(d.is_unique_name(Some("baz")));
    }

    #[test]
    fn add_used_names_blocks_reuse() {
        let mut d = NameDeduper::new();
        d.add_used_names(["alpha", "beta"]);
        assert!(!d.is_unique_name(Some("alpha")));
        assert_eq!(d.get_unique_name(Some("alpha")), Some("alpha_1".to_string()));
    }

    #[test]
    fn reserved_names_skipped_during_generation() {
        let mut d = NameDeduper::new();
        d.get_unique_name(Some("x"));
        d.add_reserved_names(["x_1"]);
        assert_eq!(d.get_unique_name(Some("x")), Some("x_2".to_string()));
    }

    #[test]
    fn reserved_names_do_not_block_is_unique() {
        let mut d = NameDeduper::new();
        d.add_reserved_names(["y"]);
        assert!(d.is_unique_name(Some("y")));
    }

    #[test]
    fn reserved_names_do_not_block_direct_allocation() {
        let mut d = NameDeduper::new();
        d.add_reserved_names(["z"]);
        assert_eq!(d.get_unique_name(Some("z")), None);
    }
}
