use std::fmt;

/// DWARF line-number program machine state registers.
///
/// Tracks the state of the DWARF line-number program virtual machine as
/// described in the DWARF specification. Each row in the line-number matrix
/// corresponds to a snapshot of this state.
///
/// Mirrors Ghidra's `DWARFLineProgramState`.
#[derive(Debug, Clone)]
pub struct DWARFLineProgramState {
    /// Program-counter value corresponding to a machine instruction generated by the compiler.
    pub address: u64,
    /// Unsigned integer identifying the source file for a machine instruction.
    pub file: u32,
    /// Unsigned integer indicating a source line number. Lines begin at 1;
    /// 0 means the instruction cannot be attributed to any source line.
    pub line: u32,
    /// Unsigned integer indicating a column number within a source line.
    /// Columns begin at 1; 0 means the left edge of the line.
    pub column: u32,
    /// True when the current instruction is the beginning of a statement.
    pub is_statement: bool,
    /// True when the current instruction is the beginning of a basic block.
    pub is_basic_block: bool,
    /// True when the current address is the first byte after the end of a
    /// sequence of target machine instructions.
    pub is_end_sequence: bool,
    pub prologue_end: bool,
    pub epilogue_begin: bool,
    pub isa: u64,
    pub discriminator: u64,
    /// True when the row is based on instructions likely attached to a
    /// dead/tombstoned location.
    pub tombstone: bool,
}

impl DWARFLineProgramState {
    /// Creates a new state with default register values.
    ///
    /// `default_is_statement` initialises the `is_statement` register, which
    /// is set by the `default_is_stmt` field of the line-number program header.
    pub fn new(default_is_statement: bool) -> Self {
        Self {
            address: 0,
            file: 1,
            line: 1,
            column: 0,
            is_statement: default_is_statement,
            is_basic_block: false,
            is_end_sequence: false,
            prologue_end: false,
            epilogue_begin: false,
            isa: 0,
            discriminator: 0,
            tombstone: false,
        }
    }

    /// Returns `true` when `self` and `other` refer to the same source file and line.
    pub fn is_same_file_line(&self, other: &DWARFLineProgramState) -> bool {
        self.file == other.file && self.line == other.line
    }
}

impl fmt::Display for DWARFLineProgramState {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(
            f,
            "DWARFLineProgramState [address={}, file={}, line={}, column={}, \
             isStatement={}, isBasicBlock={}, isEndSequence={}, prologueEnd={}, \
             epilogueBegin={}, isa={}, discriminator={}, tombstone={}]",
            self.address,
            self.file,
            self.line,
            self.column,
            self.is_statement,
            self.is_basic_block,
            self.is_end_sequence,
            self.prologue_end,
            self.epilogue_begin,
            self.isa,
            self.discriminator,
            self.tombstone,
        )
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn default_field_values() {
        let s = DWARFLineProgramState::new(true);
        assert_eq!(s.address, 0);
        assert_eq!(s.file, 1);
        assert_eq!(s.line, 1);
        assert_eq!(s.column, 0);
        assert!(s.is_statement);
        assert!(!s.is_basic_block);
        assert!(!s.is_end_sequence);
        assert!(!s.prologue_end);
        assert!(!s.epilogue_begin);
        assert_eq!(s.isa, 0);
        assert_eq!(s.discriminator, 0);
        assert!(!s.tombstone);
    }

    #[test]
    fn default_is_statement_false() {
        let s = DWARFLineProgramState::new(false);
        assert!(!s.is_statement);
    }

    #[test]
    fn clone_produces_independent_copy() {
        let mut original = DWARFLineProgramState::new(true);
        original.address = 0xdeadbeef;
        original.file = 3;
        original.line = 42;
        original.column = 7;
        original.is_basic_block = true;
        original.tombstone = true;

        let copy = original.clone();
        assert_eq!(copy.address, 0xdeadbeef);
        assert_eq!(copy.file, 3);
        assert_eq!(copy.line, 42);
        assert_eq!(copy.column, 7);
        assert!(copy.is_statement);
        assert!(copy.is_basic_block);
        assert!(copy.tombstone);
    }

    #[test]
    fn clone_is_independent() {
        let mut original = DWARFLineProgramState::new(false);
        original.line = 10;
        let copy = original.clone();
        assert_eq!(copy.line, 10);
        // Mutating original must not affect the clone.
        original.line = 20;
        assert_eq!(copy.line, 10);
    }

    #[test]
    fn is_same_file_line_matches() {
        let mut a = DWARFLineProgramState::new(true);
        a.file = 2;
        a.line = 100;
        let mut b = DWARFLineProgramState::new(false);
        b.file = 2;
        b.line = 100;
        assert!(a.is_same_file_line(&b));
    }

    #[test]
    fn is_same_file_line_different_file() {
        let mut a = DWARFLineProgramState::new(true);
        a.file = 1;
        a.line = 10;
        let mut b = DWARFLineProgramState::new(true);
        b.file = 2;
        b.line = 10;
        assert!(!a.is_same_file_line(&b));
    }

    #[test]
    fn is_same_file_line_different_line() {
        let mut a = DWARFLineProgramState::new(true);
        a.file = 1;
        a.line = 10;
        let mut b = DWARFLineProgramState::new(true);
        b.file = 1;
        b.line = 11;
        assert!(!a.is_same_file_line(&b));
    }

    #[test]
    fn display_contains_all_fields() {
        let mut s = DWARFLineProgramState::new(true);
        s.address = 0x1000;
        s.file = 2;
        s.line = 5;
        s.column = 3;
        s.is_basic_block = true;
        s.is_end_sequence = true;
        s.prologue_end = true;
        s.epilogue_begin = true;
        s.isa = 7;
        s.discriminator = 9;
        s.tombstone = true;

        let text = s.to_string();
        assert!(text.contains("address=4096"));
        assert!(text.contains("file=2"));
        assert!(text.contains("line=5"));
        assert!(text.contains("column=3"));
        assert!(text.contains("isStatement=true"));
        assert!(text.contains("isBasicBlock=true"));
        assert!(text.contains("isEndSequence=true"));
        assert!(text.contains("prologueEnd=true"));
        assert!(text.contains("epilogueBegin=true"));
        assert!(text.contains("isa=7"));
        assert!(text.contains("discriminator=9"));
        assert!(text.contains("tombstone=true"));
    }

    #[test]
    fn reflexive_is_same_file_line() {
        let s = DWARFLineProgramState::new(true);
        assert!(s.is_same_file_line(&s));
    }
}
