/// Marker trait signaling that the implementing action is temporary and gets built
/// automatically by the tool.
///
/// Corresponds to `docking.actions.AutoGeneratedDockingAction`.
pub trait AutoGeneratedDockingAction {}

#[cfg(test)]
mod tests {
    use super::*;

    struct ConcreteAction;
    impl AutoGeneratedDockingAction for ConcreteAction {}

    #[test]
    fn marker_trait_implementable() {
        let _action = ConcreteAction;
    }

    #[test]
    fn trait_object_usable() {
        let action: &dyn AutoGeneratedDockingAction = &ConcreteAction;
        let _ = action;
    }
}
