//! Method access flags for Java class method members.
//!
//! Ported from `ghidra.javaclass.flags.MethodsInfoAccessFlags`.

/// Declared public; may be accessed from outside its package.
pub const ACC_PUBLIC: u16 = 0x0001;

/// Declared private; accessible only within the defining class.
pub const ACC_PRIVATE: u16 = 0x0002;

/// Declared protected; may be accessed within subclasses.
pub const ACC_PROTECTED: u16 = 0x0004;

/// Declared static.
pub const ACC_STATIC: u16 = 0x0008;

/// Declared final; must not be overridden.
pub const ACC_FINAL: u16 = 0x0010;

/// Declared synchronized; invocation is wrapped by a monitor use.
pub const ACC_SYNCHRONIZED: u16 = 0x0020;

/// A bridge method, generated by the compiler.
pub const ACC_BRIDGE: u16 = 0x0040;

/// Declared with variable number of arguments.
pub const ACC_VARARGS: u16 = 0x0080;

/// Declared native; implemented in a language other than Java.
pub const ACC_NATIVE: u16 = 0x0100;

/// Declared abstract; no implementation is provided.
pub const ACC_ABSTRACT: u16 = 0x0400;

/// Declared strictfp; floating-point mode is FP-strict.
pub const ACC_STRICT: u16 = 0x0800;

/// Declared synthetic; not present in the source code.
pub const ACC_SYNTHETIC: u16 = 0x1000;

/// Return a text representation for a given set of access flags.
/// Only flags that map to Java modifier keywords are returned.
/// Returns examples like "public static final", "package private", or "protected".
pub fn format_access_flags(access: u16) -> String {
    let mut result = String::new();

    if (access & ACC_PUBLIC) == ACC_PUBLIC {
        result.push_str("public ");
    }
    if (access & ACC_PRIVATE) == ACC_PRIVATE {
        result.push_str("private ");
    }
    if (access & ACC_PROTECTED) == ACC_PROTECTED {
        result.push_str("protected ");
    }
    if (access & ACC_STATIC) == ACC_STATIC {
        result.push_str("static ");
    }
    if (access & ACC_FINAL) == ACC_FINAL {
        result.push_str("final ");
    }
    if (access & ACC_SYNCHRONIZED) == ACC_SYNCHRONIZED {
        result.push_str("synchronized ");
    }
    if (access & ACC_NATIVE) == ACC_NATIVE {
        result.push_str("native ");
    }
    if (access & ACC_ABSTRACT) == ACC_ABSTRACT {
        result.push_str("abstract ");
    }

    result.trim_end().to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn flag_values_match_java_source() {
        assert_eq!(ACC_PUBLIC, 0x0001);
        assert_eq!(ACC_PRIVATE, 0x0002);
        assert_eq!(ACC_PROTECTED, 0x0004);
        assert_eq!(ACC_STATIC, 0x0008);
        assert_eq!(ACC_FINAL, 0x0010);
        assert_eq!(ACC_SYNCHRONIZED, 0x0020);
        assert_eq!(ACC_BRIDGE, 0x0040);
        assert_eq!(ACC_VARARGS, 0x0080);
        assert_eq!(ACC_NATIVE, 0x0100);
        assert_eq!(ACC_ABSTRACT, 0x0400);
        assert_eq!(ACC_STRICT, 0x0800);
        assert_eq!(ACC_SYNTHETIC, 0x1000);
    }

    #[test]
    fn all_flags_are_distinct() {
        let mut all = vec![
            ACC_PUBLIC,
            ACC_PRIVATE,
            ACC_PROTECTED,
            ACC_STATIC,
            ACC_FINAL,
            ACC_SYNCHRONIZED,
            ACC_BRIDGE,
            ACC_VARARGS,
            ACC_NATIVE,
            ACC_ABSTRACT,
            ACC_STRICT,
            ACC_SYNTHETIC,
        ];
        all.sort();
        let count = all.len();
        all.dedup();
        assert_eq!(all.len(), count, "duplicate flag value detected");
    }

    #[test]
    fn flags_are_non_zero() {
        let flags = [
            ACC_PUBLIC,
            ACC_PRIVATE,
            ACC_PROTECTED,
            ACC_STATIC,
            ACC_FINAL,
            ACC_SYNCHRONIZED,
            ACC_BRIDGE,
            ACC_VARARGS,
            ACC_NATIVE,
            ACC_ABSTRACT,
            ACC_STRICT,
            ACC_SYNTHETIC,
        ];
        for flag in flags.iter() {
            assert_ne!(*flag, 0, "flag value should not be zero");
        }
    }

    #[test]
    fn flags_can_be_combined() {
        let public_static = ACC_PUBLIC | ACC_STATIC;
        assert_eq!(public_static, 0x0009);
        assert!(public_static & ACC_PUBLIC != 0);
        assert!(public_static & ACC_STATIC != 0);
        assert!(public_static & ACC_PRIVATE == 0);

        let private_final = ACC_PRIVATE | ACC_FINAL;
        assert_eq!(private_final, 0x0012);
        assert!(private_final & ACC_PRIVATE != 0);
        assert!(private_final & ACC_FINAL != 0);
        assert!(private_final & ACC_PUBLIC == 0);
    }

    #[test]
    fn format_single_flags() {
        assert_eq!(format_access_flags(ACC_PUBLIC), "public");
        assert_eq!(format_access_flags(ACC_PRIVATE), "private");
        assert_eq!(format_access_flags(ACC_PROTECTED), "protected");
        assert_eq!(format_access_flags(ACC_STATIC), "static");
        assert_eq!(format_access_flags(ACC_FINAL), "final");
    }

    #[test]
    fn format_combined_flags() {
        assert_eq!(format_access_flags(ACC_PUBLIC | ACC_STATIC | ACC_FINAL), "public static final");
        assert_eq!(format_access_flags(ACC_PUBLIC | ACC_ABSTRACT), "public abstract");
        assert_eq!(format_access_flags(ACC_PRIVATE | ACC_SYNCHRONIZED), "private synchronized");
    }

    #[test]
    fn format_excludes_non_modifier_flags() {
        let with_bridge = ACC_PUBLIC | ACC_BRIDGE | ACC_STATIC;
        assert_eq!(format_access_flags(with_bridge), "public static");

        let with_varargs = ACC_PROTECTED | ACC_VARARGS;
        assert_eq!(format_access_flags(with_varargs), "protected");

        let with_synthetic = ACC_NATIVE | ACC_SYNTHETIC;
        assert_eq!(format_access_flags(with_synthetic), "native");

        let with_strict = ACC_ABSTRACT | ACC_STRICT;
        assert_eq!(format_access_flags(with_strict), "abstract");
    }

    #[test]
    fn format_empty_flags() {
        assert_eq!(format_access_flags(0), "");
    }

    #[test]
    fn test_to_string_public_static_final_synchronized() {
        let flags = ACC_PUBLIC | ACC_STATIC | ACC_FINAL | ACC_SYNCHRONIZED;
        assert_eq!(format_access_flags(flags), "public static final synchronized");
    }

    #[test]
    fn test_to_string_protected_native() {
        let flags = ACC_PROTECTED | ACC_NATIVE;
        assert_eq!(format_access_flags(flags), "protected native");
    }

    #[test]
    fn test_to_string_private_abstract() {
        let flags = ACC_PRIVATE | ACC_ABSTRACT;
        assert_eq!(format_access_flags(flags), "private abstract");
    }
}
