use std::collections::HashMap;
use std::fmt;
use std::sync::Arc;

use crate::app::util::pcode::abstract_appender::{AbstractAppender, AbstractAppenderBase};
use crate::app::util::pcode::abstract_pcode_formatter::{
    is_line_label, AbstractPcodeFormatter, FormatResult,
};
use crate::app::util::pcode::appender::Appender;
use crate::app::util::pcode::pcode_formatter::PcodeFormatter;
use crate::pcode::error::lowlevel_error::LowlevelError;
use crate::program::model::address::AddressSpace;
use crate::program::model::lang::language::Language;
use crate::program::model::lang::register::Register;
use crate::program::model::lang::sleigh::template::OpTpl;
use crate::program::model::pcode::PcodeOp;
use crate::util::msg::Msg;

/// The executor's internal counter.
///
/// Port of `ghidra.pcode.exec.PcodeFrame`.
///
/// To distinguish the program counter of a p-code program from the program counter of the machine
/// it models, we address p-code ops by "index." When derived from an instruction, the address and
/// index together form the "sequence number." Because the executor cares not about the derivation
/// of a p-code program, it counts through indices. The frame carries with it the p-code ops
/// comprising its current p-code program.
///
/// A p-code emulator feeds p-code to an executor by decoding one instruction at a time. Thus, the
/// "current p-code program" comprises only those ops generated by a single instruction. Or else, it
/// is a user-supplied p-code program, e.g., to evaluate a Sleigh expression. The frame completes
/// the program by falling-through, i.e., stepping past the final op, or by branching externally,
/// i.e., to a different machine instruction. The emulator must then update its program counter
/// accordingly and proceed to the next instruction.
pub struct PcodeFrame {
    language: Arc<dyn Language>,
    /// Java takes a shared *immutable* `List<PcodeOp>` here and hands it straight back from
    /// `getCode()`, relying on the caller's immutable copy for safety. Rust gets the same guarantee
    /// from ownership: the frame owns the ops and [`code`](Self::code) lends out only a shared
    /// slice, so no caller can mutate them.
    code: Vec<PcodeOp>,
    userop_names: HashMap<i32, String>,

    count: i32,
    index: i32,
    branched: i32,
}

impl PcodeFrame {
    /// Construct a frame of p-code execution.
    ///
    /// `language` is the language to which the program applies, `code` is the program's p-code, and
    /// `userop_names` maps additional sleigh/p-code userop numbers to their names.
    pub fn new(
        language: Arc<dyn Language>,
        code: Vec<PcodeOp>,
        userop_names: HashMap<i32, String>,
    ) -> Self {
        PcodeFrame {
            language,
            code,
            userop_names,
            count: 0,
            index: 0,
            branched: -1,
        }
    }

    /// Get and reset the number of p-code ops executed.
    ///
    /// Contrast this to [`index`](Self::index), which marks the next op to be executed. This counts
    /// the number of ops executed, which will differ from the index when an internal branch is
    /// taken.
    pub fn reset_count(&mut self) -> i32 {
        std::mem::replace(&mut self.count, 0)
    }

    /// The index of the *next* p-code op to be executed.
    ///
    /// If the last p-code op resulted in a branch, this will instead return -1.
    ///
    /// See [`is_branch`](Self::is_branch), [`is_fall_through`](Self::is_fall_through), and
    /// [`is_finished`](Self::is_finished).
    pub fn index(&self) -> i32 {
        self.index
    }

    /// Get the op at the current index, and then advance that index.
    ///
    /// This is used in the execution loop to retrieve each op to execute.
    ///
    /// # Panics
    ///
    /// Panics if the index is out of range, mirroring the `IndexOutOfBoundsException` Java's
    /// `List.get` would throw.
    pub fn next_op(&mut self) -> &PcodeOp {
        let i = self.advance();
        &self.code[i as usize]
    }

    /// Advance the index, returning its value *before* it was advanced.
    pub fn advance(&mut self) -> i32 {
        self.count += 1;
        let index = self.index;
        self.index += 1;
        index
    }

    /// Step the index back one, returning its value *before* it was stepped back.
    pub fn step_back(&mut self) -> i32 {
        self.count -= 1;
        let index = self.index;
        self.index -= 1;
        index
    }

    /// Get the name of the userop for the given number, as expressed in the Sleigh source.
    ///
    /// `userop` is the userop number, as encoded in the first operand of `PcodeOp::CALLOTHER`.
    pub fn get_userop_name(&self, userop: i32) -> Option<&str> {
        self.userop_names.get(&userop).map(String::as_str)
    }

    /// Get the map of userop numbers to names.
    pub fn userop_names(&self) -> &HashMap<i32, String> {
        &self.userop_names
    }

    /// Check if the index has advanced past the end of the p-code program.
    ///
    /// If the index has advanced beyond the program, it implies the program has finished executing.
    /// In the case of instruction emulation, no branch was encountered. The machine should advance
    /// to the fall-through instruction.
    pub fn is_fall_through(&self) -> bool {
        self.index as usize == self.code.len()
    }

    /// Check if the p-code program has executed a branch.
    ///
    /// Branches can be internal, i.e., within the current program, or external, i.e., to another
    /// machine instruction. This refers strictly to the latter.
    pub fn is_branch(&self) -> bool {
        self.index == -1
    }

    /// Check if the p-code program is completely executed, either in fall-through or an external
    /// branch.
    pub fn is_finished(&self) -> bool {
        !(0 <= self.index && (self.index as usize) < self.code.len())
    }

    /// Perform an internal branch, relative to the *current op*.
    ///
    /// Because the index advances before execution of each op, `rel` is adjusted by an extra -1.
    ///
    /// Returns a [`LowlevelError`] if the resulting index falls outside the program.
    pub fn branch(&mut self, rel: i32) -> Result<(), LowlevelError> {
        self.index += rel - 1; // -1 because we already advanced
        if !(0 <= self.index && self.index as usize <= self.code.len()) {
            return Err(LowlevelError::with_message("Bad p-code branch"));
        }
        Ok(())
    }

    /// Complete the p-code program, indicating an external branch.
    pub fn finish_as_branch(&mut self) {
        self.branched = self.index - 1; // -1 because we already advanced
        self.index = -1;
    }

    /// Get all the ops in the current p-code program.
    pub fn code(&self) -> &[PcodeOp] {
        &self.code
    }

    /// Copy the frame's code (shallow copy) into a new vector.
    pub fn copy_code(&self) -> Vec<PcodeOp> {
        self.code.clone()
    }

    /// Get the index of the last (branch) op executed.
    ///
    /// The behavior here is a bit strange for compatibility with
    /// [`EmulateInstructionStateModifier`](crate::pcode::emulate::emulate_instruction_state_modifier::EmulateInstructionStateModifier).
    /// If the p-code program (likely derived from a machine instruction) completed with
    /// fall-through, then this will return -1. If it completed on a branch, then this will return
    /// the index of that branch.
    pub fn branched(&self) -> i32 {
        self.branched
    }
}

impl fmt::Display for PcodeFrame {
    /// Port of `PcodeFrame.toString()`, which formats the frame's ops with its private
    /// `MyFormatter`.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let formatter = FrameFormatter { frame: self };
        f.write_str(&formatter.format_ops(self.language.as_ref(), &self.code))
    }
}

/// Port of `PcodeFrame.MyAppender`, an `AbstractAppender<String>` that renders the frame's ops with
/// markers for the current index and the branched-from index.
///
/// Java's inner class reads the enclosing frame's fields directly; here it borrows the frame.
struct FrameAppender<'a> {
    base: AbstractAppenderBase,
    frame: &'a PcodeFrame,
    buf: String,
    is_line_label: bool,
    i: i32,
}

impl<'a> FrameAppender<'a> {
    fn new(frame: &'a PcodeFrame, language: Arc<dyn Language>) -> Self {
        let mut buf = format!("<p-code frame: index={}", frame.index);
        if frame.branched != -1 {
            buf.push_str(&format!(" branched={}", frame.branched));
        }
        buf.push_str(" {\n");
        FrameAppender {
            base: AbstractAppenderBase::new(language, true),
            frame,
            buf,
            is_line_label: false,
            i: 0,
        }
    }

    /// Terminate the current line, counting it as an op unless it was a line label.
    fn end_line(&mut self) {
        if !self.is_line_label {
            self.i += 1;
        }
        self.buf.push('\n');
    }

    /// Port of `MyAppender.stringifyUseropUnchecked`, which falls back to the frame's own userop
    /// names when the language doesn't know the id.
    ///
    /// The base's counterpart is an inherent method rather than an overridable one, so the fallback
    /// is spliced in here and [`Appender::append_userop`] calls this instead of
    /// `AbstractAppenderBase::stringify_userop`.
    fn stringify_userop_unchecked(&self, id: i32) -> Option<String> {
        self.base
            .stringify_userop_unchecked(id)
            .or_else(|| self.frame.get_userop_name(id).map(str::to_string))
    }
}

impl Appender for FrameAppender<'_> {
    type Output = String;

    fn get_language(&self) -> Arc<dyn Language> {
        self.base.language()
    }

    fn append_line_label(&mut self, label: i64) {
        self.append_string("  ");
        let s = AbstractAppenderBase::stringify_line_label(label);
        self.append_string(&s);
    }

    fn append_indent(&mut self) {
        if self.is_line_label {
            self.append_string("    ");
        }
        if self.i == self.frame.branched {
            self.append_string(" *> ");
        } else if self.i == self.frame.index {
            self.append_string(" -> ");
        } else {
            self.append_string("    ");
        }
    }

    fn append_line_label_ref(&mut self, label: i64) {
        AbstractAppenderBase::append_line_label_ref(self, label);
    }

    fn append_mnemonic(&mut self, opcode: i32) {
        AbstractAppenderBase::append_mnemonic(self, opcode);
    }

    fn append_userop(&mut self, id: i32) {
        let name = match self.stringify_userop_unchecked(id) {
            Some(name) => name,
            None => {
                Msg::error("PcodeFrame", &format!("Pseudo-op index not found: {id}"));
                "unknown".to_string()
            }
        };
        self.append_string(&name);
    }

    fn append_raw_varnode(&mut self, space: &AddressSpace, offset: i64, size: i64) {
        AbstractAppenderBase::append_raw_varnode(self, space, offset, size);
    }

    fn append_character(&mut self, c: char) {
        AbstractAppenderBase::append_character(self, c);
    }

    fn append_address_word_offcut(&mut self, word_offset: i64, offcut: i64) {
        AbstractAppenderBase::append_address_word_offcut(self, word_offset, offcut);
    }

    fn append_label(&mut self, label: &str) {
        AbstractAppenderBase::append_label(self, label);
    }

    fn append_register(&mut self, register: &Register) {
        AbstractAppenderBase::append_register(self, register);
    }

    fn append_scalar(&mut self, value: i64) {
        AbstractAppenderBase::append_scalar(self, value);
    }

    fn append_space(&mut self, space: &AddressSpace) {
        AbstractAppenderBase::append_space(self, space);
    }

    fn append_unique(&mut self, offset: i64) {
        AbstractAppenderBase::append_unique(self, offset);
    }

    fn finish(&mut self) -> String {
        if self.frame.is_fall_through() {
            self.buf.push_str(" *> fall-through\n");
        }
        self.buf.push_str("}>");
        std::mem::take(&mut self.buf)
    }
}

impl AbstractAppender for FrameAppender<'_> {
    fn append_string(&mut self, string: &str) {
        self.buf.push_str(string);
    }
}

/// Port of `PcodeFrame.MyFormatter`.
struct FrameFormatter<'a> {
    frame: &'a PcodeFrame,
}

impl<'a> AbstractPcodeFormatter for FrameFormatter<'a> {
    type Appender = FrameAppender<'a>;

    fn create_appender(&self, language: Arc<dyn Language>, _indent: bool) -> FrameAppender<'a> {
        // Java's `MyAppender(Language)` always passes `indent = true` to super, ignoring the flag
        // computed by `formatTemplates` -- and then overrides `appendIndent` anyway.
        FrameAppender::new(self.frame, language)
    }

    /// Java overrides `formatOpTemplate` to set the appender's `isLineLabel` flag, call `super`,
    /// and then end the line. Rust can't call a trait's default method body from an override, so
    /// the wrapping happens in the loop instead; the observable order -- flag, format, end line,
    /// then honour `Terminate` -- is identical.
    fn format_op_templates(
        &self,
        language: Arc<dyn Language>,
        pcode_op_templates: &[OpTpl],
    ) -> String {
        let indent = pcode_op_templates.iter().any(is_line_label);
        let mut appender = self.create_appender(language, indent);

        for template in pcode_op_templates {
            appender.is_line_label = is_line_label(template);
            let result = self.format_op_template(&mut appender, template);
            appender.end_line();
            if result == FormatResult::Terminate {
                break;
            }
        }
        appender.finish()
    }
}

impl PcodeFormatter<String> for FrameFormatter<'_> {
    fn format_templates(&self, _language: &dyn Language, pcode_op_templates: &[OpTpl]) -> String {
        // The appender needs an owned `Arc<dyn Language>`, which the frame already holds; it is the
        // same language `format_ops` was handed.
        self.format_op_templates(Arc::clone(&self.frame.language), pcode_op_templates)
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::app::plugin::processors::generic::MemoryBlockDefinition;
    use crate::program::model::address::{
        Address, AddressFactory, AddressSet, AddressSetView, AddressSpaceType,
        DefaultAddressFactory,
    };
    use crate::program::model::lang::compiler_spec::CompilerSpec;
    use crate::program::model::lang::compiler_spec_description::CompilerSpecDescription;
    use crate::program::model::lang::compiler_spec_id::CompilerSpecID;
    use crate::program::model::lang::compiler_spec_not_found_exception::CompilerSpecNotFoundException;
    use crate::program::model::lang::instruction_prototype::InstructionPrototype;
    use crate::program::model::lang::language::ParseError;
    use crate::program::model::lang::language_description::LanguageDescription;
    use crate::program::model::lang::language_id::LanguageID;
    use crate::program::model::lang::parallel_instruction_language_helper::ParallelInstructionLanguageHelper;
    use crate::program::model::lang::processor_context::ProcessorContext;
    use crate::program::model::lang::register::RegisterRef;
    use crate::program::model::lang::unknown_instruction_exception::UnknownInstructionException;
    use crate::program::model::listing::default_program_context::DefaultProgramContext;
    use crate::program::model::mem::MemBuffer;
    use crate::program::model::pcode::{OpCode, SequenceNumber, Varnode};
    use crate::program::seam_stubs::{AddressLabelInfo, Processor};
    use crate::util::task::TaskMonitor;
    use std::collections::HashSet;

    struct Spaces {
        ram: Arc<AddressSpace>,
        constant: Arc<AddressSpace>,
    }

    fn spaces() -> Spaces {
        Spaces {
            ram: AddressSpace::new("ram", 32, 1, AddressSpaceType::Ram, 0),
            constant: AddressSpace::new("const", 64, 1, AddressSpaceType::Constant, 1),
        }
    }

    struct MockLanguage {
        factory: DefaultAddressFactory,
    }

    impl MockLanguage {
        fn new(spaces: &Spaces) -> Self {
            MockLanguage {
                factory: DefaultAddressFactory::new(vec![
                    spaces.ram.clone(),
                    spaces.constant.clone(),
                ]),
            }
        }
    }

    impl Language for MockLanguage {
        fn get_language_id(&self) -> LanguageID {
            LanguageID::new("x86:LE:32:default").unwrap()
        }
        fn get_language_description(&self) -> Box<dyn LanguageDescription> {
            unimplemented!("not exercised by these tests")
        }
        fn get_parallel_instruction_helper(
            &self,
        ) -> Option<Box<dyn ParallelInstructionLanguageHelper>> {
            None
        }
        fn get_processor(&self) -> Box<dyn Processor> {
            unimplemented!("not exercised by these tests")
        }
        fn get_version(&self) -> i32 {
            1
        }
        fn get_minor_version(&self) -> i32 {
            0
        }
        fn get_address_factory(&self) -> Box<dyn AddressFactory> {
            Box::new(self.factory.clone())
        }
        fn get_default_space(&self) -> Arc<AddressSpace> {
            self.factory.get_default_address_space().unwrap()
        }
        fn get_default_data_space(&self) -> Arc<AddressSpace> {
            self.get_default_space()
        }
        fn is_big_endian(&self) -> bool {
            false
        }
        fn get_instruction_alignment(&self) -> i32 {
            1
        }
        fn supports_pcode(&self) -> bool {
            true
        }
        fn is_volatile(&self, _addr: &Address) -> bool {
            false
        }
        fn parse(
            &self,
            _buf: &dyn MemBuffer,
            _context: &mut dyn ProcessorContext,
            _in_delay_slot: bool,
        ) -> Result<Box<dyn InstructionPrototype>, ParseError> {
            Err(ParseError::UnknownInstruction(UnknownInstructionException::new()))
        }
        fn get_number_of_user_defined_op_names(&self) -> i32 {
            1
        }
        fn get_user_defined_op_name(&self, index: i32) -> Option<String> {
            // Only op 0 is known to the language; the frame supplies the rest.
            if index == 0 {
                Some("lang_op".to_string())
            } else {
                None
            }
        }
        fn get_registers_at(&self, _address: &Address) -> Vec<RegisterRef> {
            Vec::new()
        }
        fn get_register_in_space(
            &self,
            _addrspc: &Arc<AddressSpace>,
            _offset: i64,
            _size: i32,
        ) -> Option<RegisterRef> {
            None
        }
        fn get_registers(&self) -> Vec<RegisterRef> {
            Vec::new()
        }
        fn get_register_names(&self) -> Vec<String> {
            Vec::new()
        }
        fn get_register_by_name(&self, _name: &str) -> Option<RegisterRef> {
            None
        }
        fn get_register_at(&self, _addr: &Address, _size: i32) -> Option<RegisterRef> {
            None
        }
        fn get_program_counter(&self) -> Option<RegisterRef> {
            None
        }
        fn get_context_base_register(&self) -> Option<RegisterRef> {
            None
        }
        fn get_context_registers(&self) -> Vec<RegisterRef> {
            Vec::new()
        }
        fn get_default_memory_blocks(&self) -> Vec<Box<dyn MemoryBlockDefinition>> {
            Vec::new()
        }
        fn get_default_symbols(&self) -> Vec<Box<dyn AddressLabelInfo>> {
            Vec::new()
        }
        fn get_segmented_space(&self) -> String {
            String::new()
        }
        fn get_volatile_addresses(&self) -> Box<dyn AddressSetView> {
            Box::new(AddressSet::new())
        }
        fn apply_context_settings(&self, _ctx: &mut dyn DefaultProgramContext) {}
        fn reload_language(&self, _task_monitor: &dyn TaskMonitor) -> std::io::Result<()> {
            Ok(())
        }
        fn get_compatible_compiler_spec_descriptions(
            &self,
        ) -> Vec<Box<dyn CompilerSpecDescription>> {
            Vec::new()
        }
        fn get_compiler_spec_by_id(
            &self,
            compiler_spec_id: &CompilerSpecID,
        ) -> Result<Box<dyn CompilerSpec>, CompilerSpecNotFoundException> {
            Err(CompilerSpecNotFoundException::new(&self.get_language_id(), compiler_spec_id))
        }
        fn get_default_compiler_spec(&self) -> Box<dyn CompilerSpec> {
            unimplemented!("not exercised by these tests")
        }
        fn has_property(&self, _key: &str) -> bool {
            false
        }
        fn get_property_as_int(&self, _key: &str, default_int: i32) -> i32 {
            default_int
        }
        fn get_property_as_boolean(&self, _key: &str, default_boolean: bool) -> bool {
            default_boolean
        }
        fn get_property_or(&self, _key: &str, default_string: &str) -> String {
            default_string.to_string()
        }
        fn get_property(&self, _key: &str) -> Option<String> {
            None
        }
        fn get_property_keys(&self) -> HashSet<String> {
            HashSet::new()
        }
        fn has_manual(&self) -> bool {
            false
        }
        fn get_manual_entry(
            &self,
            _instruction_mnemonic: &str,
        ) -> Option<crate::util::manual_entry::ManualEntry> {
            None
        }
        fn get_manual_instruction_mnemonic_keys(&self) -> HashSet<String> {
            HashSet::new()
        }
        fn get_manual_exception(&self) -> Option<Box<dyn std::error::Error + Send + Sync + 'static>> {
            None
        }
        fn get_sorted_vector_registers(&self) -> Vec<RegisterRef> {
            Vec::new()
        }
        fn get_register_addresses(&self) -> Box<dyn AddressSetView> {
            Box::new(AddressSet::new())
        }
        fn get_maximum_instruction_length(&self) -> Option<i32> {
            None
        }
    }

    /// `r0 = COPY r1`, in terms of two RAM locations (the mock language has no registers).
    fn copy_op(s: &Spaces, at: i64) -> PcodeOp {
        PcodeOp::new(
            OpCode::Copy,
            SequenceNumber::new(Address::new(s.ram.clone(), at), 0),
            vec![Varnode::new(Address::new(s.ram.clone(), 0x10), 1)],
            Some(Varnode::new(Address::new(s.ram.clone(), 0x14), 1)),
        )
    }

    fn frame(s: &Spaces, code: Vec<PcodeOp>, userops: HashMap<i32, String>) -> PcodeFrame {
        PcodeFrame::new(Arc::new(MockLanguage::new(s)), code, userops)
    }

    #[test]
    fn new_frame_starts_at_index_zero_unbranched() {
        let s = spaces();
        let f = frame(&s, vec![copy_op(&s, 0x1000)], HashMap::new());

        assert_eq!(f.index(), 0);
        assert_eq!(f.branched(), -1);
        assert!(!f.is_fall_through());
        assert!(!f.is_branch());
        assert!(!f.is_finished());
        assert_eq!(f.code().len(), 1);
    }

    #[test]
    fn advance_counts_ops_and_reset_count_clears() {
        let s = spaces();
        let mut f = frame(&s, vec![copy_op(&s, 0x1000), copy_op(&s, 0x1001)], HashMap::new());

        assert_eq!(f.advance(), 0);
        assert_eq!(f.advance(), 1);
        assert_eq!(f.index(), 2);
        // Java: resetCount() returns the running count, then zeroes it.
        assert_eq!(f.reset_count(), 2);
        assert_eq!(f.reset_count(), 0);
        // ... and the index is untouched by the reset.
        assert_eq!(f.index(), 2);
    }

    #[test]
    fn next_op_returns_op_at_index_then_advances() {
        let s = spaces();
        let mut f = frame(&s, vec![copy_op(&s, 0x1000), copy_op(&s, 0x1001)], HashMap::new());

        assert_eq!(f.next_op().seqnum.pc.offset(), 0x1000);
        assert_eq!(f.index(), 1);
        assert_eq!(f.next_op().seqnum.pc.offset(), 0x1001);
        assert!(f.is_fall_through());
        assert!(f.is_finished());
        assert!(!f.is_branch());
    }

    #[test]
    fn step_back_undoes_advance() {
        let s = spaces();
        let mut f = frame(&s, vec![copy_op(&s, 0x1000)], HashMap::new());

        f.advance();
        // stepBack returns the index *before* stepping back.
        assert_eq!(f.step_back(), 1);
        assert_eq!(f.index(), 0);
        assert_eq!(f.reset_count(), 0);
    }

    #[test]
    fn branch_is_relative_to_current_op() {
        let s = spaces();
        let mut f = frame(
            &s,
            vec![copy_op(&s, 0x1000), copy_op(&s, 0x1001), copy_op(&s, 0x1002)],
            HashMap::new(),
        );

        f.advance(); // index = 1, we are "executing" op 0
        // A relative branch of +2 from op 0 lands on op 2.
        f.branch(2).unwrap();
        assert_eq!(f.index(), 2);

        // Branching back to op 0 from op 2 (index 3 after advancing) is rel = -2.
        f.advance();
        f.branch(-2).unwrap();
        assert_eq!(f.index(), 0);
    }

    #[test]
    fn branch_past_end_is_a_lowlevel_error() {
        let s = spaces();
        let mut f = frame(&s, vec![copy_op(&s, 0x1000)], HashMap::new());
        f.advance();

        let err = f.branch(5).unwrap_err();
        assert_eq!(err.message(), "Bad p-code branch");
    }

    #[test]
    fn branch_to_exactly_past_last_op_is_fall_through() {
        let s = spaces();
        let mut f = frame(&s, vec![copy_op(&s, 0x1000), copy_op(&s, 0x1001)], HashMap::new());
        f.advance(); // index = 1

        // Java allows index == code.size(); that's fall-through, not an error.
        f.branch(2).unwrap();
        assert_eq!(f.index(), 2);
        assert!(f.is_fall_through());
        assert!(f.is_finished());
    }

    #[test]
    fn finish_as_branch_records_last_op_and_marks_branch() {
        let s = spaces();
        let mut f = frame(&s, vec![copy_op(&s, 0x1000), copy_op(&s, 0x1001)], HashMap::new());

        f.advance();
        f.advance(); // index = 2, we are "executing" op 1
        f.finish_as_branch();

        assert_eq!(f.branched(), 1);
        assert_eq!(f.index(), -1);
        assert!(f.is_branch());
        assert!(f.is_finished());
        assert!(!f.is_fall_through());
    }

    #[test]
    fn userop_names_fall_back_to_the_frame_map() {
        let s = spaces();
        let f = frame(&s, Vec::new(), HashMap::from([(3, "frame_op".to_string())]));

        assert_eq!(f.get_userop_name(3), Some("frame_op"));
        assert_eq!(f.get_userop_name(4), None);
        assert_eq!(f.userop_names().len(), 1);
    }

    #[test]
    fn copy_code_is_a_shallow_copy() {
        let s = spaces();
        let f = frame(&s, vec![copy_op(&s, 0x1000)], HashMap::new());

        let copied = f.copy_code();
        assert_eq!(copied.len(), 1);
        assert_eq!(copied[0], f.code()[0]);
    }

    #[test]
    fn to_string_marks_the_current_index() {
        let s = spaces();
        let f = frame(&s, vec![copy_op(&s, 0x1000)], HashMap::new());

        assert_eq!(
            f.to_string(),
            "<p-code frame: index=0 {\n -> *[ram]0x14:1 = COPY *[ram]0x10:1\n}>"
        );
    }

    #[test]
    fn to_string_notes_fall_through_once_past_the_end() {
        let s = spaces();
        let mut f = frame(&s, vec![copy_op(&s, 0x1000)], HashMap::new());
        f.advance();

        // The op is no longer marked (index 1 != op 0), and fall-through is announced.
        assert_eq!(
            f.to_string(),
            "<p-code frame: index=1 {\n    *[ram]0x14:1 = COPY *[ram]0x10:1\n *> fall-through\n}>"
        );
    }

    #[test]
    fn to_string_marks_the_branched_op() {
        let s = spaces();
        let mut f = frame(&s, vec![copy_op(&s, 0x1000), copy_op(&s, 0x1001)], HashMap::new());
        f.advance();
        f.finish_as_branch();

        assert_eq!(
            f.to_string(),
            concat!(
                "<p-code frame: index=-1 branched=0 {\n",
                " *> *[ram]0x14:1 = COPY *[ram]0x10:1\n",
                "    *[ram]0x14:1 = COPY *[ram]0x10:1\n",
                "}>"
            )
        );
    }

    #[test]
    fn to_string_resolves_callother_via_the_frame_userop_map() {
        let s = spaces();
        let callother = PcodeOp::new(
            OpCode::CallOther,
            SequenceNumber::new(Address::new(s.ram.clone(), 0x1000), 0),
            vec![Varnode::new(Address::new(s.constant.clone(), 7), 4)],
            None,
        );
        let f = frame(&s, vec![callother], HashMap::from([(7, "frame_op".to_string())]));

        // Userop 7 is unknown to the language, so the name comes from the frame's map.
        assert_eq!(f.to_string(), "<p-code frame: index=0 {\n -> CALLOTHER \"frame_op\"\n}>");
    }
}
