//! Differential test: ghidra-rs `Address`/`AddressSpace` against values produced by a real
//! Ghidra install.
//!
//! Every other test in this crate asserts what its author believed Ghidra does. This one asserts
//! what Ghidra actually did, on the same inputs — the fixture is generated by
//! `scripts/fixtures/gen_address_fixtures.sh` running `AddressGolden.java` inside a real Ghidra
//! distribution, and committed so contributors without that install still run the comparison.
//!
//! The cases concentrate on the Java-to-Rust traps the pattern audit flagged: offsets straddling
//! `0x8000_0000_0000_0000` (Java has no unsigned integers, so Ghidra keeps addresses in a signed
//! long and compares with masking — a literal port using signed comparison inverts the ordering),
//! and wrap/no-wrap arithmetic at space boundaries (Java wraps silently; Rust panics in debug).
//!
//! Regenerate after a Ghidra upgrade; a diff in the fixture is a change in Ghidra's behaviour and
//! deserves reading before it is accepted.

use std::collections::HashMap;
use std::sync::Arc;

use ghidra_rs::program::model::address::{Address, AddressSpace, AddressSpaceType};
use serde_json::Value;

const FIXTURE: &str = include_str!("fixtures/address/address_golden.json");

/// Mirrors the spaces constructed in AddressGolden.java.
fn space_for(name: &str) -> Arc<AddressSpace> {
    let (size, unit) = match name {
        "ram64" => (64, 1),
        "ram32" => (32, 1),
        "ram16" => (16, 1),
        "word32" => (32, 2),
        "quad32" => (32, 8),
        other => panic!("unknown space in fixture: {other}"),
    };
    AddressSpace::new(name, size, unit, AddressSpaceType::Ram, 0)
}

fn records() -> Vec<Value> {
    serde_json::from_str::<Value>(FIXTURE)
        .expect("fixture parses")
        .as_array()
        .expect("fixture is an array")
        .clone()
}

fn i(v: &Value, k: &str) -> i64 {
    v.get(k)
        .and_then(Value::as_i64)
        .unwrap_or_else(|| panic!("missing integer field {k} in {v}"))
}

fn s<'a>(v: &'a Value, k: &str) -> &'a str {
    v.get(k)
        .and_then(Value::as_str)
        .unwrap_or_else(|| panic!("missing string field {k} in {v}"))
}

/// Collects mismatches rather than failing on the first, so one run reports the whole picture.
#[derive(Default)]
struct Mismatches {
    by_kind: HashMap<String, Vec<String>>,
    total: usize,
}

impl Mismatches {
    fn record(&mut self, kind: &str, detail: String) {
        self.total += 1;
        self.by_kind.entry(kind.to_string()).or_default().push(detail);
    }

    fn assert_none(&self) {
        if self.total == 0 {
            return;
        }
        let mut report = format!("\n{} mismatch(es) against real Ghidra:\n", self.total);
        let mut kinds: Vec<_> = self.by_kind.iter().collect();
        kinds.sort_by_key(|(k, _)| k.clone());
        for (kind, details) in kinds {
            report.push_str(&format!("\n  {} ({} cases):\n", kind, details.len()));
            for d in details.iter().take(8) {
                report.push_str(&format!("    {d}\n"));
            }
            if details.len() > 8 {
                report.push_str(&format!("    ... and {} more\n", details.len() - 8));
            }
        }
        panic!("{report}");
    }
}

#[test]
fn address_space_properties_match_ghidra() {
    let mut m = Mismatches::default();
    for r in records().iter().filter(|r| s(r, "kind") == "space") {
        let name = s(r, "space");
        let space = space_for(name);

        if space.size() as i64 != i(r, "size") {
            m.record("space.size", format!("{name}: {} != {}", space.size(), i(r, "size")));
        }
        if space.unit_size() as i64 != i(r, "unit_size") {
            m.record(
                "space.unit_size",
                format!("{name}: {} != {}", space.unit_size(), i(r, "unit_size")),
            );
        }
        if space.min_offset() != i(r, "min_offset") {
            m.record(
                "space.min_offset",
                format!("{name}: {} != {}", space.min_offset(), i(r, "min_offset")),
            );
        }
        if space.max_offset() != i(r, "max_offset") {
            m.record(
                "space.max_offset",
                format!("{name}: {:#x} != {:#x}", space.max_offset(), i(r, "max_offset")),
            );
        }
    }
    m.assert_none();
}

#[test]
fn address_offsets_match_ghidra() {
    let mut m = Mismatches::default();
    for r in records().iter().filter(|r| s(r, "kind") == "address") {
        let name = s(r, "space");
        let space = space_for(name);
        let offset = i(r, "offset");
        let a = Address::new(Arc::clone(&space), offset);

        if a.offset() != i(r, "stored_offset") {
            m.record(
                "stored_offset",
                format!("{name}@{offset:#x}: {:#x} != {:#x}", a.offset(), i(r, "stored_offset")),
            );
        }
        if a.unsigned_offset() != i(r, "unsigned_offset") as u64 {
            m.record(
                "unsigned_offset",
                format!(
                    "{name}@{offset:#x}: {:#x} != {:#x}",
                    a.unsigned_offset(),
                    i(r, "unsigned_offset") as u64
                ),
            );
        }
        if a.addressable_word_offset() != i(r, "word_offset") {
            m.record(
                "word_offset",
                format!(
                    "{name}@{offset:#x}: {:#x} != {:#x}",
                    a.addressable_word_offset(),
                    i(r, "word_offset")
                ),
            );
        }
    }
    m.assert_none();
}

#[test]
fn wrapping_arithmetic_matches_ghidra() {
    let mut m = Mismatches::default();
    for r in records()
        .iter()
        .filter(|r| matches!(s(r, "kind"), "add_wrap" | "subtract_wrap"))
    {
        let kind = s(r, "kind");
        let name = s(r, "space");
        let space = space_for(name);
        let offset = i(r, "offset");
        let delta = i(r, "delta");
        let a = Address::new(Arc::clone(&space), offset);

        let got = match kind {
            "add_wrap" => a.add_wrap(delta).offset(),
            _ => a.subtract_wrap(delta).offset(),
        };
        let want = i(r, "result");
        if got != want {
            m.record(
                kind,
                format!("{name}@{offset:#x} delta={delta:#x}: {got:#x} != {want:#x}"),
            );
        }
    }
    m.assert_none();
}

#[test]
fn non_wrapping_arithmetic_matches_ghidra_including_overflow() {
    let mut m = Mismatches::default();
    for r in records()
        .iter()
        .filter(|r| matches!(s(r, "kind"), "add_no_wrap" | "subtract_no_wrap"))
    {
        let kind = s(r, "kind");
        let name = s(r, "space");
        let space = space_for(name);
        let offset = i(r, "offset");
        let delta = i(r, "delta");
        let a = Address::new(Arc::clone(&space), offset);

        let got = match kind {
            "add_no_wrap" => a.add_no_wrap(delta),
            _ => a.subtract_no_wrap(delta),
        };
        let outcome = s(r, "outcome");

        match (got, outcome) {
            (Ok(addr), "ok") => {
                let want = i(r, "result");
                if addr.offset() != want {
                    m.record(
                        kind,
                        format!(
                            "{name}@{offset:#x} delta={delta:#x}: {:#x} != {want:#x}",
                            addr.offset()
                        ),
                    );
                }
            }
            (Err(_), "ok") => m.record(
                kind,
                format!(
                    "{name}@{offset:#x} delta={delta:#x}: we errored, Ghidra returned {:#x}",
                    i(r, "result")
                ),
            ),
            (Ok(addr), _) => m.record(
                kind,
                format!(
                    "{name}@{offset:#x} delta={delta:#x}: we returned {:#x}, Ghidra raised {outcome}",
                    addr.offset()
                ),
            ),
            (Err(_), _) => {} // both refused
        }
    }
    m.assert_none();
}

/// Ghidra orders addresses by UNSIGNED offset. A port comparing signed offsets inverts every
/// pair straddling 0x8000_0000_0000_0000, which is the exact hazard the audit counted 1,235
/// signed/unsigned casts for.
#[test]
fn address_comparison_and_distance_match_ghidra() {
    let mut m = Mismatches::default();
    for r in records().iter().filter(|r| s(r, "kind") == "pair") {
        let name = s(r, "space");
        let space = space_for(name);
        let (a_off, b_off) = (i(r, "a"), i(r, "b"));
        let a = Address::new(Arc::clone(&space), a_off);
        let b = Address::new(Arc::clone(&space), b_off);

        let got_cmp = match a.cmp(&b) {
            std::cmp::Ordering::Less => -1,
            std::cmp::Ordering::Equal => 0,
            std::cmp::Ordering::Greater => 1,
        };
        if got_cmp != i(r, "compare") {
            m.record(
                "compare",
                format!(
                    "{name}: {a_off:#x} vs {b_off:#x}: {got_cmp} != {}",
                    i(r, "compare")
                ),
            );
        }

        let got_sub = a.subtract(&b);
        if got_sub != i(r, "subtract") {
            m.record(
                "subtract",
                format!(
                    "{name}: {a_off:#x} - {b_off:#x}: {got_sub:#x} != {:#x}",
                    i(r, "subtract")
                ),
            );
        }

        let got_succ = a.is_successor(&b);
        let want_succ = r.get("is_successor").and_then(Value::as_bool).unwrap();
        if got_succ != want_succ {
            m.record(
                "is_successor",
                format!("{name}: {a_off:#x} after {b_off:#x}: {got_succ} != {want_succ}"),
            );
        }
    }
    m.assert_none();
}
