//! Minimal stand-in for `ghidra.app.util.cparser.C.ParseException`.
//!
//! The real `ParseException` is generated by JavaCC from the C grammar (`GrammarNoScanner.jj` /
//! `GrammarWithScanner.jj`) at build time, so it does not exist anywhere in `orig_src` for this
//! port to read -- unlike a hand-written Java source file, there is no fixed shape to match.
//! [`Declaration`](super::declaration::Declaration) (this package's only class in this porting
//! batch) only ever constructs a `ParseException` from a single formatted message string (`new
//! ParseException("Undefined data type \"" + name + "\"")`, etc.) and otherwise treats it as an
//! opaque checked exception, so this port models just that: a message-carrying error type.

/// Port of (the message-carrying subset of) `ghidra.app.util.cparser.C.ParseException`.
#[derive(thiserror::Error, Debug, Clone, PartialEq, Eq)]
#[error("{0}")]
pub struct ParseException(pub String);

impl ParseException {
    /// Construct a `ParseException` with the given message.
    pub fn new(message: impl Into<String>) -> Self {
        ParseException(message.into())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn message_is_preserved_and_displayed() {
        let e = ParseException::new("Undefined data type \"foo\"");
        assert_eq!(e.0, "Undefined data type \"foo\"");
        assert_eq!(e.to_string(), "Undefined data type \"foo\"");
    }
}
