// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FilePath {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DomObjId {
    #[prost(uint32, tag = "1")]
    pub id: u32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TxId {
    #[prost(int32, tag = "1")]
    pub id: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ObjPath {
    #[prost(string, tag = "1")]
    pub path: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Language {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Compiler {
    #[prost(string, tag = "1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Addr {
    #[prost(string, tag = "1")]
    pub space: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub offset: u64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AddrRange {
    #[prost(string, tag = "1")]
    pub space: ::prost::alloc::string::String,
    #[prost(uint64, tag = "2")]
    pub offset: u64,
    #[prost(uint64, tag = "3")]
    pub extend: u64,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Snap {
    #[prost(int64, tag = "1")]
    pub snap: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Schedule {
    #[prost(string, tag = "1")]
    pub schedule: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Span {
    #[prost(int64, tag = "1")]
    pub min: i64,
    #[prost(int64, tag = "2")]
    pub max: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Box {
    #[prost(message, optional, tag = "1")]
    pub span: ::core::option::Option<Span>,
    #[prost(message, optional, tag = "2")]
    pub range: ::core::option::Option<AddrRange>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReplyError {
    #[prost(string, tag = "1")]
    pub message: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestCreateTrace {
    #[prost(message, optional, tag = "1")]
    pub path: ::core::option::Option<FilePath>,
    #[prost(message, optional, tag = "2")]
    pub language: ::core::option::Option<Language>,
    #[prost(message, optional, tag = "3")]
    pub compiler: ::core::option::Option<Compiler>,
    #[prost(message, optional, tag = "4")]
    pub oid: ::core::option::Option<DomObjId>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReplyCreateTrace {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestSaveTrace {
    #[prost(message, optional, tag = "1")]
    pub oid: ::core::option::Option<DomObjId>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReplySaveTrace {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestCloseTrace {
    #[prost(message, optional, tag = "1")]
    pub oid: ::core::option::Option<DomObjId>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReplyCloseTrace {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestStartTx {
    #[prost(message, optional, tag = "1")]
    pub oid: ::core::option::Option<DomObjId>,
    #[prost(bool, tag = "2")]
    pub undoable: bool,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub txid: ::core::option::Option<TxId>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReplyStartTx {}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestEndTx {
    #[prost(message, optional, tag = "1")]
    pub oid: ::core::option::Option<DomObjId>,
    #[prost(message, optional, tag = "2")]
    pub txid: ::core::option::Option<TxId>,
    #[prost(bool, tag = "3")]
    pub abort: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReplyEndTx {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestCreateOverlaySpace {
    #[prost(message, optional, tag = "1")]
    pub oid: ::core::option::Option<DomObjId>,
    #[prost(string, tag = "2")]
    pub base_space: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReplyCreateOverlaySpace {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestSetMemoryState {
    #[prost(message, optional, tag = "1")]
    pub oid: ::core::option::Option<DomObjId>,
    #[prost(message, optional, tag = "2")]
    pub snap: ::core::option::Option<Snap>,
    #[prost(message, optional, tag = "3")]
    pub range: ::core::option::Option<AddrRange>,
    #[prost(enumeration = "MemoryState", tag = "4")]
    pub state: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReplySetMemoryState {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestPutBytes {
    #[prost(message, optional, tag = "1")]
    pub oid: ::core::option::Option<DomObjId>,
    #[prost(message, optional, tag = "2")]
    pub snap: ::core::option::Option<Snap>,
    #[prost(message, optional, tag = "3")]
    pub start: ::core::option::Option<Addr>,
    #[prost(bytes = "vec", tag = "4")]
    pub data: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReplyPutBytes {
    #[prost(int32, tag = "1")]
    pub written: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestDeleteBytes {
    #[prost(message, optional, tag = "1")]
    pub oid: ::core::option::Option<DomObjId>,
    #[prost(message, optional, tag = "2")]
    pub snap: ::core::option::Option<Snap>,
    #[prost(message, optional, tag = "3")]
    pub range: ::core::option::Option<AddrRange>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReplyDeleteBytes {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegVal {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "2")]
    pub value: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RequestPutRegisterValue {
    #[prost(message, optional, tag = "1")]
    pub oid: ::core::option::Option<DomObjId>,
    #[prost(message, optional, tag = "2")]
    pub snap: ::core::option::Option<Snap>,
    #[prost(string, tag = "3")]
    pub space: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "4")]
    pub values: ::prost::alloc::vec::Vec<RegVal>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReplyPutRegisterValue {
    #[prost(string, repeated, tag = "1")]
    pub skipped_names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestDeleteRegisterValue {
    #[prost(message, optional, tag = "1")]
    pub oid: ::core::option::Option<DomObjId>,
    #[prost(message, optional, tag = "2")]
    pub snap: ::core::option::Option<Snap>,
    #[prost(string, tag = "3")]
    pub space: ::prost::alloc::string::String,
    #[prost(string, repeated, tag = "4")]
    pub names: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReplyDeleteRegisterValue {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ObjSpec {
    #[prost(oneof = "obj_spec::Key", tags = "1, 2")]
    pub key: ::core::option::Option<obj_spec::Key>,
}
/// Nested message and enum types in `ObjSpec`.
pub mod obj_spec {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Key {
        #[prost(int64, tag = "1")]
        Id(i64),
        #[prost(message, tag = "2")]
        Path(super::ObjPath),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ObjDesc {
    #[prost(int64, tag = "1")]
    pub id: i64,
    #[prost(message, optional, tag = "2")]
    pub path: ::core::option::Option<ObjPath>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ValSpec {
    #[prost(message, optional, tag = "1")]
    pub parent: ::core::option::Option<ObjSpec>,
    #[prost(message, optional, tag = "2")]
    pub span: ::core::option::Option<Span>,
    #[prost(string, tag = "3")]
    pub key: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub value: ::core::option::Option<Value>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ValDesc {
    #[prost(message, optional, tag = "1")]
    pub parent: ::core::option::Option<ObjDesc>,
    #[prost(message, optional, tag = "2")]
    pub span: ::core::option::Option<Span>,
    #[prost(string, tag = "3")]
    pub key: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "4")]
    pub value: ::core::option::Option<Value>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Null {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct BoolArr {
    #[prost(bool, repeated, tag = "1")]
    pub arr: ::prost::alloc::vec::Vec<bool>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ShortArr {
    #[prost(int32, repeated, tag = "1")]
    pub arr: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct IntArr {
    #[prost(int32, repeated, tag = "1")]
    pub arr: ::prost::alloc::vec::Vec<i32>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct LongArr {
    #[prost(int64, repeated, tag = "1")]
    pub arr: ::prost::alloc::vec::Vec<i64>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StringArr {
    #[prost(string, repeated, tag = "1")]
    pub arr: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ValueType {
    /// Names from schema context
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Value {
    #[prost(
        oneof = "value::Value",
        tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19"
    )]
    pub value: ::core::option::Option<value::Value>,
}
/// Nested message and enum types in `Value`.
pub mod value {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Value {
        #[prost(message, tag = "1")]
        NullValue(super::Null),
        #[prost(bool, tag = "2")]
        BoolValue(bool),
        #[prost(int32, tag = "3")]
        ByteValue(i32),
        #[prost(uint32, tag = "4")]
        CharValue(u32),
        #[prost(int32, tag = "5")]
        ShortValue(i32),
        #[prost(int32, tag = "6")]
        IntValue(i32),
        #[prost(int64, tag = "7")]
        LongValue(i64),
        #[prost(string, tag = "8")]
        StringValue(::prost::alloc::string::String),
        #[prost(message, tag = "9")]
        BoolArrValue(super::BoolArr),
        #[prost(bytes, tag = "10")]
        BytesValue(::prost::alloc::vec::Vec<u8>),
        #[prost(string, tag = "11")]
        CharArrValue(::prost::alloc::string::String),
        #[prost(message, tag = "12")]
        ShortArrValue(super::ShortArr),
        #[prost(message, tag = "13")]
        IntArrValue(super::IntArr),
        #[prost(message, tag = "14")]
        LongArrValue(super::LongArr),
        #[prost(message, tag = "15")]
        StringArrValue(super::StringArr),
        #[prost(message, tag = "16")]
        AddressValue(super::Addr),
        #[prost(message, tag = "17")]
        RangeValue(super::AddrRange),
        #[prost(message, tag = "18")]
        ChildSpec(super::ObjSpec),
        #[prost(message, tag = "19")]
        ChildDesc(super::ObjDesc),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestCreateRootObject {
    #[prost(message, optional, tag = "1")]
    pub oid: ::core::option::Option<DomObjId>,
    #[prost(string, tag = "2")]
    pub schema_context: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub root_schema: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestCreateObject {
    #[prost(message, optional, tag = "1")]
    pub oid: ::core::option::Option<DomObjId>,
    #[prost(message, optional, tag = "2")]
    pub path: ::core::option::Option<ObjPath>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReplyCreateObject {
    #[prost(message, optional, tag = "1")]
    pub object: ::core::option::Option<ObjSpec>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestInsertObject {
    #[prost(message, optional, tag = "1")]
    pub oid: ::core::option::Option<DomObjId>,
    #[prost(message, optional, tag = "2")]
    pub object: ::core::option::Option<ObjSpec>,
    #[prost(message, optional, tag = "3")]
    pub span: ::core::option::Option<Span>,
    #[prost(enumeration = "Resolution", tag = "4")]
    pub resolution: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReplyInsertObject {
    #[prost(message, optional, tag = "1")]
    pub span: ::core::option::Option<Span>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestRemoveObject {
    #[prost(message, optional, tag = "1")]
    pub oid: ::core::option::Option<DomObjId>,
    #[prost(message, optional, tag = "2")]
    pub object: ::core::option::Option<ObjSpec>,
    #[prost(message, optional, tag = "3")]
    pub span: ::core::option::Option<Span>,
    #[prost(bool, tag = "4")]
    pub tree: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReplyRemoveObject {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestSetValue {
    #[prost(message, optional, tag = "1")]
    pub oid: ::core::option::Option<DomObjId>,
    #[prost(message, optional, tag = "2")]
    pub value: ::core::option::Option<ValSpec>,
    #[prost(enumeration = "Resolution", tag = "3")]
    pub resolution: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReplySetValue {
    #[prost(message, optional, tag = "1")]
    pub span: ::core::option::Option<Span>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestRetainValues {
    #[prost(message, optional, tag = "1")]
    pub oid: ::core::option::Option<DomObjId>,
    #[prost(message, optional, tag = "2")]
    pub object: ::core::option::Option<ObjSpec>,
    #[prost(message, optional, tag = "3")]
    pub span: ::core::option::Option<Span>,
    #[prost(enumeration = "ValueKinds", tag = "4")]
    pub kinds: i32,
    #[prost(string, repeated, tag = "5")]
    pub keys: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReplyRetainValues {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestGetObject {
    #[prost(message, optional, tag = "1")]
    pub oid: ::core::option::Option<DomObjId>,
    #[prost(message, optional, tag = "2")]
    pub object: ::core::option::Option<ObjSpec>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReplyGetObject {
    #[prost(message, optional, tag = "1")]
    pub object: ::core::option::Option<ObjDesc>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestGetValues {
    #[prost(message, optional, tag = "1")]
    pub oid: ::core::option::Option<DomObjId>,
    #[prost(message, optional, tag = "2")]
    pub span: ::core::option::Option<Span>,
    #[prost(message, optional, tag = "3")]
    pub pattern: ::core::option::Option<ObjPath>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ReplyGetValues {
    #[prost(message, repeated, tag = "1")]
    pub values: ::prost::alloc::vec::Vec<ValDesc>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestGetValuesIntersecting {
    #[prost(message, optional, tag = "1")]
    pub oid: ::core::option::Option<DomObjId>,
    #[prost(message, optional, tag = "2")]
    pub r#box: ::core::option::Option<Box>,
    #[prost(string, tag = "3")]
    pub key: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestDisassemble {
    #[prost(message, optional, tag = "1")]
    pub oid: ::core::option::Option<DomObjId>,
    #[prost(message, optional, tag = "2")]
    pub snap: ::core::option::Option<Snap>,
    #[prost(message, optional, tag = "3")]
    pub start: ::core::option::Option<Addr>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReplyDisassemble {
    #[prost(int64, tag = "1")]
    pub length: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestActivate {
    #[prost(message, optional, tag = "1")]
    pub oid: ::core::option::Option<DomObjId>,
    #[prost(message, optional, tag = "2")]
    pub object: ::core::option::Option<ObjSpec>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReplyActivate {}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RequestSnapshot {
    #[prost(message, optional, tag = "1")]
    pub oid: ::core::option::Option<DomObjId>,
    #[prost(string, tag = "2")]
    pub description: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub datetime: ::prost::alloc::string::String,
    #[prost(oneof = "request_snapshot::Time", tags = "4, 5")]
    pub time: ::core::option::Option<request_snapshot::Time>,
}
/// Nested message and enum types in `RequestSnapshot`.
pub mod request_snapshot {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Oneof)]
    pub enum Time {
        #[prost(message, tag = "4")]
        Snap(super::Snap),
        #[prost(message, tag = "5")]
        Schedule(super::Schedule),
    }
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReplySnapshot {
    #[prost(message, optional, tag = "1")]
    pub snap: ::core::option::Option<Snap>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MethodParameter {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub r#type: ::core::option::Option<ValueType>,
    #[prost(bool, tag = "3")]
    pub required: bool,
    #[prost(message, optional, tag = "4")]
    pub default_value: ::core::option::Option<Value>,
    #[prost(string, tag = "5")]
    pub display: ::prost::alloc::string::String,
    #[prost(string, tag = "6")]
    pub description: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MethodArgument {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub value: ::core::option::Option<Value>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Method {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub action: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub display: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub description: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "5")]
    pub parameters: ::prost::alloc::vec::Vec<MethodParameter>,
    /// I'd like to make them all void, but I think executing a command and capturing its output
    /// justifies being able to return a result. It should be used very sparingly.
    #[prost(message, optional, tag = "6")]
    pub return_type: ::core::option::Option<ValueType>,
    #[prost(string, tag = "7")]
    pub ok_text: ::prost::alloc::string::String,
    #[prost(string, tag = "8")]
    pub icon: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RequestNegotiate {
    #[prost(string, tag = "1")]
    pub version: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "2")]
    pub methods: ::prost::alloc::vec::Vec<Method>,
    #[prost(string, tag = "3")]
    pub description: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ReplyNegotiate {
    #[prost(string, tag = "1")]
    pub description: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct XRequestInvokeMethod {
    #[prost(message, optional, tag = "1")]
    pub oid: ::core::option::Option<DomObjId>,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "3")]
    pub arguments: ::prost::alloc::vec::Vec<MethodArgument>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct XReplyInvokeMethod {
    #[prost(string, tag = "1")]
    pub error: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub return_value: ::core::option::Option<Value>,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RootMessage {
    #[prost(
        oneof = "root_message::Msg",
        tags = "1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49"
    )]
    pub msg: ::core::option::Option<root_message::Msg>,
}
/// Nested message and enum types in `RootMessage`.
pub mod root_message {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Msg {
        #[prost(message, tag = "1")]
        Error(super::ReplyError),
        #[prost(message, tag = "2")]
        RequestNegotiate(super::RequestNegotiate),
        #[prost(message, tag = "3")]
        ReplyNegotiate(super::ReplyNegotiate),
        #[prost(message, tag = "4")]
        RequestCreateTrace(super::RequestCreateTrace),
        #[prost(message, tag = "5")]
        ReplyCreateTrace(super::ReplyCreateTrace),
        #[prost(message, tag = "6")]
        RequestSaveTrace(super::RequestSaveTrace),
        #[prost(message, tag = "7")]
        ReplySaveTrace(super::ReplySaveTrace),
        #[prost(message, tag = "8")]
        RequestCloseTrace(super::RequestCloseTrace),
        #[prost(message, tag = "9")]
        ReplyCloseTrace(super::ReplyCloseTrace),
        #[prost(message, tag = "10")]
        RequestStartTx(super::RequestStartTx),
        #[prost(message, tag = "11")]
        ReplyStartTx(super::ReplyStartTx),
        #[prost(message, tag = "12")]
        RequestEndTx(super::RequestEndTx),
        #[prost(message, tag = "13")]
        ReplyEndTx(super::ReplyEndTx),
        #[prost(message, tag = "14")]
        RequestCreateOverlay(super::RequestCreateOverlaySpace),
        #[prost(message, tag = "15")]
        ReplyCreateOverlay(super::ReplyCreateOverlaySpace),
        #[prost(message, tag = "16")]
        RequestSetMemoryState(super::RequestSetMemoryState),
        #[prost(message, tag = "17")]
        ReplySetMemoryState(super::ReplySetMemoryState),
        #[prost(message, tag = "18")]
        RequestPutBytes(super::RequestPutBytes),
        #[prost(message, tag = "19")]
        ReplyPutBytes(super::ReplyPutBytes),
        #[prost(message, tag = "20")]
        RequestDeleteBytes(super::RequestDeleteBytes),
        #[prost(message, tag = "21")]
        ReplyDeleteBytes(super::ReplyDeleteBytes),
        #[prost(message, tag = "22")]
        RequestPutRegisterValue(super::RequestPutRegisterValue),
        #[prost(message, tag = "23")]
        ReplyPutRegisterValue(super::ReplyPutRegisterValue),
        #[prost(message, tag = "24")]
        RequestDeleteRegisterValue(super::RequestDeleteRegisterValue),
        #[prost(message, tag = "25")]
        ReplyDeleteRegisterValue(super::ReplyDeleteRegisterValue),
        #[prost(message, tag = "26")]
        RequestCreateRootObject(super::RequestCreateRootObject),
        /// Use same reply as CreateObject
        #[prost(message, tag = "27")]
        RequestCreateObject(super::RequestCreateObject),
        #[prost(message, tag = "28")]
        ReplyCreateObject(super::ReplyCreateObject),
        #[prost(message, tag = "29")]
        RequestInsertObject(super::RequestInsertObject),
        #[prost(message, tag = "30")]
        ReplyInsertObject(super::ReplyInsertObject),
        #[prost(message, tag = "31")]
        RequestRemoveObject(super::RequestRemoveObject),
        #[prost(message, tag = "32")]
        ReplyRemoveObject(super::ReplyRemoveObject),
        #[prost(message, tag = "33")]
        RequestSetValue(super::RequestSetValue),
        #[prost(message, tag = "34")]
        ReplySetValue(super::ReplySetValue),
        #[prost(message, tag = "35")]
        RequestRetainValues(super::RequestRetainValues),
        #[prost(message, tag = "36")]
        ReplyRetainValues(super::ReplyRetainValues),
        #[prost(message, tag = "37")]
        RequestGetObject(super::RequestGetObject),
        #[prost(message, tag = "38")]
        ReplyGetObject(super::ReplyGetObject),
        #[prost(message, tag = "39")]
        RequestGetValues(super::RequestGetValues),
        #[prost(message, tag = "40")]
        ReplyGetValues(super::ReplyGetValues),
        /// Reuse reply_get_values
        #[prost(message, tag = "41")]
        RequestGetValuesIntersecting(super::RequestGetValuesIntersecting),
        #[prost(message, tag = "42")]
        RequestDisassemble(super::RequestDisassemble),
        #[prost(message, tag = "43")]
        ReplyDisassemble(super::ReplyDisassemble),
        #[prost(message, tag = "44")]
        RequestActivate(super::RequestActivate),
        #[prost(message, tag = "45")]
        ReplyActivate(super::ReplyActivate),
        #[prost(message, tag = "46")]
        RequestSnapshot(super::RequestSnapshot),
        #[prost(message, tag = "47")]
        ReplySnapshot(super::ReplySnapshot),
        #[prost(message, tag = "48")]
        XrequestInvokeMethod(super::XRequestInvokeMethod),
        #[prost(message, tag = "49")]
        XreplyInvokeMethod(super::XReplyInvokeMethod),
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum MemoryState {
    MsUnknown = 0,
    MsKnown = 1,
    MsError = 2,
}
impl MemoryState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::MsUnknown => "MS_UNKNOWN",
            Self::MsKnown => "MS_KNOWN",
            Self::MsError => "MS_ERROR",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "MS_UNKNOWN" => Some(Self::MsUnknown),
            "MS_KNOWN" => Some(Self::MsKnown),
            "MS_ERROR" => Some(Self::MsError),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Resolution {
    CrTruncate = 0,
    CrDeny = 1,
    CrAdjust = 2,
}
impl Resolution {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::CrTruncate => "CR_TRUNCATE",
            Self::CrDeny => "CR_DENY",
            Self::CrAdjust => "CR_ADJUST",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "CR_TRUNCATE" => Some(Self::CrTruncate),
            "CR_DENY" => Some(Self::CrDeny),
            "CR_ADJUST" => Some(Self::CrAdjust),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ValueKinds {
    VkElements = 0,
    VkAttributes = 1,
    VkBoth = 2,
}
impl ValueKinds {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::VkElements => "VK_ELEMENTS",
            Self::VkAttributes => "VK_ATTRIBUTES",
            Self::VkBoth => "VK_BOTH",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "VK_ELEMENTS" => Some(Self::VkElements),
            "VK_ATTRIBUTES" => Some(Self::VkAttributes),
            "VK_BOTH" => Some(Self::VkBoth),
            _ => None,
        }
    }
}
