use once_cell::sync::Lazy;

use crate::program::model::data::category_path::CategoryPath;

use super::go_ver_range::GoVerRange;

/// Name of the Go calling spec.
pub const GOLANG_CSPEC_NAME: &str = "golang";

/// Category path to place Go types in.
pub static GOLANG_CATEGORYPATH: Lazy<CategoryPath> =
    Lazy::new(|| CategoryPath::parse("/golang").expect("valid category path"));

/// Category path to place recovered Go types in.
pub static GOLANG_RECOVERED_TYPES_CATEGORYPATH: Lazy<CategoryPath> =
    Lazy::new(|| CategoryPath::parse("/golang-recovered").expect("valid category path"));

/// Name of the ABI-internal calling convention.
pub const GOLANG_ABI_INTERNAL_CALLINGCONVENTION_NAME: &str = "abi-internal";

/// Name of the ABI0 calling convention.
pub const GOLANG_ABI0_CALLINGCONVENTION_NAME: &str = "abi0";

/// Name of the duffzero calling convention.
pub const GOLANG_DUFFZERO_CALLINGCONVENTION_NAME: &str = "duffzero";

/// Name of the duffcopy calling convention.
pub const GOLANG_DUFFCOPY_CALLINGCONVENTION_NAME: &str = "duffcopy";

/// Autogenerated source file name.
pub const GOLANG_AUTOGENERATED_FILENAME: &str = "<autogenerated>";

/// Initial gcWriteBarrier scheme with signature `func gcWriteBarrier(val,dest)`.
/// x86-64 has gcWriteBarrierReg() variants.
pub static GCWRITE_BUFFERED_VERS: Lazy<GoVerRange> =
    Lazy::new(|| GoVerRange::parse("-1.20"));

/// Name of the gcwrite_buffered calling convention.
pub const GOLANG_GCWRITE_BUFFERED_CALLINGCONVENTION_NAME: &str = "gcwrite_buffered";

/// x86-64 registers used by gcWriteBarrier (Go's register names).
pub const GCWRITE_BUFFERED_X86_64_REGS: &[&str] = &["CX", "DX", "BX", "BP", "SI", "R8", "R9"];

/// Next gcWriteBarrier scheme with signature: `func gcWriteBarrier[1-8]() uintptr`.
pub static GCWRITE_BATCH_VERS: Lazy<GoVerRange> =
    Lazy::new(|| GoVerRange::parse("1.21-"));

/// Name of the gcwrite_batch calling convention.
pub const GOLANG_GCWRITE_BATCH_CALLINGCONVENTION_NAME: &str = "gcwrite_batch";

/// Name of the receiver parameter in Go methods.
pub const GOLANG_RECEIVER_PARAM_NAME: &str = "self";

/// Name of the generics parameter in Go functions.
pub const GOLANG_GENERICS_PARAM_NAME: &str = "generics_dict";

/// Name of the closure context parameter in Go closures.
pub const GOLANG_CLOSURE_CONTEXT_NAME: &str = ".context";

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_string_constants() {
        assert_eq!(GOLANG_CSPEC_NAME, "golang");
        assert_eq!(GOLANG_ABI_INTERNAL_CALLINGCONVENTION_NAME, "abi-internal");
        assert_eq!(GOLANG_ABI0_CALLINGCONVENTION_NAME, "abi0");
        assert_eq!(GOLANG_DUFFZERO_CALLINGCONVENTION_NAME, "duffzero");
        assert_eq!(GOLANG_DUFFCOPY_CALLINGCONVENTION_NAME, "duffcopy");
        assert_eq!(GOLANG_AUTOGENERATED_FILENAME, "<autogenerated>");
        assert_eq!(GOLANG_GCWRITE_BUFFERED_CALLINGCONVENTION_NAME, "gcwrite_buffered");
        assert_eq!(GOLANG_GCWRITE_BATCH_CALLINGCONVENTION_NAME, "gcwrite_batch");
        assert_eq!(GOLANG_RECEIVER_PARAM_NAME, "self");
        assert_eq!(GOLANG_GENERICS_PARAM_NAME, "generics_dict");
        assert_eq!(GOLANG_CLOSURE_CONTEXT_NAME, ".context");
    }

    #[test]
    fn test_category_paths() {
        let golang_path = &*GOLANG_CATEGORYPATH;
        let recovered_path = &*GOLANG_RECOVERED_TYPES_CATEGORYPATH;

        assert_eq!(golang_path.get_path(), "/golang");
        assert_eq!(recovered_path.get_path(), "/golang-recovered");
    }

    #[test]
    fn test_version_ranges() {
        let buffered_vers = &*GCWRITE_BUFFERED_VERS;
        let batch_vers = &*GCWRITE_BATCH_VERS;

        // GCWRITE_BUFFERED_VERS should parse as "-1.20" (up to 1.20)
        assert!(!buffered_vers.is_empty());

        // GCWRITE_BATCH_VERS should parse as "1.21-" (1.21 and onwards)
        assert!(!batch_vers.is_empty());
    }

    #[test]
    fn test_x86_64_registers() {
        assert_eq!(GCWRITE_BUFFERED_X86_64_REGS.len(), 7);
        assert_eq!(GCWRITE_BUFFERED_X86_64_REGS[0], "CX");
        assert_eq!(GCWRITE_BUFFERED_X86_64_REGS[6], "R9");
    }
}
