//! Port of `ghidra.program.model.pcode.DynamicEntry`.
//!
//! A `HighSymbol` mapping based on local hashing of the symbol's Varnode within a function's
//! syntax tree. The storage address of a temporary Varnode (a Varnode in the "unique" address
//! space) is too ephemeral to use as a permanent way to identify it. This entry stores a hash
//! (generated by [`DynamicHash`](crate::program::model::pcode::dynamic_hash::DynamicHash)) that
//! is better suited to identifying the Varnode.
//!
//! The Java class `extends SymbolEntry`, an abstract class that is not itself ported yet (it is
//! still `TODO` in `PORT_MANIFEST.tsv`). Rather than adding a placeholder for the whole
//! `SymbolEntry` hierarchy, its two public members that `DynamicEntry` actually needs -- the
//! `symbol`/`pcaddr` fields (read via `getPCAdress()`) and the `decodeRangeList`/`encodeRangelist`
//! protected helpers -- are flattened directly into this trait and its default method bodies,
//! the same way [`HighSymbol`](crate::program::seam_stubs::HighSymbol)'s default `decode` inlines
//! logic that would otherwise belong to a separate, unported `HighSymbol` base. This was selected
//! as a dependency-cycle cut-point, so it is promoted to a trait rather than a concrete struct.
//!
//! The static factory `DynamicEntry.build(Varnode)` walks `vn.getHigh().getSymbol()` to find the
//! owning [`HighSymbol`](crate::program::seam_stubs::HighSymbol), then runs the *full*
//! `DynamicHash(Varnode, HighFunction)` data-flow graph walk to compute the hash. That graph walk
//! is exactly the part of `DynamicHash` documented as out of scope in
//! [`dynamic_hash`](crate::program::model::pcode::dynamic_hash) (it needs a linked
//! `PcodeSyntaxTree`/`VarnodeAST` graph this crate's plain, graph-unlinked
//! [`Varnode`](crate::program::model::pcode::Varnode) can't provide). [`DefaultDynamicEntry::build`]
//! therefore ports only the trivial tail of `build`: given a symbol and an *already computed*
//! [`DynamicHash`](crate::program::model::pcode::dynamic_hash::DynamicHash) (e.g. from
//! [`calc_level0_hash`](crate::program::model::pcode::dynamic_hash::calc_level0_hash)), assemble
//! the resulting entry.

use std::io;
use std::sync::Arc;

use crate::program::model::address::Address;
use crate::program::model::data::mutability_settings_definition::NORMAL;
use crate::program::model::pcode::decoder::{Decoder, DecoderError};
use crate::program::model::pcode::decoder_exception::DecoderException;
use crate::program::model::pcode::dynamic_hash::DynamicHash;
use crate::program::model::pcode::encoder::Encoder;
use crate::program::model::pcode::ids::{ATTRIB_FIRST, ATTRIB_LAST, ATTRIB_SPACE, ATTRIB_VAL, ELEM_HASH, ELEM_RANGE, ELEM_RANGELIST};
use crate::program::seam_stubs::{HashVariableStorage, HighSymbol};
    use crate::program::model::listing::variable_storage::VariableStorage;

/// A `HighSymbol` mapping based on local hashing of the symbol's Varnode. Port of the instance
/// contract of `ghidra.program.model.pcode.DynamicEntry` (with the public parts of its
/// `SymbolEntry` base flattened in -- see the module docs).
pub trait DynamicEntry {
    /// The symbol owning this entry. Port of the inherited `SymbolEntry.symbol` field.
    fn get_high_symbol(&self) -> Arc<dyn HighSymbol>;

    /// The earliest address in the code where this storage is used for this symbol. Port of
    /// `SymbolEntry.getPCAdress()`.
    fn get_pc_address(&self) -> Option<Address>;

    /// Stands in for the inherited `SymbolEntry.pcaddr` field setter, needed by
    /// [`DynamicEntry::decode`]'s default body.
    fn set_pc_address(&mut self, addr: Option<Address>);

    /// The hash value. Port of `DynamicEntry.getHash()`.
    fn get_hash(&self) -> i64;

    /// Stands in for the private `hash` field setter, needed by [`DynamicEntry::decode`]'s
    /// default body.
    fn set_hash(&mut self, hash: i64);

    /// Decode this entry from the stream. Port of `DynamicEntry.decode(Decoder)` (with
    /// `SymbolEntry.decodeRangeList` inlined).
    fn decode(&mut self, decoder: &dyn Decoder) -> Result<(), DecoderException> {
        let addrel = decoder.open_element_with_id(ELEM_HASH).map_err(decode_err)?;
        let hash = decoder.read_unsigned_integer_with_id(ATTRIB_VAL).map_err(decode_err)?;
        self.set_hash(hash as i64);
        decoder.close_element(addrel).map_err(decode_err)?;

        let rangelistel = decoder.open_element_with_id(ELEM_RANGELIST).map_err(decode_err)?;
        if decoder.peek_element().map_err(decode_err)? != 0 {
            let rangeel = decoder.open_element_with_id(ELEM_RANGE).map_err(decode_err)?;
            let space = decoder.read_space_with_id(ATTRIB_SPACE).map_err(decode_err)?;
            let offset = decoder.read_unsigned_integer_with_id(ATTRIB_FIRST).map_err(decode_err)?;
            self.set_pc_address(Some(space.address(offset as i64)));
            decoder.close_element(rangeel).map_err(decode_err)?;
        }
        decoder.close_element(rangelistel).map_err(decode_err)?;

        Ok(())
    }

    /// Encode this entry as (a set of) elements to the given stream. Port of
    /// `DynamicEntry.encode(Encoder)` (with `SymbolEntry.encodeRangelist` inlined).
    fn encode(&self, encoder: &mut dyn Encoder) -> io::Result<()> {
        encoder.open_element(ELEM_HASH)?;
        encoder.write_unsigned_integer(ATTRIB_VAL, self.get_hash() as u64)?;
        encoder.close_element(ELEM_HASH)?;

        encoder.open_element(ELEM_RANGELIST)?;
        if let Some(addr) = self.get_pc_address() {
            if !addr.is_external_address() {
                let off = addr.unsigned_offset();
                encoder.open_element(ELEM_RANGE)?;
                encoder.write_space(ATTRIB_SPACE, addr.space())?;
                encoder.write_unsigned_integer(ATTRIB_FIRST, off)?;
                encoder.write_unsigned_integer(ATTRIB_LAST, off)?;
                encoder.close_element(ELEM_RANGE)?;
            }
        }
        encoder.close_element(ELEM_RANGELIST)?;

        Ok(())
    }

    /// The storage associated with this particular mapping of the symbol. Port of
    /// `DynamicEntry.getStorage()`.
    fn get_storage(&self) -> Box<dyn VariableStorage> {
        Box::new(HashVariableStorage(self.get_hash()))
    }

    /// The number of bytes consumed by the symbol when using this storage. Port of
    /// `DynamicEntry.getSize()`.
    fn get_size(&self) -> i32 {
        self.get_high_symbol().get_data_type().get_length()
    }

    /// One of `MutabilitySettingsDefinition::NORMAL`/`VOLATILE`/`CONSTANT`. Port of
    /// `DynamicEntry.getMutability()`.
    fn get_mutability(&self) -> i32 {
        NORMAL
    }
}

fn decode_err(e: DecoderError) -> DecoderException {
    DecoderException::with_cause("failed to decode DynamicEntry", e)
}

/// A minimal concrete [`DynamicEntry`], holding the owning symbol plus the mapping's hash/address
/// state directly. Port of the two `DynamicEntry` constructors (`DynamicEntry(HighSymbol)` via
/// [`DefaultDynamicEntry::new`], `DynamicEntry(HighSymbol, Address, long)` via
/// [`DefaultDynamicEntry::with_hash`]).
pub struct DefaultDynamicEntry {
    symbol: Arc<dyn HighSymbol>,
    pc_address: Option<Address>,
    hash: i64,
}

impl DefaultDynamicEntry {
    /// Port of the `DynamicEntry(HighSymbol sym)` constructor, for use with [`DynamicEntry::decode`].
    pub fn new(symbol: Arc<dyn HighSymbol>) -> Self {
        DefaultDynamicEntry { symbol, pc_address: None, hash: 0 }
    }

    /// Port of the `DynamicEntry(HighSymbol sym, Address addr, long h)` constructor.
    pub fn with_hash(symbol: Arc<dyn HighSymbol>, addr: Address, hash: i64) -> Self {
        DefaultDynamicEntry { symbol, pc_address: Some(addr), hash }
    }

    /// Port of the trivial tail of the static `DynamicEntry.build(Varnode)`: given the owning
    /// symbol and an already-computed [`DynamicHash`], assemble the resulting entry. See the
    /// module docs for why the hash itself (the `DynamicHash(Varnode, HighFunction)` graph walk)
    /// is not computed here.
    pub fn build(symbol: Arc<dyn HighSymbol>, dynamic_hash: &dyn DynamicHash) -> Self {
        DefaultDynamicEntry::with_hash(symbol, dynamic_hash.get_address(), dynamic_hash.get_hash())
    }
}

impl DynamicEntry for DefaultDynamicEntry {
    fn get_high_symbol(&self) -> Arc<dyn HighSymbol> {
        self.symbol.clone()
    }

    fn get_pc_address(&self) -> Option<Address> {
        self.pc_address.clone()
    }

    fn set_pc_address(&mut self, addr: Option<Address>) {
        self.pc_address = addr;
    }

    fn get_hash(&self) -> i64 {
        self.hash
    }

    fn set_hash(&mut self, hash: i64) {
        self.hash = hash;
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::program::model::address::{AddressFactory, AddressSpace, AddressSpaceType};
    use crate::program::model::data::data_type::DataType;
    use crate::program::model::pcode::ids::{AttributeId, ElementId};
    use crate::program::model::pcode::high_function::HighFunction;
    use std::sync::atomic::{AtomicUsize, Ordering};

    fn ram_space() -> Arc<AddressSpace> {
        AddressSpace::new("ram", 32, 1, AddressSpaceType::Ram, 1)
    }

    struct MockDataType(i32);
    impl DataType for MockDataType {
        fn get_length(&self) -> i32 {
            self.0
        }
    }

    struct MockHighSymbol {
        length: i32,
    }
    impl HighSymbol for MockHighSymbol {
        fn get_id(&self) -> i64 {
            1
        }
        fn get_high_function(&self) -> Arc<dyn HighFunction> {
            unimplemented!("not needed for this smoke test")
        }
        fn get_data_type(&self) -> Box<dyn DataType> {
            Box::new(MockDataType(self.length))
        }
    }

    /// Decoder that plays back a single `<hash val=.../><rangelist><range space=... first=.../></rangelist>`
    /// sequence, mirroring what [`DynamicEntry::encode`] would have produced.
    struct MockDecoder {
        space: Arc<AddressSpace>,
        hash: u64,
        offset: u64,
        has_range: bool,
        open_calls: AtomicUsize,
    }

    impl Decoder for MockDecoder {
        fn get_address_factory(&self) -> Arc<dyn AddressFactory> {
            unimplemented!()
        }
        fn set_address_factory(&self, _factory: Arc<dyn AddressFactory>) {}
        fn peek_element(&self) -> Result<i32, DecoderError> {
            Ok(if self.has_range { 1 } else { 0 })
        }
        fn open_element(&self) -> Result<i32, DecoderError> {
            Ok(self.open_calls.fetch_add(1, Ordering::SeqCst) as i32 + 1)
        }
        fn open_element_with_id(&self, _elem_id: ElementId) -> Result<i32, DecoderError> {
            self.open_element()
        }
        fn close_element(&self, _id: i32) -> Result<(), DecoderError> {
            Ok(())
        }
        fn close_element_skipping(&self, _id: i32) -> Result<(), DecoderError> {
            Ok(())
        }
        fn get_next_attribute_id(&self) -> Result<i32, DecoderError> {
            Ok(0)
        }
        fn rewind_attributes(&self) {}
        fn read_bool(&self) -> Result<bool, DecoderError> {
            unimplemented!()
        }
        fn read_bool_with_id(&self, _attrib_id: AttributeId) -> Result<bool, DecoderError> {
            unimplemented!()
        }
        fn read_signed_integer(&self) -> Result<i64, DecoderError> {
            unimplemented!()
        }
        fn read_signed_integer_with_id(&self, _attrib_id: AttributeId) -> Result<i64, DecoderError> {
            unimplemented!()
        }
        fn read_unsigned_integer(&self) -> Result<u64, DecoderError> {
            unimplemented!()
        }
        fn read_unsigned_integer_with_id(&self, attrib_id: AttributeId) -> Result<u64, DecoderError> {
            if attrib_id.id == ATTRIB_VAL.id {
                Ok(self.hash)
            } else if attrib_id.id == ATTRIB_FIRST.id {
                Ok(self.offset)
            } else {
                Err(DecoderError::MissingAttribute(attrib_id.name.to_string()))
            }
        }
        fn read_string(&self) -> Result<String, DecoderError> {
            unimplemented!()
        }
        fn read_string_with_id(&self, _attrib_id: AttributeId) -> Result<String, DecoderError> {
            unimplemented!()
        }
        fn read_space(&self) -> Result<Arc<AddressSpace>, DecoderError> {
            unimplemented!()
        }
        fn read_space_with_id(&self, _attrib_id: AttributeId) -> Result<Arc<AddressSpace>, DecoderError> {
            Ok(self.space.clone())
        }
    }

    /// Encoder recording the sequence of elements/attributes written, for asserting
    /// [`DynamicEntry::encode`]'s structure.
    #[derive(Default)]
    struct RecordingEncoder {
        events: Vec<String>,
    }

    impl Encoder for RecordingEncoder {
        fn open_element(&mut self, elem_id: ElementId) -> io::Result<()> {
            self.events.push(format!("open:{}", elem_id.name));
            Ok(())
        }
        fn close_element(&mut self, elem_id: ElementId) -> io::Result<()> {
            self.events.push(format!("close:{}", elem_id.name));
            Ok(())
        }
        fn write_bool(&mut self, _attrib_id: AttributeId, _val: bool) -> io::Result<()> {
            Ok(())
        }
        fn write_signed_integer(&mut self, _attrib_id: AttributeId, _val: i64) -> io::Result<()> {
            Ok(())
        }
        fn write_unsigned_integer(&mut self, attrib_id: AttributeId, val: u64) -> io::Result<()> {
            self.events.push(format!("attr:{}={}", attrib_id.name, val));
            Ok(())
        }
        fn write_string(&mut self, _attrib_id: AttributeId, _val: &str) -> io::Result<()> {
            Ok(())
        }
        fn write_string_indexed(
            &mut self,
            _attrib_id: AttributeId,
            _index: i32,
            _val: &str,
        ) -> io::Result<()> {
            Ok(())
        }
        fn write_space(&mut self, attrib_id: AttributeId, spc: &AddressSpace) -> io::Result<()> {
            self.events.push(format!("attr:{}={}", attrib_id.name, spc.name()));
            Ok(())
        }
        fn write_space_indexed(
            &mut self,
            _attrib_id: AttributeId,
            _index: i32,
            _name: &str,
        ) -> io::Result<()> {
            Ok(())
        }
        fn write_opcode(
            &mut self,
            _attrib_id: AttributeId,
            _opcode: crate::decompiler::opcodes::op_code::OpCode,
        ) -> io::Result<()> {
            Ok(())
        }
        fn write_opcode_ordinal(&mut self, _attrib_id: AttributeId, _opcode: i32) -> io::Result<()> {
            Ok(())
        }
    }

    #[test]
    fn decode_reads_hash_and_pc_address() {
        let space = ram_space();
        let mut entry = DefaultDynamicEntry::new(Arc::new(MockHighSymbol { length: 4 }));
        let decoder = MockDecoder {
            space: space.clone(),
            hash: 0xdead_beef,
            offset: 0x1000,
            has_range: true,
            open_calls: AtomicUsize::new(0),
        };

        entry.decode(&decoder).expect("decode should succeed");

        assert_eq!(entry.get_hash(), 0xdead_beefu64 as i64);
        assert_eq!(entry.get_pc_address(), Some(space.address(0x1000)));
    }

    #[test]
    fn decode_with_no_range_leaves_pc_address_unset() {
        let space = ram_space();
        let mut entry = DefaultDynamicEntry::new(Arc::new(MockHighSymbol { length: 4 }));
        let decoder = MockDecoder {
            space,
            hash: 42,
            offset: 0,
            has_range: false,
            open_calls: AtomicUsize::new(0),
        };

        entry.decode(&decoder).expect("decode should succeed");

        assert_eq!(entry.get_hash(), 42);
        assert_eq!(entry.get_pc_address(), None);
    }

    #[test]
    fn encode_emits_hash_and_range_matching_pc_address() {
        let space = ram_space();
        let entry = DefaultDynamicEntry::with_hash(
            Arc::new(MockHighSymbol { length: 4 }),
            space.address(0x2000),
            0x77,
        );

        let mut encoder = RecordingEncoder::default();
        entry.encode(&mut encoder).expect("encode should succeed");

        assert_eq!(
            encoder.events,
            vec![
                "open:hash".to_string(),
                "attr:val=119".to_string(),
                "close:hash".to_string(),
                "open:rangelist".to_string(),
                "open:range".to_string(),
                "attr:space=ram".to_string(),
                "attr:first=8192".to_string(),
                "attr:last=8192".to_string(),
                "close:range".to_string(),
                "close:rangelist".to_string(),
            ]
        );
    }

    #[test]
    fn encode_with_no_pc_address_emits_empty_rangelist() {
        let entry = DefaultDynamicEntry::new(Arc::new(MockHighSymbol { length: 4 }));

        let mut encoder = RecordingEncoder::default();
        entry.encode(&mut encoder).expect("encode should succeed");

        assert_eq!(
            encoder.events,
            vec![
                "open:hash".to_string(),
                "attr:val=0".to_string(),
                "close:hash".to_string(),
                "open:rangelist".to_string(),
                "close:rangelist".to_string(),
            ]
        );
    }

    #[test]
    fn get_size_delegates_to_symbol_data_type_length() {
        let entry = DefaultDynamicEntry::new(Arc::new(MockHighSymbol { length: 8 }));
        assert_eq!(entry.get_size(), 8);
    }

    #[test]
    fn get_mutability_is_normal() {
        let entry = DefaultDynamicEntry::new(Arc::new(MockHighSymbol { length: 4 }));
        assert_eq!(entry.get_mutability(), NORMAL);
    }

    #[test]
    fn get_storage_reports_hash_addressed_storage() {
        let entry = DefaultDynamicEntry::with_hash(
            Arc::new(MockHighSymbol { length: 4 }),
            ram_space().address(0),
            99,
        );
        let storage = entry.get_storage();
        assert!(storage.is_hash_storage());
    }

    #[test]
    fn build_assembles_entry_from_precomputed_hash() {
        struct StoredHash {
            hash: i64,
            address: Address,
        }
        impl DynamicHash for StoredHash {
            fn get_hash(&self) -> i64 {
                self.hash
            }
            fn get_address(&self) -> Address {
                self.address.clone()
            }
        }

        let space = ram_space();
        let address = space.address(0x3000);
        let stored = StoredHash { hash: 55, address: address.clone() };
        let symbol: Arc<dyn HighSymbol> = Arc::new(MockHighSymbol { length: 4 });

        let entry = DefaultDynamicEntry::build(symbol, &stored);

        assert_eq!(entry.get_hash(), 55);
        assert_eq!(entry.get_pc_address(), Some(address));
    }

    #[test]
    fn dynamic_entry_trait_is_object_safe() {
        let boxed: Box<dyn DynamicEntry> = Box::new(DefaultDynamicEntry::with_hash(
            Arc::new(MockHighSymbol { length: 4 }),
            ram_space().address(0x10),
            7,
        ));
        assert_eq!(boxed.get_hash(), 7);
        assert_eq!(boxed.get_mutability(), NORMAL);
    }
}
