//! Models `ghidra.pcodeCPort.slghpatexpress.BinaryExpression`.

use crate::decompiler::seam_stubs::{Pattern, PatternExpression};
use crate::decompiler::slghpatexpress::TokenPattern;
use crate::program::model::pcode::encoder::Encoder;
use crate::sleigh::grammar::Location;
use std::io;

/// An abstract pattern expression that combines two sub-expressions.
///
/// BinaryExpression is the base class for addition, subtraction, multiplication, division,
/// shifts, and other two-operand pattern expressions. Its sub-expressions (`left` and `right`)
/// are managed with reference counting semantics in Java: construction with operands calls
/// `lay_claim()` on each, and `dispose()` releases them.
///
/// Models `ghidra.pcodeCPort.slghpatexpress.BinaryExpression`.
pub struct BinaryExpression {
    location: Location,
    left: Option<Box<dyn PatternExpression>>,
    right: Option<Box<dyn PatternExpression>>,
}

impl BinaryExpression {
    /// Creates a new, empty binary expression with the given location.
    ///
    /// The sub-expressions are initially `None` and must be set via a subclass
    /// or by explicit construction with `with_operands`.
    pub fn new(location: Location) -> Self {
        Self {
            location,
            left: None,
            right: None,
        }
    }

    /// Creates a new binary expression with left and right sub-expression operands.
    ///
    /// In Java, this calls `lay_claim()` on each operand; in Rust, we simply take ownership.
    pub fn with_operands(
        location: Location,
        left: Box<dyn PatternExpression>,
        right: Box<dyn PatternExpression>,
    ) -> Self {
        Self {
            location,
            left: Some(left),
            right: Some(right),
        }
    }

    /// Returns the left sub-expression of this binary operation.
    pub fn get_left(&self) -> Option<&dyn PatternExpression> {
        self.left.as_deref()
    }

    /// Returns the right sub-expression of this binary operation.
    pub fn get_right(&self) -> Option<&dyn PatternExpression> {
        self.right.as_deref()
    }

    /// Generates the minimal (unconstrained) token pattern for this expression.
    ///
    /// The minimal pattern carries no constraints; derived classes override this with
    /// operand-specific logic.
    pub fn gen_min_pattern(&self) -> Box<dyn TokenPattern> {
        Box::new(MinimalPattern::new(self.location.clone()))
    }

    /// Encodes the left and right sub-expressions to the given encoder.
    ///
    /// The outer tag is generated by derived classes; this method encodes only the operands.
    pub fn encode(&self, encoder: &mut dyn Encoder) -> io::Result<()> {
        if let Some(left) = &self.left {
            left.encode(encoder)?;
        }
        if let Some(right) = &self.right {
            right.encode(encoder)?;
        }
        Ok(())
    }
}

impl std::fmt::Display for BinaryExpression {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "binary({})", self.location)
    }
}

impl crate::decompiler::seam_stubs::PatternExpression for BinaryExpression {}

/// A minimal token pattern used when no operand constraints apply.
struct MinimalPattern {
    location: Location,
}

impl MinimalPattern {
    fn new(location: Location) -> Self {
        Self { location }
    }
}

impl TokenPattern for MinimalPattern {
    fn location(&self) -> &Location {
        &self.location
    }

    fn get_pattern(&self) -> &dyn Pattern {
        &EmptyPattern
    }

    fn always_true(&self) -> bool {
        false
    }

    fn always_false(&self) -> bool {
        false
    }

    fn always_instruction_true(&self) -> bool {
        false
    }

    fn get_left_ellipsis(&self) -> bool {
        false
    }

    fn get_right_ellipsis(&self) -> bool {
        false
    }

    fn set_left_ellipsis(&mut self, _val: bool) {}

    fn set_right_ellipsis(&mut self, _val: bool) {}

    fn get_minimum_length(&self) -> i32 {
        0
    }

    fn simplify_pattern(&mut self) {}

    fn copy_into(&mut self, _tokpat: &dyn TokenPattern) {}

    fn do_and(&self, _tokpat: &dyn TokenPattern) -> Box<dyn TokenPattern> {
        Box::new(MinimalPattern::new(self.location.clone()))
    }

    fn do_or(&self, _tokpat: &dyn TokenPattern) -> Box<dyn TokenPattern> {
        Box::new(MinimalPattern::new(self.location.clone()))
    }

    fn do_cat(&self, _tokpat: &dyn TokenPattern) -> Box<dyn TokenPattern> {
        Box::new(MinimalPattern::new(self.location.clone()))
    }

    fn common_sub_pattern(&self, _tokpat: &dyn TokenPattern) -> Box<dyn TokenPattern> {
        Box::new(MinimalPattern::new(self.location.clone()))
    }
}

struct EmptyPattern;
impl crate::decompiler::seam_stubs::Pattern for EmptyPattern {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn new_creates_with_location() {
        let location = Location::new("test.sleigh", 1);
        let expr = BinaryExpression::new(location.clone());
        assert_eq!(expr.location, location);
        assert!(expr.left.is_none());
        assert!(expr.right.is_none());
    }

    #[test]
    fn with_operands_stores_both_operands() {
        let location = Location::new("test.sleigh", 1);

        struct DummyOperand;
        impl PatternExpression for DummyOperand {}

        let left = Box::new(DummyOperand);
        let right = Box::new(DummyOperand);
        let expr = BinaryExpression::with_operands(location.clone(), left, right);
        assert_eq!(expr.location, location);
        assert!(expr.left.is_some());
        assert!(expr.right.is_some());
    }

    #[test]
    fn get_left_and_right_return_stored_operands() {
        let location = Location::new("test.sleigh", 1);

        struct DummyOperand;
        impl PatternExpression for DummyOperand {}

        let left = Box::new(DummyOperand);
        let right = Box::new(DummyOperand);
        let expr = BinaryExpression::with_operands(location, left, right);
        assert!(expr.get_left().is_some());
        assert!(expr.get_right().is_some());
    }

    #[test]
    fn get_left_and_right_return_none_when_empty() {
        let location = Location::new("test.sleigh", 1);
        let expr = BinaryExpression::new(location);
        assert!(expr.get_left().is_none());
        assert!(expr.get_right().is_none());
    }

    #[test]
    fn gen_min_pattern_returns_token_pattern() {
        let location = Location::new("test.sleigh", 1);
        let expr = BinaryExpression::new(location.clone());
        let pattern = expr.gen_min_pattern();
        assert_eq!(pattern.location(), &location);
    }

    #[test]
    fn gen_min_pattern_has_no_constraints() {
        let location = Location::new("test.sleigh", 1);
        let expr = BinaryExpression::new(location);
        let pattern = expr.gen_min_pattern();
        assert!(!pattern.always_true());
        assert!(!pattern.always_false());
    }

    #[test]
    fn encode_succeeds_with_no_operands() {
        let location = Location::new("test.sleigh", 1);
        let expr = BinaryExpression::new(location);

        #[derive(Default)]
        struct NoOpEncoder;
        impl Encoder for NoOpEncoder {
            fn open_element(
                &mut self,
                _elem_id: crate::program::model::pcode::ids::ElementId,
            ) -> io::Result<()> {
                Ok(())
            }

            fn close_element(
                &mut self,
                _elem_id: crate::program::model::pcode::ids::ElementId,
            ) -> io::Result<()> {
                Ok(())
            }

            fn write_bool(
                &mut self,
                _attrib_id: crate::program::model::pcode::ids::AttributeId,
                _val: bool,
            ) -> io::Result<()> {
                Ok(())
            }

            fn write_signed_integer(
                &mut self,
                _attrib_id: crate::program::model::pcode::ids::AttributeId,
                _val: i64,
            ) -> io::Result<()> {
                Ok(())
            }
        }

        let mut encoder = NoOpEncoder::default();
        assert!(expr.encode(&mut encoder).is_ok());
    }

    #[test]
    fn encode_calls_both_operands_encode() {
        use std::cell::RefCell;
        use std::rc::Rc;

        struct CountingOperand {
            encoded: Rc<RefCell<bool>>,
        }

        impl PatternExpression for CountingOperand {
            fn encode(&self, _encoder: &mut dyn Encoder) -> io::Result<()> {
                *self.encoded.borrow_mut() = true;
                Ok(())
            }
        }

        #[derive(Default)]
        struct NoOpEncoder;
        impl Encoder for NoOpEncoder {
            fn open_element(
                &mut self,
                _elem_id: crate::program::model::pcode::ids::ElementId,
            ) -> io::Result<()> {
                Ok(())
            }

            fn close_element(
                &mut self,
                _elem_id: crate::program::model::pcode::ids::ElementId,
            ) -> io::Result<()> {
                Ok(())
            }

            fn write_bool(
                &mut self,
                _attrib_id: crate::program::model::pcode::ids::AttributeId,
                _val: bool,
            ) -> io::Result<()> {
                Ok(())
            }

            fn write_signed_integer(
                &mut self,
                _attrib_id: crate::program::model::pcode::ids::AttributeId,
                _val: i64,
            ) -> io::Result<()> {
                Ok(())
            }
        }

        let location = Location::new("test.sleigh", 1);
        let left_encoded = Rc::new(RefCell::new(false));
        let right_encoded = Rc::new(RefCell::new(false));
        let left = Box::new(CountingOperand {
            encoded: left_encoded.clone(),
        });
        let right = Box::new(CountingOperand {
            encoded: right_encoded.clone(),
        });
        let expr = BinaryExpression::with_operands(location, left, right);
        let mut encoder = NoOpEncoder::default();

        expr.encode(&mut encoder).unwrap();

        assert!(*left_encoded.borrow());
        assert!(*right_encoded.borrow());
    }

    #[test]
    fn display_shows_location() {
        let location = Location::new("test.sleigh", 42);
        let expr = BinaryExpression::new(location);
        let display = expr.to_string();
        assert!(display.contains("42"));
    }
}
