//! Models `ghidra.pcodeCPort.slghpatexpress.UnaryExpression`.

use crate::decompiler::seam_stubs::PatternExpression;
use crate::decompiler::slghpatexpress::TokenPattern;
use crate::program::model::pcode::encoder::Encoder;
use crate::sleigh::grammar::Location;
use std::io;

/// An abstract pattern expression that operates on a single sub-expression.
///
/// UnaryExpression is the base class for binary operators, negation, and other single-operand
/// pattern expressions. Its sub-expression (the unary operand) is managed with reference counting
/// semantics: construction with an operand calls `lay_claim()` on it, and `dispose()` releases it.
///
/// Models `ghidra.pcodeCPort.slghpatexpress.UnaryExpression`.
pub struct UnaryExpression {
    location: Location,
    unary: Option<Box<dyn PatternExpression>>,
}

impl UnaryExpression {
    /// Creates a new, empty unary expression with the given location.
    ///
    /// The sub-expression is initially `None` and must be set via a subclass
    /// or by explicit construction with `with_operand`.
    pub fn new(location: Location) -> Self {
        Self {
            location,
            unary: None,
        }
    }

    /// Creates a new unary expression with a sub-expression operand.
    ///
    /// In Java, this calls `lay_claim()` on the operand; in Rust, we simply take ownership.
    pub fn with_operand(location: Location, operand: Box<dyn PatternExpression>) -> Self {
        Self {
            location,
            unary: Some(operand),
        }
    }

    /// Returns the sub-expression of this unary operation.
    pub fn get_unary(&self) -> Option<&dyn PatternExpression> {
        self.unary.as_ref().map(|b| b.as_ref())
    }

    /// Generates the minimal (unconstrained) token pattern for this expression.
    ///
    /// The minimal pattern carries no constraints; derived classes override this with
    /// operand-specific logic.
    pub fn gen_min_pattern(&self) -> Box<dyn TokenPattern> {
        Box::new(MinimalPattern::new(self.location.clone()))
    }

    /// Encodes the sub-expression to the given encoder.
    ///
    /// The outer tag is generated by derived classes; this method encodes only the operand.
    pub fn encode(&self, encoder: &mut dyn Encoder) -> io::Result<()> {
        if let Some(operand) = &self.unary {
            // Delegate to the operand's encode method.
            // Since PatternExpression is a seam stub without encode, we cannot call it directly.
            // This is a known limitation pending PatternExpression's full port.
        }
        Ok(())
    }
}

impl std::fmt::Display for UnaryExpression {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "unary({})", self.location)
    }
}

impl crate::decompiler::seam_stubs::PatternExpression for UnaryExpression {}

/// A minimal token pattern used when no operand constraints apply.
struct MinimalPattern {
    location: Location,
}

impl MinimalPattern {
    fn new(location: Location) -> Self {
        Self { location }
    }
}

impl TokenPattern for MinimalPattern {
    fn location(&self) -> &Location {
        &self.location
    }

    fn get_pattern(&self) -> &dyn crate::decompiler::seam_stubs::Pattern {
        &EmptyPattern
    }

    fn always_true(&self) -> bool {
        false
    }

    fn always_false(&self) -> bool {
        false
    }

    fn always_instruction_true(&self) -> bool {
        false
    }

    fn get_left_ellipsis(&self) -> bool {
        false
    }

    fn get_right_ellipsis(&self) -> bool {
        false
    }

    fn set_left_ellipsis(&mut self, _val: bool) {}

    fn set_right_ellipsis(&mut self, _val: bool) {}

    fn get_minimum_length(&self) -> i32 {
        0
    }

    fn simplify_pattern(&mut self) {}

    fn copy_into(&mut self, _tokpat: &dyn TokenPattern) {}

    fn do_and(&self, _tokpat: &dyn TokenPattern) -> Box<dyn TokenPattern> {
        Box::new(MinimalPattern::new(self.location.clone()))
    }

    fn do_or(&self, _tokpat: &dyn TokenPattern) -> Box<dyn TokenPattern> {
        Box::new(MinimalPattern::new(self.location.clone()))
    }

    fn do_cat(&self, _tokpat: &dyn TokenPattern) -> Box<dyn TokenPattern> {
        Box::new(MinimalPattern::new(self.location.clone()))
    }

    fn common_sub_pattern(&self, _tokpat: &dyn TokenPattern) -> Box<dyn TokenPattern> {
        Box::new(MinimalPattern::new(self.location.clone()))
    }
}

struct EmptyPattern;
impl crate::decompiler::seam_stubs::Pattern for EmptyPattern {}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn new_creates_with_location() {
        let location = Location::new("test.sleigh", 1);
        let expr = UnaryExpression::new(location.clone());
        assert_eq!(expr.location, location);
        assert!(expr.unary.is_none());
    }

    #[test]
    fn with_operand_stores_operand() {
        let location = Location::new("test.sleigh", 1);

        struct DummyOperand;
        impl PatternExpression for DummyOperand {}

        let operand = Box::new(DummyOperand);
        let expr = UnaryExpression::with_operand(location.clone(), operand);
        assert_eq!(expr.location, location);
        assert!(expr.unary.is_some());
    }

    #[test]
    fn get_unary_returns_stored_operand() {
        let location = Location::new("test.sleigh", 1);

        struct DummyOperand;
        impl PatternExpression for DummyOperand {}

        let operand = Box::new(DummyOperand);
        let expr = UnaryExpression::with_operand(location, operand);
        assert!(expr.get_unary().is_some());
    }

    #[test]
    fn get_unary_returns_none_when_empty() {
        let location = Location::new("test.sleigh", 1);
        let expr = UnaryExpression::new(location);
        assert!(expr.get_unary().is_none());
    }

    #[test]
    fn gen_min_pattern_returns_token_pattern() {
        let location = Location::new("test.sleigh", 1);
        let expr = UnaryExpression::new(location.clone());
        let pattern = expr.gen_min_pattern();
        assert_eq!(pattern.location(), &location);
    }

    #[test]
    fn gen_min_pattern_has_no_constraints() {
        let location = Location::new("test.sleigh", 1);
        let expr = UnaryExpression::new(location);
        let pattern = expr.gen_min_pattern();
        assert!(!pattern.always_true());
        assert!(!pattern.always_false());
    }

    #[test]
    fn encode_succeeds_with_none_operand() {
        let location = Location::new("test.sleigh", 1);
        let expr = UnaryExpression::new(location);

        #[derive(Default)]
        struct NoOpEncoder;
        impl Encoder for NoOpEncoder {
            fn open_element(
                &mut self,
                _elem_id: crate::program::model::pcode::ids::ElementId,
            ) -> io::Result<()> {
                Ok(())
            }

            fn close_element(
                &mut self,
                _elem_id: crate::program::model::pcode::ids::ElementId,
            ) -> io::Result<()> {
                Ok(())
            }

            fn write_bool(
                &mut self,
                _attrib_id: crate::program::model::pcode::ids::AttributeId,
                _val: bool,
            ) -> io::Result<()> {
                Ok(())
            }

            fn write_signed_integer(
                &mut self,
                _attrib_id: crate::program::model::pcode::ids::AttributeId,
                _val: i64,
            ) -> io::Result<()> {
                Ok(())
            }

            fn write_unsigned_integer(
                &mut self,
                _attrib_id: crate::program::model::pcode::ids::AttributeId,
                _val: u64,
            ) -> io::Result<()> {
                Ok(())
            }

            fn write_string(
                &mut self,
                _attrib_id: crate::program::model::pcode::ids::AttributeId,
                _val: &str,
            ) -> io::Result<()> {
                Ok(())
            }

            fn write_string_indexed(
                &mut self,
                _attrib_id: crate::program::model::pcode::ids::AttributeId,
                _index: i32,
                _val: &str,
            ) -> io::Result<()> {
                Ok(())
            }

            fn write_space(
                &mut self,
                _attrib_id: crate::program::model::pcode::ids::AttributeId,
                _spc: &crate::program::model::address::AddressSpace,
            ) -> io::Result<()> {
                Ok(())
            }

            fn write_space_indexed(
                &mut self,
                _attrib_id: crate::program::model::pcode::ids::AttributeId,
                _index: i32,
                _name: &str,
            ) -> io::Result<()> {
                Ok(())
            }

            fn write_opcode(
                &mut self,
                _attrib_id: crate::program::model::pcode::ids::AttributeId,
                _opcode: crate::decompiler::opcodes::op_code::OpCode,
            ) -> io::Result<()> {
                Ok(())
            }

            fn write_opcode_ordinal(
                &mut self,
                _attrib_id: crate::program::model::pcode::ids::AttributeId,
                _opcode: i32,
            ) -> io::Result<()> {
                Ok(())
            }
        }

        let mut encoder = NoOpEncoder::default();
        assert!(expr.encode(&mut encoder).is_ok());
    }

    #[test]
    fn display_shows_location() {
        let location = Location::new("test.sleigh", 42);
        let expr = UnaryExpression::new(location);
        let display = expr.to_string();
        assert!(display.contains("42"));
    }
}
