//! Models `ghidra.pcodeCPort.slghpatexpress.UnaryExpression`.

use crate::decompiler::slghpatexpress::{PatternExpression, PatternValue, TokenPattern};
use crate::decompiler::utils::MutableInt;
use crate::generic::stl::vector_stl::VectorStl;
use crate::program::model::pcode::encoder::Encoder;
use crate::sleigh::grammar::Location;
use std::io;

/// An abstract pattern expression that operates on a single sub-expression.
///
/// UnaryExpression is the base class for binary operators, negation, and other single-operand
/// pattern expressions. Its sub-expression (the unary operand) is managed with reference counting
/// semantics: construction with an operand calls `lay_claim()` on it, and `dispose()` releases it.
///
/// Models `ghidra.pcodeCPort.slghpatexpress.UnaryExpression`.
pub struct UnaryExpression {
    location: Location,
    unary: Option<Box<dyn PatternExpression>>,
}

impl UnaryExpression {
    /// Creates a new, empty unary expression with the given location.
    ///
    /// The sub-expression is initially `None` and must be set via a subclass
    /// or by explicit construction with `with_operand`.
    pub fn new(location: Location) -> Self {
        Self {
            location,
            unary: None,
        }
    }

    /// Creates a new unary expression with a sub-expression operand.
    ///
    /// In Java, this calls `lay_claim()` on the operand; in Rust, we simply take ownership.
    pub fn with_operand(location: Location, operand: Box<dyn PatternExpression>) -> Self {
        Self {
            location,
            unary: Some(operand),
        }
    }

    /// Returns the sub-expression of this unary operation.
    pub fn get_unary(&self) -> Option<&dyn PatternExpression> {
        self.unary.as_ref().map(|b| b.as_ref())
    }

    /// Generates the minimal (unconstrained) token pattern for this expression.
    ///
    /// The minimal pattern carries no constraints; derived classes override this with
    /// operand-specific logic.
    pub fn gen_min_pattern(&self) -> Box<dyn TokenPattern> {
        Box::new(MinimalPattern::new(self.location.clone()))
    }

    /// Encodes the sub-expression to the given encoder.
    ///
    /// The outer tag is generated by derived classes; this method encodes only the operand.
    pub fn encode(&self, encoder: &mut dyn Encoder) -> io::Result<()> {
        if let Some(operand) = &self.unary {
            operand.encode(encoder)?;
        }
        Ok(())
    }
}

impl std::fmt::Display for UnaryExpression {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        write!(f, "unary({})", self.location)
    }
}

impl PatternExpression for UnaryExpression {
    /// Models `UnaryExpression.listValues`: `unary.listValues(list);`.
    fn list_values<'a>(&'a self, list: &mut Vec<&'a dyn PatternValue>) {
        if let Some(unary) = &self.unary {
            unary.list_values(list);
        }
    }

    /// Models `UnaryExpression.getMinMax`: `unary.getMinMax(...);`.
    fn get_min_max(&self, minlist: &mut VectorStl<i64>, maxlist: &mut VectorStl<i64>) {
        if let Some(unary) = &self.unary {
            unary.get_min_max(minlist, maxlist);
        }
    }

    /// `UnaryExpression.getSubValue` is never overridden in Java -- it stays abstract, only
    /// given a real body by each concrete operator (`NotExpression`, `MinusExpression`), since
    /// Java's `UnaryExpression` itself is `abstract` and can never be instantiated directly. See
    /// the identical note on [`crate::decompiler::slghpatexpress::BinaryExpression::get_sub_value`].
    fn get_sub_value(&self, _replace: &VectorStl<i64>, _listpos: &mut MutableInt) -> i64 {
        unimplemented!(
            "UnaryExpression.getSubValue is abstract in Java; only its operator subclasses \
             (NotExpression, MinusExpression) provide a real body"
        )
    }

    fn encode(&self, encoder: &mut dyn Encoder) -> io::Result<()> {
        self.encode(encoder)
    }
}

/// A minimal token pattern used when no operand constraints apply.
struct MinimalPattern {
    location: Location,
}

impl MinimalPattern {
    fn new(location: Location) -> Self {
        Self { location }
    }
}

impl TokenPattern for MinimalPattern {
    fn location(&self) -> &Location {
        &self.location
    }

    fn get_pattern(&self) -> &dyn crate::decompiler::slghpattern::Pattern {
        &EmptyPattern
    }

    fn always_true(&self) -> bool {
        false
    }

    fn always_false(&self) -> bool {
        false
    }

    fn always_instruction_true(&self) -> bool {
        false
    }

    fn get_left_ellipsis(&self) -> bool {
        false
    }

    fn get_right_ellipsis(&self) -> bool {
        false
    }

    fn set_left_ellipsis(&mut self, _val: bool) {}

    fn set_right_ellipsis(&mut self, _val: bool) {}

    fn get_minimum_length(&self) -> i32 {
        0
    }

    fn simplify_pattern(&mut self) {}

    fn copy_into(&mut self, _tokpat: &dyn TokenPattern) {}

    fn do_and(&self, _tokpat: &dyn TokenPattern) -> Box<dyn TokenPattern> {
        Box::new(MinimalPattern::new(self.location.clone()))
    }

    fn do_or(&self, _tokpat: &dyn TokenPattern) -> Box<dyn TokenPattern> {
        Box::new(MinimalPattern::new(self.location.clone()))
    }

    fn do_cat(&self, _tokpat: &dyn TokenPattern) -> Box<dyn TokenPattern> {
        Box::new(MinimalPattern::new(self.location.clone()))
    }

    fn common_sub_pattern(&self, _tokpat: &dyn TokenPattern) -> Box<dyn TokenPattern> {
        Box::new(MinimalPattern::new(self.location.clone()))
    }
}

struct EmptyPattern;
impl crate::decompiler::slghpattern::Pattern for EmptyPattern {
        fn simplify_clone(&self) -> Box<dyn crate::decompiler::slghpattern::Pattern> {
            unimplemented!("not exercised by these tests")
        }
        fn shift_instruction(&mut self, _sa: i32) {}
        fn do_or(&self, _b: &dyn crate::decompiler::slghpattern::Pattern, _sa: i32) -> Box<dyn crate::decompiler::slghpattern::Pattern> {
            unimplemented!("not exercised by these tests")
        }
        fn do_and(&self, _b: &dyn crate::decompiler::slghpattern::Pattern, _sa: i32) -> Box<dyn crate::decompiler::slghpattern::Pattern> {
            unimplemented!("not exercised by these tests")
        }
        fn common_sub_pattern(&self, _b: &dyn crate::decompiler::slghpattern::Pattern, _sa: i32) -> Box<dyn crate::decompiler::slghpattern::Pattern> {
            unimplemented!("not exercised by these tests")
        }
        fn always_true(&self) -> bool {
            false
        }
        fn always_false(&self) -> bool {
            false
        }
        fn always_instruction_true(&self) -> bool {
            false
        }
        fn encode(&self, _encoder: &mut dyn crate::program::model::pcode::Encoder) -> std::io::Result<()> {
            Ok(())
        }
    }

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn new_creates_with_location() {
        let location = Location::new("test.sleigh", 1);
        let expr = UnaryExpression::new(location.clone());
        assert_eq!(expr.location, location);
        assert!(expr.unary.is_none());
    }

    #[test]
    fn with_operand_stores_operand() {
        let location = Location::new("test.sleigh", 1);

        struct DummyOperand;
        impl PatternExpression for DummyOperand {
            fn list_values<'a>(&'a self, _list: &mut Vec<&'a dyn crate::decompiler::slghpatexpress::PatternValue>) {
                unimplemented!("not exercised by this test")
            }
            fn get_min_max(&self, _minlist: &mut crate::generic::stl::vector_stl::VectorStl<i64>, _maxlist: &mut crate::generic::stl::vector_stl::VectorStl<i64>) {
                unimplemented!("not exercised by this test")
            }
            fn get_sub_value(&self, _replace: &crate::generic::stl::vector_stl::VectorStl<i64>, _listpos: &mut crate::decompiler::utils::MutableInt) -> i64 {
                unimplemented!("not exercised by this test")
            }
            fn encode(&self, _encoder: &mut dyn Encoder) -> io::Result<()> {
                Ok(())
            }
        }

        let operand = Box::new(DummyOperand);
        let expr = UnaryExpression::with_operand(location.clone(), operand);
        assert_eq!(expr.location, location);
        assert!(expr.unary.is_some());
    }

    #[test]
    fn get_unary_returns_stored_operand() {
        let location = Location::new("test.sleigh", 1);

        struct DummyOperand;
        impl PatternExpression for DummyOperand {
            fn list_values<'a>(&'a self, _list: &mut Vec<&'a dyn crate::decompiler::slghpatexpress::PatternValue>) {
                unimplemented!("not exercised by this test")
            }
            fn get_min_max(&self, _minlist: &mut crate::generic::stl::vector_stl::VectorStl<i64>, _maxlist: &mut crate::generic::stl::vector_stl::VectorStl<i64>) {
                unimplemented!("not exercised by this test")
            }
            fn get_sub_value(&self, _replace: &crate::generic::stl::vector_stl::VectorStl<i64>, _listpos: &mut crate::decompiler::utils::MutableInt) -> i64 {
                unimplemented!("not exercised by this test")
            }
            fn encode(&self, _encoder: &mut dyn Encoder) -> io::Result<()> {
                Ok(())
            }
        }

        let operand = Box::new(DummyOperand);
        let expr = UnaryExpression::with_operand(location, operand);
        assert!(expr.get_unary().is_some());
    }

    #[test]
    fn get_unary_returns_none_when_empty() {
        let location = Location::new("test.sleigh", 1);
        let expr = UnaryExpression::new(location);
        assert!(expr.get_unary().is_none());
    }

    #[test]
    fn gen_min_pattern_returns_token_pattern() {
        let location = Location::new("test.sleigh", 1);
        let expr = UnaryExpression::new(location.clone());
        let pattern = expr.gen_min_pattern();
        assert_eq!(pattern.location(), &location);
    }

    #[test]
    fn gen_min_pattern_has_no_constraints() {
        let location = Location::new("test.sleigh", 1);
        let expr = UnaryExpression::new(location);
        let pattern = expr.gen_min_pattern();
        assert!(!pattern.always_true());
        assert!(!pattern.always_false());
    }

    #[test]
    fn encode_succeeds_with_none_operand() {
        let location = Location::new("test.sleigh", 1);
        let expr = UnaryExpression::new(location);

        #[derive(Default)]
        struct NoOpEncoder;
        impl Encoder for NoOpEncoder {
            fn open_element(
                &mut self,
                _elem_id: crate::program::model::pcode::ids::ElementId,
            ) -> io::Result<()> {
                Ok(())
            }

            fn close_element(
                &mut self,
                _elem_id: crate::program::model::pcode::ids::ElementId,
            ) -> io::Result<()> {
                Ok(())
            }

            fn write_bool(
                &mut self,
                _attrib_id: crate::program::model::pcode::ids::AttributeId,
                _val: bool,
            ) -> io::Result<()> {
                Ok(())
            }

            fn write_signed_integer(
                &mut self,
                _attrib_id: crate::program::model::pcode::ids::AttributeId,
                _val: i64,
            ) -> io::Result<()> {
                Ok(())
            }

            fn write_unsigned_integer(
                &mut self,
                _attrib_id: crate::program::model::pcode::ids::AttributeId,
                _val: u64,
            ) -> io::Result<()> {
                Ok(())
            }

            fn write_string(
                &mut self,
                _attrib_id: crate::program::model::pcode::ids::AttributeId,
                _val: &str,
            ) -> io::Result<()> {
                Ok(())
            }

            fn write_string_indexed(
                &mut self,
                _attrib_id: crate::program::model::pcode::ids::AttributeId,
                _index: i32,
                _val: &str,
            ) -> io::Result<()> {
                Ok(())
            }

            fn write_space(
                &mut self,
                _attrib_id: crate::program::model::pcode::ids::AttributeId,
                _spc: &crate::program::model::address::AddressSpace,
            ) -> io::Result<()> {
                Ok(())
            }

            fn write_space_indexed(
                &mut self,
                _attrib_id: crate::program::model::pcode::ids::AttributeId,
                _index: i32,
                _name: &str,
            ) -> io::Result<()> {
                Ok(())
            }

            fn write_opcode(
                &mut self,
                _attrib_id: crate::program::model::pcode::ids::AttributeId,
                _opcode: crate::decompiler::opcodes::op_code::OpCode,
            ) -> io::Result<()> {
                Ok(())
            }

            fn write_opcode_ordinal(
                &mut self,
                _attrib_id: crate::program::model::pcode::ids::AttributeId,
                _opcode: i32,
            ) -> io::Result<()> {
                Ok(())
            }
        }

        let mut encoder = NoOpEncoder::default();
        assert!(expr.encode(&mut encoder).is_ok());
    }

    #[test]
    fn display_shows_location() {
        let location = Location::new("test.sleigh", 42);
        let expr = UnaryExpression::new(location);
        let display = expr.to_string();
        assert!(display.contains("42"));
    }
}
