/// A callback for bytes generated by the terminal, e.g., to report a key press or reply to a request.
///
/// Most likely these bytes should be sent down an output stream, usually to a pty.
pub trait VtOutput {
    /// Handle output from the terminal
    ///
    /// # Arguments
    ///
    /// * `buf` - the buffer of bytes generated
    fn out(&mut self, buf: &[u8]);
}

#[cfg(test)]
mod tests {
    use super::*;

    struct TestOutput {
        buffer: Vec<u8>,
    }

    impl TestOutput {
        fn new() -> Self {
            TestOutput {
                buffer: Vec::new(),
            }
        }
    }

    impl VtOutput for TestOutput {
        fn out(&mut self, buf: &[u8]) {
            self.buffer.extend_from_slice(buf);
        }
    }

    #[test]
    fn test_vt_output_single_byte() {
        let mut output = TestOutput::new();
        output.out(&[42]);
        assert_eq!(output.buffer, vec![42]);
    }

    #[test]
    fn test_vt_output_multiple_bytes() {
        let mut output = TestOutput::new();
        output.out(&[1, 2, 3, 4, 5]);
        assert_eq!(output.buffer, vec![1, 2, 3, 4, 5]);
    }

    #[test]
    fn test_vt_output_multiple_calls() {
        let mut output = TestOutput::new();
        output.out(&[1, 2]);
        output.out(&[3, 4]);
        output.out(&[5]);
        assert_eq!(output.buffer, vec![1, 2, 3, 4, 5]);
    }

    #[test]
    fn test_vt_output_empty_buffer() {
        let mut output = TestOutput::new();
        output.out(&[]);
        assert_eq!(output.buffer, Vec::<u8>::new());
    }

    #[test]
    fn test_vt_output_with_control_characters() {
        let mut output = TestOutput::new();
        // Test with common control characters like newline, carriage return, bell
        output.out(&[0x0A]); // newline
        output.out(&[0x0D]); // carriage return
        output.out(&[0x07]); // bell
        assert_eq!(output.buffer, vec![0x0A, 0x0D, 0x07]);
    }
}
