//! The subset of `java.nio.charset` (`Charset`, `CharsetDecoder`, `CharsetEncoder`,
//! `CoderResult`, `CharacterCodingException`) that Ghidra's string and char data types rely on.
//!
//! Ghidra decodes string data through whatever `java.nio.charset.Charset` a user picks, and its
//! rendering (`StringRenderBuilder`) depends on the exact way a JDK decoder reports bad input:
//! how many bytes each malformed sequence spans, and where decoding resumes. [`JavaCharset`]
//! reproduces those JDK 21 behaviours for:
//!
//! - `UTF-8`, `UTF-16`, `UTF-16BE`, `UTF-16LE`, `UTF-32`, `UTF-32BE`, `UTF-32LE`, implemented
//!   algorithmically after `sun.nio.cs.UTF_8`, `sun.nio.cs.UnicodeDecoder`/`UnicodeEncoder` and
//!   `sun.nio.cs.UTF_32Coder` (byte-order-mark handling included);
//! - every JDK charset whose encoder emits one byte per char (104 of them: `US-ASCII`,
//!   `ISO-8859-*`, `windows-125*`, the IBM/EBCDIC code pages such as `IBM-Thai`, the Mac code
//!   pages, `KOI8-*`, ...), table-driven from [`SINGLE_BYTE_TABLES`], which was generated by
//!   probing a JDK 21 runtime byte by byte and char by char.
//!
//! The multi-byte CJK charsets (`Shift_JIS`, `GBK`, `Big5`, `EUC-*`, `ISO-2022-*`, ...) and the
//! JDK-private variants (`CESU-8`, `x-UTF-16LE-BOM`, ...) are not provided: their tables are
//! large and no charset-codec dependency is approved for this crate. [`JavaCharset::for_name`]
//! reports them as unsupported, exactly as `Charset.isSupported` does for a charset a JVM lacks.
//!
//! Java strings are sequences of UTF-16 code units, and a JDK decoder can produce an unpaired
//! surrogate (a `UTF-32` decoder decodes `0x0000D800` to the lone char `U+D800`). Decoders here
//! therefore produce UTF-16 units (`Vec<u16>`), and the encoders consume them, so the Java
//! semantics survive intact; [`JavaCharset::decode_to_string`] converts to a Rust `String` at the
//! end, where an unpaired surrogate can only be represented as `U+FFFD`.

use std::fmt;

use super::single_byte_tables::SINGLE_BYTE_TABLES;

/// One JDK single-byte charset: its canonical name, aliases, the char each byte decodes to
/// (`U+FFFD` marks a byte the decoder rejects), its encoder replacement byte, and the chars whose
/// encoding differs from the inverse of the decode table (`-1`: not encodable).
#[derive(Debug)]
pub struct SingleByteTable {
    pub(super) name: &'static str,
    pub(super) aliases: &'static [&'static str],
    pub(super) decode: [u16; 256],
    pub(super) replacement: u8,
    pub(super) encode_overrides: &'static [(u16, i16)],
}

/// Byte order of a UTF-16/UTF-32 codec. `Unmarked` is the plain `UTF-16`/`UTF-32` charset, whose
/// decoder reads the order from a leading byte-order mark (defaulting to big endian).
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
enum ByteOrder {
    Unmarked,
    Big,
    Little,
}

#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
enum Kind {
    Utf8,
    Utf16(ByteOrder),
    Utf32(ByteOrder),
    /// Index into [`SINGLE_BYTE_TABLES`].
    SingleByte(usize),
}

/// The algorithmic (UTF) charsets: canonical name, aliases, kind.
const UTF_CHARSETS: &[(&str, &[&str], Kind)] = &[
    ("UTF-8", &["UTF8", "unicode-1-1-utf-8"], Kind::Utf8),
    ("UTF-16", &["UTF_16", "UnicodeBig", "unicode", "utf16"], Kind::Utf16(ByteOrder::Unmarked)),
    (
        "UTF-16BE",
        &["ISO-10646-UCS-2", "UTF_16BE", "UnicodeBigUnmarked", "X-UTF-16BE"],
        Kind::Utf16(ByteOrder::Big),
    ),
    ("UTF-16LE", &["UTF_16LE", "UnicodeLittleUnmarked", "X-UTF-16LE"], Kind::Utf16(ByteOrder::Little)),
    ("UTF-32", &["UTF32", "UTF_32"], Kind::Utf32(ByteOrder::Unmarked)),
    ("UTF-32BE", &["UTF_32BE", "X-UTF-32BE"], Kind::Utf32(ByteOrder::Big)),
    ("UTF-32LE", &["UTF_32LE", "X-UTF-32LE"], Kind::Utf32(ByteOrder::Little)),
];

const REPLACEMENT_CHAR: u16 = 0xFFFD;
const BYTE_ORDER_MARK: u16 = 0xFEFF;
const REVERSED_MARK: u16 = 0xFFFE;
const BOM_BIG_32: u32 = 0x0000_FEFF;
const BOM_LITTLE_32: u32 = 0xFFFE_0000;

/// A character set, standing in for `java.nio.charset.Charset`. See the module docs for which
/// charsets exist.
#[derive(Clone, Copy, PartialEq, Eq, Hash)]
pub struct JavaCharset {
    kind: Kind,
}

impl fmt::Debug for JavaCharset {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "JavaCharset({})", self.name())
    }
}

impl fmt::Display for JavaCharset {
    /// `Charset.toString()` is the canonical name.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(self.name())
    }
}

impl JavaCharset {
    /// `StandardCharsets.US_ASCII`.
    pub fn us_ascii() -> JavaCharset {
        JavaCharset::for_name("US-ASCII").expect("US-ASCII is always present")
    }

    /// `StandardCharsets.ISO_8859_1`.
    pub fn iso_8859_1() -> JavaCharset {
        JavaCharset::for_name("ISO-8859-1").expect("ISO-8859-1 is always present")
    }

    /// `StandardCharsets.UTF_8`.
    pub const UTF_8: JavaCharset = JavaCharset { kind: Kind::Utf8 };
    /// `StandardCharsets.UTF_16` (reads a byte-order mark; writes one, then big endian).
    pub const UTF_16: JavaCharset = JavaCharset { kind: Kind::Utf16(ByteOrder::Unmarked) };
    /// `StandardCharsets.UTF_16BE`.
    pub const UTF_16BE: JavaCharset = JavaCharset { kind: Kind::Utf16(ByteOrder::Big) };
    /// `StandardCharsets.UTF_16LE`.
    pub const UTF_16LE: JavaCharset = JavaCharset { kind: Kind::Utf16(ByteOrder::Little) };
    /// `Charset.forName("UTF-32")` (reads a byte-order mark; writes big endian without one).
    pub const UTF_32: JavaCharset = JavaCharset { kind: Kind::Utf32(ByteOrder::Unmarked) };
    /// `Charset.forName("UTF-32BE")`.
    pub const UTF_32BE: JavaCharset = JavaCharset { kind: Kind::Utf32(ByteOrder::Big) };
    /// `Charset.forName("UTF-32LE")`.
    pub const UTF_32LE: JavaCharset = JavaCharset { kind: Kind::Utf32(ByteOrder::Little) };

    /// `Charset.forName(name)`: looks `name` up among canonical names and aliases, ignoring ASCII
    /// case. `None` where Java throws `UnsupportedCharsetException`/`IllegalCharsetNameException`.
    pub fn for_name(name: &str) -> Option<JavaCharset> {
        for (canonical, aliases, kind) in UTF_CHARSETS {
            if canonical.eq_ignore_ascii_case(name) || aliases.iter().any(|a| a.eq_ignore_ascii_case(name)) {
                return Some(JavaCharset { kind: *kind });
            }
        }
        SINGLE_BYTE_TABLES
            .iter()
            .position(|t| t.name.eq_ignore_ascii_case(name) || t.aliases.iter().any(|a| a.eq_ignore_ascii_case(name)))
            .map(|i| JavaCharset { kind: Kind::SingleByte(i) })
    }

    /// `Charset.isSupported(name)`.
    pub fn is_supported(name: &str) -> bool {
        JavaCharset::for_name(name).is_some()
    }

    /// `Charset.availableCharsets()`: every charset, ordered by canonical name ignoring ASCII case
    /// (Java's `ASCIICaseInsensitiveComparator`).
    pub fn available_charsets() -> Vec<JavaCharset> {
        let mut all: Vec<JavaCharset> = UTF_CHARSETS
            .iter()
            .map(|(_, _, kind)| JavaCharset { kind: *kind })
            .chain((0..SINGLE_BYTE_TABLES.len()).map(|i| JavaCharset { kind: Kind::SingleByte(i) }))
            .collect();
        all.sort_by_key(|cs| cs.name().to_ascii_lowercase());
        all
    }

    /// `Charset.name()`: the canonical name.
    pub fn name(&self) -> &'static str {
        match self.kind {
            Kind::SingleByte(i) => SINGLE_BYTE_TABLES[i].name,
            kind => UTF_CHARSETS.iter().find(|(_, _, k)| *k == kind).map(|(n, _, _)| *n).unwrap_or(""),
        }
    }

    /// `Charset.aliases()`.
    pub fn aliases(&self) -> &'static [&'static str] {
        match self.kind {
            Kind::SingleByte(i) => SINGLE_BYTE_TABLES[i].aliases,
            kind => UTF_CHARSETS.iter().find(|(_, _, k)| *k == kind).map(|(_, a, _)| *a).unwrap_or(&[]),
        }
    }

    /// `newEncoder().maxBytesPerChar()`, rounded up to a whole byte count.
    pub fn max_bytes_per_char(&self) -> i32 {
        match self.kind {
            Kind::Utf8 => 3,
            // The UTF-16 encoder writes a 2-byte mark before the first char.
            Kind::Utf16(ByteOrder::Unmarked) => 4,
            Kind::Utf16(_) => 2,
            Kind::Utf32(_) => 4,
            Kind::SingleByte(_) => 1,
        }
    }

    /// `newDecoder()`: a decoder in its reset state that reports (rather than replaces) malformed
    /// and unmappable input (`CodingErrorAction.REPORT`).
    pub fn new_decoder(&self) -> JavaCharsetDecoder {
        JavaCharsetDecoder { kind: self.kind, current: self.initial_order() }
    }

    fn initial_order(&self) -> ByteOrder {
        match self.kind {
            Kind::Utf16(order) => order,
            // UTF_32Coder.Decoder starts every decode with currentBO == NONE, whatever charset.
            Kind::Utf32(_) => ByteOrder::Unmarked,
            _ => ByteOrder::Big,
        }
    }

    /// `new String(bytes, charset)`, as Java UTF-16 code units: every malformed or unmappable
    /// sequence becomes one `U+FFFD`.
    pub fn decode_to_units(&self, bytes: &[u8]) -> Vec<u16> {
        let mut decoder = self.new_decoder();
        let mut out = Vec::with_capacity(bytes.len());
        let mut pos = 0;
        while pos < bytes.len() {
            let result = decoder.decode(bytes, &mut pos, &mut out);
            if let Some(len) = result.error_length() {
                out.push(REPLACEMENT_CHAR);
                pos += len;
            }
        }
        out
    }

    /// `new String(bytes, charset)` as a Rust string. An unpaired surrogate the decoder produced
    /// (possible only from `UTF-32`) becomes `U+FFFD`, since a `String` cannot hold one.
    pub fn decode_to_string(&self, bytes: &[u8]) -> String {
        String::from_utf16_lossy(&self.decode_to_units(bytes))
    }

    /// `newEncoder().encode(CharBuffer)`: encodes Java chars, failing on the first malformed
    /// (unpaired surrogate) or unmappable char.
    pub fn encode_units(&self, chars: &[u16]) -> Result<Vec<u8>, CharacterCodingException> {
        let mut out = Vec::with_capacity(chars.len() * self.max_bytes_per_char() as usize);
        let mut pos = 0;
        self.write_mark(chars, &mut out);
        while pos < chars.len() {
            match self.encode_one(chars, pos, &mut out) {
                Ok(n) => pos += n,
                Err(e) => return Err(e),
            }
        }
        Ok(out)
    }

    /// Encodes a Rust string, as [`encode_units`](Self::encode_units) does its UTF-16 form.
    pub fn encode_str(&self, text: &str) -> Result<Vec<u8>, CharacterCodingException> {
        let units: Vec<u16> = text.encode_utf16().collect();
        self.encode_units(&units)
    }

    /// `Charset.encode(CharBuffer)`: encodes Java chars, writing the charset's replacement for
    /// every malformed or unmappable char (or surrogate pair).
    pub fn encode_units_replacing(&self, chars: &[u16]) -> Vec<u8> {
        let mut out = Vec::with_capacity(chars.len() * self.max_bytes_per_char() as usize);
        let mut pos = 0;
        self.write_mark(chars, &mut out);
        while pos < chars.len() {
            match self.encode_one(chars, pos, &mut out) {
                Ok(n) => pos += n,
                Err(e) => {
                    self.write_replacement(&mut out);
                    pos += e.length();
                }
            }
        }
        out
    }

    /// The unmarked `UTF-16` encoder writes a big-endian byte-order mark before the first char.
    fn write_mark(&self, chars: &[u16], out: &mut Vec<u8>) {
        if self.kind == Kind::Utf16(ByteOrder::Unmarked) && !chars.is_empty() {
            out.extend_from_slice(&BYTE_ORDER_MARK.to_be_bytes());
        }
    }

    fn write_replacement(&self, out: &mut Vec<u8>) {
        match self.kind {
            Kind::Utf8 => out.push(b'?'),
            Kind::Utf16(order) => put_u16(out, REPLACEMENT_CHAR, order != ByteOrder::Little),
            Kind::Utf32(order) => put_u32(out, REPLACEMENT_CHAR as u32, order != ByteOrder::Little),
            Kind::SingleByte(i) => out.push(SINGLE_BYTE_TABLES[i].replacement),
        }
    }

    /// Encodes the char (or surrogate pair) at `chars[pos]`, returning how many chars it used.
    fn encode_one(&self, chars: &[u16], pos: usize, out: &mut Vec<u8>) -> Result<usize, CharacterCodingException> {
        let c = chars[pos];
        let (code_point, used) = if is_high_surrogate(c) {
            match chars.get(pos + 1) {
                Some(&low) if is_low_surrogate(low) => (to_code_point(c, low), 2),
                _ => return Err(CharacterCodingException::Malformed(1)),
            }
        } else if is_low_surrogate(c) {
            return Err(CharacterCodingException::Malformed(1));
        } else {
            (c as u32, 1)
        };
        match self.kind {
            Kind::Utf8 => {
                let ch = char::from_u32(code_point).expect("surrogates were rejected above");
                let mut buf = [0u8; 4];
                out.extend_from_slice(ch.encode_utf8(&mut buf).as_bytes());
            }
            Kind::Utf16(order) => {
                let big = order != ByteOrder::Little;
                for &unit in &chars[pos..pos + used] {
                    put_u16(out, unit, big);
                }
            }
            Kind::Utf32(order) => put_u32(out, code_point, order != ByteOrder::Little),
            Kind::SingleByte(i) => {
                if used == 2 {
                    return Err(CharacterCodingException::Unmappable(2));
                }
                match single_byte_encode(&SINGLE_BYTE_TABLES[i], c) {
                    Some(b) => out.push(b),
                    None => return Err(CharacterCodingException::Unmappable(1)),
                }
            }
        }
        Ok(used)
    }

    /// Whether `ch` can be encoded (`newEncoder().canEncode(char)`).
    pub fn can_encode(&self, ch: char) -> bool {
        let mut units = [0u16; 2];
        let mut scratch = Vec::new();
        self.encode_one(ch.encode_utf16(&mut units), 0, &mut scratch).is_ok()
    }
}

fn single_byte_encode(table: &SingleByteTable, c: u16) -> Option<u8> {
    if let Some(&(_, b)) = table.encode_overrides.iter().find(|(ch, _)| *ch == c) {
        return if b < 0 { None } else { Some(b as u8) };
    }
    if c == REPLACEMENT_CHAR {
        return None;
    }
    table.decode.iter().position(|&d| d == c).map(|b| b as u8)
}

fn put_u16(out: &mut Vec<u8>, value: u16, big_endian: bool) {
    out.extend_from_slice(&if big_endian { value.to_be_bytes() } else { value.to_le_bytes() });
}

fn put_u32(out: &mut Vec<u8>, value: u32, big_endian: bool) {
    out.extend_from_slice(&if big_endian { value.to_be_bytes() } else { value.to_le_bytes() });
}

/// `Character.isHighSurrogate(char)`.
pub fn is_high_surrogate(c: u16) -> bool {
    (0xD800..=0xDBFF).contains(&c)
}

/// `Character.isLowSurrogate(char)`.
pub fn is_low_surrogate(c: u16) -> bool {
    (0xDC00..=0xDFFF).contains(&c)
}

/// `Character.toCodePoint(char, char)`.
pub fn to_code_point(high: u16, low: u16) -> u32 {
    (((high as u32) - 0xD800) << 10) + ((low as u32) - 0xDC00) + 0x1_0000
}

/// `Character.codePointAt(CharSequence, int)`: the code point starting at `units[index]`, pairing
/// a high surrogate with a following low surrogate.
pub fn code_point_at(units: &[u16], index: usize) -> u32 {
    let c = units[index];
    if is_high_surrogate(c) {
        if let Some(&low) = units.get(index + 1) {
            if is_low_surrogate(low) {
                return to_code_point(c, low);
            }
        }
    }
    c as u32
}

/// `Character.charCount(int)`.
pub fn char_count(code_point: u32) -> usize {
    if code_point >= 0x1_0000 {
        2
    } else {
        1
    }
}

/// The outcome of one [`JavaCharsetDecoder::decode`] call, standing in for
/// `java.nio.charset.CoderResult` (with `endOfInput == true`, so there is no overflow).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CoderResult {
    /// All input was consumed (`CoderResult.UNDERFLOW`).
    Underflow,
    /// A malformed sequence of this many bytes starts at the position
    /// (`CoderResult.malformedForLength`).
    Malformed(usize),
    /// An unmappable sequence of this many bytes starts at the position
    /// (`CoderResult.unmappableForLength`).
    Unmappable(usize),
}

impl CoderResult {
    /// `CoderResult.isError()`.
    pub fn is_error(&self) -> bool {
        !matches!(self, CoderResult::Underflow)
    }

    /// `CoderResult.length()` for an error, `None` for underflow.
    pub fn error_length(&self) -> Option<usize> {
        match *self {
            CoderResult::Underflow => None,
            CoderResult::Malformed(n) | CoderResult::Unmappable(n) => Some(n),
        }
    }
}

/// `java.nio.charset.MalformedInputException` / `UnmappableCharacterException` (both
/// `CharacterCodingException`s).
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum CharacterCodingException {
    /// `MalformedInputException`: the input is not a legal sequence.
    Malformed(usize),
    /// `UnmappableCharacterException`: the input is legal but has no mapping in the charset.
    Unmappable(usize),
}

impl CharacterCodingException {
    /// `getInputLength()`.
    pub fn length(&self) -> usize {
        match *self {
            CharacterCodingException::Malformed(n) | CharacterCodingException::Unmappable(n) => n,
        }
    }
}

impl fmt::Display for CharacterCodingException {
    /// The JDK exception messages: `"Input length = N"`.
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "Input length = {}", self.length())
    }
}

impl std::error::Error for CharacterCodingException {}

/// A charset decoder with `CodingErrorAction.REPORT` for malformed and unmappable input,
/// standing in for `java.nio.charset.CharsetDecoder`. It is stateful the same way the JDK
/// decoders are: a UTF-16/UTF-32 byte-order mark is only recognised at the start of the input.
#[derive(Debug, Clone)]
pub struct JavaCharsetDecoder {
    kind: Kind,
    current: ByteOrder,
}

impl JavaCharsetDecoder {
    /// `decode(in, out, true)`: decodes `input[*pos..]` into `out` until the input is exhausted
    /// or a bad sequence is found. On error `*pos` is left at the start of the bad sequence, whose
    /// length the result carries; bytes left over at the end of the input that cannot form a
    /// complete character are reported as one malformed sequence, as Java does at end of input.
    pub fn decode(&mut self, input: &[u8], pos: &mut usize, out: &mut Vec<u16>) -> CoderResult {
        let result = match self.kind {
            Kind::Utf8 => decode_utf8(input, pos, out),
            Kind::Utf16(_) => self.decode_utf16(input, pos, out),
            Kind::Utf32(expected) => self.decode_utf32(input, pos, out, expected),
            Kind::SingleByte(i) => decode_single_byte(&SINGLE_BYTE_TABLES[i], input, pos, out),
        };
        match result {
            CoderResult::Underflow if *pos < input.len() => CoderResult::Malformed(input.len() - *pos),
            other => other,
        }
    }

    /// After `sun.nio.cs.UnicodeDecoder.decodeLoop`.
    fn decode_utf16(&mut self, input: &[u8], pos: &mut usize, out: &mut Vec<u16>) -> CoderResult {
        while input.len() - *pos > 1 {
            let (b1, b2) = (input[*pos], input[*pos + 1]);
            if self.current == ByteOrder::Unmarked {
                let c = u16::from_be_bytes([b1, b2]);
                if c == BYTE_ORDER_MARK {
                    self.current = ByteOrder::Big;
                    *pos += 2;
                    continue;
                } else if c == REVERSED_MARK {
                    self.current = ByteOrder::Little;
                    *pos += 2;
                    continue;
                }
                self.current = ByteOrder::Big;
            }
            let c = self.unit(b1, b2);
            if is_high_surrogate(c) {
                if input.len() - *pos < 4 {
                    return CoderResult::Underflow;
                }
                let c2 = self.unit(input[*pos + 2], input[*pos + 3]);
                if !is_low_surrogate(c2) {
                    return CoderResult::Malformed(4);
                }
                out.push(c);
                out.push(c2);
                *pos += 4;
                continue;
            }
            if is_low_surrogate(c) {
                return CoderResult::Malformed(2);
            }
            out.push(c);
            *pos += 2;
        }
        CoderResult::Underflow
    }

    fn unit(&self, b1: u8, b2: u8) -> u16 {
        if self.current == ByteOrder::Little {
            u16::from_le_bytes([b1, b2])
        } else {
            u16::from_be_bytes([b1, b2])
        }
    }

    /// After `sun.nio.cs.UTF_32Coder.Decoder.decodeLoop`.
    fn decode_utf32(&mut self, input: &[u8], pos: &mut usize, out: &mut Vec<u16>, expected: ByteOrder) -> CoderResult {
        if input.len() - *pos < 4 {
            return CoderResult::Underflow;
        }
        if self.current == ByteOrder::Unmarked {
            let cp = u32::from_be_bytes([input[*pos], input[*pos + 1], input[*pos + 2], input[*pos + 3]]);
            if cp == BOM_BIG_32 && expected != ByteOrder::Little {
                self.current = ByteOrder::Big;
                *pos += 4;
            } else if cp == BOM_LITTLE_32 && expected != ByteOrder::Big {
                self.current = ByteOrder::Little;
                *pos += 4;
            } else if expected == ByteOrder::Unmarked {
                self.current = ByteOrder::Big;
            } else {
                self.current = expected;
            }
        }
        while input.len() - *pos >= 4 {
            let bytes = [input[*pos], input[*pos + 1], input[*pos + 2], input[*pos + 3]];
            let cp = if self.current == ByteOrder::Little {
                u32::from_le_bytes(bytes)
            } else {
                u32::from_be_bytes(bytes)
            };
            if cp < 0x1_0000 {
                // Character.isBmpCodePoint: includes the surrogate range.
                out.push(cp as u16);
            } else if cp <= 0x10_FFFF {
                let v = cp - 0x1_0000;
                out.push(0xD800 + (v >> 10) as u16);
                out.push(0xDC00 + (v & 0x3FF) as u16);
            } else {
                return CoderResult::Malformed(4);
            }
            *pos += 4;
        }
        CoderResult::Underflow
    }
}

fn decode_single_byte(table: &SingleByteTable, input: &[u8], pos: &mut usize, out: &mut Vec<u16>) -> CoderResult {
    while *pos < input.len() {
        let c = table.decode[input[*pos] as usize];
        if c == REPLACEMENT_CHAR {
            // US_ASCII's decoder reports bytes >= 0x80 as malformed; SingleByte.Decoder reports
            // bytes without a mapping as unmappable.
            return if table.name == "US-ASCII" {
                CoderResult::Malformed(1)
            } else {
                CoderResult::Unmappable(1)
            };
        }
        out.push(c);
        *pos += 1;
    }
    CoderResult::Underflow
}

fn is_not_continuation(b: u8) -> bool {
    (b & 0xC0) != 0x80
}

/// `UTF_8.Decoder.isMalformed3`.
fn is_malformed3(b1: u8, b2: u8, b3: u8) -> bool {
    (b1 == 0xE0 && (b2 & 0xE0) == 0x80) || is_not_continuation(b2) || is_not_continuation(b3)
}

/// `UTF_8.Decoder.isMalformed3_2`.
fn is_malformed3_2(b1: u8, b2: u8) -> bool {
    (b1 == 0xE0 && (b2 & 0xE0) == 0x80) || is_not_continuation(b2)
}

/// `UTF_8.Decoder.isMalformed4_2`.
fn is_malformed4_2(b1: u8, b2: u8) -> bool {
    (b1 == 0xF0 && !(0x90..=0xBF).contains(&b2)) || (b1 == 0xF4 && (b2 & 0xF0) != 0x80) || is_not_continuation(b2)
}

/// `UTF_8.Decoder.malformedN`: the length reported for a malformed `nb`-byte sequence starting
/// at `input[sp]`.
fn malformed_n(input: &[u8], sp: usize, nb: usize) -> usize {
    match nb {
        3 => {
            let (b1, b2) = (input[sp], input[sp + 1]);
            if (b1 == 0xE0 && (b2 & 0xE0) == 0x80) || is_not_continuation(b2) {
                1
            } else {
                2
            }
        }
        4 => {
            let (b1, b2) = (input[sp], input[sp + 1]);
            if b1 > 0xF4
                || (b1 == 0xF0 && !(0x90..=0xBF).contains(&b2))
                || (b1 == 0xF4 && (b2 & 0xF0) != 0x80)
                || is_not_continuation(b2)
            {
                1
            } else if is_not_continuation(input[sp + 2]) {
                2
            } else {
                3
            }
        }
        _ => 1,
    }
}

/// After `sun.nio.cs.UTF_8.Decoder.decodeArrayLoop`.
fn decode_utf8(input: &[u8], pos: &mut usize, out: &mut Vec<u16>) -> CoderResult {
    let sl = input.len();
    while *pos < sl {
        let sp = *pos;
        let b1 = input[sp];
        if b1 < 0x80 {
            out.push(b1 as u16);
            *pos += 1;
        } else if (b1 >> 5) == 0b110 && (b1 & 0x1E) != 0 {
            if sl - sp < 2 {
                return CoderResult::Underflow;
            }
            let b2 = input[sp + 1];
            if is_not_continuation(b2) {
                return CoderResult::Malformed(1);
            }
            out.push((((b1 as u16) & 0x1F) << 6) | ((b2 as u16) & 0x3F));
            *pos += 2;
        } else if (b1 >> 4) == 0b1110 {
            let remaining = sl - sp;
            if remaining < 3 {
                if remaining > 1 && is_malformed3_2(b1, input[sp + 1]) {
                    return CoderResult::Malformed(1);
                }
                return CoderResult::Underflow;
            }
            let (b2, b3) = (input[sp + 1], input[sp + 2]);
            if is_malformed3(b1, b2, b3) {
                return CoderResult::Malformed(malformed_n(input, sp, 3));
            }
            let c = (((b1 as u16) & 0x0F) << 12) | (((b2 as u16) & 0x3F) << 6) | ((b3 as u16) & 0x3F);
            if (0xD800..=0xDFFF).contains(&c) {
                return CoderResult::Malformed(3);
            }
            out.push(c);
            *pos += 3;
        } else if (b1 >> 3) == 0b11110 {
            let remaining = sl - sp;
            if remaining < 4 {
                if b1 > 0xF4 || (remaining > 1 && is_malformed4_2(b1, input[sp + 1])) {
                    return CoderResult::Malformed(1);
                }
                if remaining > 2 && is_not_continuation(input[sp + 2]) {
                    return CoderResult::Malformed(2);
                }
                return CoderResult::Underflow;
            }
            let (b2, b3, b4) = (input[sp + 1], input[sp + 2], input[sp + 3]);
            let uc = (((b1 as u32) & 0x07) << 18) | (((b2 as u32) & 0x3F) << 12) | (((b3 as u32) & 0x3F) << 6) | ((b4 as u32) & 0x3F);
            if is_not_continuation(b2) || is_not_continuation(b3) || is_not_continuation(b4) || !(0x1_0000..=0x10_FFFF).contains(&uc) {
                return CoderResult::Malformed(malformed_n(input, sp, 4));
            }
            let v = uc - 0x1_0000;
            out.push(0xD800 + (v >> 10) as u16);
            out.push(0xDC00 + (v & 0x3FF) as u16);
            *pos += 4;
        } else {
            return CoderResult::Malformed(1);
        }
    }
    CoderResult::Underflow
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Runs the decode loop `StringRenderBuilder.decodeBytesUsingCharset` uses and records what
    /// the JDK probe printed: each decoded char as `U+XXXX`, each error as `ERRnm` (malformed) or
    /// `ERRnu` (unmappable).
    fn trace(name: &str, bytes: &[u8]) -> String {
        let cs = JavaCharset::for_name(name).unwrap();
        let mut decoder = cs.new_decoder();
        let mut pos = 0;
        let mut out = Vec::new();
        let mut parts = Vec::new();
        while pos < bytes.len() {
            out.clear();
            let r = decoder.decode(bytes, &mut pos, &mut out);
            parts.extend(out.iter().map(|c| format!("U+{c:04X}")));
            match r {
                CoderResult::Malformed(n) => {
                    parts.push(format!("ERR{n}m"));
                    pos += n;
                }
                CoderResult::Unmappable(n) => {
                    parts.push(format!("ERR{n}u"));
                    pos += n;
                }
                CoderResult::Underflow => {}
            }
        }
        parts.join(" ")
    }

    // Expected values below were printed by a JDK 21 `CharsetDecoder` (REPORT) running the same
    // loop.

    #[test]
    fn utf8_malformed_lengths_match_jdk() {
        assert_eq!(trace("UTF-8", &[b't', b'e', b's', b't', 0xE1, 0x84]), "U+0074 U+0065 U+0073 U+0074 ERR2m");
        assert_eq!(trace("UTF-8", &[0xE1, 0x84, 0x41]), "ERR2m U+0041");
        assert_eq!(trace("UTF-8", &[0xED, 0xA0, 0x80, 0x41]), "ERR3m U+0041");
        assert_eq!(trace("UTF-8", &[0xC0, 0x80, 0x41]), "ERR1m ERR1m U+0041");
        assert_eq!(trace("UTF-8", &[0xF4, 0x90, 0x80, 0x80, 0x41]), "ERR1m ERR1m ERR1m ERR1m U+0041");
        assert_eq!(trace("UTF-8", &[0xF0, 0x9F, 0x98, 0x80, 0x41]), "U+D83D U+DE00 U+0041");
        assert_eq!(trace("UTF-8", &[0xF0, 0x9F, 0x41]), "ERR2m U+0041");
        assert_eq!(trace("UTF-8", &[0xE0, 0x80, 0x41]), "ERR1m ERR1m U+0041");
        assert_eq!(trace("UTF-8", &[0x80, 0xBF, 0x41]), "ERR1m ERR1m U+0041");
        assert_eq!(trace("UTF-8", &[0xF8, 0x88, 0x80, 0x80, 0x80]), "ERR1m ERR1m ERR1m ERR1m ERR1m");
        assert_eq!(trace("UTF-8", &[0xEF, 0xBF, 0xBF]), "U+FFFF");
    }

    #[test]
    fn utf16_matches_jdk() {
        assert_eq!(trace("UTF-16BE", &[0xD8, 0x00, 0x00, 0x41]), "ERR4m");
        assert_eq!(trace("UTF-16BE", &[0xD8, 0x00]), "ERR2m");
        assert_eq!(trace("UTF-16BE", &[0xDC, 0x00, 0x00, 0x41]), "ERR2m U+0041");
        assert_eq!(trace("UTF-16BE", &[0xFF, 0xFE, 0x00, 0x41]), "U+FFFE U+0041");
        assert_eq!(trace("UTF-16BE", &[0xFE, 0xFF, 0x00, 0x41]), "U+FEFF U+0041");
        assert_eq!(trace("UTF-16BE", &[0x00, 0x41, 0x00]), "U+0041 ERR1m");
        assert_eq!(trace("UTF-16BE", &[0xD8, 0x3D, 0xDE, 0x00]), "U+D83D U+DE00");
        assert_eq!(trace("UTF-16LE", &[0xFF, 0xFE, 0x41, 0x00]), "U+FEFF U+0041");
        assert_eq!(trace("UTF-16LE", &[0xFE, 0xFF, 0x41, 0x00]), "U+FFFE U+0041");
        assert_eq!(trace("UTF-16", &[0xFF, 0xFE, 0x41, 0x00]), "U+0041");
        assert_eq!(trace("UTF-16", &[0x00, 0x41]), "U+0041");
    }

    #[test]
    fn utf32_matches_jdk() {
        assert_eq!(trace("UTF-32LE", &[0xFF, 0xFE, 0, 0, b't', 0, 0, 0]), "U+0074");
        assert_eq!(trace("UTF-32LE", &[b't', 0, 0, 0, 0xFF, 0xFE, 0, 0]), "U+0074 U+FEFF");
        assert_eq!(trace("UTF-32LE", &[0, 0, 0xFE, 0xFF, b't', 0, 0, 0]), "ERR4m U+0074");
        assert_eq!(trace("UTF-32BE", &[0, 0, 0xFE, 0xFF, 0, 0, 0, b't']), "U+0074");
        assert_eq!(trace("UTF-32BE", &[0, 0, 0xD8, 0x00, 0, 0, 0, b't']), "U+D800 U+0074");
        assert_eq!(trace("UTF-32LE", &[0xAA, 0xAA, 0xAA, 0xAA]), "ERR4m");
        assert_eq!(trace("UTF-32LE", &[0x00, 0xF6, 0x01, 0x00, 0x41, 0, 0]), "U+D83D U+DE00 ERR3m");
        assert_eq!(trace("UTF-32LE", &[0xFE, 0xFF, 0, 0, 0x41, 0, 0, 0]), "U+FFFE U+0041");
        assert_eq!(trace("UTF-32", &[0xFF, 0xFE, 0, 0, b't', 0, 0, 0]), "U+0074");
        assert_eq!(trace("UTF-32", &[0, 0, 0, b't']), "U+0074");
    }

    #[test]
    fn single_byte_matches_jdk() {
        assert_eq!(trace("US-ASCII", &[b't', 0x80, b's']), "U+0074 ERR1m U+0073");
        assert_eq!(trace("windows-1252", &[b't', 0x81, b's', 0x80]), "U+0074 ERR1u U+0073 U+20AC");
        assert_eq!(trace("IBM-Thai", &[66, 73]), "U+0E01 U+005B");
    }

    /// `new String(bytes, cs)`, as printed by the JDK.
    #[test]
    fn lossy_decode_matches_jdk_string_constructor() {
        let units = |name: &str, b: &[u8]| JavaCharset::for_name(name).unwrap().decode_to_units(b);
        assert_eq!(units("UTF-8", &[b't', 0xE1, 0x84]), vec![0x74, 0xFFFD]);
        assert_eq!(units("UTF-8", &[0xED, 0xA0, 0x80, 0x41]), vec![0xFFFD, 0x41]);
        assert_eq!(units("UTF-8", &[0xF4, 0x90, 0x80, 0x80, 0x41]), vec![0xFFFD, 0xFFFD, 0xFFFD, 0xFFFD, 0x41]);
        assert_eq!(units("UTF-8", &[0xF0, 0x9F, 0x98]), vec![0xFFFD]);
        assert_eq!(units("UTF-8", &[0xE0, 0x80]), vec![0xFFFD, 0xFFFD]);
        assert_eq!(units("UTF-16LE", &[0x00, 0xD8, 0x41, 0x00, 0x42, 0x00]), vec![0xFFFD, 0x42]);
        assert_eq!(units("UTF-32LE", &[0xAA, 0xAA, 0xAA, 0xAA, 0x41, 0, 0, 0]), vec![0xFFFD, 0x41]);
        assert_eq!(units("UTF-32LE", &[0x41, 0, 0, 0, 0x42]), vec![0x41, 0xFFFD]);
        assert_eq!(units("UTF-32BE", &[0, 0, 0xD8, 0x00]), vec![0xD800]);
        assert_eq!(units("windows-1252", &[b't', 0x81, b's']), vec![0x74, 0xFFFD, 0x73]);
        assert_eq!(JavaCharset::UTF_32BE.decode_to_string(&[0, 0, 0xD8, 0x00]), "\u{FFFD}");
    }

    /// `cs.encode(...)` / `cs.newEncoder().encode(...)`, as printed by the JDK.
    #[test]
    fn encoders_match_jdk() {
        let u = |s: &str| s.encode_utf16().collect::<Vec<u16>>();
        assert_eq!(JavaCharset::UTF_16.encode_units(&u("A")).unwrap(), vec![0xFE, 0xFF, 0x00, 0x41]);
        assert_eq!(JavaCharset::UTF_16.encode_units(&[]).unwrap(), Vec::<u8>::new());
        assert_eq!(JavaCharset::UTF_32.encode_units(&u("A")).unwrap(), vec![0, 0, 0, 0x41]);
        assert_eq!(JavaCharset::UTF_16LE.encode_units(&u("A\u{FEFF}")).unwrap(), vec![0x41, 0, 0xFF, 0xFE]);
        assert_eq!(JavaCharset::UTF_32LE.encode_units(&u("A")).unwrap(), vec![0x41, 0, 0, 0]);
        assert_eq!(JavaCharset::UTF_8.encode_units_replacing(&[0x41, 0xD800, 0x42]), vec![0x41, 0x3F, 0x42]);
        assert_eq!(JavaCharset::UTF_8.encode_units(&[0x41, 0xD800, 0x42]), Err(CharacterCodingException::Malformed(1)));
        assert_eq!(JavaCharset::UTF_16BE.encode_units_replacing(&[0xD800]), vec![0xFF, 0xFD]);
        assert_eq!(JavaCharset::UTF_32BE.encode_units_replacing(&[0xD800]), vec![0, 0, 0xFF, 0xFD]);
        let ascii = JavaCharset::us_ascii();
        assert_eq!(ascii.encode_units_replacing(&u("A\u{e9}")), vec![0x41, 0x3F]);
        assert_eq!(ascii.encode_units(&u("A\u{e9}")), Err(CharacterCodingException::Unmappable(1)));
        assert_eq!(JavaCharset::iso_8859_1().encode_units_replacing(&u("\u{20ac}")), vec![0x3F]);
        assert_eq!(JavaCharset::for_name("windows-1252").unwrap().encode_str("\u{20ac}").unwrap(), vec![0x80]);
        assert_eq!(JavaCharset::UTF_8.encode_str("\u{1F600}").unwrap(), vec![0xF0, 0x9F, 0x98, 0x80]);
        // IBM-Thai: U+0E48 decodes from both 0x51 and 0xED; the JDK encoder picks 0xED.
        let thai = JavaCharset::for_name("IBM-Thai").unwrap();
        assert_eq!(thai.encode_str("\u{0E48}[").unwrap(), vec![0xED, 73]);
        assert!(thai.can_encode('['));
        assert!(!thai.can_encode('\u{20ac}'));
    }

    #[test]
    fn names_and_aliases_are_case_insensitive() {
        assert_eq!(JavaCharset::for_name("utf8"), Some(JavaCharset::UTF_8));
        assert_eq!(JavaCharset::for_name("x-utf-16le"), Some(JavaCharset::UTF_16LE));
        assert_eq!(JavaCharset::for_name("cp838").unwrap().name(), "IBM-Thai");
        assert_eq!(JavaCharset::for_name("latin1").unwrap().name(), "ISO-8859-1");
        assert_eq!(JavaCharset::for_name("ASCII").unwrap(), JavaCharset::us_ascii());
        assert!(JavaCharset::for_name("Shift_JIS").is_none());
        assert!(!JavaCharset::is_supported("no-such-charset"));
        assert_eq!(JavaCharset::UTF_16BE.to_string(), "UTF-16BE");
    }

    #[test]
    fn available_charsets_are_sorted_case_insensitively() {
        let all = JavaCharset::available_charsets();
        assert_eq!(all.len(), 111);
        assert_eq!(all[0].name(), "IBM-Thai");
        let names: Vec<String> = all.iter().map(|c| c.name().to_ascii_lowercase()).collect();
        let mut sorted = names.clone();
        sorted.sort();
        assert_eq!(names, sorted);
        assert!(all.contains(&JavaCharset::UTF_32LE));
    }
}
