//! The `java.lang.Character` Unicode-database queries Ghidra's string rendering and labelling
//! need: `Character.isDefined(int)`, `Character.UnicodeScript.of(int)` and
//! `Character.isISOControl(int)`.
//!
//! The Rust standard library has no "is this code point assigned" or script query, so the two
//! tables in [`unicode_data_tables`](super::unicode_data_tables) were generated by probing a
//! JDK 21 runtime over every code point (Unicode 15.0, the version Ghidra runs with).

use super::charset_info::UnicodeScript;
use super::unicode_data_tables::{DEFINED_RANGES, SCRIPT_RANGES};

/// `Character.isDefined(int)`: whether `code_point` is assigned a meaning in Unicode (general
/// category other than `Cn`). Surrogates and private-use code points are defined.
pub fn is_defined(code_point: u32) -> bool {
    DEFINED_RANGES
        .binary_search_by(|&(start, end)| {
            if end < code_point {
                std::cmp::Ordering::Less
            } else if start > code_point {
                std::cmp::Ordering::Greater
            } else {
                std::cmp::Ordering::Equal
            }
        })
        .is_ok()
}

/// `Character.isISOControl(int)`: `U+0000..U+001F` and `U+007F..U+009F`.
pub fn is_iso_control(code_point: u32) -> bool {
    code_point <= 0x1F || (0x7F..=0x9F).contains(&code_point)
}

impl UnicodeScript {
    /// `Character.UnicodeScript.of(int)`: the script `code_point` belongs to.
    ///
    /// Java throws `IllegalArgumentException` for a value above `U+10FFFF`; this returns
    /// [`UnicodeScript::Unknown`] for it, the value Java gives unassigned code points.
    pub fn of(code_point: u32) -> UnicodeScript {
        match SCRIPT_RANGES.binary_search_by(|&(start, end, _)| {
            if end < code_point {
                std::cmp::Ordering::Less
            } else if start > code_point {
                std::cmp::Ordering::Greater
            } else {
                std::cmp::Ordering::Equal
            }
        }) {
            Ok(i) => SCRIPT_RANGES[i].2,
            Err(_) => UnicodeScript::Unknown,
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    // Expected values are what JDK 21 returns.

    #[test]
    fn is_defined_matches_jdk() {
        assert!(is_defined(0));
        assert!(is_defined('a' as u32));
        assert!(is_defined(0x0E01));
        assert!(is_defined(0xD800));
        assert!(is_defined(0xE000));
        assert!(is_defined(0xFFFD));
        assert!(!is_defined(0x0378));
        assert!(!is_defined(0xFFFF));
        assert!(!is_defined(0x10FFFF));
        assert!(!is_defined(0x110000));
        assert!(is_defined(0x1F600));
    }

    #[test]
    fn script_of_matches_jdk() {
        assert_eq!(UnicodeScript::of('a' as u32), UnicodeScript::Latin);
        assert_eq!(UnicodeScript::of(' ' as u32), UnicodeScript::Common);
        assert_eq!(UnicodeScript::of(0x0E01), UnicodeScript::Thai);
        assert_eq!(UnicodeScript::of(0x4E00), UnicodeScript::Han);
        assert_eq!(UnicodeScript::of(0x0301), UnicodeScript::Inherited);
        assert_eq!(UnicodeScript::of(0x0378), UnicodeScript::Unknown);
        assert_eq!(UnicodeScript::of(0x1F600), UnicodeScript::Common);
        assert_eq!(UnicodeScript::of(0x110000), UnicodeScript::Unknown);
    }

    #[test]
    fn iso_control() {
        assert!(is_iso_control(0));
        assert!(is_iso_control(0x9F));
        assert!(!is_iso_control(0xA0));
        assert!(!is_iso_control(' ' as u32));
    }
}
