use crate::program::model::address::{
    Address, AddressSetView, AddressSpace, AddressSpaceType, KeyRange,
};
use std::collections::HashMap;
use std::sync::Arc;

const ADDR_OFFSET_SIZE: u32 = 32;
const MAP_ID_SIZE: u32 = 8;
const MAX_OFFSET: u64 = (1u64 << ADDR_OFFSET_SIZE) - 1;
const ADDR_OFFSET_MASK: u64 = MAX_OFFSET;
const MAP_ID_MASK: u64 = u64::MAX << (64 - MAP_ID_SIZE);
const BASE_MASK: u64 = !ADDR_OFFSET_MASK;
const BASE_ID_SIZE: u32 = 64 - MAP_ID_SIZE - ADDR_OFFSET_SIZE;
const BASE_ID_MASK: u64 = (1u64 << BASE_ID_SIZE) - 1;
const STACK_SPACE_ID: usize = BASE_ID_MASK as usize;

/// Standalone map between addresses and compact database keys.
///
/// This mirrors the non-overlay behavior of Ghidra's `AddressMapImpl`.
#[derive(Debug, Clone)]
pub struct AddressMapImpl {
    space_map: HashMap<String, Arc<AddressSpace>>,
    stack_space: Option<Arc<AddressSpace>>,
    base_addresses: Vec<Address>,
    last_base_index: Option<usize>,
    map_id_bits: u64,
}

impl Default for AddressMapImpl {
    fn default() -> Self {
        Self::new()
    }
}

impl AddressMapImpl {
    /// Creates a new address map with map ID 0.
    pub fn new() -> Self {
        Self::with_map_id(0)
    }

    /// Creates a new address map with the specified 8-bit map ID.
    pub fn with_map_id(map_id: u8) -> Self {
        Self {
            space_map: HashMap::new(),
            stack_space: None,
            base_addresses: Vec::new(),
            last_base_index: None,
            map_id_bits: (map_id as u64) << (64 - MAP_ID_SIZE),
        }
    }

    /// Decodes a key generated by this map.
    pub fn decode_address(&self, value: i64) -> Option<Address> {
        let value = value as u64;
        if (value & MAP_ID_MASK) != self.map_id_bits {
            return None;
        }

        let base_index = ((value >> ADDR_OFFSET_SIZE) & BASE_ID_MASK) as usize;
        let offset = (value & ADDR_OFFSET_MASK) as i64;
        if base_index == STACK_SPACE_ID {
            return self
                .stack_space
                .as_ref()
                .map(|space| Address::new(space.clone(), (offset as u32 as i32) as i64));
        }
        self.base_addresses
            .get(base_index)
            .map(|base| Address::new(base.space().clone(), base.offset().wrapping_add(offset)))
    }

    /// Generates a unique key for the supplied address.
    pub fn key(&mut self, address: &Address) -> i64 {
        let base_index = self.base_address_index(address);
        (self.map_id_bits
            | ((base_index as u64) << ADDR_OFFSET_SIZE)
            | ((address.offset() as u64) & ADDR_OFFSET_MASK)) as i64
    }

    /// Finds the key range containing the supplied address using Java's
    /// `Collections.binarySearch` return convention.
    pub fn find_key_range(&self, key_ranges: &[KeyRange], address: &Address) -> isize {
        let mut low: isize = 0;
        let mut high: isize = key_ranges.len() as isize - 1;
        while low <= high {
            let mid = (low + high) >> 1;
            match self.compare_key_range_to_address(key_ranges[mid as usize], address) {
                value if value < 0 => low = mid + 1,
                value if value > 0 => high = mid - 1,
                _ => return mid,
            }
        }
        -(low + 1)
    }

    /// Gets key ranges for an address range.
    pub fn key_ranges(&mut self, start: &Address, end: &Address) -> Vec<KeyRange> {
        if start.space() != end.space() || start.offset() > end.offset() {
            panic!("invalid address range");
        }
        let mut key_ranges = Vec::new();
        self.add_key_ranges(&mut key_ranges, start, end);
        key_ranges
    }

    /// Gets key ranges for each range in an address set.
    pub fn key_ranges_for_set(&mut self, set: &dyn AddressSetView) -> Vec<KeyRange> {
        let mut key_ranges = Vec::new();
        let mut iterator = set.address_ranges();
        while let Some(range) = iterator.next_range() {
            self.add_key_ranges(&mut key_ranges, range.min_address(), range.max_address());
        }
        key_ranges
    }

    /// Reconciles address-space changes. Overlay address spaces are not yet
    /// modeled in this crate, so this is a no-op for the current address model.
    pub fn reconcile(&mut self) {}

    fn add_key_ranges(&mut self, key_ranges: &mut Vec<KeyRange>, start: &Address, end: &Address) {
        let mut current = start.clone();
        while current <= *end {
            let base_offset = base_offset(current.offset());
            let base_end_offset = (base_offset as u64 | MAX_OFFSET) as i64;
            let range_end = Address::new(
                current.space().clone(),
                if end.offset() < base_end_offset {
                    end.offset()
                } else {
                    base_end_offset
                },
            );
            let min_key = self.key(&current);
            let max_key = self.key(&range_end);
            key_ranges.push(KeyRange::new(min_key, max_key));
            if range_end == *end {
                break;
            }
            current = range_end.next().unwrap();
        }
    }

    fn compare_key_range_to_address(&self, range: KeyRange, address: &Address) -> i32 {
        let min = self.decode_address(range.min_key);
        if min.as_ref().is_some_and(|min| min > address) {
            return 1;
        }
        let max = self.decode_address(range.max_key);
        if max.as_ref().is_some_and(|max| max < address) {
            return -1;
        }
        0
    }

    fn base_address_index(&mut self, address: &Address) -> usize {
        if address.space().space_type() == AddressSpaceType::Stack {
            if let Some(stack_space) = &self.stack_space {
                if stack_space != address.space() {
                    panic!("Only one stack space allowed");
                }
            }
            self.stack_space = Some(address.space().clone());
            return STACK_SPACE_ID;
        }

        let base_offset = base_offset(address.offset());
        if let Some(index) = self.last_base_index {
            let base = &self.base_addresses[index];
            if base.space() == address.space() && base.offset() == base_offset {
                return index;
            }
        }

        if let Some(index) = self
            .base_addresses
            .iter()
            .position(|base| base.space() == address.space() && base.offset() == base_offset)
        {
            self.last_base_index = Some(index);
            return index;
        }

        self.check_address_space(address.space());
        let index = self.base_addresses.len();
        self.base_addresses
            .push(Address::new(address.space().clone(), base_offset));
        self.last_base_index = Some(index);
        index
    }

    fn check_address_space(&mut self, address_space: &Arc<AddressSpace>) {
        match self.space_map.get(address_space.name()) {
            Some(existing) if existing != address_space => {
                panic!("Address space conflicts with another space in map")
            }
            Some(_) => {}
            None => {
                self.space_map
                    .insert(address_space.name().to_string(), address_space.clone());
            }
        }
    }
}

fn base_offset(offset: i64) -> i64 {
    ((offset as u64) & BASE_MASK) as i64
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::program::model::address::{AddressSet, AddressSpaceType};

    #[test]
    fn key_round_trips_addresses() {
        let mut map = AddressMapImpl::new();
        let first = addr("ram", 1, AddressSpaceType::Ram, 0x1234);
        let second = addr("ram", 1, AddressSpaceType::Ram, 0x1_0000_0042);

        let first_key = map.key(&first);
        let second_key = map.key(&second);

        assert_eq!(map.decode_address(first_key), Some(first));
        assert_eq!(map.decode_address(second_key), Some(second));
        assert_ne!(first_key, second_key);
    }

    #[test]
    fn map_id_mismatch_does_not_decode() {
        let mut first_map = AddressMapImpl::with_map_id(1);
        let second_map = AddressMapImpl::with_map_id(2);
        let key = first_map.key(&addr("ram", 1, AddressSpaceType::Ram, 0x1000));

        assert_eq!(second_map.decode_address(key), None);
    }

    #[test]
    fn key_ranges_split_at_base_boundaries() {
        let mut map = AddressMapImpl::new();
        let start = addr("ram", 1, AddressSpaceType::Ram, 0xffff_fffe);
        let end = addr("ram", 1, AddressSpaceType::Ram, 0x1_0000_0001);

        let ranges = map.key_ranges(&start, &end);

        assert_eq!(ranges.len(), 2);
        assert_eq!(map.decode_address(ranges[0].min_key), Some(start));
        assert_eq!(
            map.decode_address(ranges[0].max_key),
            Some(addr("ram", 1, AddressSpaceType::Ram, 0xffff_ffff))
        );
        assert_eq!(
            map.decode_address(ranges[1].min_key),
            Some(addr("ram", 1, AddressSpaceType::Ram, 0x1_0000_0000))
        );
        assert_eq!(map.decode_address(ranges[1].max_key), Some(end));
    }

    #[test]
    fn key_ranges_for_set_and_find_key_range() {
        let mut map = AddressMapImpl::new();
        let mut set = AddressSet::new();
        set.add_range(
            &addr("ram", 1, AddressSpaceType::Ram, 0x1000),
            &addr("ram", 1, AddressSpaceType::Ram, 0x1002),
        );
        set.add_range(
            &addr("ram", 1, AddressSpaceType::Ram, 0x2000),
            &addr("ram", 1, AddressSpaceType::Ram, 0x2002),
        );

        let ranges = map.key_ranges_for_set(&set);

        assert_eq!(ranges.len(), 2);
        assert_eq!(
            map.find_key_range(&ranges, &addr("ram", 1, AddressSpaceType::Ram, 0x1001)),
            0
        );
        assert_eq!(
            map.find_key_range(&ranges, &addr("ram", 1, AddressSpaceType::Ram, 0x2001)),
            1
        );
        assert!(map.find_key_range(&ranges, &addr("ram", 1, AddressSpaceType::Ram, 0x3000)) < 0);
    }

    #[test]
    fn stack_address_uses_special_base_index() {
        let mut map = AddressMapImpl::new();
        let stack = addr("stack", 2, AddressSpaceType::Stack, -0x20);

        let key = map.key(&stack);

        assert_eq!(map.decode_address(key), Some(stack));
    }

    fn addr(name: &str, unique: i32, space_type: AddressSpaceType, offset: i64) -> Address {
        let space = AddressSpace::new(name, 64, 1, space_type, unique);
        Address::new(space, offset)
    }
}
