pub mod dt_constants;
pub mod fdt_constants;

pub use dt_constants::{
    DT_TABLE_DEFAULT_PAGE_SIZE, DT_TABLE_DEFAULT_VERSION, DT_TABLE_MAGIC,
    DT_TABLE_MAGIC_BYTES, DT_TABLE_MAGIC_SIZE,
};

pub use fdt_constants::{
    FDT_BEGIN_NODE, FDT_END, FDT_END_NODE, FDT_MAGIC, FDT_MAGIC_BYTES, FDT_MAGIC_SIZE,
    FDT_NOP, FDT_PROP, FDT_TAGSIZE, FDT_V1_SIZE, FDT_V16_SIZE, FDT_V17_SIZE, FDT_V2_SIZE,
    FDT_V3_SIZE, FDT_VERSION_1, FDT_VERSION_16, FDT_VERSION_17, FDT_VERSION_2, FDT_VERSION_3,
};
