//! A handler that knows how to load and store variables' values from local storage.
//!
//! Port of `ghidra.pcode.emu.jit.alloc.VarHandler`.
//!
//! Some variables are hosted in a single JVM local of compatible type. Others, notably
//! multi-precision integers, are allocated among two or more JVM local integers. Each such
//! integer is called a "leg" of the multi-precision integer. Other literature may call these
//! "digits" (whose value is in `[0, 0xffffffff]`). Depending on the operator implementation, a
//! value may need to be loaded with alternative types or in different forms -- e.g., any float
//! operator will need to convert its inputs into the appropriate float type, even if the operands
//! were allocated as an int type. Similarly, some operators implement their multi-precision
//! computations by invoking static methods whose parameters are `int[]`, and so they will load
//! and store the array forms instead of accessing the legs' locals. This trait provides
//! generators for the various circumstances; each implementor provides the generation logic for a
//! particular allocation strategy.
//!
//! # Differences from Java
//!
//! - Java's `JitCodeGenerator<?>` wildcard parameter becomes `&dyn JitCodeGenerator`, matching the
//!   convention set by
//!   [`SimpleAccessGen`](crate::pcode::emu::jit::gen::access::simple_access_gen::SimpleAccessGen).
//! - `JitType type()` returns Java's raw (existential) `JitType`. Per the module docs of
//!   [`jit_type`](crate::pcode::emu::jit::analysis::jit_type), that existential is modeled by the
//!   closed enum [`AnyJitType`] rather than `dyn JitType`, since the set of p-code types is fixed
//!   by that module.
//! - `genStoreFromStack`'s Java bound `N0 extends Ent<N1, FT>` and `genStoreFromArray`'s
//!   `N0 extends Ent<N1, TRef<int[]>>` become the direct parameter types `Emitter<Ent<N1, FT>>`
//!   and `Emitter<Ent<N1, TRef>>`, per the [`Emitter`](crate::pcode::emu::jit::gen::util::emitter)
//!   module docs on replacing such bounds; `int[]` itself collapses to the non-generic [`TRef`],
//!   as [`Types`](crate::pcode::emu::jit::gen::util::types) already does for every reference type
//!   in this port.
//! - `subpiece` returns a *different* concrete handler depending on the implementor and even the
//!   arguments (e.g., `NoHandler` returns itself, others construct a differently-shaped handler),
//!   so it returns `Box<dyn VarHandler>` -- the one place this trait is genuinely used
//!   polymorphically over an unknown implementor. That forces every other method with its own
//!   type parameters (`genLoadToStack`, `genLoadToOpnd`, `genLoadLegToStack`, `genLoadToArray`,
//!   `genLoadToBool`, `genStoreFromStack`, `genStoreFromOpnd`, `genStoreFromArray`) to carry a
//!   `where Self: Sized` bound, so they drop out of the vtable instead of making the trait as a
//!   whole object-unsafe -- the same technique used by
//!   [`JitOpVisitor`](crate::pcode::emu::jit::analysis::jit_op_visitor::JitOpVisitor). Those
//!   methods remain callable on any statically-known `T: VarHandler`, just not through `&dyn
//!   VarHandler`.
//! - `SubPieceOpGen` and `PcodeOp`, referenced only in doc comments in the Java source (never in a
//!   signature), are neither imported nor stubbed here.

use crate::pcode::emu::jit::analysis::jit_type::{AnyJitType, MpIntJitType, SimpleJitType};
use crate::pcode::emu::jit::gen::util::emitter::{Emitter, Ent, Next};
use crate::pcode::emu::jit::gen::util::types::{BPrim, TInt, TRef};
use crate::pcode::seam_stubs::{Ext, JitCodeGenerator, Opnd, OpndEm, Scope};
use crate::program::model::lang::endian::Endian;
use crate::program::model::pcode::Varnode;

/// Generate a name for the variable representing the given varnode.
///
/// These are for debugging purposes: when dumping generated bytecode, the declared local
/// variables and their scopes are often also dumped. This provides a human with the local
/// variable index for various varnodes.
///
/// Port of the static `VarHandler.nameVn(Varnode)`.
pub fn name_vn(vn: &Varnode) -> String {
    format!(
        "var_{}_{:x}_{}",
        vn.get_address().space().name(),
        vn.get_offset() as u64,
        vn.get_size()
    )
}

/// A handler that knows how to load and store variables' values from local storage.
///
/// Port of `ghidra.pcode.emu.jit.alloc.VarHandler`. See the [module docs](self).
pub trait VarHandler: Send + Sync {
    /// Get the complete varnode accessible to this handler.
    ///
    /// Port of `VarHandler.vn()`.
    fn vn(&self) -> Varnode;

    /// Get the name for this handler's local variable, named after the varnode it represents.
    ///
    /// Port of `VarHandler.name()`.
    fn name(&self) -> String {
        name_vn(&self.vn())
    }

    /// Get the p-code type of the local variable this handler uses.
    ///
    /// Port of `VarHandler.type()`.
    fn type_(&self) -> AnyJitType;

    /// Emit bytecode to load the varnode's value onto the JVM stack.
    ///
    /// Port of `VarHandler.genLoadToStack`.
    ///
    /// - `em`: the emitter typed with the incoming stack.
    /// - `gen`: the code generator.
    /// - `type_`: the p-code type of the value expected on the JVM stack by the proceeding
    ///   bytecode.
    /// - `ext`: the kind of extension to apply when adjusting from JVM size to varnode size.
    ///
    /// Returns the emitter typed with the resulting stack.
    fn gen_load_to_stack<TT, TJT, N>(
        &self,
        em: Emitter<N>,
        gen: &dyn JitCodeGenerator,
        type_: TJT,
        ext: Ext,
    ) -> Emitter<Ent<N, TT>>
    where
        TT: BPrim,
        TJT: SimpleJitType<B = TT>,
        N: Next,
        Self: Sized;

    /// Emit bytecode to load the varnode's value into several locals.
    ///
    /// Port of `VarHandler.genLoadToOpnd`.
    ///
    /// - `scope`: a scope for generating temporary local storage.
    ///
    /// Returns the operand containing the locals, and the emitter typed with the incoming stack.
    fn gen_load_to_opnd<N: Next>(
        &self,
        em: Emitter<N>,
        gen: &dyn JitCodeGenerator,
        type_: MpIntJitType,
        ext: Ext,
        scope: &dyn Scope,
    ) -> OpndEm<MpIntJitType, N>
    where
        Self: Sized;

    /// Emit bytecode to load one leg of a multi-precision value from the varnode onto the JVM
    /// stack.
    ///
    /// Port of `VarHandler.genLoadLegToStack`.
    ///
    /// - `type_`: the p-code type of the complete multi-precision value.
    /// - `leg`: the index of the leg to load, 0 being least significant.
    ///
    /// Returns the emitter typed with the resulting stack, i.e., having the int leg pushed onto
    /// it.
    fn gen_load_leg_to_stack<N: Next>(
        &self,
        em: Emitter<N>,
        gen: &dyn JitCodeGenerator,
        type_: MpIntJitType,
        leg: i32,
        ext: Ext,
    ) -> Emitter<Ent<N, TInt>>
    where
        Self: Sized;

    /// Emit bytecode to load the varnode's value into an integer array in little-endian order,
    /// pushing its ref onto the JVM stack.
    ///
    /// Port of `VarHandler.genLoadToArray`.
    ///
    /// - `slack`: the number of additional, more significant, elements to allocate in the array.
    ///
    /// Returns the emitter typed with the resulting stack, i.e., having the ref pushed onto it.
    #[allow(clippy::too_many_arguments)]
    fn gen_load_to_array<N: Next>(
        &self,
        em: Emitter<N>,
        gen: &dyn JitCodeGenerator,
        type_: MpIntJitType,
        ext: Ext,
        scope: &dyn Scope,
        slack: i32,
    ) -> Emitter<Ent<N, TRef>>
    where
        Self: Sized;

    /// Emit bytecode to load the varnode's value, interpreted as a boolean, as an integer onto
    /// the JVM stack.
    ///
    /// Port of `VarHandler.genLoadToBool`.
    fn gen_load_to_bool<N: Next>(
        &self,
        em: Emitter<N>,
        gen: &dyn JitCodeGenerator,
    ) -> Emitter<Ent<N, TInt>>
    where
        Self: Sized;

    /// Emit bytecode to store a value into a variable from the JVM stack.
    ///
    /// Port of `VarHandler.genStoreFromStack`.
    ///
    /// - `type_`: the p-code type of the value on the stack.
    /// - `scope`: a scope for generating temporary local storage.
    ///
    /// Returns the emitter typed with the resulting stack, i.e., having popped the value.
    fn gen_store_from_stack<FT, FJT, N1>(
        &self,
        em: Emitter<Ent<N1, FT>>,
        gen: &dyn JitCodeGenerator,
        type_: FJT,
        ext: Ext,
        scope: &dyn Scope,
    ) -> Emitter<N1>
    where
        FT: BPrim,
        FJT: SimpleJitType<B = FT>,
        N1: Next,
        Self: Sized;

    /// Emit bytecode to store a varnode's value from several locals.
    ///
    /// Port of `VarHandler.genStoreFromOpnd`.
    ///
    /// - `opnd`: the operand whose locals contain the value to be stored.
    /// - `scope`: a scope for generating temporary local storage.
    fn gen_store_from_opnd<N: Next>(
        &self,
        em: Emitter<N>,
        gen: &dyn JitCodeGenerator,
        opnd: &dyn Opnd<MpIntJitType>,
        ext: Ext,
        scope: &dyn Scope,
    ) -> Emitter<N>
    where
        Self: Sized;

    /// Emit bytecode to store a varnode's value from an array of integer legs, in little-endian
    /// order.
    ///
    /// Port of `VarHandler.genStoreFromArray`.
    ///
    /// - `type_`: the p-code type of the value on the stack.
    /// - `scope`: a scope for generating temporary local storage.
    ///
    /// Returns the emitter typed with the resulting stack, i.e., having popped the array.
    fn gen_store_from_array<N1: Next>(
        &self,
        em: Emitter<Ent<N1, TRef>>,
        gen: &dyn JitCodeGenerator,
        type_: MpIntJitType,
        ext: Ext,
        scope: &dyn Scope,
    ) -> Emitter<N1>
    where
        Self: Sized;

    /// Create a handler for a `SUBPIECE` of a value.
    ///
    /// Port of `VarHandler.subpiece`.
    ///
    /// To implement a subpiece operator, we could load the entire varnode and then extract the
    /// designated portion. Or, we could load only the designated portion, averting any code and
    /// execution cost of loading the un-designated portions. We accomplish this by re-writing the
    /// subpiece op and a load of the sub-varnode.
    ///
    /// - `endian`: the endianness of the emulation target.
    /// - `byte_offset`: the number of least-significant bytes to remove.
    /// - `max_byte_size`: the maximum size of the resulting variable. In general, a subpiece
    ///   should never exceed the size of the parent varnode, but if it does, this will truncate
    ///   that excess.
    ///
    /// Returns the resulting subpiece handler.
    fn subpiece(
        &self,
        endian: Endian,
        byte_offset: i32,
        max_byte_size: i32,
    ) -> Box<dyn VarHandler>;
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::pcode::emu::jit::analysis::jit_type::IntJitType;
    use crate::pcode::emu::jit::gen::util::emitter::Bot;
    use crate::pcode::emu::jit::gen::util::types::T_INT;
    use crate::pcode::seam_stubs::MethodVisitor;
    use crate::program::model::address::{Address, AddressSpace, AddressSpaceType};

    fn make_varnode(offset: i64, size: i32) -> Varnode {
        let space = AddressSpace::new("ram", 64, 1, AddressSpaceType::Ram, 0);
        let addr = Address::new(space, offset);
        Varnode::new(addr, size)
    }

    struct MockCodeGenerator;
    impl JitCodeGenerator for MockCodeGenerator {}

    struct MockScope;
    impl Scope for MockScope {}

    /// A minimal implementor covering every trait method, mirroring the "singleton dummy handler"
    /// shape of Java's `NoHandler`, but returning real (rather than throwing) values so the
    /// type-level plumbing can be exercised.
    struct TestVarHandler {
        vn: Varnode,
    }

    impl VarHandler for TestVarHandler {
        fn vn(&self) -> Varnode {
            self.vn.clone()
        }

        fn type_(&self) -> AnyJitType {
            AnyJitType::Int(IntJitType::I4)
        }

        fn gen_load_to_stack<TT, TJT, N>(
            &self,
            em: Emitter<N>,
            _gen: &dyn JitCodeGenerator,
            _type_: TJT,
            _ext: Ext,
        ) -> Emitter<Ent<N, TT>>
        where
            TT: BPrim,
            TJT: SimpleJitType<B = TT>,
            N: Next,
        {
            em.recast()
        }

        fn gen_load_to_opnd<N: Next>(
            &self,
            em: Emitter<N>,
            _gen: &dyn JitCodeGenerator,
            _type_: MpIntJitType,
            _ext: Ext,
            _scope: &dyn Scope,
        ) -> OpndEm<MpIntJitType, N> {
            struct MockOpnd;
            impl Opnd<MpIntJitType> for MockOpnd {}
            OpndEm::new(Box::new(MockOpnd), em)
        }

        fn gen_load_leg_to_stack<N: Next>(
            &self,
            em: Emitter<N>,
            _gen: &dyn JitCodeGenerator,
            _type_: MpIntJitType,
            _leg: i32,
            _ext: Ext,
        ) -> Emitter<Ent<N, TInt>> {
            em.recast()
        }

        fn gen_load_to_array<N: Next>(
            &self,
            em: Emitter<N>,
            _gen: &dyn JitCodeGenerator,
            _type_: MpIntJitType,
            _ext: Ext,
            _scope: &dyn Scope,
            _slack: i32,
        ) -> Emitter<Ent<N, TRef>> {
            em.recast()
        }

        fn gen_load_to_bool<N: Next>(
            &self,
            em: Emitter<N>,
            _gen: &dyn JitCodeGenerator,
        ) -> Emitter<Ent<N, TInt>> {
            em.recast()
        }

        fn gen_store_from_stack<FT, FJT, N1>(
            &self,
            em: Emitter<Ent<N1, FT>>,
            _gen: &dyn JitCodeGenerator,
            _type_: FJT,
            _ext: Ext,
            _scope: &dyn Scope,
        ) -> Emitter<N1>
        where
            FT: BPrim,
            FJT: SimpleJitType<B = FT>,
            N1: Next,
        {
            em.recast()
        }

        fn gen_store_from_opnd<N: Next>(
            &self,
            em: Emitter<N>,
            _gen: &dyn JitCodeGenerator,
            _opnd: &dyn Opnd<MpIntJitType>,
            _ext: Ext,
            _scope: &dyn Scope,
        ) -> Emitter<N> {
            em
        }

        fn gen_store_from_array<N1: Next>(
            &self,
            em: Emitter<Ent<N1, TRef>>,
            _gen: &dyn JitCodeGenerator,
            _type_: MpIntJitType,
            _ext: Ext,
            _scope: &dyn Scope,
        ) -> Emitter<N1> {
            em.recast()
        }

        fn subpiece(
            &self,
            _endian: Endian,
            byte_offset: i32,
            max_byte_size: i32,
        ) -> Box<dyn VarHandler> {
            let vn = Varnode::new(
                self.vn.get_address().add(byte_offset as i64).expect("address overflow"),
                (self.vn.get_size() - byte_offset).min(max_byte_size),
            );
            Box::new(TestVarHandler { vn })
        }
    }

    #[test]
    fn name_vn_matches_java_format_string() {
        // Java: "var_%s_%x_%d".formatted(space.getName(), vn.getOffset(), vn.getSize())
        let vn = make_varnode(0x1234, 4);
        assert_eq!(name_vn(&vn), "var_ram_1234_4");
    }

    #[test]
    fn name_vn_formats_offset_as_unsigned_hex() {
        // Java's %x on a long formats the bits as unsigned hex, not signed decimal.
        let space = AddressSpace::new("ram", 64, 1, AddressSpaceType::Ram, 0);
        let vn = Varnode::new(Address::new(space, -1), 1);
        assert_eq!(name_vn(&vn), "var_ram_ffffffffffffffff_1");
    }

    #[test]
    fn default_name_delegates_to_vn() {
        // Java: default String name() { return nameVn(vn()); }
        let handler = TestVarHandler { vn: make_varnode(0x2000, 8) };
        assert_eq!(handler.name(), name_vn(&handler.vn()));
        assert_eq!(handler.name(), "var_ram_2000_8");
    }

    #[test]
    fn subpiece_narrows_the_varnode_like_a_real_handler_would() {
        let handler = TestVarHandler { vn: make_varnode(0x3000, 8) };
        let sub = handler.subpiece(Endian::Little, 2, 4);
        assert_eq!(sub.vn().get_offset(), 0x3002);
        assert_eq!(sub.vn().get_size(), 4);
    }

    #[test]
    fn dyn_var_handler_dispatches_object_safe_methods() {
        // The presence of `subpiece` -> `Box<dyn VarHandler>` requires the trait to be
        // object-safe; this exercises it through a genuine `&dyn VarHandler`.
        let handler: Box<dyn VarHandler> = Box::new(TestVarHandler { vn: make_varnode(0x4000, 4) });
        assert_eq!(handler.type_(), AnyJitType::Int(IntJitType::I4));
        let sub = handler.subpiece(Endian::Big, 0, 4);
        assert_eq!(sub.name(), "var_ram_4000_4");
    }

    #[test]
    fn gen_load_to_stack_recasts_the_stack_shape() {
        let handler = TestVarHandler { vn: make_varnode(0x5000, 4) };
        let gen = MockCodeGenerator;
        let em: Emitter<Bot> = Emitter::new(MethodVisitor::new());

        // Java: genLoadToStack returns Emitter<Ent<N, TT>>, i.e., the resulting stack has the
        // loaded value on top of the incoming stack N.
        let result: Emitter<Ent<Bot, TInt>> =
            handler.gen_load_to_stack(em, &gen, IntJitType::I4, Ext::Zero);
        let _ = result.local_variables();
        let _ = T_INT;
    }
}
