use crate::app::seam_stubs::MessageLog;
use crate::framework::model::DomainObject;
use crate::program::model::listing::program::Program;
use crate::util::classfinder::extension_point::ExtensionPoint;
use crate::util::task::TaskMonitor;

/// A command that can be applied to a binary analysis program.
///
/// NOTE: All implementations of `BinaryAnalysisCommand` must end with "BinaryAnalysisCommand" in
/// their type name. The class searcher will not find implementations that do not follow this naming
/// convention.
///
/// This trait represents a single analysis operation that can be applied to a `Program`. The
/// command encapsulates analysis logic and provides information about whether it can be applied
/// to a given program and the status of the analysis after application.
pub trait BinaryAnalysisCommand: ExtensionPoint + Send + Sync {
    /// Determines if this command can be applied to the given program.
    ///
    /// # Arguments
    ///
    /// * `program` - The program to inspect.
    ///
    /// # Returns
    ///
    /// `true` if this command can be applied to the given program, `false` otherwise.
    fn can_apply(&self, program: &dyn Program) -> bool;

    /// Applies this command to the given program.
    ///
    /// # Arguments
    ///
    /// * `program` - The program to apply this command to.
    /// * `monitor` - A task monitor for tracking progress and checking for cancellation.
    ///
    /// # Returns
    ///
    /// `true` if the command applied successfully, `false` otherwise.
    ///
    /// # Errors
    ///
    /// May return an error if something goes wrong during execution.
    fn apply_to(
        &self,
        program: &dyn Program,
        monitor: &dyn TaskMonitor,
    ) -> Result<bool, Box<dyn std::error::Error>>;

    /// Gets the messages generated by this command.
    ///
    /// # Returns
    ///
    /// A message log containing any messages generated during command execution. Returns `None`
    /// if no messages were generated.
    fn get_messages(&self) -> Option<Box<dyn MessageLog>>;

    /// Gets the name of this command.
    ///
    /// # Returns
    ///
    /// The display name of this command.
    fn get_name(&self) -> String;
}

#[cfg(test)]
mod tests {
    use super::*;

    struct MockProgram;

    impl DomainObject for MockProgram {
        fn is_changed(&self) -> bool {
            false
        }
    }

    impl Program for MockProgram {
        fn get_name(&self) -> String {
            "mock_program".to_string()
        }

        fn get_language_id(&self) -> String {
            "x86".to_string()
        }

        fn get_language(
            &self,
        ) -> Option<std::sync::Arc<dyn crate::program::model::lang::Language>> {
            None
        }

        fn get_address_factory(
            &self,
        ) -> Option<std::sync::Arc<dyn crate::program::model::address::AddressFactory>> {
            None
        }

        fn get_loaded_and_initialized_address_set(
            &self,
        ) -> Box<dyn crate::program::model::address::AddressSetView> {
            unimplemented!()
        }

        fn get_all_initialized_address_set(
            &self,
        ) -> Box<dyn crate::program::model::address::AddressSetView> {
            unimplemented!()
        }

        fn get_listing(&mut self) -> Option<&mut dyn crate::program::model::listing::Listing> {
            None
        }

        fn get_memory(
            &self,
        ) -> Option<std::sync::Arc<dyn crate::program::model::mem::Memory>> {
            None
        }

        fn get_memory_mut(
            &mut self,
        ) -> Option<&mut dyn crate::program::model::mem::Memory> {
            None
        }

        fn get_global_namespace(
            &self,
        ) -> Option<std::sync::Arc<dyn crate::program::model::symbol::Namespace>> {
            None
        }

        fn get_reference_manager(
            &mut self,
        ) -> Option<&mut dyn crate::program::model::symbol::ReferenceManager> {
            None
        }

        fn get_equate_table(
            &mut self,
        ) -> Option<&mut dyn crate::program::model::symbol::EquateTable> {
            None
        }

        fn get_symbol_table(
            &mut self,
        ) -> Option<&mut dyn crate::program::model::symbol::SymbolTable> {
            None
        }

        fn get_external_manager(
            &mut self,
        ) -> Option<&mut dyn crate::program::model::symbol::ExternalManager> {
            None
        }

        fn get_function_manager(
            &mut self,
        ) -> Option<&mut dyn crate::program::model::listing::FunctionManager> {
            None
        }

        fn get_data_type_manager(
            &self,
        ) -> Option<Box<dyn crate::program::model::data::data_type_manager::DataTypeManager>> {
            None
        }

        fn get_executable_path(&self) -> String {
            "/path/to/binary".to_string()
        }

        fn get_executable_format(&self) -> String {
            "ELF".to_string()
        }

        fn get_compiler(&self) -> String {
            "gcc".to_string()
        }

        fn get_compiler_spec_id(
            &self,
        ) -> Option<crate::program::model::lang::CompilerSpecID> {
            None
        }

        fn get_register(&self, _name: &str) -> Option<crate::program::model::lang::RegisterRef> {
            None
        }

        fn get_register_at(
            &self,
            _address: &crate::program::model::address::Address,
        ) -> Option<crate::program::model::lang::RegisterRef> {
            None
        }

        fn get_compiler_spec(
            &self,
        ) -> Option<Box<dyn crate::program::model::lang::CompilerSpec>> {
            None
        }

        fn get_program_context(
            &mut self,
        ) -> Option<&mut dyn crate::program::model::listing::ProgramContext> {
            None
        }

        fn get_image_base(&self) -> Option<crate::program::model::address::Address> {
            None
        }

        fn get_address_map(
            &self,
        ) -> Option<std::sync::Arc<dyn crate::program::database::map::address_map::AddressMap>> {
            None
        }
    }

    struct MockTaskMonitor;

    impl TaskMonitor for MockTaskMonitor {
        fn is_cancelled(&self) -> bool {
            false
        }

        fn set_show_progress_value(&self, _show: bool) {}

        fn set_message(&self, _message: &str) {}

        fn get_message(&self) -> String {
            String::new()
        }

        fn set_progress(&self, _value: i64) {}

        fn initialize(&self, _max: i64) {}

        fn set_maximum(&self, _max: i64) {}

        fn get_maximum(&self) -> i64 {
            0
        }

        fn set_indeterminate(&self, _indeterminate: bool) {}

        fn is_indeterminate(&self) -> bool {
            false
        }

        fn check_cancelled(&self) -> Result<(), crate::util::exception::CancelledException> {
            Ok(())
        }

        fn increment_progress(&self, _amount: i64) {}

        fn get_progress(&self) -> i64 {
            0
        }

        fn cancel(&self) {}

        fn add_cancelled_listener(&self, _listener: Box<dyn crate::util::task::CancelledListener>) {
        }

        fn remove_cancelled_listener(&self, _listener: &dyn crate::util::task::CancelledListener) {
        }

        fn set_cancel_enabled(&self, _enabled: bool) {}

        fn is_cancel_enabled(&self) -> bool {
            true
        }

        fn clear_cancelled(&self) {}
    }

    struct TestCommand {
        name: String,
        can_apply_result: bool,
        apply_result: bool,
    }

    impl BinaryAnalysisCommand for TestCommand {
        fn can_apply(&self, _program: &dyn Program) -> bool {
            self.can_apply_result
        }

        fn apply_to(
            &self,
            _program: &dyn Program,
            _monitor: &dyn TaskMonitor,
        ) -> Result<bool, Box<dyn std::error::Error>> {
            Ok(self.apply_result)
        }

        fn get_messages(&self) -> Option<Box<dyn MessageLog>> {
            None
        }

        fn get_name(&self) -> String {
            self.name.clone()
        }
    }

    impl ExtensionPoint for TestCommand {}

    #[test]
    fn test_can_apply_true() {
        let cmd = TestCommand {
            name: "test_cmd".to_string(),
            can_apply_result: true,
            apply_result: false,
        };
        let program = MockProgram;
        assert!(cmd.can_apply(&program));
    }

    #[test]
    fn test_can_apply_false() {
        let cmd = TestCommand {
            name: "test_cmd".to_string(),
            can_apply_result: false,
            apply_result: false,
        };
        let program = MockProgram;
        assert!(!cmd.can_apply(&program));
    }

    #[test]
    fn test_apply_to_success() {
        let cmd = TestCommand {
            name: "test_cmd".to_string(),
            can_apply_result: true,
            apply_result: true,
        };
        let program = MockProgram;
        let monitor = MockTaskMonitor;
        let result = cmd.apply_to(&program, &monitor);
        assert!(result.is_ok());
        assert!(result.unwrap());
    }

    #[test]
    fn test_apply_to_failure() {
        let cmd = TestCommand {
            name: "test_cmd".to_string(),
            can_apply_result: true,
            apply_result: false,
        };
        let program = MockProgram;
        let monitor = MockTaskMonitor;
        let result = cmd.apply_to(&program, &monitor);
        assert!(result.is_ok());
        assert!(!result.unwrap());
    }

    #[test]
    fn test_get_name() {
        let cmd = TestCommand {
            name: "my_analysis_command".to_string(),
            can_apply_result: true,
            apply_result: true,
        };
        assert_eq!(cmd.get_name(), "my_analysis_command");
    }

    #[test]
    fn test_get_messages_none() {
        let cmd = TestCommand {
            name: "test_cmd".to_string(),
            can_apply_result: true,
            apply_result: true,
        };
        assert!(cmd.get_messages().is_none());
    }

    #[test]
    fn test_trait_object() {
        let cmd = TestCommand {
            name: "test_cmd".to_string(),
            can_apply_result: true,
            apply_result: true,
        };
        let boxed: Box<dyn BinaryAnalysisCommand> = Box::new(cmd);
        assert_eq!(boxed.get_name(), "test_cmd");
        assert!(boxed.can_apply(&MockProgram));
    }
}
