use std::any::Any;
use std::fmt;

use crate::framework::model::DomainObjectChangeRecord;
use crate::program::model::address::Address;
use crate::program::util::ProgramEvent;

/// Event data for a DomainObjectChangeEvent generated by a Program.
///
/// Port of `ghidra.program.util.ProgramChangeRecord`.
pub struct ProgramChangeRecord {
    change_record: DomainObjectChangeRecord,
    start: Option<Address>,
    end: Option<Address>,
    affected_obj: Option<Box<dyn Any + Send + Sync>>,
}

impl ProgramChangeRecord {
    /// Construct a new ProgramChangeRecord; any of the Address or Object params may be None,
    /// depending on what the event type is.
    ///
    /// # Arguments
    /// * `event_type` - event type
    /// * `start` - starting address that is affected by the event
    /// * `end` - ending address that is affected by the event
    /// * `affected` - the object that was affected by this change, if applicable
    /// * `old_value` - original value
    /// * `new_value` - new value
    pub fn new(
        event_type: ProgramEvent,
        start: Option<Address>,
        end: Option<Address>,
        affected: Option<Box<dyn Any + Send + Sync>>,
        old_value: Option<Box<dyn Any + Send + Sync>>,
        new_value: Option<Box<dyn Any + Send + Sync>>,
    ) -> Self {
        Self {
            change_record: DomainObjectChangeRecord::with_values(
                Box::new(event_type),
                old_value,
                new_value,
            ),
            start,
            end,
            affected_obj: affected,
        }
    }

    /// Construct a new ProgramChangeRecord with no start, end, or affected object.
    ///
    /// # Arguments
    /// * `event_type` - event type
    /// * `old_value` - original value
    /// * `new_value` - new value
    pub fn new_without_range(
        event_type: ProgramEvent,
        old_value: Option<Box<dyn Any + Send + Sync>>,
        new_value: Option<Box<dyn Any + Send + Sync>>,
    ) -> Self {
        Self::new(event_type, None, None, None, old_value, new_value)
    }

    /// Get the start address of the affected addresses of this change or `None` if not
    /// applicable.
    pub fn start(&self) -> Option<&Address> {
        self.start.as_ref()
    }

    /// Get the end address of the affected addresses of this change or `None` if not
    /// applicable.
    pub fn end(&self) -> Option<&Address> {
        self.end.as_ref()
    }

    /// Return the object that is the subject of this change record, or `None` if not
    /// applicable.
    pub fn object(&self) -> Option<&(dyn Any + Send + Sync)> {
        self.affected_obj.as_deref()
    }

    /// Returns a reference to the underlying DomainObjectChangeRecord.
    pub fn change_record(&self) -> &DomainObjectChangeRecord {
        &self.change_record
    }
}

impl fmt::Display for ProgramChangeRecord {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        write!(f, "{}", self.change_record)?;
        if self.affected_obj.is_some() {
            write!(f, ", affected = <object>")?;
        }
        if let Some(start) = &self.start {
            write!(f, ", start = {}", start)?;
        }
        if let Some(end) = &self.end {
            write!(f, ", end = {}", end)?;
        }
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn new_without_range_has_no_start_end_or_object() {
        let record =
            ProgramChangeRecord::new_without_range(ProgramEvent::SymbolAdded, None, None);
        assert!(record.start().is_none());
        assert!(record.end().is_none());
        assert!(record.object().is_none());
    }

    #[test]
    fn new_without_range_stores_old_and_new_values() {
        let old = Some(Box::new("old".to_string()) as Box<dyn Any + Send + Sync>);
        let new = Some(Box::new("new".to_string()) as Box<dyn Any + Send + Sync>);
        let record = ProgramChangeRecord::new_without_range(ProgramEvent::SymbolRenamed, old, new);

        assert_eq!(
            record.change_record().old_value().unwrap().downcast_ref::<String>(),
            Some(&"old".to_string())
        );
        assert_eq!(
            record.change_record().new_value().unwrap().downcast_ref::<String>(),
            Some(&"new".to_string())
        );
    }

    #[test]
    fn new_with_affected_object_stores_it() {
        let affected = Box::new(42i32) as Box<dyn Any + Send + Sync>;
        let record =
            ProgramChangeRecord::new(ProgramEvent::FunctionChanged, None, None, Some(affected), None, None);
        assert_eq!(record.object().unwrap().downcast_ref::<i32>(), Some(&42));
    }

    #[test]
    fn record_uses_given_event_type() {
        let record =
            ProgramChangeRecord::new_without_range(ProgramEvent::CommentChanged, None, None);
        assert_eq!(
            record.change_record().event_type().get_id(),
            ProgramEvent::CommentChanged.get_id()
        );
    }

    #[test]
    fn display_without_affected_start_or_end() {
        let record =
            ProgramChangeRecord::new_without_range(ProgramEvent::SymbolAdded, None, None);
        let s = format!("{}", record);
        assert!(!s.contains("affected"));
        assert!(!s.contains("start"));
        assert!(!s.contains("end"));
    }

    #[test]
    fn display_with_affected() {
        let affected = Box::new("obj".to_string()) as Box<dyn Any + Send + Sync>;
        let record =
            ProgramChangeRecord::new(ProgramEvent::SymbolRemoved, None, None, Some(affected), None, None);
        let s = format!("{}", record);
        assert!(s.contains("affected"));
    }

    #[test]
    fn display_includes_record_info() {
        let record =
            ProgramChangeRecord::new_without_range(ProgramEvent::SymbolAdded, None, None);
        let s = format!("{}", record);
        assert!(s.contains("DomainObjectChangeRecord"));
    }
}
