pub mod function_inline_settings_definition;
pub mod function_no_return_settings_definition;
pub mod function_thunk_settings_definition;

pub use function_inline_settings_definition::FunctionInlineSettingsDefinition;
pub use function_no_return_settings_definition::FunctionNoReturnSettingsDefinition;
pub use function_thunk_settings_definition::FunctionThunkSettingsDefinition;
