//! Port of `ghidra.program.model.data.AbstractStringDataType`.
//!
//! The Java class is abstract with instance fields (shape rule R11): a shared-state part and a
//! behaviour part. Every concrete subclass (`StringDataType`, `TerminatedStringDataType`,
//! `PascalStringDataType`, `UnicodeDataType`, ...) only passes constants to the constructor, so
//! the per-class constructor arguments are a [`StringDataTypeSpec`], the per-instance state is the
//! [`BuiltInBase`](super::built_in::BuiltInBase) every built-in carries, and the behaviour is the
//! [`AbstractStringDataType`] trait, whose provided methods are the Java method bodies. The
//! concrete types are generated by [`string_data_type!`].
//!
//! Java's `BuiltIn` superclass is the [`BuiltIn`](super::built_in::BuiltIn) trait, implemented for
//! each concrete type by the macro.

use std::any::TypeId;

use crate::docking::settings::settings::Settings;
use crate::docking::settings::settings_definition::SettingsDefinition;
use crate::program::model::data::charset_settings_definition::CharsetSettingsDefinition;
use crate::program::model::data::data_type::DataType;
use crate::program::model::data::data_type_display_options::DataTypeDisplayOptions;
use crate::program::model::data::data_type_encode_exception::DataTypeEncodeException;
use crate::program::model::data::data_type_with_charset::{DataTypeEncodeError, DataTypeWithCharset};
use crate::program::model::data::dynamic::Dynamic;
use crate::program::model::data::render_unicode_settings_definition::RenderUnicodeSettingsDefinition;
use crate::program::model::data::string_data_instance::{NoSettings, StringDataInstance, DEFAULT_CHARSET_NAME};
use crate::program::model::data::string_layout_enum::StringLayoutEnum;
use crate::program::model::data::translation_settings_definition::TranslationSettingsDefinition;
use crate::program::model::mem::MemBuffer;

/// Port of `AbstractStringDataType.DEFAULT_UNICODE_LABEL`.
pub const DEFAULT_UNICODE_LABEL: &str = "UNICODE";
/// Port of `AbstractStringDataType.DEFAULT_UNICODE_LABEL_PREFIX`.
pub const DEFAULT_UNICODE_LABEL_PREFIX: &str = "UNI";
/// Port of `AbstractStringDataType.DEFAULT_UNICODE_ABBREV_PREFIX`.
pub const DEFAULT_UNICODE_ABBREV_PREFIX: &str = "u";

/// Port of `AbstractStringDataType.DEFAULT_LABEL`.
pub const DEFAULT_LABEL: &str = "STRING";
/// Port of `AbstractStringDataType.DEFAULT_LABEL_PREFIX`.
pub const DEFAULT_LABEL_PREFIX: &str = "STR";
/// Port of `AbstractStringDataType.DEFAULT_ABBREV_PREFIX`.
pub const DEFAULT_ABBREV_PREFIX: &str = "s";

/// Port of `AbstractStringDataType.USE_CHARSET_DEF_DEFAULT`: no fixed charset, so the charset
/// settings definition decides.
pub const USE_CHARSET_DEF_DEFAULT: Option<&str> = None;

/// Port of `AbstractStringDataType.COMMON_STRING_SETTINGS_DEFS` (`{ TRANSLATION, RENDER }`).
pub fn common_string_settings_defs() -> Vec<Box<dyn SettingsDefinition>> {
    vec![
        Box::new(TranslationSettingsDefinition::translation().clone()),
        Box::new(RenderUnicodeSettingsDefinition::DEF),
    ]
}

/// Port of `AbstractStringDataType.COMMON_WITH_CHARSET_STRING_SETTINGS_DEFS`
/// (`SettingsDefinition.concat(COMMON_STRING_SETTINGS_DEFS, CHARSET)`).
pub fn common_with_charset_string_settings_defs() -> Vec<Box<dyn SettingsDefinition>> {
    let mut defs = common_string_settings_defs();
    defs.push(Box::new(CharsetSettingsDefinition::charset().clone()));
    defs
}

/// The constructor arguments of a concrete string data type (the `AbstractStringDataType`
/// constructor's parameters other than the data type manager).
#[derive(Debug)]
pub struct StringDataTypeSpec {
    /// The data type name.
    pub name: &'static str,
    /// The mnemonic.
    pub mnemonic: &'static str,
    /// The default label.
    pub default_label: &'static str,
    /// The default label prefix.
    pub default_label_prefix: &'static str,
    /// The default abbreviated label prefix.
    pub default_abbrev_label_prefix: &'static str,
    /// The description.
    pub description: &'static str,
    /// A fixed charset, or [`USE_CHARSET_DEF_DEFAULT`] to use the charset setting.
    pub charset_name: Option<&'static str>,
    /// The replacement data type (Java passes the replacement's `dataType` singleton).
    pub replacement_data_type: fn() -> Box<dyn DataType>,
    /// The string layout.
    pub string_layout: StringLayoutEnum,
}

/// Common base for all Ghidra string data types.
///
/// Port of `ghidra.program.model.data.AbstractStringDataType`; see the module docs. The provided
/// methods carry the Java overrides of `DataType`/`Dynamic`/`DataTypeWithCharset` methods under
/// `string_*` names (a subtrait cannot redeclare a supertrait method); the concrete types delegate
/// to them.
///
/// The `std::any::Any` supertrait lets [`Sequence`](crate::util::ascii::sequence::Sequence) compare
/// two string data types by concrete class, as Java's `getClass()` comparison does.
pub trait AbstractStringDataType: DataType + Dynamic + DataTypeWithCharset + std::any::Any {
    /// The constant constructor arguments of this string data type.
    fn spec(&self) -> &'static StringDataTypeSpec;

    /// Port of `getStringLayout()`.
    fn get_string_layout(&self) -> StringLayoutEnum {
        self.spec().string_layout
    }

    /// Port of `getStringDataInstance(MemBuffer, Settings, int)`.
    fn get_string_data_instance<'a>(&self, buf: &'a dyn MemBuffer, settings: &dyn Settings, length: i32) -> StringDataInstance<'a> {
        StringDataInstance::new(self, settings, buf, length)
    }

    /// Port of `getBuiltInSettingsDefinitions()`: the common settings, plus the charset setting
    /// when the type has no fixed charset.
    fn string_settings_definitions(&self) -> Vec<Box<dyn SettingsDefinition>> {
        if self.spec().charset_name.is_some() {
            common_string_settings_defs()
        } else {
            common_with_charset_string_settings_defs()
        }
    }

    /// Port of `getCharsetName(Settings)`.
    fn string_charset_name(&self, settings: &dyn Settings) -> String {
        match self.spec().charset_name {
            Some(name) => name.to_string(),
            None => CharsetSettingsDefinition::charset().get_charset(settings, DEFAULT_CHARSET_NAME),
        }
    }

    /// Port of `getLength(MemBuffer, int)`.
    fn string_dynamic_length(&self, buf: &dyn MemBuffer, max_length: i32) -> i32 {
        self.get_string_data_instance(buf, &NoSettings, max_length).get_string_length()
    }

    /// Port of `getValueClass(Settings)`: `String`.
    fn string_value_type_id(&self) -> TypeId {
        TypeId::of::<String>()
    }

    /// Port of `getValue(MemBuffer, Settings, int)`.
    fn string_value(&self, buf: &dyn MemBuffer, settings: &dyn Settings, length: i32) -> Option<String> {
        self.get_string_data_instance(buf, settings, length).get_string_value()
    }

    /// Port of `encodeValue(Object, MemBuffer, Settings, int)` for a `CharSequence` value.
    fn string_encode_value(&self, value: &str, buf: &dyn MemBuffer, settings: &dyn Settings, length: i32) -> Result<Vec<u8>, DataTypeEncodeError> {
        self.get_string_data_instance(buf, settings, length)
            .encode_replacement_from_string_value(value)
            .map_err(|e| DataTypeEncodeException::with_cause_only(value, self.get_display_name(), Box::new(e)).into())
    }

    /// Port of `encodeValue(Object, MemBuffer, Settings, int)`: requires a `String` or `&str`.
    fn string_encode_any_value(
        &self,
        value: &dyn std::any::Any,
        buf: &dyn MemBuffer,
        settings: &dyn Settings,
        length: i32,
    ) -> Result<Vec<u8>, DataTypeEncodeError> {
        let text = value
            .downcast_ref::<String>()
            .map(String::as_str)
            .or_else(|| value.downcast_ref::<&str>().copied());
        match text {
            Some(text) => self.string_encode_value(text, buf, settings, length),
            None => Err(DataTypeEncodeException::new("Requires CharSequence", "?", self.get_display_name()).into()),
        }
    }

    /// Port of `getRepresentation(MemBuffer, Settings, int)`.
    fn string_representation(&self, buf: &dyn MemBuffer, settings: &dyn Settings, length: i32) -> String {
        self.get_string_data_instance(buf, settings, length).get_string_representation()
    }

    /// Port of `encodeRepresentation(String, MemBuffer, Settings, int)`.
    fn string_encode_representation(&self, repr: &str, buf: &dyn MemBuffer, settings: &dyn Settings, length: i32) -> Result<Vec<u8>, DataTypeEncodeError> {
        self.get_string_data_instance(buf, settings, length)
            .encode_replacement_from_string_representation(repr)
            .map_err(|e| DataTypeEncodeException::with_cause_only(repr, self.get_display_name(), Box::new(e)).into())
    }

    /// Port of `getDefaultLabelPrefix(MemBuffer, Settings, int, DataTypeDisplayOptions)`.
    fn string_default_label_prefix_for_data(
        &self,
        buf: &dyn MemBuffer,
        settings: &dyn Settings,
        len: i32,
        options: &dyn DataTypeDisplayOptions,
    ) -> String {
        let spec = self.spec();
        self.get_string_data_instance(buf, settings, len).get_label(
            &format!("{}_", spec.default_abbrev_label_prefix),
            spec.default_label_prefix,
            spec.default_label,
            options,
        )
    }

    /// Port of `getDefaultOffcutLabelPrefix(MemBuffer, Settings, int, DataTypeDisplayOptions, int)`.
    fn string_default_offcut_label_prefix(
        &self,
        buf: &dyn MemBuffer,
        settings: &dyn Settings,
        len: i32,
        options: &dyn DataTypeDisplayOptions,
        offcut_length: i32,
    ) -> String {
        let spec = self.spec();
        self.get_string_data_instance(buf, settings, len).get_offcut_label_string(
            &format!("{}_", spec.default_abbrev_label_prefix),
            spec.default_label_prefix,
            spec.default_label,
            options,
            offcut_length,
        )
    }
}

/// Defines a concrete string data type: a struct embedding a
/// [`BuiltInBase`](super::built_in::BuiltInBase), its `dataType` singleton, and its
/// `DataType`/`DataTypeImpl`/`BuiltInDataType`/`BuiltIn`/`Dynamic`/`DataTypeWithCharset`/
/// `AbstractStringDataType` impls, from the Java constructor arguments.
macro_rules! string_data_type {
    (
        $(#[$meta:meta])*
        $ty:ident {
            name: $name:literal,
            mnemonic: $mnemonic:literal,
            default_label: $label:expr,
            default_label_prefix: $prefix:expr,
            default_abbrev_label_prefix: $abbrev:expr,
            description: $desc:literal,
            charset: $charset:expr,
            replacement: $replacement:path,
            layout: $layout:expr,
        }
    ) => {
        $(#[$meta])*
        #[derive(Debug, Clone)]
        pub struct $ty {
            base: $crate::program::model::data::built_in::BuiltInBase,
        }

        impl $ty {
            /// The constructor arguments of this type.
            pub const SPEC: $crate::program::model::data::abstract_string_data_type::StringDataTypeSpec =
                $crate::program::model::data::abstract_string_data_type::StringDataTypeSpec {
                    name: $name,
                    mnemonic: $mnemonic,
                    default_label: $label,
                    default_label_prefix: $prefix,
                    default_abbrev_label_prefix: $abbrev,
                    description: $desc,
                    charset_name: $charset,
                    replacement_data_type: || Box::new(<$replacement>::new(None)),
                    string_layout: $layout,
                };

            /// Creates an instance bound to `dtm`'s data organization (Java: `new T(dtm)`; `None`
            /// is the no-argument constructor).
            pub fn new(dtm: Option<&dyn $crate::program::model::data::data_type_manager::DataTypeManager>) -> Self {
                Self { base: $crate::program::model::data::built_in::BuiltInBase::new(None, $name, dtm) }
            }

            fn c_type_declaration(
                &self,
                data_organization: Option<&$crate::program::model::data::data_organization_impl::DataOrganizationImpl>,
            ) -> Option<String> {
                $crate::program::model::data::built_in::BuiltIn::built_in_get_c_type_declaration(self, data_organization)
            }

            fn built_in_settings_definitions(&self) -> Vec<Box<dyn $crate::docking::settings::settings_definition::SettingsDefinition>> {
                $crate::program::model::data::abstract_string_data_type::AbstractStringDataType::string_settings_definitions(self)
            }

            fn decompiler_display_name(&self, _language: $crate::program::model::lang::decompiler_language::DecompilerLanguage) -> String {
                $name.to_string()
            }
        }

        $crate::program::model::data::built_in::built_in_singleton!($ty);
        $crate::program::model::data::built_in::impl_built_in!($ty);

        impl std::fmt::Display for $ty {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                f.write_str(&$crate::program::model::data::data_type::DataType::get_display_name(self))
            }
        }

        impl $crate::program::model::data::data_type::DataType for $ty {
            $crate::program::model::data::built_in::built_in_data_type_methods!(own_abbreviated_label_prefix);

            fn get_length(&self) -> i32 {
                -1
            }
            fn get_mnemonic(&self, _settings: &dyn $crate::docking::settings::settings::Settings) -> String {
                $mnemonic.to_string()
            }
            fn get_description(&self) -> String {
                $desc.to_string()
            }
            fn get_default_label_prefix(&self) -> Option<String> {
                Some(Self::SPEC.default_label_prefix.to_string())
            }
            fn get_default_abbreviated_label_prefix(&self) -> Option<String> {
                Some(Self::SPEC.default_abbrev_label_prefix.to_string())
            }
            fn get_value(
                &self,
                buf: &dyn $crate::program::model::mem::MemBuffer,
                settings: &dyn $crate::docking::settings::settings::Settings,
                length: i32,
            ) -> Option<Box<dyn std::any::Any>> {
                $crate::program::model::data::abstract_string_data_type::AbstractStringDataType::string_value(self, buf, settings, length)
                    .map(|s| Box::new(s) as Box<dyn std::any::Any>)
            }
            fn is_encodable(&self) -> bool {
                true
            }
            fn encode_value(
                &self,
                value: &dyn std::any::Any,
                buf: &dyn $crate::program::model::mem::MemBuffer,
                settings: &dyn $crate::docking::settings::settings::Settings,
                length: i32,
            ) -> Result<Vec<u8>, $crate::program::model::data::data_type_with_charset::DataTypeEncodeError> {
                $crate::program::model::data::abstract_string_data_type::AbstractStringDataType::string_encode_any_value(self, value, buf, settings, length)
            }
            fn get_value_class(&self, _settings: &dyn $crate::docking::settings::settings::Settings) -> Option<std::any::TypeId> {
                Some($crate::program::model::data::abstract_string_data_type::AbstractStringDataType::string_value_type_id(self))
            }
            fn get_representation(
                &self,
                buf: &dyn $crate::program::model::mem::MemBuffer,
                settings: &dyn $crate::docking::settings::settings::Settings,
                length: i32,
            ) -> String {
                $crate::program::model::data::abstract_string_data_type::AbstractStringDataType::string_representation(self, buf, settings, length)
            }
            fn encode_representation(
                &self,
                repr: &str,
                buf: &dyn $crate::program::model::mem::MemBuffer,
                settings: &dyn $crate::docking::settings::settings::Settings,
                length: i32,
            ) -> Result<Vec<u8>, $crate::program::model::data::data_type_with_charset::DataTypeEncodeError> {
                $crate::program::model::data::abstract_string_data_type::AbstractStringDataType::string_encode_representation(self, repr, buf, settings, length)
            }
            fn get_default_label_prefix_for_data(
                &self,
                buf: &dyn $crate::program::model::mem::MemBuffer,
                settings: &dyn $crate::docking::settings::settings::Settings,
                len: i32,
                options: &dyn $crate::program::model::data::data_type_display_options::DataTypeDisplayOptions,
            ) -> Option<String> {
                Some($crate::program::model::data::abstract_string_data_type::AbstractStringDataType::string_default_label_prefix_for_data(self, buf, settings, len, options))
            }
            fn get_default_offcut_label_prefix(
                &self,
                buf: &dyn $crate::program::model::mem::MemBuffer,
                settings: &dyn $crate::docking::settings::settings::Settings,
                len: i32,
                options: &dyn $crate::program::model::data::data_type_display_options::DataTypeDisplayOptions,
                offcut_offset: i32,
            ) -> Option<String> {
                Some($crate::program::model::data::abstract_string_data_type::AbstractStringDataType::string_default_offcut_label_prefix(self, buf, settings, len, options, offcut_offset))
            }
            fn is_equivalent(&self, dt: &dyn $crate::program::model::data::data_type::DataType) -> bool {
                $crate::program::model::data::built_in::same_class(self, dt)
            }
            fn is_dynamic_type(&self) -> bool {
                true
            }
            fn is_string_type(&self) -> bool {
                true
            }
            fn as_dynamic(&self) -> Option<&dyn $crate::program::model::data::dynamic::Dynamic> {
                Some(self)
            }
            fn as_abstract_string(&self) -> Option<&dyn $crate::program::model::data::abstract_string_data_type::AbstractStringDataType> {
                Some(self)
            }
            fn as_data_type_with_charset(&self) -> Option<&dyn $crate::program::model::data::data_type_with_charset::DataTypeWithCharset> {
                Some(self)
            }
        }

        impl $crate::program::model::data::dynamic::Dynamic for $ty {
            fn get_dynamic_length(&self, buf: &dyn $crate::program::model::mem::MemBuffer, max_length: i32) -> i32 {
                $crate::program::model::data::abstract_string_data_type::AbstractStringDataType::string_dynamic_length(self, buf, max_length)
            }
            fn can_specify_length(&self) -> bool {
                true
            }
            fn get_replacement_base_type(&self) -> Box<dyn $crate::program::model::data::data_type::DataType> {
                (Self::SPEC.replacement_data_type)()
            }
        }

        impl $crate::program::model::data::data_type_with_charset::DataTypeWithCharset for $ty {
            fn get_charset_name(&self, settings: &dyn $crate::docking::settings::settings::Settings) -> String {
                $crate::program::model::data::abstract_string_data_type::AbstractStringDataType::string_charset_name(self, settings)
            }
        }

        impl $crate::program::model::data::abstract_string_data_type::AbstractStringDataType for $ty {
            fn spec(&self) -> &'static $crate::program::model::data::abstract_string_data_type::StringDataTypeSpec {
                &Self::SPEC
            }
        }
    };
}
pub(crate) use string_data_type;
