//! Port of `ghidra.program.model.data.AbstractIntegerDataType`.
//!
//! The Java class is abstract with no instance state (shape rule R12), so it is a trait. Its
//! superclass `BuiltIn` is the [`BuiltIn`](super::built_in::BuiltIn) trait plus the shared
//! [`BuiltInBase`](super::built_in::BuiltInBase) state. The trait extends [`DataType`] +
//! [`BuiltInDataType`] + [`ArrayStringable`]; the 36 concrete subclasses are generated by
//! [`integer_data_type!`] (see its docs for how each Java override maps onto a macro field), and
//! `BooleanDataType`/`CharDataType` implement it by hand.
//!
//! Several Java methods here share a name with an already-provided method on [`DataType`]
//! (`getMnemonic`, `getDefaultLabelPrefix`, `getValue`, `isEncodable`, `encodeValue`,
//! `getRepresentation`, `encodeRepresentation`, `getValueClass`, `isEquivalent`) or with a
//! *required* (no-default) method on [`ArrayStringable`] (`hasStringValue`,
//! `getArrayDefaultLabelPrefix`, `getArrayDefaultOffcutLabelPrefix`). Rust does not allow a
//! subtrait to override (or default) a supertrait's method by redeclaring the same name -- it
//! would just create an ambiguous method for any type implementing both -- so, mirroring the
//! convention established by [`CharDataType`](super::char_data_type::CharDataType) and the other
//! `Abstract*DataType` traits, those overrides are exposed here under distinct `integer_*` names.
//! The concrete implementations delegate their `DataType`/`ArrayStringable` methods to these
//! helpers (see [`integer_data_type!`]).
//!
//! The Java class's constructor is not translated (traits cannot declare constructors or store
//! fields); implementors are expected to persist their own `name`/`DataTypeManager` state and
//! expose it via [`DataType::get_name`]/[`DataType::get_data_organization`], both of which the
//! default methods here rely on instead of private fields.
//!
//! `getValue`/`encodeValue`/`getValueClass` do not use `java.lang.Object`/`Class<?>` here: instead
//! of Java's runtime `instanceof`-driven acceptance of `BigInteger`, `Scalar`, `Character`,
//! `Byte`, `Short`, `Integer`, or `Long`, [`IntegerValue`] and [`IntegerEncodeValue`] enumerate the
//! same set of accepted shapes directly (mirroring how
//! [`AbstractFloatDataType::encode_float_value`] replaces `Object value` with
//! [`FloatEncodeValue`](super::abstract_float_data_type::FloatEncodeValue)). Since
//! [`Scalar`](crate::program::model::scalar::Scalar) is itself a plain, already-ported struct
//! (not a cycle cut-point), it is used directly rather than through a placeholder.
//!
//! `isEquivalent(DataType)` (renamed [`integer_is_equivalent`](AbstractIntegerDataType::integer_is_equivalent))
//! compares `dt.getClass().equals(getClass())` in Java; the concrete types expose their class via
//! [`DataType::runtime_class`] and compare that. An implementor without a runtime class (a test
//! double) falls back to comparing [`DataType::is_integer_type`]/
//! [`DataType::is_signed_integer_type`] plus the name.
//!
//! The static factories `getSignedDataType`/`getSignedDataTypes`/`getUnsignedDataType`/
//! `getUnsignedDataTypes` are the free functions [`get_signed_data_type`],
//! [`get_signed_data_types`], [`get_unsigned_data_type`] and [`get_unsigned_data_types`].
//!
//! The CHAR-format branches of `getRepresentation`/`encodeRepresentation` render/parse this
//! integer's bytes as a character through
//! [`string_data_instance`](super::string_data_instance), as do the array label helpers
//! (`getArrayDefaultLabelPrefix`/`getArrayDefaultOffcutLabelPrefix`).
//!
//! `Utils.bigIntegerToBytes`/`DataConverter` (Java) are replaced by
//! [`crate::pcode::utils::utils`]'s `bytes_to_long`/`long_to_bytes`/`bytes_to_big_integer`/
//! `big_integer_to_bytes` (the same helpers [`AbstractFloatDataType`] uses), which represent
//! `BigInteger` as `i128`. As with every other use of that representation in this crate, integer
//! lengths whose magnitude cannot fit in an `i128` (i.e. 16-byte *unsigned* values near or above
//! `2^127`) are not perfectly representable; [`encode_bounds`] and [`pow2_i128`] saturate rather
//! than panic in that case instead of silently wrapping.

use std::any::TypeId;
use std::fmt;
use std::sync::Arc;

use crate::docking::settings::enum_settings_definition::EnumSettingsDefinition;
use crate::docking::settings::format_settings_definition::{self, FormatSettingsDefinition};
use crate::docking::settings::settings::Settings;
use crate::docking::settings::settings_definition::SettingsDefinition;
use crate::pcode::utils::utils::{big_integer_to_bytes, bytes_to_big_integer, bytes_to_long};
use crate::program::model::data::abstract_string_data_type::{
    DEFAULT_ABBREV_PREFIX, DEFAULT_LABEL, DEFAULT_LABEL_PREFIX,
};
use crate::program::model::data::array_data_type::ArrayDataType;
use crate::program::model::data::byte_data_type::ByteDataType;
use crate::program::model::data::data_type_manager::DataTypeManager;
use crate::program::model::data::default_data_type::DefaultDataType;
use crate::program::model::data::dword_data_type::DWordDataType;
use crate::program::model::data::integer16_data_type::Integer16DataType;
use crate::program::model::data::integer3_data_type::Integer3DataType;
use crate::program::model::data::integer5_data_type::Integer5DataType;
use crate::program::model::data::integer6_data_type::Integer6DataType;
use crate::program::model::data::integer7_data_type::Integer7DataType;
use crate::program::model::data::integer_data_type::IntegerDataType;
use crate::program::model::data::long_data_type::LongDataType;
use crate::program::model::data::long_long_data_type::LongLongDataType;
use crate::program::model::data::qword_data_type::QWordDataType;
use crate::program::model::data::short_data_type::ShortDataType;
use crate::program::model::data::signed_byte_data_type::SignedByteDataType;
use crate::program::model::data::signed_dword_data_type::SignedDWordDataType;
use crate::program::model::data::signed_qword_data_type::SignedQWordDataType;
use crate::program::model::data::signed_word_data_type::SignedWordDataType;
use crate::program::model::data::undefined::get_undefined_data_type;
use crate::program::model::data::unsigned_integer16_data_type::UnsignedInteger16DataType;
use crate::program::model::data::unsigned_integer3_data_type::UnsignedInteger3DataType;
use crate::program::model::data::unsigned_integer5_data_type::UnsignedInteger5DataType;
use crate::program::model::data::unsigned_integer6_data_type::UnsignedInteger6DataType;
use crate::program::model::data::unsigned_integer7_data_type::UnsignedInteger7DataType;
use crate::program::model::data::unsigned_integer_data_type::UnsignedIntegerDataType;
use crate::program::model::data::unsigned_long_data_type::UnsignedLongDataType;
use crate::program::model::data::unsigned_long_long_data_type::UnsignedLongLongDataType;
use crate::program::model::data::unsigned_short_data_type::UnsignedShortDataType;
use crate::program::model::data::word_data_type::WordDataType;
use crate::program::model::data::array_stringable::ArrayStringable;
use crate::program::model::data::built_in_data_type::BuiltInDataType;
use crate::program::model::data::data_type::DataType;
use crate::program::model::data::data_type_display_options::DataTypeDisplayOptions;
use crate::program::model::data::data_type_encode_exception::DataTypeEncodeException;
use crate::program::model::data::data_type_mnemonic_settings_definition::{
    self, DataTypeMnemonicSettingsDefinition,
};
use crate::program::model::data::endian_settings_definition::{self, EndianSettingsDefinition};
use crate::program::model::data::padding_settings_definition::PaddingSettingsDefinition;
use crate::program::model::data::string_data_instance::{self as sdi, StringDataInstance};
use crate::program::model::scalar::Scalar;
use crate::program::model::mem::MemBuffer;
use crate::util::StringFormat;

/// Package-private `AbstractIntegerDataType.C_SIGNED_CHAR`.
pub const C_SIGNED_CHAR: &str = "signed char";
/// Package-private `AbstractIntegerDataType.C_UNSIGNED_CHAR`.
pub const C_UNSIGNED_CHAR: &str = "unsigned char";
/// Package-private `AbstractIntegerDataType.C_SIGNED_SHORT`.
pub const C_SIGNED_SHORT: &str = "short";
/// Package-private `AbstractIntegerDataType.C_UNSIGNED_SHORT`.
pub const C_UNSIGNED_SHORT: &str = "unsigned short";
/// Package-private `AbstractIntegerDataType.C_SIGNED_INT`.
pub const C_SIGNED_INT: &str = "int";
/// Package-private `AbstractIntegerDataType.C_UNSIGNED_INT`.
pub const C_UNSIGNED_INT: &str = "unsigned int";
/// Package-private `AbstractIntegerDataType.C_SIGNED_LONG`.
pub const C_SIGNED_LONG: &str = "long";
/// Package-private `AbstractIntegerDataType.C_UNSIGNED_LONG`.
pub const C_UNSIGNED_LONG: &str = "unsigned long";
/// Package-private `AbstractIntegerDataType.C_SIGNED_LONGLONG`.
pub const C_SIGNED_LONGLONG: &str = "long long";
/// Package-private `AbstractIntegerDataType.C_UNSIGNED_LONGLONG`.
pub const C_UNSIGNED_LONGLONG: &str = "unsigned long long";

/// Value returned by [`AbstractIntegerDataType::integer_value`], standing in for the `Object`
/// (`Scalar` or `BigInteger`) returned by `AbstractIntegerDataType.getValue`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IntegerValue {
    /// Used when this data-type's length is 8 bytes or fewer.
    Scalar(Scalar),
    /// Used when this data-type's length exceeds 8 bytes, represented as an `i128` in place of
    /// Java's arbitrary-precision `BigInteger` (see the module docs).
    Big(i128),
}

/// Value accepted by [`AbstractIntegerDataType::integer_encode_value`], standing in for the
/// `Object value` parameter of `AbstractIntegerDataType.encodeValue`/`castValueToEncode`,
/// documented in the Java source as accepting a `BigInteger`, `Scalar`, `Character`, `Byte`,
/// `Short`, `Integer`, or `Long`.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IntegerEncodeValue {
    /// Stands in for a `BigInteger` value.
    BigInt(i128),
    /// Stands in for a `Scalar` value; its own signedness (not this data-type's) is used.
    Scalar(Scalar),
    /// Stands in for a `Character` value, interpreted via `Character.getNumericValue` (i.e. as a
    /// base-36 digit, matching `'0'..='9'`/`'a'..='z'`/`'A'..='Z'`) rather than as a code point.
    Char(char),
    /// Stands in for a `Byte` value.
    I8(i8),
    /// Stands in for a `Short` value.
    I16(i16),
    /// Stands in for an `Integer` value.
    I32(i32),
    /// Stands in for a `Long` value.
    I64(i64),
}

impl fmt::Display for IntegerEncodeValue {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            IntegerEncodeValue::BigInt(v) => write!(f, "{v}"),
            IntegerEncodeValue::Scalar(s) => write!(f, "{s}"),
            IntegerEncodeValue::Char(c) => write!(f, "{c}"),
            IntegerEncodeValue::I8(v) => write!(f, "{v}"),
            IntegerEncodeValue::I16(v) => write!(f, "{v}"),
            IntegerEncodeValue::I32(v) => write!(f, "{v}"),
            IntegerEncodeValue::I64(v) => write!(f, "{v}"),
        }
    }
}

/// Computes `2^bits` as an `i128`, saturating to `i128::MAX` rather than panicking/wrapping once
/// `bits` would overflow `i128`'s 127-bit positive range. See the module docs' note on the
/// `i128`-as-`BigInteger` representation's limits.
fn pow2_i128(bits: u32) -> i128 {
    if bits >= 127 {
        i128::MAX
    } else {
        1i128 << bits
    }
}

/// Computes `(min_value_inclusive, max_value_exclusive)` for a `length`-byte integer of the given
/// signedness, standing in for the two `BigInteger` bounds `AbstractIntegerDataType.encodeValue`
/// computes inline. `max_value_exclusive` is `None` when it cannot be represented as an `i128`
/// (only possible for unsigned lengths of 16 bytes), meaning "no representable value can reach
/// this bound".
fn encode_bounds(length: i32, signed: bool) -> (i128, Option<i128>) {
    let bits = (length * 8) as u32;
    let min_inclusive = if !signed || bits == 0 {
        0
    } else if bits - 1 >= 127 {
        i128::MIN
    } else {
        -(1i128 << (bits - 1))
    };
    let max_bits = if signed { bits.saturating_sub(1) } else { bits };
    let max_exclusive = if max_bits >= 127 { None } else { Some(1i128 << max_bits) };
    (min_inclusive, max_exclusive)
}

/// Resolves the endianness to use for a byte<->value conversion, standing in for
/// `ENDIAN.isBigEndian(settings, buf)`. [`EndianSettingsDefinition::is_big_endian`] takes a
/// different `MemBuffer` placeholder (`crate::program::model::lang::sleigh::walker::MemBuffer`)
/// than the one this trait's methods use (`crate::program::model::mem::MemBuffer`), so -- mirroring
/// [`AbstractStringDataType::get_string_data_instance`]'s identical workaround -- this reads the
/// raw enum choice via [`EnumSettingsDefinition::get_choice`] and falls back to the buffer's own
/// endianness exactly as [`EndianSettingsDefinition::is_big_endian`] would.
fn resolve_big_endian(settings: &dyn Settings, buf: &dyn MemBuffer) -> bool {
    match EndianSettingsDefinition::DEF.get_choice(settings) {
        endian_settings_definition::BIG => true,
        endian_settings_definition::LITTLE => false,
        _ => buf.is_big_endian(),
    }
}

/// Port of the package-private `AbstractIntegerDataType.getRepresentation(BigInteger, Settings,
/// int, boolean)`, used by [`AbstractIntegerDataType::integer_representation`]. Always reads the
/// format via the literal [`FormatSettingsDefinition::DEF_HEX`] (not a per-instance override),
/// exactly matching the Java source.
///
/// `pub(crate)` (rather than private) because the Java method is itself package-private, not
/// `private`: `BitFieldDataType.getRepresentation` (same `ghidra.program.model.data` package)
/// calls it directly too (`AbstractIntegerDataType.getRepresentation(big, settings,
/// effectiveBitSize, isSigned)`), and `bit_field_data_type.rs` reuses this exact function for
/// that cross-module call.
pub(crate) fn format_integer_representation(mut big_int: i128, settings: &dyn Settings, bit_length: i32, is_signed: bool) -> String {
    let padded = PaddingSettingsDefinition::DEF.is_padded(Some(settings));
    let negative = big_int < 0;
    let format = FormatSettingsDefinition::DEF_HEX.get_choice(settings);
    if negative && (!is_signed || format != format_settings_definition::DECIMAL) {
        big_int += pow2_i128(bit_length.max(0) as u32);
    }
    let (val_str, nominal_len) = match format {
        format_settings_definition::DECIMAL => return big_int.to_string(),
        format_settings_definition::BINARY => (format!("{big_int:b}b"), bit_length),
        format_settings_definition::OCTAL => (format!("{big_int:o}o"), (bit_length + 2) / 3),
        _ => (format!("{big_int:X}h"), (bit_length + 3) / 4),
    };
    if padded {
        StringFormat::pad_it(&val_str, (nominal_len + 1).max(0) as usize, '\0', true)
    } else {
        val_str
    }
}

/// Converts the `Object value` accepted by `AbstractIntegerDataType.encodeValue` into an
/// [`IntegerEncodeValue`]: an [`IntegerEncodeValue`] itself, a [`Scalar`], an `i128` (standing in
/// for `BigInteger`), a `char` (`Character`), or an `i8`/`i16`/`i32`/`i64` (`Byte`/`Short`/
/// `Integer`/`Long`). Anything else is Java's "Unsupported value type".
pub fn integer_encode_value_from_any(value: &dyn std::any::Any) -> Option<IntegerEncodeValue> {
    if let Some(v) = value.downcast_ref::<IntegerEncodeValue>() {
        return Some(*v);
    }
    if let Some(v) = value.downcast_ref::<Scalar>() {
        return Some(IntegerEncodeValue::Scalar(*v));
    }
    if let Some(v) = value.downcast_ref::<i128>() {
        return Some(IntegerEncodeValue::BigInt(*v));
    }
    if let Some(v) = value.downcast_ref::<char>() {
        return Some(IntegerEncodeValue::Char(*v));
    }
    if let Some(v) = value.downcast_ref::<i8>() {
        return Some(IntegerEncodeValue::I8(*v));
    }
    if let Some(v) = value.downcast_ref::<i16>() {
        return Some(IntegerEncodeValue::I16(*v));
    }
    if let Some(v) = value.downcast_ref::<i32>() {
        return Some(IntegerEncodeValue::I32(*v));
    }
    value.downcast_ref::<i64>().map(|v| IntegerEncodeValue::I64(*v))
}

/// Base type for integer data types such as chars, ints, and longs.
///
/// Port of `ghidra.program.model.data.AbstractIntegerDataType`. See the module-level
/// documentation for the conventions used to resolve name clashes with
/// [`DataType`]/[`ArrayStringable`] and for what was intentionally simplified or left unported.
pub trait AbstractIntegerDataType: DataType + BuiltInDataType + ArrayStringable {
    /// Determine if this type is signed.
    ///
    /// Port of the abstract `AbstractIntegerDataType.isSigned()`.
    fn is_signed(&self) -> bool;

    /// This data type as a `&dyn DataType` (Java's `this`), for the static `StringDataInstance`
    /// helpers the CHAR format uses.
    fn as_data_type(&self) -> &dyn DataType;

    /// Returns the data-type with the opposite signedness from this data-type. For example, this
    /// method on an `IntegerDataType`-equivalent implementor would return an instance of the
    /// `UnsignedIntegerDataType`-equivalent type.
    ///
    /// Port of the abstract `AbstractIntegerDataType.getOppositeSignednessDataType()`.
    fn get_opposite_signedness_data_type(&self) -> Box<dyn AbstractIntegerDataType>;

    /// Return the Format settings definition included in the settings definition array.
    ///
    /// Port of the protected `AbstractIntegerDataType.getFormatSettingsDefinition()`.
    fn get_format_settings_definition(&self) -> FormatSettingsDefinition {
        FormatSettingsDefinition::DEF_HEX
    }

    /// Port of the protected `AbstractIntegerDataType.getBuiltInSettingsDefinitions()`. Always
    /// `[FormatSettingsDefinition.DEF_HEX, PADDING, ENDIAN, MNEMONIC]`, using the literal
    /// `DEF_HEX` rather than [`get_format_settings_definition`](Self::get_format_settings_definition),
    /// exactly matching the Java source's `SETTINGS_DEFS` constant.
    fn get_built_in_settings_definitions(&self) -> Vec<Box<dyn SettingsDefinition>> {
        vec![
            Box::new(FormatSettingsDefinition::DEF_HEX),
            Box::new(PaddingSettingsDefinition::DEF),
            Box::new(EndianSettingsDefinition::DEF),
            Box::new(DataTypeMnemonicSettingsDefinition::DEF),
        ]
    }

    /// Port of `AbstractIntegerDataType.getDefaultLabelPrefix()`, exposed under a distinct name
    /// since [`DataType::get_default_label_prefix`] already provides a default. A concrete `impl
    /// DataType for ...` should delegate `get_default_label_prefix` to this.
    fn integer_default_label_prefix(&self) -> String {
        self.get_name().to_uppercase()
    }

    /// Port of `AbstractIntegerDataType.getMnemonic(Settings)`, exposed under a distinct name
    /// since [`DataType::get_mnemonic`] already provides a default. A concrete `impl DataType for
    /// ...` should delegate `get_mnemonic` to this.
    fn integer_mnemonic(&self, settings: &dyn Settings) -> String {
        let style = DataTypeMnemonicSettingsDefinition::DEF.get_mnemonic_style(Some(settings));
        if style == data_type_mnemonic_settings_definition::ASSEMBLY {
            self.get_assembly_mnemonic()
        } else if style == data_type_mnemonic_settings_definition::CSPEC {
            self.get_c_mnemonic()
        } else {
            self.get_name()
        }
    }

    /// The Assembly style data-type declaration for this data-type.
    ///
    /// Port of `AbstractIntegerDataType.getAssemblyMnemonic()`.
    fn get_assembly_mnemonic(&self) -> String {
        self.get_name()
    }

    /// The C style data-type mnemonic for this data-type.
    ///
    /// Port of `AbstractIntegerDataType.getCMnemonic()`.
    fn get_c_mnemonic(&self) -> String {
        self.get_c_declaration().unwrap_or_else(|| self.get_name())
    }

    /// The C style data-type declaration for this data-type, or `None` if no appropriate
    /// declaration exists.
    ///
    /// Port of `AbstractIntegerDataType.getCDeclaration()`.
    fn get_c_declaration(&self) -> Option<String> {
        let size = self.get_length();
        if size <= 0 {
            return None;
        }
        let signed = self.is_signed();
        let data_organization = self.get_data_organization();
        if size == data_organization.get_char_size() {
            return Some(if signed { C_SIGNED_CHAR } else { C_UNSIGNED_CHAR }.to_string());
        }
        if size == data_organization.get_integer_size() {
            return Some(if signed { C_SIGNED_INT } else { C_UNSIGNED_INT }.to_string());
        }
        if size == data_organization.get_short_size() {
            return Some(if signed { C_SIGNED_SHORT } else { C_UNSIGNED_SHORT }.to_string());
        }
        if size == data_organization.get_long_size() {
            return Some(if signed { C_SIGNED_LONG } else { C_UNSIGNED_LONG }.to_string());
        }
        if size == data_organization.get_long_long_size() {
            return Some(if signed { C_SIGNED_LONGLONG } else { C_UNSIGNED_LONGLONG }.to_string());
        }
        None
    }

    /// Port of `AbstractIntegerDataType.getValue(MemBuffer, Settings, int)`, exposed under a
    /// distinct name since [`DataType::get_value`] already provides a default with a different
    /// return type (`Option<Box<dyn Any>>` vs `Option<IntegerValue>`). The `length` parameter is
    /// ignored, matching the Java method (which always uses [`DataType::get_length`]). A concrete
    /// `impl DataType for ...` should delegate `get_value` to this.
    fn integer_value(&self, buf: &dyn MemBuffer, settings: &dyn Settings, _length: i32) -> Option<IntegerValue> {
        let size = self.get_length();
        if size <= 0 {
            return None;
        }
        let mut bytes = vec![0u8; size as usize];
        if buf.get_bytes_into(&mut bytes, 0) != size {
            return None;
        }
        let big_endian = resolve_big_endian(settings, buf);
        if size > 8 {
            let value = bytes_to_big_integer(&bytes, size as usize, big_endian, self.is_signed());
            Some(IntegerValue::Big(value))
        } else {
            let value = bytes_to_long(&bytes, size as usize, big_endian);
            Some(IntegerValue::Scalar(Scalar::new_with_signedness(size as u8 * 8, value, self.is_signed())))
        }
    }

    /// Port of `AbstractIntegerDataType.isEncodable()`, exposed under a distinct name since
    /// [`DataType::is_encodable`] already provides a default. Always `true`. A concrete `impl
    /// DataType for ...` should delegate `is_encodable` to this.
    fn is_integer_encodable(&self) -> bool {
        true
    }

    /// Port of the protected `AbstractIntegerDataType.castValueToEncode(Object)`.
    fn cast_value_to_encode(&self, value: &IntegerEncodeValue) -> Result<i128, DataTypeEncodeException> {
        match *value {
            IntegerEncodeValue::BigInt(v) => Ok(v),
            IntegerEncodeValue::Scalar(s) => Ok(s.get_big_integer()),
            IntegerEncodeValue::Char(c) => match c.to_digit(36) {
                Some(n) => Ok(n as i128),
                None => Err(DataTypeEncodeException::new(
                    "Character cannot be converted to number",
                    value,
                    self.get_name(),
                )),
            },
            IntegerEncodeValue::I8(n) => Ok(self.cast_fixed_width(n as i64, 8)),
            IntegerEncodeValue::I16(n) => Ok(self.cast_fixed_width(n as i64, 16)),
            IntegerEncodeValue::I32(n) => Ok(self.cast_fixed_width(n as i64, 32)),
            IntegerEncodeValue::I64(n) => Ok(self.cast_fixed_width(n, 64)),
        }
    }

    /// Port of the inline logic in `castValueToEncode` shared by the `Byte`/`Short`/`Integer`/
    /// `Long` branches (including the private `getBitCount(Class)` helper, folded in here since
    /// each caller already knows its own bit width statically).
    fn cast_fixed_width(&self, n: i64, bits: u32) -> i128 {
        let signed_val = n as i128;
        if self.is_signed() || signed_val >= 0 {
            signed_val
        } else {
            signed_val + pow2_i128(bits)
        }
    }

    /// Port of `AbstractIntegerDataType.encodeValue(Object, MemBuffer, Settings, int)`, exposed
    /// under a distinct name since [`DataType::encode_value`] already provides a default with a
    /// different `value` type (`&dyn Any` vs [`IntegerEncodeValue`]) and error type
    /// ([`DataTypeEncodeError`](crate::program::model::data::data_type_with_charset::DataTypeEncodeError)
    /// vs [`DataTypeEncodeException`]). A concrete `impl DataType for ...` should delegate
    /// `encode_value` to this.
    fn integer_encode_value(
        &self,
        value: &IntegerEncodeValue,
        buf: &dyn MemBuffer,
        settings: &dyn Settings,
        length: i32,
    ) -> Result<Vec<u8>, DataTypeEncodeException> {
        let length = if length == -1 { self.get_length() } else { length };
        if length != self.get_length() {
            return Err(DataTypeEncodeException::new("Length mismatch", value, self.get_name()));
        }
        let big_value = self.cast_value_to_encode(value)?;
        if big_value.is_negative() && !self.is_signed() {
            return Err(DataTypeEncodeException::new(
                "Unsigned type cannot have negative value",
                value,
                self.get_name(),
            ));
        }
        let (min_value_inclusive, max_value_exclusive) = encode_bounds(length, self.is_signed());
        if let Some(max_value_exclusive) = max_value_exclusive {
            if big_value >= max_value_exclusive {
                return Err(DataTypeEncodeException::new("Value is too large", big_value, self.get_name()));
            }
        }
        if min_value_inclusive > big_value {
            return Err(DataTypeEncodeException::new("Value is too small", big_value, self.get_name()));
        }
        let big_endian = resolve_big_endian(settings, buf);
        Ok(big_integer_to_bytes(big_value, length as usize, big_endian))
    }

    /// Port of `AbstractIntegerDataType.getValueClass(Settings)`, exposed under a distinct name
    /// since [`DataType::get_value_class`] already provides a default. Identifies
    /// [`Scalar`](crate::program::model::scalar::Scalar) when this data-type's length is 8 bytes
    /// or fewer, or `i128` (standing in for `BigInteger`) otherwise. A concrete `impl DataType for
    /// ...` should delegate `get_value_class` to this.
    fn integer_value_type_id(&self, _settings: &dyn Settings) -> TypeId {
        if self.get_length() > 8 {
            TypeId::of::<i128>()
        } else {
            TypeId::of::<Scalar>()
        }
    }

    /// Port of `AbstractIntegerDataType.getRepresentation(MemBuffer, Settings, int)`, exposed
    /// under a distinct name since [`DataType::get_representation`] already provides a default.
    /// A concrete `impl DataType for ...` should delegate `get_representation` to this.
    fn integer_representation(&self, buf: &dyn MemBuffer, settings: &dyn Settings, length: i32) -> String {
        let mut size = self.get_length();
        if size <= 0 {
            size = length;
            if size <= 0 {
                return "??".to_string();
            }
        }
        let mut bytes = vec![0u8; size as usize];
        if buf.get_bytes_into(&mut bytes, 0) != size {
            return "??".to_string();
        }
        let big_endian = resolve_big_endian(settings, buf);
        let value = bytes_to_big_integer(&bytes, size as usize, big_endian, true);

        let format = self.get_format_settings_definition().get_format(Some(settings));
        if format == format_settings_definition::CHAR {
            return sdi::get_char_representation(self.as_data_type(), &bytes, Some(settings));
        }

        format_integer_representation(value, settings, 8 * length, self.is_signed())
    }

    /// Port of `AbstractIntegerDataType.encodeRepresentation(String, MemBuffer, Settings, int)`,
    /// exposed under a distinct name since [`DataType::encode_representation`] already provides a
    /// default. A concrete `impl DataType for ...` should delegate `encode_representation` to
    /// this.
    fn integer_encode_representation(
        &self,
        repr: &str,
        buf: &dyn MemBuffer,
        settings: &dyn Settings,
        length: i32,
    ) -> Result<Vec<u8>, DataTypeEncodeException> {
        let format = self.get_format_settings_definition().get_format(Some(settings));
        let (radix, suffix) = match format {
            format_settings_definition::CHAR => {
                let sdi = sdi::get_string_data_instance(self.as_data_type(), buf, settings, self.get_length());
                return sdi
                    .encode_replacement_from_char_representation(repr)
                    .map_err(|e| DataTypeEncodeException::with_cause_only(repr, self.get_name(), Box::new(e)));
            }
            format_settings_definition::DECIMAL => (10u32, ""),
            format_settings_definition::BINARY => (2u32, "b"),
            format_settings_definition::OCTAL => (8u32, "o"),
            _ => (16u32, "h"),
        };
        let Some(digits) = repr.strip_suffix(suffix) else {
            return Err(DataTypeEncodeException::new(
                format!("value must have {suffix} suffix"),
                repr,
                self.get_name(),
            ));
        };
        let mut value = i128::from_str_radix(digits, radix)
            .map_err(|e| DataTypeEncodeException::with_cause_only(repr, self.get_name(), Box::new(e)))?;

        // Ghidra doesn't actually heed signedness unless the format is DECIMAL. Thus, for user
        // input, and to make this an inverse of getRepresentation, we'll adjust values between
        // SMAX and UMAX to ensure they get encoded as expected, rather than rejected. We'll still
        // accept signed values, though, since the user would rightly expect those to work, even
        // though it'll get echoed back in unsigned form.
        if format != format_settings_definition::DECIMAL && self.is_signed() {
            let umax = pow2_i128((8 * length) as u32);
            let smax = umax >> 1;
            if smax <= value && value < umax {
                value -= umax;
            }
        }
        self.integer_encode_value(&IntegerEncodeValue::BigInt(value), buf, settings, length)
    }

    /// Port of `AbstractIntegerDataType.hasStringValue(Settings)`, implementing the abstract
    /// [`ArrayStringable::has_string_value`] but exposed under a distinct name since that
    /// supertrait method has no default to override (see the module docs). A concrete `impl
    /// ArrayStringable for ...` should delegate `has_string_value` to this.
    fn integer_has_string_value(&self, settings: &dyn Settings) -> bool {
        self.get_format_settings_definition().get_format(Some(settings)) == format_settings_definition::CHAR
    }

    /// Port of `AbstractIntegerDataType.getArrayDefaultLabelPrefix(MemBuffer, Settings, int,
    /// DataTypeDisplayOptions)`, implementing the abstract
    /// [`ArrayStringable::get_array_default_label_prefix`] but exposed under a distinct name since
    /// that supertrait method has no default to override (see the module docs). A concrete `impl
    /// ArrayStringable for ...` should delegate `get_array_default_label_prefix` to this.
    fn integer_array_default_label_prefix(
        &self,
        buf: &dyn MemBuffer,
        settings: &dyn Settings,
        len: i32,
        options: &dyn DataTypeDisplayOptions,
    ) -> Option<String> {
        if !self.integer_has_string_value(settings) || !buf.is_initialized_memory() {
            return None;
        }
        let abbrev_prefix = format!("{DEFAULT_ABBREV_PREFIX}_");
        Some(StringDataInstance::new_element(self, settings, buf, len, true).get_label(&abbrev_prefix, DEFAULT_LABEL_PREFIX, DEFAULT_LABEL, options))
    }

    /// Port of `AbstractIntegerDataType.getArrayDefaultOffcutLabelPrefix(MemBuffer, Settings, int,
    /// DataTypeDisplayOptions, int)`, implementing the abstract
    /// [`ArrayStringable::get_array_default_offcut_label_prefix`] but exposed under a distinct
    /// name since that supertrait method has no default to override (see the module docs). A
    /// concrete `impl ArrayStringable for ...` should delegate
    /// `get_array_default_offcut_label_prefix` to this.
    fn integer_array_default_offcut_label_prefix(
        &self,
        buf: &dyn MemBuffer,
        settings: &dyn Settings,
        len: i32,
        options: &dyn DataTypeDisplayOptions,
        offcut_offset: i32,
    ) -> Option<String> {
        if !self.integer_has_string_value(settings) || !buf.is_initialized_memory() {
            return None;
        }
        let abbrev_prefix = format!("{DEFAULT_ABBREV_PREFIX}_");
        Some(
            StringDataInstance::new_element(self, settings, buf, len, true)
                .get_offcut_label_string(&abbrev_prefix, DEFAULT_LABEL_PREFIX, DEFAULT_LABEL, options, offcut_offset),
        )
    }

    /// Port of `AbstractIntegerDataType.isEquivalent(DataType)`, exposed under a distinct name
    /// since [`DataType::is_equivalent`] already provides a default. See the module docs for how
    /// this approximates Java's `getClass().equals(getClass())` comparison. A concrete `impl
    /// DataType for ...` should delegate `is_equivalent` to this.
    fn integer_is_equivalent(&self, dt: &dyn DataType) -> bool {
        match self.runtime_class() {
            // A concrete integer type exposes its class: compare it exactly, like Java.
            Some(class) => dt.runtime_class() == Some(class),
            None => {
                dt.is_integer_type() && dt.is_signed_integer_type() == self.is_signed() && dt.get_name() == self.get_name()
            }
        }
    }
}

/// Defines a concrete integer built-in: a struct embedding a
/// [`BuiltInBase`](super::built_in::BuiltInBase), its `dataType` singleton, and its
/// `DataType`/`DataTypeImpl`/`BuiltInDataType`/`BuiltIn`/`ArrayStringable`/
/// `AbstractIntegerDataType`/`Abstract{Signed,Unsigned}IntegerDataType` impls.
///
/// Every concrete Java `AbstractIntegerDataType` subclass differs only in the overrides listed
/// as the macro's fields:
/// - `name`: the name passed to the Java constructor.
/// - `sign`: `signed` (`extends AbstractSignedIntegerDataType`) or `unsigned`.
/// - `length`: a literal (`getLength()` returns a constant), or a `DataOrganizationImpl` getter
///   such as `get_integer_size` (`getLength()` reads the data organization, and
///   `hasLanguageDependantLength()` is `true`).
/// - `description`: `getDescription()`.
/// - `assembly_mnemonic`: a literal override of `getAssemblyMnemonic()`, or `default`.
/// - `c_declaration`: `default` (inherited `getCDeclaration()`), `none` (overridden to return
///   `null`), or one of the `C_*` constants.
/// - `c_type_declaration`: `none` (overridden to return `null`), `this_signed` /
///   `this_unsigned` (`getCTypeDeclaration(this, signed, dataOrganization, false)`; the
///   inherited `BuiltIn` behaviour is `this_unsigned`), or a literal C type name
///   (`getCTypeDeclaration(getName(), "<ctype>", false)`).
/// - `java_display_name`: the `getDecompilerDisplayName(JAVA_LANGUAGE)` override, or `default`.
/// - `opposite`: the type `getOppositeSignednessDataType()` returns.
macro_rules! integer_data_type {
    (
        $(#[$meta:meta])*
        $ty:ident {
            name: $name:literal,
            sign: $sign:ident,
            length: $len:tt,
            description: $desc:literal,
            assembly_mnemonic: $asm:tt,
            c_declaration: $cdecl:tt,
            c_type_declaration: $ctd:tt,
            java_display_name: $java:tt,
            opposite: $opp:ident,
        }
    ) => {
        $(#[$meta])*
        #[derive(Debug, Clone)]
        pub struct $ty {
            base: $crate::program::model::data::built_in::BuiltInBase,
        }

        impl $ty {
            /// Creates an instance bound to `dtm`'s data organization (Java: `new T(dtm)`; `None`
            /// is the no-argument constructor).
            pub fn new(
                dtm: Option<&dyn $crate::program::model::data::data_type_manager::DataTypeManager>,
            ) -> Self {
                Self {
                    base: $crate::program::model::data::built_in::BuiltInBase::new(None, $name, dtm),
                }
            }

            /// An instance sharing `base`'s data organization binding (Java:
            /// `T.dataType.clone(getDataTypeManager())`).
            pub fn bound_like(base: &$crate::program::model::data::built_in::BuiltInBase) -> Self {
                Self { base: base.rebound($name) }
            }

            fn c_type_declaration(
                &self,
                data_organization: Option<
                    &$crate::program::model::data::data_organization_impl::DataOrganizationImpl,
                >,
            ) -> Option<String> {
                $crate::program::model::data::abstract_integer_data_type::integer_data_type!(@ctype self, data_organization, $ctd)
            }

            fn built_in_settings_definitions(
                &self,
            ) -> Vec<Box<dyn $crate::docking::settings::settings_definition::SettingsDefinition>>
            {
                $crate::program::model::data::abstract_integer_data_type::AbstractIntegerDataType::get_built_in_settings_definitions(self)
            }

            fn decompiler_display_name(
                &self,
                language: $crate::program::model::lang::decompiler_language::DecompilerLanguage,
            ) -> String {
                $crate::program::model::data::abstract_integer_data_type::integer_data_type!(@java self, language, $java)
            }
        }

        $crate::program::model::data::built_in::built_in_singleton!($ty);
        $crate::program::model::data::built_in::impl_built_in!($ty);

        impl std::fmt::Display for $ty {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                f.write_str(&$crate::program::model::data::data_type::DataType::get_display_name(self))
            }
        }

        impl $crate::program::model::data::data_type::DataType for $ty {
            $crate::program::model::data::built_in::built_in_data_type_methods!();

            fn has_language_dependant_length(&self) -> bool {
                $crate::program::model::data::abstract_integer_data_type::integer_data_type!(@lang_dep $len)
            }
            fn get_length(&self) -> i32 {
                $crate::program::model::data::abstract_integer_data_type::integer_data_type!(@length self, $len)
            }
            fn get_description(&self) -> String {
                $desc.to_string()
            }
            fn get_mnemonic(&self, settings: &dyn $crate::docking::settings::settings::Settings) -> String {
                $crate::program::model::data::abstract_integer_data_type::AbstractIntegerDataType::integer_mnemonic(self, settings)
            }
            fn get_default_label_prefix(&self) -> Option<String> {
                Some($crate::program::model::data::abstract_integer_data_type::AbstractIntegerDataType::integer_default_label_prefix(self))
            }
            fn get_value(
                &self,
                buf: &dyn $crate::program::model::mem::MemBuffer,
                settings: &dyn $crate::docking::settings::settings::Settings,
                length: i32,
            ) -> Option<Box<dyn std::any::Any>> {
                $crate::program::model::data::abstract_integer_data_type::integer_value_as_any(
                    $crate::program::model::data::abstract_integer_data_type::AbstractIntegerDataType::integer_value(self, buf, settings, length),
                )
            }
            fn is_encodable(&self) -> bool {
                true
            }
            fn encode_value(
                &self,
                value: &dyn std::any::Any,
                buf: &dyn $crate::program::model::mem::MemBuffer,
                settings: &dyn $crate::docking::settings::settings::Settings,
                length: i32,
            ) -> Result<Vec<u8>, $crate::program::model::data::data_type_with_charset::DataTypeEncodeError> {
                $crate::program::model::data::abstract_integer_data_type::encode_any_value(self, value, buf, settings, length)
            }
            fn get_value_class(
                &self,
                settings: &dyn $crate::docking::settings::settings::Settings,
            ) -> Option<std::any::TypeId> {
                Some($crate::program::model::data::abstract_integer_data_type::AbstractIntegerDataType::integer_value_type_id(self, settings))
            }
            fn get_representation(
                &self,
                buf: &dyn $crate::program::model::mem::MemBuffer,
                settings: &dyn $crate::docking::settings::settings::Settings,
                length: i32,
            ) -> String {
                $crate::program::model::data::abstract_integer_data_type::AbstractIntegerDataType::integer_representation(self, buf, settings, length)
            }
            fn encode_representation(
                &self,
                repr: &str,
                buf: &dyn $crate::program::model::mem::MemBuffer,
                settings: &dyn $crate::docking::settings::settings::Settings,
                length: i32,
            ) -> Result<Vec<u8>, $crate::program::model::data::data_type_with_charset::DataTypeEncodeError> {
                $crate::program::model::data::abstract_integer_data_type::AbstractIntegerDataType::integer_encode_representation(self, repr, buf, settings, length)
                    .map_err(|e| $crate::program::model::data::data_type_with_charset::DataTypeEncodeError(e.to_string()))
            }
            fn is_equivalent(&self, dt: &dyn $crate::program::model::data::data_type::DataType) -> bool {
                $crate::program::model::data::abstract_integer_data_type::AbstractIntegerDataType::integer_is_equivalent(self, dt)
            }
            fn is_integer_type(&self) -> bool {
                true
            }
            fn is_signed_integer_type(&self) -> bool {
                $crate::program::model::data::abstract_integer_data_type::integer_data_type!(@signed $sign)
            }
            fn is_array_stringable_type(&self) -> bool {
                true
            }
            fn as_abstract_integer(
                &self,
            ) -> Option<&dyn $crate::program::model::data::abstract_integer_data_type::AbstractIntegerDataType> {
                Some(self)
            }
            fn as_array_stringable(
                &self,
            ) -> Option<&dyn $crate::program::model::data::array_stringable::ArrayStringable> {
                Some(self)
            }
            fn into_array_stringable(
                self: Box<Self>,
            ) -> Option<Box<dyn $crate::program::model::data::array_stringable::ArrayStringable>> {
                Some(self)
            }
        }

        impl $crate::program::model::data::array_stringable::ArrayStringable for $ty {
            fn has_string_value(&self, settings: &dyn $crate::docking::settings::settings::Settings) -> bool {
                $crate::program::model::data::abstract_integer_data_type::AbstractIntegerDataType::integer_has_string_value(self, settings)
            }
            fn get_array_default_label_prefix(
                &self,
                buf: &dyn $crate::program::model::mem::MemBuffer,
                settings: &dyn $crate::docking::settings::settings::Settings,
                len: i32,
                options: &dyn $crate::program::model::data::data_type_display_options::DataTypeDisplayOptions,
            ) -> Option<String> {
                $crate::program::model::data::abstract_integer_data_type::AbstractIntegerDataType::integer_array_default_label_prefix(self, buf, settings, len, options)
            }
            fn get_array_default_offcut_label_prefix(
                &self,
                buf: &dyn $crate::program::model::mem::MemBuffer,
                settings: &dyn $crate::docking::settings::settings::Settings,
                len: i32,
                options: &dyn $crate::program::model::data::data_type_display_options::DataTypeDisplayOptions,
                offcut_length: i32,
            ) -> Option<String> {
                $crate::program::model::data::abstract_integer_data_type::AbstractIntegerDataType::integer_array_default_offcut_label_prefix(self, buf, settings, len, options, offcut_length)
            }
        }

        impl $crate::program::model::data::abstract_integer_data_type::AbstractIntegerDataType for $ty {
            fn is_signed(&self) -> bool {
                $crate::program::model::data::abstract_integer_data_type::integer_data_type!(@signed $sign)
            }
            fn as_data_type(&self) -> &dyn $crate::program::model::data::data_type::DataType {
                self
            }
            fn get_opposite_signedness_data_type(
                &self,
            ) -> Box<dyn $crate::program::model::data::abstract_integer_data_type::AbstractIntegerDataType> {
                Box::new($opp::bound_like(&self.base))
            }
            $crate::program::model::data::abstract_integer_data_type::integer_data_type!(@asm_item $asm);
            $crate::program::model::data::abstract_integer_data_type::integer_data_type!(@cdecl_item $cdecl);
        }

        $crate::program::model::data::abstract_integer_data_type::integer_data_type!(@sign_impl $ty, $sign);
    };

    (@signed signed) => { true };
    (@signed unsigned) => { false };

    (@sign_impl $ty:ident, signed) => {
        impl $crate::program::model::data::abstract_signed_integer_data_type::AbstractSignedIntegerDataType for $ty {}
    };
    (@sign_impl $ty:ident, unsigned) => {
        impl $crate::program::model::data::abstract_unsigned_integer_data_type::AbstractUnsignedIntegerDataType for $ty {}
    };

    (@lang_dep $n:literal) => { false };
    (@lang_dep $getter:ident) => { true };

    (@length $self:ident, $n:literal) => { $n };
    (@length $self:ident, $getter:ident) => { $self.base.data_organization().$getter() };

    (@asm_item default) => {};
    (@asm_item $asm:literal) => {
        fn get_assembly_mnemonic(&self) -> String {
            $asm.to_string()
        }
    };

    (@cdecl_item default) => {};
    (@cdecl_item none) => {
        fn get_c_declaration(&self) -> Option<String> {
            None
        }
    };
    (@cdecl_item $c:ident) => {
        fn get_c_declaration(&self) -> Option<String> {
            Some($crate::program::model::data::abstract_integer_data_type::$c.to_string())
        }
    };

    (@ctype $self:ident, $org:ident, none) => {{
        let _ = $org;
        None
    }};
    (@ctype $self:ident, $org:ident, this_signed) => {
        $org.map(|org| {
            $crate::program::model::data::built_in::BuiltIn::built_in_get_c_type_declaration_for_self($self, true, org, false)
        })
    };
    (@ctype $self:ident, $org:ident, this_unsigned) => {
        $org.map(|org| {
            $crate::program::model::data::built_in::BuiltIn::built_in_get_c_type_declaration_for_self($self, false, org, false)
        })
    };
    (@ctype $self:ident, $org:ident, $ctype:literal) => {{
        let _ = $org;
        Some($crate::program::model::data::built_in::BuiltIn::get_c_type_declaration_str(
            $self,
            &$crate::program::model::data::data_type::DataType::get_name($self),
            $ctype,
            false,
        ))
    }};

    (@java $self:ident, $lang:ident, default) => {{
        let _ = $lang;
        $crate::program::model::data::data_type::DataType::get_name($self)
    }};
    (@java $self:ident, $lang:ident, $java:literal) => {
        if $lang == $crate::program::model::lang::decompiler_language::DecompilerLanguage::JavaLanguage {
            $java.to_string()
        } else {
            $crate::program::model::data::data_type::DataType::get_name($self)
        }
    };
}
pub(crate) use integer_data_type;

/// The signed fixed-size integer singletons of sizes 1 through 8 and 16, in size order (Java's
/// private `getSignedTypes()` cache).
fn signed_types() -> [Arc<dyn AbstractIntegerDataType>; 9] {
    [
        SignedByteDataType::instance().clone(),
        SignedWordDataType::instance().clone(),
        Integer3DataType::instance().clone(),
        SignedDWordDataType::instance().clone(),
        Integer5DataType::instance().clone(),
        Integer6DataType::instance().clone(),
        Integer7DataType::instance().clone(),
        SignedQWordDataType::instance().clone(),
        Integer16DataType::instance().clone(),
    ]
}

/// The unsigned fixed-size integer singletons of sizes 1 through 8 and 16, in size order (Java's
/// private `getUnsignedTypes()` cache).
fn unsigned_types() -> [Arc<dyn AbstractIntegerDataType>; 9] {
    [
        ByteDataType::instance().clone(),
        WordDataType::instance().clone(),
        UnsignedInteger3DataType::instance().clone(),
        DWordDataType::instance().clone(),
        UnsignedInteger5DataType::instance().clone(),
        UnsignedInteger6DataType::instance().clone(),
        UnsignedInteger7DataType::instance().clone(),
        QWordDataType::instance().clone(),
        UnsignedInteger16DataType::instance().clone(),
    ]
}

/// Get a signed integer data-type which corresponds to the requested size. Sizes below 1 give
/// `DefaultDataType`, 16 gives `int16`, other sizes above 8 give an array of `sbyte`. When `dtm`
/// is given, a size matching its data organization's int/short/long/long long size gives that
/// C type bound to `dtm`.
///
/// Port of `AbstractIntegerDataType.getSignedDataType(int, DataTypeManager)`.
pub fn get_signed_data_type(size: i32, dtm: Option<&dyn DataTypeManager>) -> Arc<dyn DataType> {
    if size < 1 {
        return DefaultDataType::data_type();
    }
    if size == 16 {
        return Integer16DataType::data_type();
    }
    if size > 8 {
        let array = ArrayDataType::with_element_length(Box::new(SignedByteDataType::new(None)), size, 1)
            .expect("sbyte is a fixed-length, non-factory element type");
        return Arc::new(array);
    }
    if let Some(dtm) = dtm {
        let org = dtm.get_data_organization();
        if size == org.get_integer_size() {
            return Arc::new(IntegerDataType::new(Some(dtm)));
        }
        if size == org.get_short_size() {
            return Arc::new(ShortDataType::new(Some(dtm)));
        }
        if size == org.get_long_size() {
            return Arc::new(LongDataType::new(Some(dtm)));
        }
        if size == org.get_long_long_size() {
            return Arc::new(LongLongDataType::new(Some(dtm)));
        }
    }
    signed_types()[(size - 1) as usize].clone()
}

/// Returns all built-in signed integer data-types of sizes 1 through 8, with the C types of
/// `dtm`'s data organization (int, short, long, long long) in place of the fixed-size types of
/// the same size.
///
/// Port of `AbstractIntegerDataType.getSignedDataTypes(DataTypeManager)`. As in Java, the result
/// holds nine entries (the cache includes `int16`); only indices below 8 are replaced.
pub fn get_signed_data_types(dtm: Option<&dyn DataTypeManager>) -> Vec<Arc<dyn AbstractIntegerDataType>> {
    let mut data_types = signed_types().to_vec();
    if let Some(dtm) = dtm {
        let org = dtm.get_data_organization();
        let mut place = |size: i32, dt: Arc<dyn AbstractIntegerDataType>| {
            let index = size - 1;
            if (0..8).contains(&index) {
                data_types[index as usize] = dt;
            }
        };
        place(org.get_long_long_size(), Arc::new(LongLongDataType::new(Some(dtm))));
        place(org.get_long_size(), Arc::new(LongDataType::new(Some(dtm))));
        place(org.get_short_size(), Arc::new(ShortDataType::new(Some(dtm))));
        place(org.get_integer_size(), Arc::new(IntegerDataType::new(Some(dtm))));
    }
    data_types
}

/// Get an unsigned integer data-type which corresponds to the requested size. Sizes below 1 give
/// `DefaultDataType`, 16 gives `uint16`, other sizes above 8 give the undefined data type of
/// that size. When `dtm` is given, a size matching its data organization's int/short/long/long
/// long size gives that unsigned C type bound to `dtm`.
///
/// Port of `AbstractIntegerDataType.getUnsignedDataType(int, DataTypeManager)`.
pub fn get_unsigned_data_type(size: i32, dtm: Option<&dyn DataTypeManager>) -> Arc<dyn DataType> {
    if size < 1 {
        return DefaultDataType::data_type();
    }
    if size == 16 {
        return UnsignedInteger16DataType::data_type();
    }
    if size > 8 {
        return get_undefined_data_type(size);
    }
    if let Some(dtm) = dtm {
        let org = dtm.get_data_organization();
        if size == org.get_integer_size() {
            return Arc::new(UnsignedIntegerDataType::new(Some(dtm)));
        }
        if size == org.get_short_size() {
            return Arc::new(UnsignedShortDataType::new(Some(dtm)));
        }
        if size == org.get_long_size() {
            return Arc::new(UnsignedLongDataType::new(Some(dtm)));
        }
        if size == org.get_long_long_size() {
            return Arc::new(UnsignedLongLongDataType::new(Some(dtm)));
        }
    }
    unsigned_types()[(size - 1) as usize].clone()
}

/// Returns all built-in unsigned integer data-types of sizes 1 through 8 (plus `uint16`), with the
/// unsigned C types of `dtm`'s data organization in place of the fixed-size types of the same
/// size.
///
/// Port of `AbstractIntegerDataType.getUnsignedDataTypes(DataTypeManager)`.
pub fn get_unsigned_data_types(dtm: Option<&dyn DataTypeManager>) -> Vec<Arc<dyn AbstractIntegerDataType>> {
    let mut data_types = unsigned_types().to_vec();
    if let Some(dtm) = dtm {
        let org = dtm.get_data_organization();
        let mut place = |size: i32, dt: Arc<dyn AbstractIntegerDataType>| {
            let index = size - 1;
            if (0..8).contains(&index) {
                data_types[index as usize] = dt;
            }
        };
        place(org.get_long_long_size(), Arc::new(UnsignedLongLongDataType::new(Some(dtm))));
        place(org.get_long_size(), Arc::new(UnsignedLongDataType::new(Some(dtm))));
        place(org.get_short_size(), Arc::new(UnsignedShortDataType::new(Some(dtm))));
        place(org.get_integer_size(), Arc::new(UnsignedIntegerDataType::new(Some(dtm))));
    }
    data_types
}

/// Boxes an [`IntegerValue`] as the `Object` `AbstractIntegerDataType.getValue` returns: a
/// [`Scalar`], or an `i128` standing in for `BigInteger` (matching
/// [`AbstractIntegerDataType::integer_value_type_id`]).
pub fn integer_value_as_any(value: Option<IntegerValue>) -> Option<Box<dyn std::any::Any>> {
    value.map(|value| match value {
        IntegerValue::Scalar(scalar) => Box::new(scalar) as Box<dyn std::any::Any>,
        IntegerValue::Big(big) => Box::new(big) as Box<dyn std::any::Any>,
    })
}

/// Port of `AbstractIntegerDataType.encodeValue(Object, MemBuffer, Settings, int)` over a
/// type-erased value (see [`integer_encode_value_from_any`]).
pub fn encode_any_value<T: AbstractIntegerDataType + ?Sized>(
    data_type: &T,
    value: &dyn std::any::Any,
    buf: &dyn MemBuffer,
    settings: &dyn Settings,
    length: i32,
) -> Result<Vec<u8>, crate::program::model::data::data_type_with_charset::DataTypeEncodeError> {
    let to_error = |e: DataTypeEncodeException| {
        crate::program::model::data::data_type_with_charset::DataTypeEncodeError(e.to_string())
    };
    let Some(value) = integer_encode_value_from_any(value) else {
        return Err(to_error(DataTypeEncodeException::new(
            "Unsupported value type",
            "<value>",
            data_type.get_name(),
        )));
    };
    data_type.integer_encode_value(&value, buf, settings, length).map_err(to_error)
}

/// Shared fixtures for the concrete integer built-ins' tests.
#[cfg(test)]
pub(crate) mod test_support {
    use std::collections::HashMap;

    use crate::docking::settings::settings::Settings;
    use crate::program::model::address::SpecialAddress;
    use crate::program::model::data::data_type_manager::DataTypeManager;
    use crate::program::model::data::data_organization_impl::DataOrganizationImpl;
    use crate::program::model::mem::ByteMemBufferImpl;
    use std::sync::Arc;

    /// A memory buffer over `bytes` with the given byte order.
    pub(crate) fn buf(bytes: &[u8], big_endian: bool) -> ByteMemBufferImpl {
        ByteMemBufferImpl::new(SpecialAddress::no_address(), bytes.to_vec(), big_endian)
    }

    /// Settings holding only long values, keyed by storage key.
    #[derive(Default)]
    pub(crate) struct LongSettings(HashMap<String, i64>);

    impl LongSettings {
        /// Settings with `key = value` pairs.
        pub(crate) fn of(pairs: &[(&str, i64)]) -> Self {
            Self(pairs.iter().map(|(k, v)| (k.to_string(), *v)).collect())
        }
    }

    impl Settings for LongSettings {
        fn get_long(&self, name: &str) -> Option<i64> {
            self.0.get(name).copied()
        }
        fn get_names(&self) -> Vec<String> {
            self.0.keys().cloned().collect()
        }
        fn is_empty(&self) -> bool {
            self.0.is_empty()
        }
    }

    /// A data type manager whose only behaviour is its data organization (an LP64 layout:
    /// short 2, int 4, long 8, long long 8, pointer 8).
    pub(crate) struct Lp64Manager;

    impl DataTypeManager for Lp64Manager {
        fn get_data_organization(&self) -> Arc<DataOrganizationImpl> {
            let mut org = DataOrganizationImpl::get_default_organization(None);
            org.set_long_size(8);
            org.set_pointer_size(8);
            Arc::new(org)
        }
    }
}

#[cfg(test)]
mod tests {
    use std::sync::Arc;
    use super::*;
    use crate::program::model::address::{Address, SpecialAddress};
    use crate::program::model::data::data_organization_impl::DataOrganizationImpl;
    use crate::program::model::data::data_type_display_options::DEFAULT;

    struct BytesBuffer {
        data: Vec<u8>,
        big_endian: bool,
    }

    impl MemBuffer for BytesBuffer {
        fn get_byte(&self, _offset: i32) -> Result<u8, crate::program::model::mem::MemoryAccessException> {
            unimplemented!("not exercised by these tests")
        }
        fn get_address(&self) -> Address {
            SpecialAddress::no_address()
        }

        fn is_initialized_memory(&self) -> bool {
            true
        }

        fn get_bytes(&self, buffer: &mut [u8], offset: i32) -> usize {
            if offset < 0 {
                return 0;
            }
            let o = offset as usize;
            if o >= self.data.len() {
                return 0;
            }
            let n = buffer.len().min(self.data.len() - o);
            buffer[..n].copy_from_slice(&self.data[o..o + n]);
            n
        }

        fn is_big_endian(&self) -> bool {
            self.big_endian
        }
    }

    struct NoSettings;
    impl Settings for NoSettings {}

    /// A real [`DataOrganizationImpl`] configured as this test expects.
    fn mock_data_organization() -> DataOrganizationImpl {
        let mut org = DataOrganizationImpl::get_default_organization(None);
        org.set_big_endian(false);
        org.set_pointer_size(8);
        org.set_pointer_shift(0);
        org.set_char_is_signed(true);
        org.set_char_size(1);
        org.set_wide_char_size(2);
        org.set_short_size(2);
        org.set_integer_size(4);
        org.set_long_size(8);
        org.set_long_long_size(8);
        org.set_float_size(4);
        org.set_double_size(8);
        org.set_long_double_size(8);
        org.set_absolute_max_alignment(0);
        org.set_machine_alignment(8);
        org.set_default_alignment(1);
        org.set_default_pointer_alignment(8);
        org.clear_size_alignment_map();
        org
    }

    struct MockOppositeSignedness;
    impl DataType for MockOppositeSignedness {
        fn get_name(&self) -> String {
            "uint".to_string()
        }
    }
    impl BuiltInDataType for MockOppositeSignedness {
        fn get_c_type_declaration(&self, _data_organization: Option<&DataOrganizationImpl>) -> Option<String> {
            None
        }
        fn set_default_settings(&mut self, _settings: &dyn Settings) {}
    }
    impl ArrayStringable for MockOppositeSignedness {
        fn has_string_value(&self, _settings: &dyn Settings) -> bool {
            false
        }
        fn get_array_default_label_prefix(
            &self,
            _buf: &dyn MemBuffer,
            _settings: &dyn Settings,
            _len: i32,
            _options: &dyn DataTypeDisplayOptions,
        ) -> Option<String> {
            None
        }
        fn get_array_default_offcut_label_prefix(
            &self,
            _buf: &dyn MemBuffer,
            _settings: &dyn Settings,
            _len: i32,
            _options: &dyn DataTypeDisplayOptions,
            _offcut_length: i32,
        ) -> Option<String> {
            None
        }
    }
    impl AbstractIntegerDataType for MockOppositeSignedness {
        fn is_signed(&self) -> bool {
            false
        }
        fn as_data_type(&self) -> &dyn DataType {
            self
        }
        fn get_opposite_signedness_data_type(&self) -> Box<dyn AbstractIntegerDataType> {
            unreachable!("not exercised in this smoke test")
        }
    }

    struct MockIntDataType {
        name: &'static str,
        length: i32,
        signed: bool,
    }

    impl DataType for MockIntDataType {
        fn get_name(&self) -> String {
            self.name.to_string()
        }
        fn get_length(&self) -> i32 {
            self.length
        }
        fn get_data_organization(&self) -> Arc<DataOrganizationImpl> {
            Arc::new(mock_data_organization())
        }
        fn get_default_label_prefix(&self) -> Option<String> {
            Some(self.integer_default_label_prefix())
        }
        fn get_mnemonic(&self, settings: &dyn Settings) -> String {
            self.integer_mnemonic(settings)
        }
        fn is_integer_type(&self) -> bool {
            true
        }
        fn is_signed_integer_type(&self) -> bool {
            self.signed
        }
        fn is_equivalent(&self, dt: &dyn DataType) -> bool {
            self.integer_is_equivalent(dt)
        }
    }

    impl BuiltInDataType for MockIntDataType {
        fn get_c_type_declaration(&self, _data_organization: Option<&DataOrganizationImpl>) -> Option<String> {
            None
        }
        fn set_default_settings(&mut self, _settings: &dyn Settings) {}
    }

    impl ArrayStringable for MockIntDataType {
        fn has_string_value(&self, settings: &dyn Settings) -> bool {
            self.integer_has_string_value(settings)
        }
        fn get_array_default_label_prefix(
            &self,
            buf: &dyn MemBuffer,
            settings: &dyn Settings,
            len: i32,
            options: &dyn DataTypeDisplayOptions,
        ) -> Option<String> {
            self.integer_array_default_label_prefix(buf, settings, len, options)
        }
        fn get_array_default_offcut_label_prefix(
            &self,
            buf: &dyn MemBuffer,
            settings: &dyn Settings,
            len: i32,
            options: &dyn DataTypeDisplayOptions,
            offcut_length: i32,
        ) -> Option<String> {
            self.integer_array_default_offcut_label_prefix(buf, settings, len, options, offcut_length)
        }
    }

    impl AbstractIntegerDataType for MockIntDataType {
        fn is_signed(&self) -> bool {
            self.signed
        }
        fn as_data_type(&self) -> &dyn DataType {
            self
        }
        fn get_opposite_signedness_data_type(&self) -> Box<dyn AbstractIntegerDataType> {
            Box::new(MockOppositeSignedness)
        }
    }

    #[test]
    fn usable_as_trait_object_and_computes_c_declaration_and_mnemonic() {
        let dt = MockIntDataType { name: "int", length: 4, signed: true };
        let dyn_dt: &dyn AbstractIntegerDataType = &dt;
        assert_eq!(dyn_dt.get_c_declaration(), Some(C_SIGNED_INT.to_string()));
        assert_eq!(dyn_dt.get_c_mnemonic(), C_SIGNED_INT.to_string());
        assert_eq!(dyn_dt.integer_default_label_prefix(), "INT".to_string());
        assert_eq!(dyn_dt.get_assembly_mnemonic(), "int".to_string());
    }

    #[test]
    fn unsigned_c_declaration_by_size() {
        let dt = MockIntDataType { name: "uchar", length: 1, signed: false };
        assert_eq!(dt.get_c_declaration(), Some(C_UNSIGNED_CHAR.to_string()));
        let dt = MockIntDataType { name: "ushort", length: 2, signed: false };
        assert_eq!(dt.get_c_declaration(), Some(C_UNSIGNED_SHORT.to_string()));
        // `get_long_size` and `get_long_long_size` are both 8 in `mock_data_organization()` (matching
        // a typical LP64 data organization), so a size-8 lookup matches "long" first, exactly
        // like the ported check order (char, int, short, long, long long).
        let dt = MockIntDataType { name: "ulong", length: 8, signed: false };
        assert_eq!(dt.get_c_declaration(), Some(C_UNSIGNED_LONG.to_string()));
        let dt = MockIntDataType { name: "big", length: 16, signed: false };
        assert_eq!(dt.get_c_declaration(), None);
    }

    #[test]
    fn integer_value_reads_scalar_for_small_lengths() {
        let dt = MockIntDataType { name: "int", length: 4, signed: true };
        let buf = BytesBuffer { data: vec![0xff, 0xff, 0xff, 0xff], big_endian: true };
        let settings = NoSettings;
        match dt.integer_value(&buf, &settings, -1) {
            Some(IntegerValue::Scalar(s)) => assert_eq!(s.get_value(), -1),
            other => panic!("expected Scalar, got {other:?}"),
        }
    }

    #[test]
    fn integer_value_reads_big_for_large_lengths() {
        let dt = MockIntDataType { name: "int128", length: 16, signed: true };
        let mut data = vec![0u8; 16];
        data[15] = 5;
        let buf = BytesBuffer { data, big_endian: true };
        let settings = NoSettings;
        match dt.integer_value(&buf, &settings, -1) {
            Some(IntegerValue::Big(v)) => assert_eq!(v, 5),
            other => panic!("expected Big, got {other:?}"),
        }
    }

    #[test]
    fn integer_value_none_when_length_unreadable() {
        let dt = MockIntDataType { name: "short", length: 2, signed: true };
        let buf = BytesBuffer { data: vec![0x01], big_endian: true };
        let settings = NoSettings;
        assert!(dt.integer_value(&buf, &settings, -1).is_none());
    }

    #[test]
    fn encode_value_round_trips_through_get_value() {
        let dt = MockIntDataType { name: "int", length: 4, signed: true };
        let buf = BytesBuffer { data: vec![0u8; 4], big_endian: true };
        let settings = NoSettings;
        let encoded = dt
            .integer_encode_value(&IntegerEncodeValue::I32(-2), &buf, &settings, -1)
            .expect("encodes");
        assert_eq!(encoded, vec![0xff, 0xff, 0xff, 0xfe]);
    }

    #[test]
    fn encode_value_rejects_negative_for_unsigned() {
        let dt = MockIntDataType { name: "uint", length: 4, signed: false };
        let buf = BytesBuffer { data: vec![0u8; 4], big_endian: true };
        let settings = NoSettings;
        // A direct BigInt value (unlike a fixed-width Byte/Short/Integer/Long value) is not
        // reinterpreted as unsigned by `cast_value_to_encode`, so it stays negative here.
        let err = dt
            .integer_encode_value(&IntegerEncodeValue::BigInt(-1), &buf, &settings, -1)
            .unwrap_err();
        assert!(err.message().contains("Unsigned type cannot have negative value"));
    }

    #[test]
    fn encode_value_rejects_out_of_range() {
        let dt = MockIntDataType { name: "byte", length: 1, signed: true };
        let buf = BytesBuffer { data: vec![0u8; 1], big_endian: true };
        let settings = NoSettings;
        let err = dt
            .integer_encode_value(&IntegerEncodeValue::I32(200), &buf, &settings, -1)
            .unwrap_err();
        assert!(err.message().contains("too large"));
    }

    #[test]
    fn encode_value_unsigned_negative_input_reinterpreted() {
        let dt = MockIntDataType { name: "ubyte", length: 1, signed: false };
        let buf = BytesBuffer { data: vec![0u8; 1], big_endian: true };
        let settings = NoSettings;
        // -1i8 reinterpreted as an unsigned byte is 0xFF, which fits.
        let encoded = dt
            .integer_encode_value(&IntegerEncodeValue::I8(-1), &buf, &settings, -1)
            .expect("encodes");
        assert_eq!(encoded, vec![0xff]);
    }

    #[test]
    fn cast_value_to_encode_char_uses_base36_digit_value() {
        let dt = MockIntDataType { name: "int", length: 4, signed: true };
        assert_eq!(dt.cast_value_to_encode(&IntegerEncodeValue::Char('7')).unwrap(), 7);
        assert_eq!(dt.cast_value_to_encode(&IntegerEncodeValue::Char('a')).unwrap(), 10);
        assert!(dt.cast_value_to_encode(&IntegerEncodeValue::Char('!')).is_err());
    }

    #[test]
    fn integer_representation_hex_default() {
        let dt = MockIntDataType { name: "int", length: 4, signed: true };
        let buf = BytesBuffer { data: vec![0x00, 0x00, 0x00, 0x2a], big_endian: true };
        let settings = NoSettings;
        assert_eq!(dt.integer_representation(&buf, &settings, 4), "2Ah");
    }

    #[test]
    fn integer_representation_negative_hex_uses_unsigned_pattern() {
        let dt = MockIntDataType { name: "int", length: 1, signed: true };
        let buf = BytesBuffer { data: vec![0xff], big_endian: true };
        let settings = NoSettings;
        assert_eq!(dt.integer_representation(&buf, &settings, 1), "FFh");
    }

    #[test]
    fn integer_representation_too_short_returns_placeholder() {
        let dt = MockIntDataType { name: "int", length: 4, signed: true };
        let buf = BytesBuffer { data: vec![0x00], big_endian: true };
        let settings = NoSettings;
        assert_eq!(dt.integer_representation(&buf, &settings, 4), "??");
    }

    #[test]
    fn encode_representation_round_trips_hex() {
        let dt = MockIntDataType { name: "int", length: 4, signed: true };
        let buf = BytesBuffer { data: vec![0u8; 4], big_endian: true };
        let settings = NoSettings;
        let bytes = dt.integer_encode_representation("2Ah", &buf, &settings, 4).expect("encodes");
        assert_eq!(bytes, vec![0x00, 0x00, 0x00, 0x2a]);
    }

    #[test]
    fn encode_representation_requires_suffix() {
        let dt = MockIntDataType { name: "int", length: 4, signed: true };
        let buf = BytesBuffer { data: vec![0u8; 4], big_endian: true };
        let settings = NoSettings;
        let err = dt.integer_encode_representation("2A", &buf, &settings, 4).unwrap_err();
        assert!(err.message().contains("must have"));
    }

    #[test]
    fn integer_value_type_id_matches_length() {
        let small = MockIntDataType { name: "int", length: 4, signed: true };
        assert_eq!(small.integer_value_type_id(&NoSettings), TypeId::of::<Scalar>());
        let big = MockIntDataType { name: "int128", length: 16, signed: true };
        assert_eq!(big.integer_value_type_id(&NoSettings), TypeId::of::<i128>());
    }

    #[test]
    fn integer_is_equivalent_compares_signedness_and_name() {
        let a = MockIntDataType { name: "int", length: 4, signed: true };
        let b = MockIntDataType { name: "int", length: 4, signed: true };
        let c = MockIntDataType { name: "int", length: 4, signed: false };
        assert!(a.integer_is_equivalent(&b));
        assert!(!a.integer_is_equivalent(&c));
        assert!(a.is_equivalent(&b));
    }

    #[test]
    fn integer_has_string_value_reflects_char_format() {
        let dt = MockIntDataType { name: "char", length: 1, signed: true };
        let mut longs = std::collections::HashMap::new();
        longs.insert("format".to_string(), format_settings_definition::CHAR as i64);
        struct CharSettings(std::collections::HashMap<String, i64>);
        impl Settings for CharSettings {
            fn get_long(&self, name: &str) -> Option<i64> {
                self.0.get(name).copied()
            }
        }
        let settings = CharSettings(longs);
        assert!(dt.integer_has_string_value(&settings));
        assert!(dt.has_string_value(&settings));
        assert!(!dt.integer_has_string_value(&NoSettings));
    }

    #[test]
    fn array_default_label_prefix_uses_char_view_when_has_string_value() {
        let dt = MockIntDataType { name: "char", length: 1, signed: true };
        let mut longs = std::collections::HashMap::new();
        longs.insert("format".to_string(), format_settings_definition::CHAR as i64);
        struct CharSettings(std::collections::HashMap<String, i64>);
        impl Settings for CharSettings {
            fn get_long(&self, name: &str) -> Option<i64> {
                self.0.get(name).copied()
            }
        }
        let settings = CharSettings(longs);
        let buf = BytesBuffer { data: b"Cat\0".to_vec(), big_endian: false };
        let prefix = dt.integer_array_default_label_prefix(&buf, &settings, 4, &DEFAULT);
        assert_eq!(prefix, Some("s_Cat".to_string()));
    }

    #[test]
    fn array_default_label_prefix_none_when_not_char_format() {
        let dt = MockIntDataType { name: "int", length: 4, signed: true };
        let buf = BytesBuffer { data: vec![0u8; 4], big_endian: false };
        let settings = NoSettings;
        assert_eq!(dt.integer_array_default_label_prefix(&buf, &settings, 4, &DEFAULT), None);
    }

    #[test]
    fn opposite_signedness_returns_distinct_placeholder() {
        let dt = MockIntDataType { name: "int", length: 4, signed: true };
        let opposite = dt.get_opposite_signedness_data_type();
        assert!(!opposite.is_signed());
    }

    #[test]
    fn signed_and_unsigned_factories_follow_java_size_rules() {
        use super::test_support::Lp64Manager;
        assert!(get_signed_data_type(0, None).is_default_data_type());
        assert_eq!(get_signed_data_type(1, None).get_name(), "sbyte");
        assert_eq!(get_signed_data_type(3, None).get_name(), "int3");
        assert_eq!(get_signed_data_type(8, None).get_name(), "sqword");
        assert_eq!(get_signed_data_type(16, None).get_name(), "int16");
        let big = get_signed_data_type(12, None);
        assert!(big.is_array());
        assert_eq!(big.get_length(), 12);

        assert!(get_unsigned_data_type(-1, None).is_default_data_type());
        assert_eq!(get_unsigned_data_type(2, None).get_name(), "word");
        assert_eq!(get_unsigned_data_type(16, None).get_name(), "uint16");
        let undefined = get_unsigned_data_type(10, None);
        assert!(undefined.is_array());
        assert_eq!(undefined.get_length(), 10);

        // With an LP64 manager: int 4, short 2, long 8 (checked before long long 8).
        let dtm = Lp64Manager;
        assert_eq!(get_signed_data_type(4, Some(&dtm)).get_name(), "int");
        assert_eq!(get_signed_data_type(2, Some(&dtm)).get_name(), "short");
        assert_eq!(get_signed_data_type(8, Some(&dtm)).get_name(), "long");
        assert_eq!(get_signed_data_type(3, Some(&dtm)).get_name(), "int3");
        assert_eq!(get_unsigned_data_type(8, Some(&dtm)).get_name(), "ulong");
        assert_eq!(get_unsigned_data_type(8, Some(&dtm)).get_length(), 8);
    }

    #[test]
    fn data_type_lists_substitute_c_types_by_size() {
        use super::test_support::Lp64Manager;
        let names = |v: Vec<Arc<dyn AbstractIntegerDataType>>| v.iter().map(|d| d.get_name()).collect::<Vec<_>>();
        assert_eq!(
            names(get_signed_data_types(None)),
            ["sbyte", "sword", "int3", "sdword", "int5", "int6", "int7", "sqword", "int16"]
        );
        // long long (8) is placed first, then long (8) overwrites it, then short and int.
        assert_eq!(
            names(get_signed_data_types(Some(&Lp64Manager))),
            ["sbyte", "short", "int3", "int", "int5", "int6", "int7", "long", "int16"]
        );
        assert_eq!(
            names(get_unsigned_data_types(Some(&Lp64Manager))),
            ["byte", "ushort", "uint3", "uint", "uint5", "uint6", "uint7", "ulong", "uint16"]
        );
    }
}
