//! Port of `ghidra.program.model.data.AbstractFloatDataType`.
//!
//! The Java class is abstract with instance state (shape rule R11: shared state + trait). The
//! behaviour is the [`AbstractFloatDataType`] trait, which extends [`DataType`] +
//! [`BuiltInDataType`]; its `encodedLength`/`floatFormat` fields are the two required accessors,
//! backed by fields of each concrete struct alongside its
//! [`BuiltInBase`](super::built_in::BuiltInBase). The eight concrete float types are generated by
//! [`float_data_type!`].
//!
//! Several Java methods here share a name with an already-provided default method on [`DataType`]
//! (`getMnemonic`, `getDescription`, `getValue`, `isEncodable`, `encodeValue`,
//! `getRepresentation`, `encodeRepresentation`, `getValueClass`, `getDefaultLabelPrefix`) or
//! [`BuiltInDataType`] (`getCTypeDeclaration`). Rust does not allow a subtrait to override a
//! supertrait's method by redeclaring the same name, so those overrides are exposed here under
//! distinct `float_*` names that the concrete types delegate to.
//!
//! `getDescription`'s lazy caching (a mutable `description` field) is replaced by recomputing
//! [`build_description`](AbstractFloatDataType::build_description) on each call; the value never
//! changes for an instance.
//!
//! The static factories `getFloatDataType`/`getFloatDataTypes` are [`get_float_data_type`] and
//! [`get_float_data_types`].
//!
//! `FloatFormat`/`BigFloat` are the real [`crate::pcode::floatformat`] ports; implementors
//! typically obtain their format from
//! [`get_float_format`](crate::pcode::floatformat::get_float_format)`(encoded_length)`.
//! Values wider than 8 bytes use arbitrary-precision [`num_bigint::BigInt`] encodings, so 16- and
//! 32-byte floats are not truncated.

use std::any::{Any, TypeId};
use std::collections::BTreeMap;
use std::sync::Arc;

use crate::docking::settings::settings::Settings;
use crate::docking::settings::settings_definition::SettingsDefinition;
use crate::pcode::floatformat::{BigFloat, FloatFormat};
use crate::pcode::utils::utils;
use crate::program::model::data::built_in_data_type::BuiltInDataType;
use crate::program::model::data::data_organization_impl::DataOrganizationImpl;
use crate::program::model::data::data_type::DataType;
use crate::program::model::data::data_type_encode_exception::DataTypeEncodeException;
use crate::program::model::data::data_type_manager::DataTypeManager;
use crate::program::model::data::data_type_with_charset::DataTypeEncodeError;
use crate::program::model::data::default_data_type::DefaultDataType;
use crate::program::model::data::double_data_type::DoubleDataType;
use crate::program::model::data::float10_data_type::Float10DataType;
use crate::program::model::data::float16_data_type::Float16DataType;
use crate::program::model::data::float2_data_type::Float2DataType;
use crate::program::model::data::float4_data_type::Float4DataType;
use crate::program::model::data::float8_data_type::Float8DataType;
use crate::program::model::data::float_data_type::FloatDataType;
use crate::program::model::data::long_double_data_type::LongDoubleDataType;
use crate::program::model::data::undefined::get_undefined_data_type;
use crate::program::model::mem::MemBuffer;

/// Value accepted by [`AbstractFloatDataType::encode_float_value`], standing in for the
/// `Object value` parameter of `AbstractFloatDataType.encodeValue`, documented in the Java source
/// as "expected as Number or BigFloat object".
pub enum FloatEncodeValue {
    /// A plain numeric value, used for the standard 4- and 8-byte IEEE 754 encodings.
    Number(f64),
    /// An arbitrary-precision float value, required for non-standard lengths.
    Big(BigFloat),
}

fn describe_value(value: &FloatEncodeValue) -> String {
    match value {
        FloatEncodeValue::Number(v) => v.to_string(),
        FloatEncodeValue::Big(v) => v.to_string(),
    }
}

/// Provides a definition of a Float within a program.
///
/// Port of `ghidra.program.model.data.AbstractFloatDataType`. See the module-level documentation
/// for the conventions used to resolve name clashes with [`DataType`]/[`BuiltInDataType`] and for
/// what was intentionally left unported.
pub trait AbstractFloatDataType: DataType + BuiltInDataType {
    /// The floating encoding length as a number of 8-bit bytes.
    ///
    /// Port of the private final `encodedLength` field.
    fn encoded_length(&self) -> i32;

    /// The float format established for [`encoded_length`](Self::encoded_length), or `None` if
    /// that length has no supported format -- mirroring the Java constructor swallowing
    /// `UnsupportedFloatFormatException` and leaving `floatFormat` as `null`.
    ///
    /// Port of the private final `floatFormat` field.
    fn float_format(&self) -> Option<&FloatFormat>;

    /// Port of the protected final `AbstractFloatDataType.buildIEEE754StandardDescription()`.
    fn build_ieee754_standard_description(&self) -> String {
        let encoded_length = self.encoded_length();
        format!(
            "IEEE 754 floating-point type ({}-bit / {}-byte format, aligned-length is {}-bytes)",
            encoded_length * 8,
            encoded_length,
            self.get_aligned_length(),
        )
    }

    /// Port of the protected `AbstractFloatDataType.buildDescription()`, overridable by more
    /// specific float types.
    fn build_description(&self) -> String {
        self.build_ieee754_standard_description()
    }

    /// Port of the final `AbstractFloatDataType.getMnemonic(Settings)`, exposed under a distinct
    /// name since [`DataType::get_mnemonic`] already provides a default. A concrete
    /// `impl DataType for ...` should delegate `get_mnemonic` to this.
    fn float_mnemonic(&self, settings: &dyn Settings) -> String {
        let _ = settings;
        self.get_name()
    }

    /// Port of the final `AbstractFloatDataType.getDescription()`, exposed under a distinct name
    /// since [`DataType::get_description`] already provides a default. Recomputed on each call
    /// rather than cached (see the module-level documentation). A concrete `impl DataType for
    /// ...` should delegate `get_description` to this.
    fn float_description(&self) -> String {
        self.build_description()
    }

    /// Port of `AbstractFloatDataType.getValueClass(Settings)`, exposed under a distinct name
    /// since [`DataType::get_value_class`] already provides a default. Always identifies
    /// [`BigFloat`] (Java `BigFloat.class`). A concrete `impl DataType for ...` should delegate
    /// `get_value_class` to this.
    fn float_value_type_id(&self, settings: &dyn Settings) -> TypeId {
        let _ = settings;
        TypeId::of::<BigFloat>()
    }

    /// Port of the final `AbstractFloatDataType.getValue(MemBuffer, Settings, int)`, exposed
    /// under a distinct name since [`DataType::get_value`] already provides a default. The
    /// `length` parameter is ignored, matching the Java method (which always uses
    /// [`encoded_length`](Self::encoded_length)). A concrete `impl DataType for ...` should
    /// delegate `get_value` to this.
    fn float_value(
        &self,
        buf: &dyn MemBuffer,
        _settings: &dyn Settings,
        _length: i32,
    ) -> Option<BigFloat> {
        let len = self.encoded_length() as usize;
        let format = self.float_format()?;
        let mut bytes = vec![0u8; len];
        if buf.get_bytes_into(&mut bytes, 0) as usize != len {
            return None;
        }
        if len <= 8 {
            let value = utils::bytes_to_long(&bytes, len, buf.is_big_endian());
            Some(format.decode_big_float(value))
        } else {
            let value = utils::bytes_to_big_int(&bytes, len, buf.is_big_endian(), false);
            Some(format.decode_big_float_big(&value))
        }
    }

    /// Port of `AbstractFloatDataType.isEncodable()`, exposed under a distinct name since
    /// [`DataType::is_encodable`] already provides a default. A concrete `impl DataType for ...`
    /// should delegate `is_encodable` to this.
    fn is_float_encodable(&self) -> bool {
        self.float_format().is_some()
    }

    /// Port of the final `AbstractFloatDataType.encodeValue(Object, MemBuffer, Settings, int)`,
    /// exposed under a distinct name since [`DataType::encode_value`] already provides a default
    /// with a different `value` type (`&dyn Any` vs. [`FloatEncodeValue`]). A concrete
    /// `impl DataType for ...` should delegate `encode_value` to this.
    fn encode_float_value(
        &self,
        value: &FloatEncodeValue,
        buf: &dyn MemBuffer,
        _settings: &dyn Settings,
        _length: i32,
    ) -> Result<Vec<u8>, DataTypeEncodeException> {
        let len = self.encoded_length() as usize;
        let Some(format) = self.float_format() else {
            return Err(DataTypeEncodeException::new(
                format!("Unsupported float format ({} bytes)", len),
                describe_value(value),
                self.get_name(),
            ));
        };
        match (len, value) {
            (4, FloatEncodeValue::Number(v)) | (8, FloatEncodeValue::Number(v)) => {
                let encoding = format.get_encoding(*v);
                Ok(utils::long_to_bytes(encoding, len, buf.is_big_endian()))
            }
            (_, FloatEncodeValue::Big(v)) => {
                let encoding = format.get_encoding_big(v);
                Ok(utils::big_int_to_bytes(&encoding, len, buf.is_big_endian()))
            }
            (_, FloatEncodeValue::Number(_)) => Err(DataTypeEncodeException::new(
                "non-standard float length requires BigFloat type",
                describe_value(value),
                self.get_name(),
            )),
        }
    }

    /// Port of `AbstractFloatDataType.getRepresentation(MemBuffer, Settings, int)`, exposed under
    /// a distinct name since [`DataType::get_representation`] already provides a default. A
    /// concrete `impl DataType for ...` should delegate `get_representation` to this.
    fn float_representation(&self, buf: &dyn MemBuffer, settings: &dyn Settings, length: i32) -> String {
        match self.float_value(buf, settings, length) {
            None => "??".to_string(),
            Some(value) => match self.float_format() {
                Some(format) => format.to_decimal_string_compact(&value, true),
                None => value.to_string(),
            },
        }
    }

    /// Port of `AbstractFloatDataType.encodeRepresentation(String, MemBuffer, Settings, int)`,
    /// exposed under a distinct name since [`DataType::encode_representation`] already provides a
    /// default. A concrete `impl DataType for ...` should delegate `encode_representation` to
    /// this.
    fn encode_float_representation(
        &self,
        repr: &str,
        buf: &dyn MemBuffer,
        settings: &dyn Settings,
        length: i32,
    ) -> Result<Vec<u8>, DataTypeEncodeException> {
        let len = self.encoded_length();
        let Some(format) = self.float_format() else {
            return Err(DataTypeEncodeException::new(
                format!("Unsupported float format ({} bytes)", len),
                repr,
                self.get_name(),
            ));
        };
        if length == 8 || length == 4 {
            let value: f64 = repr.parse().map_err(|e: std::num::ParseFloatError| {
                DataTypeEncodeException::with_cause_only(repr, self.get_name(), Box::new(e))
            })?;
            return self.encode_float_value(&FloatEncodeValue::Number(value), buf, settings, length);
        }
        let bf = format.get_big_float_str(repr).map_err(|e| {
            DataTypeEncodeException::with_cause_only(repr, self.get_name(), Box::new(e))
        })?;
        // Java calls floatFormat.round(bf) here and discards the returned BigDecimal.
        let _ = format.round(&bf);
        self.encode_float_value(&FloatEncodeValue::Big(bf), buf, settings, length)
    }

    /// Port of the protected `AbstractFloatDataType.getBuiltInSettingsDefinitions()`. Always
    /// empty, matching the Java `SETTINGS_DEFS = {}` (with its `// TODO: Add
    /// FloatDisplayPrecisionSettingsDefinition` left unaddressed upstream).
    fn get_built_in_settings_definitions(&self) -> Vec<Box<dyn SettingsDefinition>> {
        Vec::new()
    }

    /// Port of `AbstractFloatDataType.getDefaultLabelPrefix()`, exposed under a distinct name
    /// since [`DataType::get_default_label_prefix`] already provides a default. A concrete
    /// `impl DataType for ...` should delegate `get_default_label_prefix` to this.
    fn float_default_label_prefix(&self) -> String {
        self.get_name().to_uppercase()
    }

    /// Port of `AbstractFloatDataType.getCTypeDeclaration(DataOrganization)`, exposed under a
    /// distinct name since [`BuiltInDataType::get_c_type_declaration`] already declares this
    /// method (with no default). A concrete `impl BuiltInDataType for ...` should delegate
    /// `get_c_type_declaration` to this.
    fn float_c_type_declaration(&self, data_organization: Option<&DataOrganizationImpl>) -> Option<String> {
        let _ = data_organization;
        if self.has_language_dependant_length() {
            None
        } else {
            Some(self.get_name())
        }
    }
}

/// Converts the `Object value` accepted by `AbstractFloatDataType.encodeValue` ("expected as
/// Number or BigFloat object") into a [`FloatEncodeValue`]: a [`FloatEncodeValue`] itself, a
/// [`BigFloat`], or a Rust number (`f64`, `f32`, `i8`..`i64`, standing in for `Number`).
pub fn float_encode_value_from_any(value: &dyn Any) -> Option<FloatEncodeValue> {
    if let Some(v) = value.downcast_ref::<FloatEncodeValue>() {
        return Some(match v {
            FloatEncodeValue::Number(n) => FloatEncodeValue::Number(*n),
            FloatEncodeValue::Big(b) => FloatEncodeValue::Big(b.clone()),
        });
    }
    if let Some(v) = value.downcast_ref::<BigFloat>() {
        return Some(FloatEncodeValue::Big(v.clone()));
    }
    let number = if let Some(v) = value.downcast_ref::<f64>() {
        *v
    } else if let Some(v) = value.downcast_ref::<f32>() {
        *v as f64
    } else if let Some(v) = value.downcast_ref::<i64>() {
        *v as f64
    } else if let Some(v) = value.downcast_ref::<i32>() {
        *v as f64
    } else if let Some(v) = value.downcast_ref::<i16>() {
        *v as f64
    } else if let Some(v) = value.downcast_ref::<i8>() {
        *v as f64
    } else {
        return None;
    };
    Some(FloatEncodeValue::Number(number))
}

/// Port of `AbstractFloatDataType.encodeValue(Object, MemBuffer, Settings, int)` over a
/// type-erased value (see [`float_encode_value_from_any`]).
pub fn encode_any_float_value<T: AbstractFloatDataType + ?Sized>(
    data_type: &T,
    value: &dyn Any,
    buf: &dyn MemBuffer,
    settings: &dyn Settings,
    length: i32,
) -> Result<Vec<u8>, DataTypeEncodeError> {
    let to_error = |e: DataTypeEncodeException| DataTypeEncodeError(e.to_string());
    let Some(value) = float_encode_value_from_any(value) else {
        let len = data_type.encoded_length();
        let message = if data_type.float_format().is_none() {
            format!("Unsupported float format ({len} bytes)")
        } else {
            "non-standard float length requires BigFloat type".to_string()
        };
        return Err(to_error(DataTypeEncodeException::new(message, "<value>", data_type.get_name())));
    };
    data_type.encode_float_value(&value, buf, settings, length).map_err(to_error)
}

/// Defines a concrete float built-in: a struct embedding a
/// [`BuiltInBase`](super::built_in::BuiltInBase) plus the `encodedLength`/`floatFormat` fields of
/// `AbstractFloatDataType` (the shared state of that R11 base), its `dataType` singleton, and its
/// `DataType`/`DataTypeImpl`/`BuiltInDataType`/`BuiltIn`/[`AbstractFloatDataType`] impls.
///
/// Fields: `name`; `length`, a literal or the `DataOrganizationImpl` getter giving the size of
/// the compiler-defined C type (which also makes `hasLanguageDependantLength()` true);
/// `description_prefix`, prepended to the IEEE 754 description by the compiler-defined types'
/// `buildDescription()` overrides (`""` otherwise); and `c_type_declaration`, `default` or the
/// literal C type of a `getCTypeDeclaration(getName(), "<ctype>", false)` override.
macro_rules! float_data_type {
    (
        $(#[$meta:meta])*
        $ty:ident {
            name: $name:literal,
            length: $len:tt,
            description_prefix: $prefix:literal,
            c_type_declaration: $ctd:tt,
        }
    ) => {
        $(#[$meta])*
        #[derive(Debug, Clone)]
        pub struct $ty {
            base: $crate::program::model::data::built_in::BuiltInBase,
            encoded_length: i32,
            float_format: Option<&'static $crate::pcode::floatformat::FloatFormat>,
        }

        impl $ty {
            /// Creates an instance for `dtm` (Java: `new T(dtm)`; `None` is the no-argument
            /// constructor). A float format is established when one exists for the length.
            pub fn new(
                dtm: Option<&dyn $crate::program::model::data::data_type_manager::DataTypeManager>,
            ) -> Self {
                let base = $crate::program::model::data::built_in::BuiltInBase::new(None, $name, dtm);
                let encoded_length: i32 =
                    $crate::program::model::data::abstract_float_data_type::float_data_type!(@length base, $len);
                if encoded_length < 1 {
                    panic!("Invalid encoded length: {encoded_length}");
                }
                Self {
                    base,
                    encoded_length,
                    float_format: $crate::pcode::floatformat::get_float_format(encoded_length).ok(),
                }
            }

            fn c_type_declaration(
                &self,
                data_organization: Option<
                    &$crate::program::model::data::data_organization_impl::DataOrganizationImpl,
                >,
            ) -> Option<String> {
                $crate::program::model::data::abstract_float_data_type::float_data_type!(@ctype self, data_organization, $ctd)
            }

            fn built_in_settings_definitions(
                &self,
            ) -> Vec<Box<dyn $crate::docking::settings::settings_definition::SettingsDefinition>>
            {
                $crate::program::model::data::abstract_float_data_type::AbstractFloatDataType::get_built_in_settings_definitions(self)
            }

            fn decompiler_display_name(
                &self,
                _language: $crate::program::model::lang::decompiler_language::DecompilerLanguage,
            ) -> String {
                self.base.name().to_string()
            }
        }

        $crate::program::model::data::built_in::built_in_singleton!($ty);
        $crate::program::model::data::built_in::impl_built_in!($ty);

        impl std::fmt::Display for $ty {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                f.write_str(self.base.name())
            }
        }

        impl $crate::program::model::data::abstract_float_data_type::AbstractFloatDataType for $ty {
            fn encoded_length(&self) -> i32 {
                self.encoded_length
            }
            fn float_format(&self) -> Option<&$crate::pcode::floatformat::FloatFormat> {
                self.float_format
            }
            fn build_description(&self) -> String {
                format!(
                    "{}{}",
                    $prefix,
                    $crate::program::model::data::abstract_float_data_type::AbstractFloatDataType::build_ieee754_standard_description(self)
                )
            }
        }

        impl $crate::program::model::data::data_type::DataType for $ty {
            $crate::program::model::data::built_in::built_in_data_type_methods!();

            fn has_language_dependant_length(&self) -> bool {
                $crate::program::model::data::abstract_float_data_type::float_data_type!(@lang_dep $len)
            }
            fn get_length(&self) -> i32 {
                self.encoded_length
            }
            fn get_description(&self) -> String {
                $crate::program::model::data::abstract_float_data_type::AbstractFloatDataType::float_description(self)
            }
            fn get_mnemonic(&self, settings: &dyn $crate::docking::settings::settings::Settings) -> String {
                $crate::program::model::data::abstract_float_data_type::AbstractFloatDataType::float_mnemonic(self, settings)
            }
            fn get_default_label_prefix(&self) -> Option<String> {
                Some($crate::program::model::data::abstract_float_data_type::AbstractFloatDataType::float_default_label_prefix(self))
            }
            fn get_value(
                &self,
                buf: &dyn $crate::program::model::mem::MemBuffer,
                settings: &dyn $crate::docking::settings::settings::Settings,
                length: i32,
            ) -> Option<Box<dyn std::any::Any>> {
                $crate::program::model::data::abstract_float_data_type::AbstractFloatDataType::float_value(self, buf, settings, length)
                    .map(|value| Box::new(value) as Box<dyn std::any::Any>)
            }
            fn get_value_class(
                &self,
                settings: &dyn $crate::docking::settings::settings::Settings,
            ) -> Option<std::any::TypeId> {
                Some($crate::program::model::data::abstract_float_data_type::AbstractFloatDataType::float_value_type_id(self, settings))
            }
            fn is_encodable(&self) -> bool {
                $crate::program::model::data::abstract_float_data_type::AbstractFloatDataType::is_float_encodable(self)
            }
            fn encode_value(
                &self,
                value: &dyn std::any::Any,
                buf: &dyn $crate::program::model::mem::MemBuffer,
                settings: &dyn $crate::docking::settings::settings::Settings,
                length: i32,
            ) -> Result<Vec<u8>, $crate::program::model::data::data_type_with_charset::DataTypeEncodeError> {
                $crate::program::model::data::abstract_float_data_type::encode_any_float_value(self, value, buf, settings, length)
            }
            fn get_representation(
                &self,
                buf: &dyn $crate::program::model::mem::MemBuffer,
                settings: &dyn $crate::docking::settings::settings::Settings,
                length: i32,
            ) -> String {
                $crate::program::model::data::abstract_float_data_type::AbstractFloatDataType::float_representation(self, buf, settings, length)
            }
            fn encode_representation(
                &self,
                repr: &str,
                buf: &dyn $crate::program::model::mem::MemBuffer,
                settings: &dyn $crate::docking::settings::settings::Settings,
                length: i32,
            ) -> Result<Vec<u8>, $crate::program::model::data::data_type_with_charset::DataTypeEncodeError> {
                $crate::program::model::data::abstract_float_data_type::AbstractFloatDataType::encode_float_representation(self, repr, buf, settings, length)
                    .map_err(|e| $crate::program::model::data::data_type_with_charset::DataTypeEncodeError(e.to_string()))
            }
            fn is_equivalent(&self, dt: &dyn $crate::program::model::data::data_type::DataType) -> bool {
                $crate::program::model::data::built_in::same_class(self, dt)
            }
            fn is_floating_point(&self) -> bool {
                true
            }
        }
    };

    (@lang_dep $n:literal) => { false };
    (@lang_dep $getter:ident) => { true };

    (@length $base:ident, $n:literal) => { $n };
    (@length $base:ident, $getter:ident) => { $base.data_organization().$getter() };

    (@ctype $self:ident, $org:ident, default) => {
        $crate::program::model::data::abstract_float_data_type::AbstractFloatDataType::float_c_type_declaration($self, $org)
    };
    (@ctype $self:ident, $org:ident, $ctype:literal) => {{
        let _ = $org;
        Some($crate::program::model::data::built_in::BuiltIn::get_c_type_declaration_str(
            $self,
            &$crate::program::model::data::data_type::DataType::get_name($self),
            $ctype,
            false,
        ))
    }};
}
pub(crate) use float_data_type;

/// The fixed-size float singletons keyed by length (Java's private `getFloatTypes()` cache).
fn float_types() -> BTreeMap<i32, Arc<dyn AbstractFloatDataType>> {
    let types: [Arc<dyn AbstractFloatDataType>; 5] = [
        Float2DataType::instance().clone(),
        Float4DataType::instance().clone(),
        Float8DataType::instance().clone(),
        Float10DataType::instance().clone(),
        Float16DataType::instance().clone(),
    ];
    types.into_iter().map(|dt| (dt.get_length(), dt)).collect()
}

/// Get a Float data-type instance with a length no larger than `raw_format_byte_size`, matching
/// the compiler-defined float/double/long double of `dtm`'s data organization when it applies,
/// otherwise the fixed-size float of that size, otherwise the undefined type of that size.
/// Sizes below 1 give `DefaultDataType`.
///
/// Port of `AbstractFloatDataType.getFloatDataType(int, DataTypeManager)`.
pub fn get_float_data_type(raw_format_byte_size: i32, dtm: Option<&dyn DataTypeManager>) -> Arc<dyn DataType> {
    if raw_format_byte_size < 1 {
        return DefaultDataType::data_type();
    }
    if let Some(dtm) = dtm {
        let org = dtm.get_data_organization();
        if raw_format_byte_size == org.get_float_size() {
            return Arc::new(FloatDataType::new(Some(dtm)));
        }
        if raw_format_byte_size == org.get_double_size() {
            return Arc::new(DoubleDataType::new(Some(dtm)));
        }
        if raw_format_byte_size == org.get_long_double_size() {
            return Arc::new(LongDoubleDataType::new(Some(dtm)));
        }
    }
    match float_types().remove(&raw_format_byte_size) {
        Some(dt) => dt,
        None => get_undefined_data_type(raw_format_byte_size),
    }
}

/// Returns all built-in float data-types, ordered by length: with a `dtm`, its float, double and
/// long double (bound to `dtm`) take precedence over the fixed-size type of the same length, and
/// the fixed-size types are bound to `dtm` too.
///
/// Port of `AbstractFloatDataType.getFloatDataTypes(DataTypeManager)`.
pub fn get_float_data_types(dtm: Option<&dyn DataTypeManager>) -> Vec<Arc<dyn AbstractFloatDataType>> {
    let float_map = float_types();
    let Some(dtm) = dtm else {
        return float_map.into_values().collect();
    };
    let org = dtm.get_data_organization();
    let mut new_float_map: BTreeMap<i32, Arc<dyn AbstractFloatDataType>> = BTreeMap::new();
    new_float_map.insert(org.get_float_size(), Arc::new(FloatDataType::new(Some(dtm))));
    new_float_map
        .entry(org.get_double_size())
        .or_insert_with(|| Arc::new(DoubleDataType::new(Some(dtm))));
    new_float_map
        .entry(org.get_long_double_size())
        .or_insert_with(|| Arc::new(LongDoubleDataType::new(Some(dtm))));
    for size in float_map.keys() {
        new_float_map.entry(*size).or_insert_with(|| fixed_float_for(*size, dtm));
    }
    new_float_map.into_values().collect()
}

/// `floatMap.get(size).clone(dtm)` for the fixed-size float types.
fn fixed_float_for(size: i32, dtm: &dyn DataTypeManager) -> Arc<dyn AbstractFloatDataType> {
    match size {
        2 => Arc::new(Float2DataType::new(Some(dtm))),
        4 => Arc::new(Float4DataType::new(Some(dtm))),
        8 => Arc::new(Float8DataType::new(Some(dtm))),
        10 => Arc::new(Float10DataType::new(Some(dtm))),
        _ => Arc::new(Float16DataType::new(Some(dtm))),
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use crate::pcode::floatformat::get_float_format;
    use crate::program::model::address::{Address, SpecialAddress};

    struct TestFloat {
        length: i32,
        format: Option<&'static FloatFormat>,
    }

    impl TestFloat {
        /// Mirrors the Java constructor: the format for `length`, or none if unsupported.
        fn new(length: i32) -> Self {
            Self { length, format: get_float_format(length).ok() }
        }
    }

    impl DataType for TestFloat {
        fn get_name(&self) -> String {
            format!("float{}", self.length)
        }
        fn get_length(&self) -> i32 {
            self.encoded_length()
        }
    }

    impl BuiltInDataType for TestFloat {
        fn get_c_type_declaration(&self, data_organization: Option<&DataOrganizationImpl>) -> Option<String> {
            self.float_c_type_declaration(data_organization)
        }
        fn set_default_settings(&mut self, _settings: &dyn Settings) {}
    }

    impl AbstractFloatDataType for TestFloat {
        fn encoded_length(&self) -> i32 {
            self.length
        }
        fn float_format(&self) -> Option<&FloatFormat> {
            self.format
        }
    }

    struct TestSettings;
    impl Settings for TestSettings {}

    struct FixedMemBuffer(Vec<u8>, bool);
    impl MemBuffer for FixedMemBuffer {
        fn get_byte(&self, offset: i32) -> Result<u8, crate::program::model::mem::MemoryAccessException> {
            Ok(self.0[offset as usize])
        }
        fn get_address(&self) -> Address {
            SpecialAddress::no_address()
        }
        fn get_bytes(&self, buffer: &mut [u8], _offset: i32) -> usize {
            let n = buffer.len().min(self.0.len());
            buffer[..n].copy_from_slice(&self.0[..n]);
            n
        }
        fn is_big_endian(&self) -> bool {
            self.1
        }
    }

    fn be(bytes: Vec<u8>) -> FixedMemBuffer {
        FixedMemBuffer(bytes, true)
    }

    #[test]
    fn usable_as_trait_object() {
        let dt = TestFloat::new(4);
        let dyn_dt: &dyn AbstractFloatDataType = &dt;
        assert_eq!(dyn_dt.encoded_length(), 4);
        assert!(dyn_dt.build_ieee754_standard_description().contains("32-bit"));
        assert!(dyn_dt.build_ieee754_standard_description().contains("4-byte"));
        assert_eq!(dyn_dt.float_default_label_prefix(), "FLOAT4");
        assert_eq!(dyn_dt.float_c_type_declaration(None), Some("float4".to_string()));
        assert!(dyn_dt.get_built_in_settings_definitions().is_empty());
    }

    #[test]
    fn build_description_defaults_to_ieee754_standard_description() {
        let dt = TestFloat::new(8);
        assert_eq!(dt.build_description(), dt.build_ieee754_standard_description());
        assert_eq!(dt.float_description(), dt.build_description());
    }

    #[test]
    fn float_mnemonic_and_value_type_id() {
        let dt = TestFloat::new(4);
        assert_eq!(dt.float_mnemonic(&TestSettings), "float4");
        assert_eq!(dt.float_value_type_id(&TestSettings), TypeId::of::<BigFloat>());
    }

    #[test]
    fn float_value_decodes_short_length_via_bytes_to_long() {
        let dt = TestFloat::new(4);
        // 42.0f = 0x42280000
        let value = dt.float_value(&be(vec![0x42, 0x28, 0, 0]), &TestSettings, -1).expect("decodes");
        assert_eq!(value, get_float_format(4).unwrap().get_big_float_f32(42.0));
        // little-endian buffer
        let le = FixedMemBuffer(vec![0, 0, 0x28, 0x42], false);
        assert_eq!(dt.float_value(&le, &TestSettings, -1), Some(value));
    }

    #[test]
    fn float_value_decodes_long_length_via_big_integer() {
        let dt = TestFloat::new(10);
        // x87 80-bit 7.0 = 0x4001 e000000000000000
        let bytes = vec![0x40, 0x01, 0xe0, 0, 0, 0, 0, 0, 0, 0];
        let value = dt.float_value(&be(bytes), &TestSettings, -1).expect("decodes");
        assert_eq!(value, get_float_format(10).unwrap().get_big_float_f64(7.0));
    }

    #[test]
    fn float_value_and_is_encodable_are_none_false_without_format() {
        let dt = TestFloat::new(3);
        assert!(dt.float_format().is_none());
        assert!(dt.float_value(&be(vec![0, 0, 1]), &TestSettings, -1).is_none());
        assert!(!dt.is_float_encodable());
        assert!(TestFloat::new(4).is_float_encodable());
    }

    #[test]
    fn encode_float_value_number_path_for_standard_length() {
        let dt = TestFloat::new(4);
        let bytes = dt
            .encode_float_value(&FloatEncodeValue::Number(3.0), &be(Vec::new()), &TestSettings, 4)
            .expect("encodes");
        assert_eq!(bytes, vec![0x40, 0x40, 0, 0]);
        let dt8 = TestFloat::new(8);
        let bytes = dt8
            .encode_float_value(&FloatEncodeValue::Number(-0.5), &FixedMemBuffer(Vec::new(), false), &TestSettings, 8)
            .expect("encodes");
        assert_eq!(bytes, (-0.5f64).to_bits().to_le_bytes().to_vec());
    }

    #[test]
    fn encode_float_value_big_path_for_nonstandard_length() {
        let dt = TestFloat::new(10);
        let five = get_float_format(10).unwrap().get_big_float_f64(5.0);
        let bytes = dt
            .encode_float_value(&FloatEncodeValue::Big(five), &be(Vec::new()), &TestSettings, 10)
            .expect("encodes");
        // 5.0 = 0x4001 a000000000000000
        assert_eq!(bytes, vec![0x40, 0x01, 0xa0, 0, 0, 0, 0, 0, 0, 0]);
    }

    #[test]
    fn encode_float_value_big_path_for_32_byte_float() {
        let dt = TestFloat::new(32);
        let ff = get_float_format(32).unwrap();
        let neg_one = ff.get_big_float_f64(-1.0);
        let bytes = dt
            .encode_float_value(&FloatEncodeValue::Big(neg_one.clone()), &be(Vec::new()), &TestSettings, 32)
            .expect("encodes");
        assert_eq!(bytes.len(), 32);
        // sign bit + exponent 262143 (0x3ffff) in the top 20 bits
        assert_eq!(&bytes[..3], &[0xbf, 0xff, 0xf0]);
        assert!(bytes[3..].iter().all(|&b| b == 0));
        assert_eq!(dt.float_value(&be(bytes), &TestSettings, -1), Some(neg_one));
    }

    #[test]
    fn encode_float_value_rejects_number_for_nonstandard_length() {
        let dt = TestFloat::new(10);
        let err = dt
            .encode_float_value(&FloatEncodeValue::Number(1.0), &be(Vec::new()), &TestSettings, 10)
            .unwrap_err();
        assert!(err.message().contains("non-standard float length"));
    }

    #[test]
    fn encode_float_value_errors_when_format_unsupported() {
        let dt = TestFloat::new(3);
        let err = dt
            .encode_float_value(&FloatEncodeValue::Number(1.0), &be(Vec::new()), &TestSettings, 3)
            .unwrap_err();
        assert!(err.message().contains("Unsupported float format"));
    }

    #[test]
    fn float_representation_renders_decoded_value_or_placeholder() {
        let dt = TestFloat::new(4);
        assert_eq!(dt.float_representation(&be(vec![0x41, 0x10, 0, 0]), &TestSettings, -1), "9.0");
        // 0.1f is shown compactly
        assert_eq!(dt.float_representation(&be(vec![0x3d, 0xcc, 0xcc, 0xcd]), &TestSettings, -1), "0.1");
        assert_eq!(dt.float_representation(&be(vec![0x7f, 0x80, 0, 0]), &TestSettings, -1), "+Infinity");
        assert_eq!(dt.float_representation(&be(vec![0, 0]), &TestSettings, -1), "??");
    }

    #[test]
    fn encode_float_representation_parses_decimal_for_standard_length() {
        let dt = TestFloat::new(4);
        let bytes = dt.encode_float_representation("3", &be(Vec::new()), &TestSettings, 4).expect("encodes");
        assert_eq!(bytes, vec![0x40, 0x40, 0, 0]);
    }

    #[test]
    fn encode_float_representation_uses_big_float_for_nonstandard_length() {
        let dt = TestFloat::new(10);
        let bytes = dt.encode_float_representation("7", &be(Vec::new()), &TestSettings, 10).expect("encodes");
        assert_eq!(bytes, vec![0x40, 0x01, 0xe0, 0, 0, 0, 0, 0, 0, 0]);
        let bytes = dt.encode_float_representation("-Infinity", &be(Vec::new()), &TestSettings, 10).expect("encodes");
        assert_eq!(bytes, vec![0xff, 0xff, 0, 0, 0, 0, 0, 0, 0, 0]);
    }

    #[test]
    fn encode_float_representation_rejects_invalid_decimal() {
        let dt = TestFloat::new(4);
        assert!(dt.encode_float_representation("not-a-number", &be(Vec::new()), &TestSettings, 4).is_err());
        let dt10 = TestFloat::new(10);
        assert!(dt10.encode_float_representation("1.2.3", &be(Vec::new()), &TestSettings, 10).is_err());
    }

    #[test]
    fn float_factories_follow_java_size_rules() {
        use crate::program::model::data::abstract_integer_data_type::test_support::Lp64Manager;
        assert!(get_float_data_type(0, None).is_default_data_type());
        assert_eq!(get_float_data_type(4, None).get_name(), "float4");
        assert_eq!(get_float_data_type(10, None).get_name(), "float10");
        assert_eq!(get_float_data_type(3, None).get_name(), "undefined3");
        // Default organization: float 4, double 8, long double 8.
        let dtm = Lp64Manager;
        assert_eq!(get_float_data_type(4, Some(&dtm)).get_name(), "float");
        assert_eq!(get_float_data_type(8, Some(&dtm)).get_name(), "double");
        assert_eq!(get_float_data_type(16, Some(&dtm)).get_name(), "float16");

        let names = |v: Vec<Arc<dyn AbstractFloatDataType>>| v.iter().map(|d| d.get_name()).collect::<Vec<_>>();
        assert_eq!(names(get_float_data_types(None)), ["float2", "float4", "float8", "float10", "float16"]);
        // long double shares double's size, so only float and double replace fixed types.
        assert_eq!(names(get_float_data_types(Some(&dtm))), ["float2", "float", "double", "float10", "float16"]);
    }

    #[test]
    fn encode_any_float_value_accepts_numbers_and_big_floats() {
        let dt = TestFloat::new(4);
        assert_eq!(encode_any_float_value(&dt, &3.0f32, &be(Vec::new()), &TestSettings, 4).unwrap(), vec![0x40, 0x40, 0, 0]);
        assert_eq!(encode_any_float_value(&dt, &3i32, &be(Vec::new()), &TestSettings, 4).unwrap(), vec![0x40, 0x40, 0, 0]);
        assert!(encode_any_float_value(&dt, &"3", &be(Vec::new()), &TestSettings, 4).is_err());
    }
}
