//! Port of `ghidra.program.model.data.CharDataType` and its subclasses `SignedCharDataType` and
//! `UnsignedCharDataType`.
//!
//! `CharDataType` is a concrete `AbstractIntegerDataType` that also has a charset. Its two
//! subclasses only change the name, signedness, description, label prefix and C declaration, so
//! all three are generated by [`char_data_type!`] from those differences; each is its own struct
//! (Java code tells them apart by class).
//!
//! A char value (`getValue`) is Java's `Character`, a UTF-16 code unit: a `u16` here.

use crate::docking::settings::format_settings_definition::FormatSettingsDefinition;
use crate::docking::settings::settings::Settings;
use crate::docking::settings::settings_definition::SettingsDefinition;
use crate::program::model::data::charset_settings_definition::CharsetSettingsDefinition;
use crate::program::model::data::data_type_mnemonic_settings_definition::DataTypeMnemonicSettingsDefinition;
use crate::program::model::data::endian_settings_definition::EndianSettingsDefinition;
use crate::program::model::data::padding_settings_definition::PaddingSettingsDefinition;
use crate::program::model::data::render_unicode_settings_definition::RenderUnicodeSettingsDefinition;
use crate::program::model::data::string_data_instance::DEFAULT_CHARSET_NAME;
use crate::program::model::data::translation_settings_definition::TranslationSettingsDefinition;
use crate::program::model::mem::MemBuffer;
use crate::util::charset::charset_info_manager::{UTF16, UTF32};
use crate::util::string_format::StringFormat;

/// `CharDataType.CHAR_SETTINGS_DEFS` (`wide == false`) or `WIDE_UTF_CHAR_SETTINGS_DEFS`.
pub(crate) fn char_settings_definitions(wide: bool) -> Vec<Box<dyn SettingsDefinition>> {
    let mut defs: Vec<Box<dyn SettingsDefinition>> = vec![
        Box::new(FormatSettingsDefinition::DEF_CHAR),
        Box::new(PaddingSettingsDefinition::DEF),
        Box::new(EndianSettingsDefinition::DEF),
        Box::new(DataTypeMnemonicSettingsDefinition::DEF),
    ];
    if !wide {
        defs.push(Box::new(CharsetSettingsDefinition::charset().clone()));
    }
    defs.push(Box::new(RenderUnicodeSettingsDefinition::DEF));
    defs.push(Box::new(TranslationSettingsDefinition::translation().clone()));
    defs
}

/// `CharDataType.getValue`: a `Character` (UTF-16 unit) read from a 1, 2 or 4 byte char.
pub(crate) fn char_value(buf: &dyn MemBuffer, size: i32) -> Option<u16> {
    if size == 1 {
        return buf.get_unsigned_byte(0).ok().map(|b| b as u16);
    }
    let val: i32 = match size {
        2 => buf.get_short(0).ok()? as i32,
        4 => buf.get_int(0).ok()?,
        _ => -1,
    };
    (0..=0xFFFF).contains(&val).then_some(val as u16)
}

/// `CharDataType.getCharsetName(Settings)`.
pub(crate) fn char_charset_name(length: i32, settings: &dyn Settings) -> String {
    match length {
        1 => CharsetSettingsDefinition::charset().get_charset(settings, DEFAULT_CHARSET_NAME),
        2 => UTF16.to_string(),
        4 => UTF32.to_string(),
        _ => DEFAULT_CHARSET_NAME.to_string(),
    }
}

/// `CharDataType.getDefaultLabelPrefix(MemBuffer, Settings, int, DataTypeDisplayOptions)`.
pub(crate) fn char_label_prefix(prefix: &str, buf: &dyn MemBuffer) -> String {
    let mut s = format!("{prefix}_");
    match buf.get_signed_byte(0) {
        Ok(b) if b > 31 => s.push(b as u8 as char),
        Ok(b) => {
            s.push_str(&StringFormat::hex_byte_string(b));
            s.push('h');
        }
        Err(_) => s.push_str("??"),
    }
    s
}

/// Defines one of the char data types. `signed` is `org` (signedness from the data
/// organization, `CharDataType`), `true` or `false`; `c_type_declaration` is `none` (`char`, a
/// standard C primitive) or `named` (`getCTypeDeclaration(getName(), getCDeclaration(), false)`).
macro_rules! char_data_type {
    (
        $(#[$meta:meta])*
        $ty:ident {
            name: $name:literal,
            signed: $signed:tt,
            description: $desc:literal,
            label_prefix: $prefix:literal,
            c_declaration: $cdecl:literal,
            c_type_declaration: $ctd:ident,
        }
    ) => {
        $(#[$meta])*
        #[derive(Debug, Clone)]
        pub struct $ty {
            base: $crate::program::model::data::built_in::BuiltInBase,
        }

        impl $ty {
            /// Creates an instance bound to `dtm`'s data organization (Java: `new T(dtm)`; `None`
            /// is the no-argument constructor).
            pub fn new(dtm: Option<&dyn $crate::program::model::data::data_type_manager::DataTypeManager>) -> Self {
                Self { base: $crate::program::model::data::built_in::BuiltInBase::new(None, $name, dtm) }
            }

            /// An instance sharing `base`'s data organization binding (Java:
            /// `T.dataType.clone(getDataTypeManager())`).
            pub fn bound_like(base: &$crate::program::model::data::built_in::BuiltInBase) -> Self {
                Self { base: base.rebound($name) }
            }

            fn c_type_declaration(
                &self,
                _data_organization: Option<&$crate::program::model::data::data_organization_impl::DataOrganizationImpl>,
            ) -> Option<String> {
                $crate::program::model::data::char_data_type::char_data_type!(@ctd self, $ctd)
            }

            fn built_in_settings_definitions(&self) -> Vec<Box<dyn $crate::docking::settings::settings_definition::SettingsDefinition>> {
                $crate::program::model::data::char_data_type::char_settings_definitions(
                    $crate::program::model::data::data_type::DataType::get_length(self) != 1,
                )
            }

            fn decompiler_display_name(&self, _language: $crate::program::model::lang::decompiler_language::DecompilerLanguage) -> String {
                $name.to_string()
            }
        }

        $crate::program::model::data::built_in::built_in_singleton!($ty);
        $crate::program::model::data::built_in::impl_built_in!($ty);

        impl std::fmt::Display for $ty {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                f.write_str(&$crate::program::model::data::data_type::DataType::get_display_name(self))
            }
        }

        impl $crate::program::model::data::data_type::DataType for $ty {
            $crate::program::model::data::built_in::built_in_data_type_methods!();

            fn has_language_dependant_length(&self) -> bool {
                true
            }
            fn get_length(&self) -> i32 {
                self.base.data_organization().get_char_size()
            }
            fn get_description(&self) -> String {
                $desc.to_string()
            }
            fn get_mnemonic(&self, settings: &dyn $crate::docking::settings::settings::Settings) -> String {
                $crate::program::model::data::abstract_integer_data_type::AbstractIntegerDataType::integer_mnemonic(self, settings)
            }
            fn get_default_label_prefix(&self) -> Option<String> {
                Some($prefix.to_string())
            }
            fn get_default_label_prefix_for_data(
                &self,
                buf: &dyn $crate::program::model::mem::MemBuffer,
                _settings: &dyn $crate::docking::settings::settings::Settings,
                _len: i32,
                _options: &dyn $crate::program::model::data::data_type_display_options::DataTypeDisplayOptions,
            ) -> Option<String> {
                Some($crate::program::model::data::char_data_type::char_label_prefix($prefix, buf))
            }
            fn get_value(
                &self,
                buf: &dyn $crate::program::model::mem::MemBuffer,
                _settings: &dyn $crate::docking::settings::settings::Settings,
                _length: i32,
            ) -> Option<Box<dyn std::any::Any>> {
                $crate::program::model::data::char_data_type::char_value(buf, self.get_length())
                    .map(|c| Box::new(c) as Box<dyn std::any::Any>)
            }
            fn is_encodable(&self) -> bool {
                true
            }
            fn encode_value(
                &self,
                value: &dyn std::any::Any,
                buf: &dyn $crate::program::model::mem::MemBuffer,
                settings: &dyn $crate::docking::settings::settings::Settings,
                _length: i32,
            ) -> Result<Vec<u8>, $crate::program::model::data::data_type_with_charset::DataTypeEncodeError> {
                $crate::program::model::data::data_type_with_charset::encode_character_value_from_any(self, value, buf, settings)
            }
            fn get_value_class(&self, _settings: &dyn $crate::docking::settings::settings::Settings) -> Option<std::any::TypeId> {
                Some(std::any::TypeId::of::<u16>())
            }
            fn get_representation(
                &self,
                buf: &dyn $crate::program::model::mem::MemBuffer,
                settings: &dyn $crate::docking::settings::settings::Settings,
                length: i32,
            ) -> String {
                $crate::program::model::data::abstract_integer_data_type::AbstractIntegerDataType::integer_representation(self, buf, settings, length)
            }
            fn encode_representation(
                &self,
                repr: &str,
                buf: &dyn $crate::program::model::mem::MemBuffer,
                settings: &dyn $crate::docking::settings::settings::Settings,
                _length: i32,
            ) -> Result<Vec<u8>, $crate::program::model::data::data_type_with_charset::DataTypeEncodeError> {
                $crate::program::model::data::data_type_with_charset::DataTypeWithCharset::encode_character_representation(self, repr, buf, settings)
            }
            fn is_equivalent(&self, dt: &dyn $crate::program::model::data::data_type::DataType) -> bool {
                $crate::program::model::data::abstract_integer_data_type::AbstractIntegerDataType::integer_is_equivalent(self, dt)
            }
            fn is_integer_type(&self) -> bool {
                true
            }
            fn is_signed_integer_type(&self) -> bool {
                $crate::program::model::data::abstract_integer_data_type::AbstractIntegerDataType::is_signed(self)
            }
            fn is_array_stringable_type(&self) -> bool {
                true
            }
            fn as_abstract_integer(&self) -> Option<&dyn $crate::program::model::data::abstract_integer_data_type::AbstractIntegerDataType> {
                Some(self)
            }
            fn as_array_stringable(&self) -> Option<&dyn $crate::program::model::data::array_stringable::ArrayStringable> {
                Some(self)
            }
            fn into_array_stringable(self: Box<Self>) -> Option<Box<dyn $crate::program::model::data::array_stringable::ArrayStringable>> {
                Some(self)
            }
            fn as_data_type_with_charset(&self) -> Option<&dyn $crate::program::model::data::data_type_with_charset::DataTypeWithCharset> {
                Some(self)
            }
        }

        impl $crate::program::model::data::array_stringable::ArrayStringable for $ty {
            fn has_string_value(&self, settings: &dyn $crate::docking::settings::settings::Settings) -> bool {
                $crate::program::model::data::abstract_integer_data_type::AbstractIntegerDataType::integer_has_string_value(self, settings)
            }
            fn get_array_default_label_prefix(
                &self,
                buf: &dyn $crate::program::model::mem::MemBuffer,
                settings: &dyn $crate::docking::settings::settings::Settings,
                len: i32,
                options: &dyn $crate::program::model::data::data_type_display_options::DataTypeDisplayOptions,
            ) -> Option<String> {
                $crate::program::model::data::abstract_integer_data_type::AbstractIntegerDataType::integer_array_default_label_prefix(self, buf, settings, len, options)
            }
            fn get_array_default_offcut_label_prefix(
                &self,
                buf: &dyn $crate::program::model::mem::MemBuffer,
                settings: &dyn $crate::docking::settings::settings::Settings,
                len: i32,
                options: &dyn $crate::program::model::data::data_type_display_options::DataTypeDisplayOptions,
                offcut_length: i32,
            ) -> Option<String> {
                $crate::program::model::data::abstract_integer_data_type::AbstractIntegerDataType::integer_array_default_offcut_label_prefix(self, buf, settings, len, options, offcut_length)
            }
        }

        impl $crate::program::model::data::data_type_with_charset::DataTypeWithCharset for $ty {
            fn get_charset_name(&self, settings: &dyn $crate::docking::settings::settings::Settings) -> String {
                $crate::program::model::data::char_data_type::char_charset_name(
                    $crate::program::model::data::data_type::DataType::get_length(self),
                    settings,
                )
            }
        }

        impl $crate::program::model::data::abstract_integer_data_type::AbstractIntegerDataType for $ty {
            fn is_signed(&self) -> bool {
                $crate::program::model::data::char_data_type::char_data_type!(@signed self, $signed)
            }
            fn as_data_type(&self) -> &dyn $crate::program::model::data::data_type::DataType {
                self
            }
            fn get_format_settings_definition(&self) -> $crate::docking::settings::format_settings_definition::FormatSettingsDefinition {
                $crate::docking::settings::format_settings_definition::FormatSettingsDefinition::DEF_CHAR
            }
            fn get_built_in_settings_definitions(&self) -> Vec<Box<dyn $crate::docking::settings::settings_definition::SettingsDefinition>> {
                self.built_in_settings_definitions()
            }
            fn get_c_declaration(&self) -> Option<String> {
                Some($cdecl.to_string())
            }
            fn get_opposite_signedness_data_type(&self) -> Box<dyn $crate::program::model::data::abstract_integer_data_type::AbstractIntegerDataType> {
                if $crate::program::model::data::abstract_integer_data_type::AbstractIntegerDataType::is_signed(self) {
                    Box::new($crate::program::model::data::unsigned_char_data_type::UnsignedCharDataType::bound_like(&self.base))
                } else {
                    Box::new($crate::program::model::data::signed_char_data_type::SignedCharDataType::bound_like(&self.base))
                }
            }
        }
    };

    (@signed $self:ident, org) => {
        $crate::program::model::data::data_type::DataType::get_data_organization($self).is_signed_char()
    };
    (@signed $self:ident, true) => { true };
    (@signed $self:ident, false) => { false };

    (@ctd $self:ident, none) => { None };
    (@ctd $self:ident, named) => {
        Some($crate::program::model::data::built_in::BuiltIn::get_c_type_declaration_str(
            $self,
            &$crate::program::model::data::data_type::DataType::get_name($self),
            &$crate::program::model::data::abstract_integer_data_type::AbstractIntegerDataType::get_c_declaration($self).unwrap_or_default(),
            false,
        ))
    };
}
pub(crate) use char_data_type;

char_data_type! {
    /// Provides a definition of a primitive char in a program. The size and signed-ness of this
    /// type is determined by the data organization of the associated data type manager.
    ///
    /// Port of `ghidra.program.model.data.CharDataType`.
    CharDataType {
        name: "char",
        signed: org,
        description: "Character",
        label_prefix: "CHAR",
        c_declaration: "char",
        c_type_declaration: none,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Arc;
    use crate::program::model::data::abstract_integer_data_type::AbstractIntegerDataType;
    use crate::program::model::data::array_stringable::ArrayStringable;
    use crate::program::model::data::built_in_data_type::BuiltInDataType;
    use crate::program::model::data::data_organization_impl::DataOrganizationImpl;
    use crate::program::model::data::data_type::DataType;
    use crate::program::model::data::data_type_display_options::DEFAULT;
    use crate::program::model::data::data_type_manager::DataTypeManager;
    use crate::program::model::data::data_type_with_charset::DataTypeWithCharset;
    use crate::program::model::data::string_data_instance::test_support::{mb, SettingsBuilder};

    /// A manager whose data organization has the given char size and signedness.
    struct CharOrg(i32, bool);
    impl DataTypeManager for CharOrg {
        fn get_data_organization(&self) -> Arc<DataOrganizationImpl> {
            let mut org = DataOrganizationImpl::get_default_organization(None);
            org.set_char_size(self.0);
            org.set_char_is_signed(self.1);
            Arc::new(org)
        }
    }

    #[test]
    fn java_constants() {
        let dt = CharDataType::instance();
        assert_eq!(dt.get_name(), "char");
        assert_eq!(dt.get_description(), "Character");
        assert_eq!(dt.get_default_label_prefix().as_deref(), Some("CHAR"));
        assert_eq!(dt.get_c_declaration().as_deref(), Some("char"));
        assert!(dt.has_language_dependant_length());
        assert_eq!(dt.get_length(), 1);
        assert_eq!(dt.get_c_type_declaration(Some(&dt.get_data_organization())), None);
        // Mutability + DEF_CHAR, PADDING, ENDIAN, MNEMONIC, CHARSET, RENDER, TRANSLATION.
        assert_eq!(dt.get_settings_definitions().len(), 8);
        assert_eq!(dt.get_format_settings_definition().get_format(None), crate::docking::settings::format_settings_definition::CHAR);
        assert!(dt.has_string_value(&SettingsBuilder::new()));
    }

    #[test]
    fn signedness_and_length_follow_the_data_organization() {
        let signed = CharDataType::new(Some(&CharOrg(1, true)));
        assert!(signed.is_signed());
        assert_eq!(signed.get_opposite_signedness_data_type().get_name(), "uchar");
        let unsigned = CharDataType::new(Some(&CharOrg(1, false)));
        assert!(!unsigned.is_signed());
        assert_eq!(unsigned.get_opposite_signedness_data_type().get_name(), "schar");
        let wide = CharDataType::new(Some(&CharOrg(2, false)));
        assert_eq!(wide.get_length(), 2);
        assert_eq!(wide.get_charset_name(&SettingsBuilder::new()), "UTF-16");
        // WIDE_UTF_CHAR_SETTINGS_DEFS has no charset.
        assert_eq!(wide.get_settings_definitions().len(), 7);
        let wide4 = CharDataType::new(Some(&CharOrg(4, false)));
        assert_eq!(wide4.get_charset_name(&SettingsBuilder::new()), "UTF-32");
    }

    #[test]
    fn value_and_label_prefix() {
        let dt = CharDataType::new(None);
        let s = SettingsBuilder::new();
        let v = dt.get_value(&mb(false, b"A"), &s, 1).unwrap();
        assert_eq!(*v.downcast_ref::<u16>().unwrap(), b'A' as u16);
        assert_eq!(dt.get_value(&mb(false, &[0xFF]), &s, 1).unwrap().downcast_ref::<u16>(), Some(&0xFF));
        assert!(dt.get_value(&mb(false, &[]), &s, 1).is_none());
        let wide = CharDataType::new(Some(&CharOrg(2, false)));
        let v = wide.get_value(&mb(false, &[0x34, 0x12]), &s, 2).unwrap();
        assert_eq!(*v.downcast_ref::<u16>().unwrap(), 0x1234);
        assert!(wide.get_value(&mb(false, &[0x34, 0x82]), &s, 2).is_none());
        assert_eq!(dt.get_default_label_prefix_for_data(&mb(false, b"A"), &s, 1, &DEFAULT).as_deref(), Some("CHAR_A"));
        assert_eq!(dt.get_default_label_prefix_for_data(&mb(false, &[0x0A]), &s, 1, &DEFAULT).as_deref(), Some("CHAR_0Ah"));
        assert_eq!(dt.get_default_label_prefix_for_data(&mb(false, &[0x80]), &s, 1, &DEFAULT).as_deref(), Some("CHAR_80h"));
        assert_eq!(dt.get_default_label_prefix_for_data(&mb(false, &[]), &s, 1, &DEFAULT).as_deref(), Some("CHAR_??"));
    }

    #[test]
    fn char_array_string_and_labels() {
        let dt = CharDataType::new(None);
        let s = SettingsBuilder::new();
        let buf = mb(false, b"hi\0x");
        assert_eq!(dt.get_array_string(&buf, &s, 4).as_deref(), Some("hi"));
        assert_eq!(dt.get_array_default_label_prefix(&buf, &s, 4, &DEFAULT).as_deref(), Some("s_hi"));
        assert_eq!(dt.get_array_default_offcut_label_prefix(&buf, &s, 4, &DEFAULT, 1).as_deref(), Some("s_i"));
    }

    #[test]
    fn encode_value() {
        let dt = CharDataType::new(None);
        assert_eq!(dt.encode_value(&'a', &mb(false, &[]), &SettingsBuilder::new(), -1).unwrap(), b"a");
        assert!(dt.encode_value(&5i32, &mb(false, &[]), &SettingsBuilder::new(), -1).is_err());
    }
}
