//! Port of `ghidra.program.model.data.Undefined`.
//!
//! `Undefined` is an abstract class with no instance state (shape rule R12), so it is a trait.
//! Its Java superclass `BuiltIn` is modeled by [`BuiltIn`](super::built_in::BuiltIn) plus the
//! shared [`BuiltInBase`](super::built_in::BuiltInBase) state each concrete
//! `Undefined1DataType` .. `Undefined8DataType` embeds; those eight classes are generated by
//! [`undefined_data_type!`].
//!
//! The static members are free functions: [`get_undefined_data_type`],
//! [`get_undefined_data_types`], [`is_undefined`] and [`is_undefined_array`]. The `instanceof`
//! checks the latter two need are the [`DataType::is_default_data_type`]/
//! [`DataType::is_undefined_type`] flags and the [`DataType::into_array`] downcast; both free
//! functions take an owned `Box<dyn DataType>` since the array case consumes the value.

use std::sync::Arc;

use crate::program::model::data::array_data_type::ArrayDataType;
use crate::program::model::data::built_in_data_type::BuiltInDataType;
use crate::program::model::data::data_type::DataType;
use crate::program::model::data::default_data_type::DefaultDataType;
use crate::program::model::data::undefined1_data_type::Undefined1DataType;
use crate::program::model::data::undefined2_data_type::Undefined2DataType;
use crate::program::model::data::undefined3_data_type::Undefined3DataType;
use crate::program::model::data::undefined4_data_type::Undefined4DataType;
use crate::program::model::data::undefined5_data_type::Undefined5DataType;
use crate::program::model::data::undefined6_data_type::Undefined6DataType;
use crate::program::model::data::undefined7_data_type::Undefined7DataType;
use crate::program::model::data::undefined8_data_type::Undefined8DataType;

/// Port of `ghidra.program.model.data.Undefined`: the base of the undefined (raw byte) data
/// types of sizes 1 through 8.
pub trait Undefined: DataType + BuiltInDataType {}

/// The shared `dataType` singletons of `Undefined1DataType` .. `Undefined8DataType`, in size
/// order (Java's private `getUndefinedTypes()` cache).
fn undefined_types() -> [Arc<dyn DataType>; 8] {
    [
        Undefined1DataType::data_type(),
        Undefined2DataType::data_type(),
        Undefined3DataType::data_type(),
        Undefined4DataType::data_type(),
        Undefined5DataType::data_type(),
        Undefined6DataType::data_type(),
        Undefined7DataType::data_type(),
        Undefined8DataType::data_type(),
    ]
}

/// Get an Undefined data-type instance of the requested size: the `DefaultDataType` for sizes
/// below 1, `UndefinedNDataType` for sizes 1 through 8, and an array of `undefined1` for larger
/// sizes.
///
/// Port of `Undefined.getUndefinedDataType(int)`.
pub fn get_undefined_data_type(size: i32) -> Arc<dyn DataType> {
    if size < 1 {
        return DefaultDataType::data_type();
    }
    if size > 8 {
        let array = ArrayDataType::with_element_length(Box::new(Undefined1DataType::new(None)), size, 1)
            .expect("undefined1 is a fixed-length, non-factory element type");
        return Arc::new(array);
    }
    undefined_types()[(size - 1) as usize].clone()
}

/// [`get_undefined_data_type`] as an owned handle, for callers that hold data types as
/// `Box<dyn DataType>`. The undefined built-ins and `DefaultDataType` carry no state beyond their
/// identity, so a fresh instance is equivalent to the shared one.
pub fn new_undefined_data_type(size: i32) -> Box<dyn DataType> {
    match size {
        s if s < 1 => DefaultDataType::boxed(),
        1 => Box::new(Undefined1DataType::new(None)),
        2 => Box::new(Undefined2DataType::new(None)),
        3 => Box::new(Undefined3DataType::new(None)),
        4 => Box::new(Undefined4DataType::new(None)),
        5 => Box::new(Undefined5DataType::new(None)),
        6 => Box::new(Undefined6DataType::new(None)),
        7 => Box::new(Undefined7DataType::new(None)),
        8 => Box::new(Undefined8DataType::new(None)),
        _ => Box::new(
            ArrayDataType::with_element_length(Box::new(Undefined1DataType::new(None)), size, 1)
                .expect("undefined1 is a fixed-length, non-factory element type"),
        ),
    }
}

/// Get the undefined data-types of sizes 1 through 8, in size order.
///
/// Port of `Undefined.getUndefinedDataTypes()`.
pub fn get_undefined_data_types() -> Vec<Arc<dyn DataType>> {
    undefined_types().to_vec()
}

/// Determine if the specified dataType is either a `DefaultDataType`, an [`Undefined`]
/// data-type, or an Array of Undefined data-types.
///
/// Port of `Undefined.isUndefined(DataType)`.
pub fn is_undefined(data_type: Box<dyn DataType>) -> bool {
    if data_type.is_default_data_type() {
        return true;
    }
    if data_type.is_undefined_type() {
        return true;
    }
    is_undefined_array(data_type)
}

/// Determine if the specified dataType is an undefined array used to represent large undefined
/// data.
///
/// Port of `Undefined.isUndefinedArray(DataType)`.
pub fn is_undefined_array(data_type: Box<dyn DataType>) -> bool {
    match data_type.into_array() {
        Some(array) => {
            let base_type = array.get_data_type();
            base_type.is_undefined_type() || base_type.is_default_data_type()
        }
        None => false,
    }
}

/// Defines a concrete `UndefinedNDataType`: a struct embedding a
/// [`BuiltInBase`](super::built_in::BuiltInBase), its `dataType` singleton, and its
/// `DataType`/`DataTypeImpl`/`BuiltInDataType`/`BuiltIn`/[`Undefined`] impls.
///
/// The eight Java classes differ only in `name`, `length`, `description`, the bit length of the
/// `Scalar` `getValue` returns, and the private `getValue(MemBuffer)` that reads the raw value
/// (`value: |buf| expr`, evaluating to `Result<i64, MemoryAccessException>`).
/// `getRepresentation` renders that value with `Long.toHexString`, zero-padded to two hex digits
/// per byte, with an `h` suffix; `getMnemonic` is the name.
macro_rules! undefined_data_type {
    (
        $(#[$meta:meta])*
        $ty:ident {
            name: $name:literal,
            length: $len:literal,
            description: $desc:literal,
            bits: $bits:literal,
            value: |$buf:ident| $value:expr,
        }
    ) => {
        $(#[$meta])*
        #[derive(Debug, Clone)]
        pub struct $ty {
            base: $crate::program::model::data::built_in::BuiltInBase,
        }

        impl $ty {
            /// Creates an instance bound to `dtm`'s data organization (Java: `new T(dtm)`; `None`
            /// is the no-argument constructor).
            pub fn new(
                dtm: Option<&dyn $crate::program::model::data::data_type_manager::DataTypeManager>,
            ) -> Self {
                Self {
                    base: $crate::program::model::data::built_in::BuiltInBase::new(
                        Some($crate::program::model::data::category_path::ROOT.clone()),
                        $name,
                        dtm,
                    ),
                }
            }

            /// Port of the private `getValue(MemBuffer)`: the raw value of this type's bytes.
            fn raw_value(
                $buf: &dyn $crate::program::model::mem::MemBuffer,
            ) -> Result<i64, $crate::program::model::mem::MemoryAccessException> {
                $value
            }

            fn c_type_declaration(
                &self,
                data_organization: Option<
                    &$crate::program::model::data::data_organization_impl::DataOrganizationImpl,
                >,
            ) -> Option<String> {
                $crate::program::model::data::built_in::BuiltIn::built_in_get_c_type_declaration(
                    self,
                    data_organization,
                )
            }

            fn built_in_settings_definitions(
                &self,
            ) -> Vec<Box<dyn $crate::docking::settings::settings_definition::SettingsDefinition>>
            {
                Vec::new()
            }

            fn decompiler_display_name(
                &self,
                _language: $crate::program::model::lang::decompiler_language::DecompilerLanguage,
            ) -> String {
                self.base.name().to_string()
            }
        }

        $crate::program::model::data::built_in::built_in_singleton!($ty);
        $crate::program::model::data::built_in::impl_built_in!($ty);

        impl std::fmt::Display for $ty {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                f.write_str(self.base.name())
            }
        }

        impl $crate::program::model::data::data_type::DataType for $ty {
            $crate::program::model::data::built_in::built_in_data_type_methods!();

            fn get_length(&self) -> i32 {
                $len
            }
            fn get_description(&self) -> String {
                $desc.to_string()
            }
            fn get_mnemonic(&self, _settings: &dyn $crate::docking::settings::settings::Settings) -> String {
                self.base.name().to_string()
            }
            fn get_representation(
                &self,
                buf: &dyn $crate::program::model::mem::MemBuffer,
                _settings: &dyn $crate::docking::settings::settings::Settings,
                _length: i32,
            ) -> String {
                match Self::raw_value(buf) {
                    Ok(value) => $crate::util::StringFormat::pad_it(
                        &format!("{:X}", value as u64),
                        2 * $len,
                        'h',
                        true,
                    ),
                    Err(_) => "??".to_string(),
                }
            }
            fn get_value(
                &self,
                buf: &dyn $crate::program::model::mem::MemBuffer,
                _settings: &dyn $crate::docking::settings::settings::Settings,
                _length: i32,
            ) -> Option<Box<dyn std::any::Any>> {
                Self::raw_value(buf)
                    .ok()
                    .map(|value| {
                        Box::new($crate::program::model::scalar::Scalar::new($bits, value))
                            as Box<dyn std::any::Any>
                    })
            }
            fn is_equivalent(&self, dt: &dyn $crate::program::model::data::data_type::DataType) -> bool {
                $crate::program::model::data::built_in::same_class(self, dt)
            }
            fn is_undefined_type(&self) -> bool {
                true
            }
        }

        impl $crate::program::model::data::undefined::Undefined for $ty {}
    };
}
pub(crate) use undefined_data_type;

#[cfg(test)]
mod tests {
    use super::*;
    use crate::docking::settings::settings::Settings;
    use crate::program::model::data::array::Array;
    use crate::program::model::data::data_organization_impl::DataOrganizationImpl;

    struct MockSettings;
    impl Settings for MockSettings {}

    struct MockUndefined1;
    impl DataType for MockUndefined1 {
        fn get_length(&self) -> i32 {
            1
        }
        fn is_undefined_type(&self) -> bool {
            true
        }
    }
    impl BuiltInDataType for MockUndefined1 {
        fn get_c_type_declaration(
            &self,
            _data_organization: Option<&DataOrganizationImpl>,
        ) -> Option<String> {
            None
        }
        fn set_default_settings(&mut self, _settings: &dyn Settings) {}
    }
    impl Undefined for MockUndefined1 {}

    struct MockIntDataType;
    impl DataType for MockIntDataType {
        fn get_length(&self) -> i32 {
            4
        }
    }

    struct MockArrayOf {
        element_len: i32,
        make_element: fn() -> Box<dyn DataType>,
    }
    impl DataType for MockArrayOf {
        fn is_array(&self) -> bool {
            true
        }
        fn into_array(
            self: Box<Self>,
        ) -> Option<Box<dyn crate::program::model::data::array::Array>> {
            Some(self)
        }
    }
    impl Array for MockArrayOf {
        fn get_num_elements(&self) -> i32 {
            4
        }
        fn get_element_length(&self) -> i32 {
            self.element_len
        }
        fn get_data_type(&self) -> Box<dyn DataType> {
            (self.make_element)()
        }
    }

    #[test]
    fn undefined_usable_as_trait_object() {
        let u = MockUndefined1;
        let dyn_u: &dyn Undefined = &u;
        assert!(dyn_u.is_undefined_type());
        assert_eq!(dyn_u.get_length(), 1);
    }

    #[test]
    fn is_undefined_true_for_undefined_data_type() {
        assert!(is_undefined(Box::new(MockUndefined1)));
    }

    #[test]
    fn is_undefined_false_for_ordinary_data_type() {
        assert!(!is_undefined(Box::new(MockIntDataType)));
    }

    #[test]
    fn is_undefined_array_true_for_array_of_undefined_elements() {
        let arr = MockArrayOf {
            element_len: 1,
            make_element: || Box::new(MockUndefined1),
        };
        assert!(is_undefined_array(Box::new(arr)));

        let arr2 = MockArrayOf {
            element_len: 1,
            make_element: || Box::new(MockUndefined1),
        };
        assert!(is_undefined(Box::new(arr2)));
    }

    #[test]
    fn is_undefined_array_false_for_array_of_ordinary_elements() {
        let arr = MockArrayOf {
            element_len: 4,
            make_element: || Box::new(MockIntDataType),
        };
        assert!(!is_undefined_array(Box::new(arr)));
    }
}
