//! Port of `ghidra.program.model.data.WideCharDataType`, and the shared shape of
//! `WideChar16DataType`/`WideChar32DataType`.
//!
//! The three Java classes are independent `BuiltIn` subclasses that differ only in name, size
//! and value representation, so they are generated by [`wide_char_data_type!`]; each is its own
//! struct.

use crate::docking::settings::settings_definition::SettingsDefinition;
use crate::program::model::data::endian_settings_definition::EndianSettingsDefinition;
use crate::program::model::data::render_unicode_settings_definition::RenderUnicodeSettingsDefinition;
use crate::program::model::data::translation_settings_definition::TranslationSettingsDefinition;
use crate::program::model::mem::MemBuffer;

/// `WideCharDataType.DEFAULT_WIDE_CHAR_SETTINGS` (`ENDIAN, RENDER, TRANSLATION`).
pub(crate) fn default_wide_char_settings() -> Vec<Box<dyn SettingsDefinition>> {
    vec![
        Box::new(EndianSettingsDefinition::DEF),
        Box::new(RenderUnicodeSettingsDefinition::DEF),
        Box::new(TranslationSettingsDefinition::translation().clone()),
    ]
}

/// The `getDefaultLabelPrefix(MemBuffer, ...)` of the wide chars: `<prefix>_` and the char when it
/// is ASCII (`StringUtilities.isAsciiChar`), else its hex value and `h`; `??` when unreadable.
pub(crate) fn wide_char_label_prefix(prefix: &str, value: Option<i32>) -> String {
    match value {
        Some(val) if (0x20..=0x7f).contains(&val) => format!("{prefix}_{}", val as u8 as char),
        Some(val) => format!("{prefix}_{:x}h", val as u32),
        None => format!("{prefix}_??"),
    }
}

/// `buf.getVarLengthUnsignedInt(0, length)` narrowed to a Java `int`.
pub(crate) fn var_length_unsigned_int(buf: &dyn MemBuffer, length: i32) -> Option<i32> {
    match length {
        1 => buf.get_unsigned_byte(0).ok().map(|b| b as i32),
        2 => buf.get_short(0).ok().map(|v| v as u16 as i32),
        4 => buf.get_int(0).ok(),
        _ => None,
    }
}

/// Defines a wide char data type.
///
/// - `length`: a literal, or `wide_char_size` (the data organization's, with
///   `hasLanguageDependantLength()`).
/// - `value`: `wchar_t` (`Character` for 2 bytes, signed 32-bit `Scalar` for 4), `char16`
///   (`Character` from an unsigned short) or `scalar32` (signed 32-bit `Scalar`).
/// - `label_value`: how the label prefix reads its value: `var` (unsigned, of the length; Java
///   checks the length is 2 or 4), `ushort` or `int`.
/// - `charset`: `by_length`, or a fixed `CharsetInfoManager` name.
/// - `c_type_declaration`: `wide` (`getCTypeDeclaration(getName(), wideCharSize, true, org,
///   false)`) or `built_in` (the inherited `BuiltIn` declaration).
macro_rules! wide_char_data_type {
    (
        $(#[$meta:meta])*
        $ty:ident {
            name: $name:literal,
            length: $len:tt,
            description: $desc:literal,
            label_prefix: $prefix:literal,
            value: $value:ident,
            label_value: $label_value:ident,
            charset: $charset:tt,
            c_type_declaration: $ctd:ident,
        }
    ) => {
        $(#[$meta])*
        #[derive(Debug, Clone)]
        pub struct $ty {
            base: $crate::program::model::data::built_in::BuiltInBase,
        }

        impl $ty {
            /// Creates an instance bound to `dtm`'s data organization (Java: `new T(dtm)`; `None`
            /// is the no-argument constructor).
            pub fn new(dtm: Option<&dyn $crate::program::model::data::data_type_manager::DataTypeManager>) -> Self {
                Self { base: $crate::program::model::data::built_in::BuiltInBase::new(None, $name, dtm) }
            }

            fn c_type_declaration(
                &self,
                data_organization: Option<&$crate::program::model::data::data_organization_impl::DataOrganizationImpl>,
            ) -> Option<String> {
                $crate::program::model::data::wide_char_data_type::wide_char_data_type!(@ctd self, data_organization, $ctd)
            }

            fn built_in_settings_definitions(&self) -> Vec<Box<dyn $crate::docking::settings::settings_definition::SettingsDefinition>> {
                $crate::program::model::data::wide_char_data_type::default_wide_char_settings()
            }

            fn decompiler_display_name(&self, _language: $crate::program::model::lang::decompiler_language::DecompilerLanguage) -> String {
                $name.to_string()
            }
        }

        $crate::program::model::data::built_in::built_in_singleton!($ty);
        $crate::program::model::data::built_in::impl_built_in!($ty);

        impl std::fmt::Display for $ty {
            fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
                f.write_str(&$crate::program::model::data::data_type::DataType::get_display_name(self))
            }
        }

        impl $crate::program::model::data::data_type::DataType for $ty {
            $crate::program::model::data::built_in::built_in_data_type_methods!();

            fn has_language_dependant_length(&self) -> bool {
                $crate::program::model::data::wide_char_data_type::wide_char_data_type!(@lang_dep $len)
            }
            fn get_length(&self) -> i32 {
                $crate::program::model::data::wide_char_data_type::wide_char_data_type!(@length self, $len)
            }
            fn get_description(&self) -> String {
                $desc.to_string()
            }
            fn get_mnemonic(&self, _settings: &dyn $crate::docking::settings::settings::Settings) -> String {
                $name.to_string()
            }
            fn get_default_label_prefix(&self) -> Option<String> {
                Some($prefix.to_string())
            }
            fn get_default_label_prefix_for_data(
                &self,
                buf: &dyn $crate::program::model::mem::MemBuffer,
                _settings: &dyn $crate::docking::settings::settings::Settings,
                length: i32,
                _options: &dyn $crate::program::model::data::data_type_display_options::DataTypeDisplayOptions,
            ) -> Option<String> {
                Some($crate::program::model::data::wide_char_data_type::wide_char_data_type!(@label buf, length, $prefix, $label_value))
            }
            fn get_representation(
                &self,
                buf: &dyn $crate::program::model::mem::MemBuffer,
                settings: &dyn $crate::docking::settings::settings::Settings,
                _length: i32,
            ) -> String {
                $crate::program::model::data::string_data_instance::StringDataInstance::new(self, settings, buf, self.get_length())
                    .get_char_representation()
            }
            fn get_value(
                &self,
                buf: &dyn $crate::program::model::mem::MemBuffer,
                _settings: &dyn $crate::docking::settings::settings::Settings,
                _length: i32,
            ) -> Option<Box<dyn std::any::Any>> {
                $crate::program::model::data::wide_char_data_type::wide_char_data_type!(@value self, buf, $value)
            }
            fn get_value_class(&self, _settings: &dyn $crate::docking::settings::settings::Settings) -> Option<std::any::TypeId> {
                $crate::program::model::data::wide_char_data_type::wide_char_data_type!(@value_class self, $value)
            }
            fn is_encodable(&self) -> bool {
                true
            }
            fn encode_value(
                &self,
                value: &dyn std::any::Any,
                buf: &dyn $crate::program::model::mem::MemBuffer,
                settings: &dyn $crate::docking::settings::settings::Settings,
                _length: i32,
            ) -> Result<Vec<u8>, $crate::program::model::data::data_type_with_charset::DataTypeEncodeError> {
                $crate::program::model::data::data_type_with_charset::encode_character_value_from_any(self, value, buf, settings)
            }
            fn encode_representation(
                &self,
                repr: &str,
                buf: &dyn $crate::program::model::mem::MemBuffer,
                settings: &dyn $crate::docking::settings::settings::Settings,
                _length: i32,
            ) -> Result<Vec<u8>, $crate::program::model::data::data_type_with_charset::DataTypeEncodeError> {
                $crate::program::model::data::data_type_with_charset::DataTypeWithCharset::encode_character_representation(self, repr, buf, settings)
            }
            fn is_equivalent(&self, dt: &dyn $crate::program::model::data::data_type::DataType) -> bool {
                $crate::program::model::data::built_in::same_class(self, dt)
            }
            fn is_array_stringable_type(&self) -> bool {
                true
            }
            fn as_array_stringable(&self) -> Option<&dyn $crate::program::model::data::array_stringable::ArrayStringable> {
                Some(self)
            }
            fn into_array_stringable(self: Box<Self>) -> Option<Box<dyn $crate::program::model::data::array_stringable::ArrayStringable>> {
                Some(self)
            }
            fn as_data_type_with_charset(&self) -> Option<&dyn $crate::program::model::data::data_type_with_charset::DataTypeWithCharset> {
                Some(self)
            }
        }

        impl $crate::program::model::data::array_stringable::ArrayStringable for $ty {
            fn has_string_value(&self, _settings: &dyn $crate::docking::settings::settings::Settings) -> bool {
                true
            }
            fn get_array_default_label_prefix(
                &self,
                buf: &dyn $crate::program::model::mem::MemBuffer,
                settings: &dyn $crate::docking::settings::settings::Settings,
                len: i32,
                options: &dyn $crate::program::model::data::data_type_display_options::DataTypeDisplayOptions,
            ) -> Option<String> {
                use $crate::program::model::data::abstract_string_data_type::{
                    DEFAULT_UNICODE_ABBREV_PREFIX, DEFAULT_UNICODE_LABEL, DEFAULT_UNICODE_LABEL_PREFIX,
                };
                Some(
                    $crate::program::model::data::string_data_instance::StringDataInstance::new_element(self, settings, buf, len, true)
                        .get_label(&format!("{DEFAULT_UNICODE_ABBREV_PREFIX}_"), DEFAULT_UNICODE_LABEL_PREFIX, DEFAULT_UNICODE_LABEL, options),
                )
            }
            fn get_array_default_offcut_label_prefix(
                &self,
                buf: &dyn $crate::program::model::mem::MemBuffer,
                settings: &dyn $crate::docking::settings::settings::Settings,
                len: i32,
                options: &dyn $crate::program::model::data::data_type_display_options::DataTypeDisplayOptions,
                offcut_length: i32,
            ) -> Option<String> {
                use $crate::program::model::data::abstract_string_data_type::{
                    DEFAULT_UNICODE_ABBREV_PREFIX, DEFAULT_UNICODE_LABEL, DEFAULT_UNICODE_LABEL_PREFIX,
                };
                Some(
                    $crate::program::model::data::string_data_instance::StringDataInstance::new_element(self, settings, buf, len, true)
                        .get_offcut_label_string(
                            &format!("{DEFAULT_UNICODE_ABBREV_PREFIX}_"),
                            DEFAULT_UNICODE_LABEL_PREFIX,
                            DEFAULT_UNICODE_LABEL,
                            options,
                            offcut_length,
                        ),
                )
            }
        }

        impl $crate::program::model::data::data_type_with_charset::DataTypeWithCharset for $ty {
            fn get_charset_name(&self, _settings: &dyn $crate::docking::settings::settings::Settings) -> String {
                $crate::program::model::data::wide_char_data_type::wide_char_data_type!(@charset self, $charset)
            }
        }
    };

    (@lang_dep wide_char_size) => { true };
    (@lang_dep $len:literal) => { false };
    (@length $self:ident, wide_char_size) => { $self.base.data_organization().get_wide_char_size() };
    (@length $self:ident, $len:literal) => { $len };

    (@ctd $self:ident, $org:ident, wide) => {
        $org.map(|org| {
            $crate::program::model::data::built_in::BuiltIn::get_c_type_declaration_len(
                $self,
                &$crate::program::model::data::data_type::DataType::get_name($self),
                org.get_wide_char_size(),
                true,
                org,
                false,
            )
        })
    };
    (@ctd $self:ident, $org:ident, built_in) => {
        $crate::program::model::data::built_in::BuiltIn::built_in_get_c_type_declaration($self, $org)
    };

    (@label $buf:ident, $length:ident, $prefix:literal, var) => {
        if $length != 2 && $length != 4 {
            format!("{}_??", $prefix)
        } else {
            $crate::program::model::data::wide_char_data_type::wide_char_label_prefix(
                $prefix,
                $crate::program::model::data::wide_char_data_type::var_length_unsigned_int($buf, $length),
            )
        }
    };
    (@label $buf:ident, $length:ident, $prefix:literal, ushort) => {{
        let _ = $length;
        $crate::program::model::data::wide_char_data_type::wide_char_label_prefix(
            $prefix,
            $crate::program::model::data::wide_char_data_type::var_length_unsigned_int($buf, 2),
        )
    }};
    (@label $buf:ident, $length:ident, $prefix:literal, int) => {{
        let _ = $length;
        $crate::program::model::data::wide_char_data_type::wide_char_label_prefix($prefix, $buf.get_int(0).ok())
    }};

    (@value $self:ident, $buf:ident, wchar_t) => {
        match $crate::program::model::data::data_type::DataType::get_length($self) {
            2 => $buf.get_short(0).ok().map(|v| Box::new(v as u16) as Box<dyn std::any::Any>),
            4 => $buf.get_int(0).ok().map(|v| {
                Box::new($crate::program::model::scalar::Scalar::new_with_signedness(32, v as i64, true)) as Box<dyn std::any::Any>
            }),
            _ => None,
        }
    };
    (@value $self:ident, $buf:ident, char16) => {
        $buf.get_short(0).ok().map(|v| Box::new(v as u16) as Box<dyn std::any::Any>)
    };
    (@value $self:ident, $buf:ident, scalar32) => {
        $buf.get_int(0).ok().map(|v| {
            Box::new($crate::program::model::scalar::Scalar::new_with_signedness(32, v as i64, true)) as Box<dyn std::any::Any>
        })
    };

    (@value_class $self:ident, wchar_t) => {
        match $crate::program::model::data::data_type::DataType::get_length($self) {
            2 => Some(std::any::TypeId::of::<u16>()),
            4 => Some(std::any::TypeId::of::<$crate::program::model::scalar::Scalar>()),
            _ => None,
        }
    };
    (@value_class $self:ident, char16) => { Some(std::any::TypeId::of::<u16>()) };
    (@value_class $self:ident, scalar32) => { Some(std::any::TypeId::of::<$crate::program::model::scalar::Scalar>()) };

    (@charset $self:ident, by_length) => {
        match $crate::program::model::data::data_type::DataType::get_length($self) {
            2 => $crate::util::charset::charset_info_manager::UTF16.to_string(),
            4 => $crate::util::charset::charset_info_manager::UTF32.to_string(),
            _ => $crate::program::model::data::string_data_instance::DEFAULT_CHARSET_NAME.to_string(),
        }
    };
    (@charset $self:ident, $name:ident) => { $crate::util::charset::charset_info_manager::$name.to_string() };
}
pub(crate) use wide_char_data_type;

wide_char_data_type! {
    /// A wide character whose size is the compiler's `wchar_t` (the data organization's wide char
    /// size).
    ///
    /// Port of `ghidra.program.model.data.WideCharDataType`.
    WideCharDataType {
        name: "wchar_t",
        length: wide_char_size,
        description: "Wide-Character (compiler-specific size)",
        label_prefix: "WCHAR",
        value: wchar_t,
        label_value: var,
        charset: by_length,
        c_type_declaration: wide,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::Arc;
    use crate::program::model::data::array_stringable::ArrayStringable;
    use crate::program::model::data::built_in_data_type::BuiltInDataType;
    use crate::program::model::data::data_organization_impl::DataOrganizationImpl;
    use crate::program::model::data::data_type::DataType;
    use crate::program::model::data::data_type_display_options::DEFAULT;
    use crate::program::model::data::data_type_manager::DataTypeManager;
    use crate::program::model::data::data_type_with_charset::DataTypeWithCharset;
    use crate::program::model::data::string_data_instance::test_support::{mb, SettingsBuilder};
    use crate::program::model::scalar::Scalar;

    struct WideOrg(i32);
    impl DataTypeManager for WideOrg {
        fn get_data_organization(&self) -> Arc<DataOrganizationImpl> {
            let mut org = DataOrganizationImpl::get_default_organization(None);
            org.set_wide_char_size(self.0);
            Arc::new(org)
        }
    }

    #[test]
    fn java_constants() {
        let dt = WideCharDataType::instance();
        assert_eq!(dt.get_name(), "wchar_t");
        assert_eq!(dt.get_mnemonic(&SettingsBuilder::new()), "wchar_t");
        assert_eq!(dt.get_description(), "Wide-Character (compiler-specific size)");
        assert!(dt.has_language_dependant_length());
        assert_eq!(dt.get_default_label_prefix().as_deref(), Some("WCHAR"));
        // Mutability + ENDIAN, RENDER, TRANSLATION.
        assert_eq!(dt.get_settings_definitions().len(), 4);
        assert!(dt.has_string_value(&SettingsBuilder::new()));
        let org = dt.get_data_organization();
        let expected = format!("typedef {}    wchar_t;", org.get_integer_c_type_approximation(org.get_wide_char_size(), true));
        assert_eq!(dt.get_c_type_declaration(Some(&org)).as_deref(), Some(expected.as_str()));
    }

    #[test]
    fn size_follows_the_data_organization() {
        let w2 = WideCharDataType::new(Some(&WideOrg(2)));
        assert_eq!(w2.get_length(), 2);
        assert_eq!(w2.get_charset_name(&SettingsBuilder::new()), "UTF-16");
        let v = w2.get_value(&mb(false, &[0x34, 0x12]), &SettingsBuilder::new(), 2).unwrap();
        assert_eq!(*v.downcast_ref::<u16>().unwrap(), 0x1234);
        let w4 = WideCharDataType::new(Some(&WideOrg(4)));
        assert_eq!(w4.get_charset_name(&SettingsBuilder::new()), "UTF-32");
        let v = w4.get_value(&mb(false, &[0xFF, 0xFF, 0xFF, 0xFF]), &SettingsBuilder::new(), 4).unwrap();
        assert_eq!(v.downcast_ref::<Scalar>().unwrap().get_signed_value(), -1);
        assert_eq!(WideCharDataType::new(Some(&WideOrg(3))).get_charset_name(&SettingsBuilder::new()), "US-ASCII");
    }

    #[test]
    fn label_prefixes() {
        let dt = WideCharDataType::new(None);
        let s = SettingsBuilder::new();
        assert_eq!(dt.get_default_label_prefix_for_data(&mb(false, &[b'a', 0]), &s, 2, &DEFAULT).as_deref(), Some("WCHAR_a"));
        assert_eq!(dt.get_default_label_prefix_for_data(&mb(false, &[0x01, 0xcc]), &s, 2, &DEFAULT).as_deref(), Some("WCHAR_cc01h"));
        assert_eq!(dt.get_default_label_prefix_for_data(&mb(false, &[0x01]), &s, 3, &DEFAULT).as_deref(), Some("WCHAR_??"));
        assert_eq!(dt.get_default_label_prefix_for_data(&mb(false, &[]), &s, 2, &DEFAULT).as_deref(), Some("WCHAR_??"));
        let w2 = WideCharDataType::new(Some(&WideOrg(2)));
        let buf = mb(false, &[b'h', 0, b'i', 0, 0, 0]);
        assert_eq!(w2.get_array_string(&buf, &s, 6).as_deref(), Some("hi"));
        assert_eq!(w2.get_array_default_label_prefix(&buf, &s, 6, &DEFAULT).as_deref(), Some("u_hi"));
        assert_eq!(w2.get_array_default_offcut_label_prefix(&buf, &s, 6, &DEFAULT, 2).as_deref(), Some("u_i"));
    }
}
