//! An instrumented executor for the Symbolic Summarizer.
//!
//! Port of `ghidra.pcode.emu.symz3.SymZ3PcodeThreadExecutor`.
//!
//! This part is responsible for executing all the actual p-code operations generated by each
//! decoded instruction. Each thread in the emulator gets a distinct executor. It records every
//! stepped op against its thread, and on every [`OpCode::CBranch`](crate::program::model::pcode::OpCode::CBranch)
//! records the precondition the concrete (left) side's decision implies for the symbolic (right)
//! side.
//!
//! # Shape
//!
//! Java's class extends `DefaultPcodeThread.PcodeThreadExecutor` and overrides `stepOp` and
//! `executeConditionalBranch`, each doing its work and then calling `super`. Per the thread
//! executor's convention (see [`PcodeThreadExecutor::with_extension`]), this is the executor's
//! *extension*: a [`PcodeExecutorHooks`] whose [`before_step_op`](PcodeExecutorHooks::before_step_op)
//! and [`before_conditional_branch`](PcodeExecutorHooks::before_conditional_branch) run ahead of
//! the thread executor's own behavior, which is where Java's overrides call `super`. The
//! [`SymZ3PartsFactory`](crate::pcode::emu::symz3::sym_z3_parts_factory::SymZ3PartsFactory)
//! installs it from `createExecutor`.
//!
//! # Deviations from Java
//!
//! * **The thread.** Java reaches the thread's state through `getThread()`, the
//!   `SymZ3PcodeThread` under construction. The extension holds what it reads instead: the
//!   thread's name (as its records identify it), and a handle on the thread's state, typed by its
//!   delegates.
//! * **`Context`.** Java opens a `new Context()` per branch; the extension holds the context it was
//!   built with (see
//!   [`SymZ3PcodeArithmetic`](crate::pcode::emu::symz3::sym_z3_pcode_arithmetic)'s module docs).
//! * **Exceptions.** A `ConcretionError` from deciding the condition is wrapped in a
//!   [`LowlevelError`], exactly as the executor's own conditional branch does.
//!
//! [`PcodeThreadExecutor`]: crate::pcode::emu::default_pcode_thread::PcodeThreadExecutor
//! [`PcodeThreadExecutor::with_extension`]: crate::pcode::emu::default_pcode_thread::PcodeThreadExecutor::with_extension

use std::sync::{Arc, Mutex};

use crate::feature::seam_stubs::Z3Context;
use crate::feature::symz3::model::sym_value_z3::SymValueZ3;
use crate::pcode::emu::symz3::internal_sym_z3_records_execution::InternalSymZ3RecordsExecution;
use crate::pcode::emu::symz3::internal_sym_z3_records_preconditions::InternalSymZ3RecordsPreconditions;
use crate::pcode::emu::symz3::sym_z3_paired_pcode_executor_state::SymZ3PairedPcodeExecutorState;
use crate::pcode::emu::symz3::sym_z3_pcode_thread::SymZ3ThreadId;
use crate::pcode::emu::thread_pcode_executor_state::{SharedPcodeExecutorState, ThreadPcodeExecutorState};
use crate::pcode::error::lowlevel_error::LowlevelError;
use crate::pcode::exec::pcode_arithmetic::Purpose;
use crate::pcode::exec::pcode_executor::{PcodeExecutor, PcodeExecutorHooks};
use crate::pcode::exec::pcode_frame::PcodeFrame;
use crate::program::model::pcode::PcodeOp;

type Pair = (Vec<u8>, SymValueZ3);

/// The state of a SymZ3 thread: the emulator's paired memory (behind its shared handle) and the
/// thread's own paired registers.
pub type SymZ3ThreadState<S, L> = ThreadPcodeExecutorState<Pair, SharedPcodeExecutorState<S>, L>;

/// An instrumented executor for the Symbolic Summarizer: the extension of a SymZ3 thread's
/// [`PcodeThreadExecutor`]. See the module docs.
///
/// `S` and `L` are the thread's shared and local paired states.
pub struct SymZ3PcodeThreadExecutor<S, L>
where
    S: SymZ3PairedPcodeExecutorState + 'static,
    L: SymZ3PairedPcodeExecutorState + 'static,
{
    thread: SymZ3ThreadId,
    state: Arc<Mutex<SymZ3ThreadState<S, L>>>,
    ctx: Arc<dyn Z3Context>,
}

impl<S, L> SymZ3PcodeThreadExecutor<S, L>
where
    S: SymZ3PairedPcodeExecutorState + 'static,
    L: SymZ3PairedPcodeExecutorState + 'static,
{
    /// Create the executor for the given thread.
    ///
    /// Port of `SymZ3PcodeThreadExecutor(SymZ3PcodeThread)`: `thread` and `state` are what the
    /// overrides read off the thread, and `ctx` stands for Java's per-branch context. See the
    /// module docs.
    pub fn new(thread: SymZ3ThreadId, state: Arc<Mutex<SymZ3ThreadState<S, L>>>, ctx: Arc<dyn Z3Context>) -> Self {
        Self { thread, state, ctx }
    }

    /// Java: `getThread()`, as the thread's records identify it.
    pub fn get_thread(&self) -> &SymZ3ThreadId {
        &self.thread
    }

    /// Java: `getThread().addOp(op)`, recording against the emulator's shared symbolic state.
    fn add_op(&self, op: &PcodeOp) {
        let state = self.state.lock().expect("thread state lock poisoned");
        let thread = &self.thread;
        state
            .get_shared_state()
            .with_symbolic_mut(|symbolic| symbolic.add_op(thread, op.clone()));
    }

    /// Java: `getThread().addPrecondition(precondition)`, recording against the thread's local
    /// symbolic state.
    fn add_precondition(&self, precondition: String) {
        let mut state = self.state.lock().expect("thread state lock poisoned");
        state.get_local_state_mut().get_right_mut().add_precondition(precondition);
    }
}

impl<S, L> PcodeExecutorHooks<Pair> for SymZ3PcodeThreadExecutor<S, L>
where
    S: SymZ3PairedPcodeExecutorState + 'static,
    L: SymZ3PairedPcodeExecutorState + 'static,
{
    /// Port of the override `stepOp(PcodeOp, PcodeFrame, PcodeUseropLibrary)`: record the op
    /// against the thread, then step it (`super.stepOp`).
    fn before_step_op(
        &mut self,
        _executor: &PcodeExecutor<Pair>,
        op: &PcodeOp,
        _frame: &PcodeFrame,
    ) -> Result<(), LowlevelError> {
        self.add_op(op);
        Ok(())
    }

    /// Port of the override `executeConditionalBranch(PcodeOp, PcodeFrame)`.
    ///
    /// The decision is driven by the concrete (left) side of the emulator, but the equivalent
    /// precondition for the symbolic (right) side is still recorded: the condition itself if the
    /// branch is taken, its negation otherwise. The branch itself (`super`) follows.
    fn before_conditional_branch(
        &mut self,
        executor: &PcodeExecutor<Pair>,
        op: &PcodeOp,
        _frame: &PcodeFrame,
    ) -> Result<(), LowlevelError> {
        let cond_var = &op.inputs[1];
        let cond = executor
            .get_state()
            .lock()
            .expect("executor state lock poisoned")
            .get_var_varnode(cond_var, executor.get_reason());
        let ctx = &*self.ctx;
        let sym_cond = cond
            .1
            .get_bool_expr(ctx)
            .expect("Java: getBoolExpr(ctx) on a condition with no Z3 expression");
        let taken = executor
            .get_arithmetic()
            .is_true(&cond, Purpose::Condition)
            .map_err(|e| LowlevelError::with_cause(e.message().to_string(), e))?;
        let precondition = if taken {
            SymValueZ3::serialize_bool(ctx, &*sym_cond)
        }
        else {
            SymValueZ3::serialize_bool(ctx, &*ctx.mk_not(&*sym_cond))
        };
        self.add_precondition(precondition);
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use std::collections::HashMap;

    use super::*;
    use crate::pcode::emu::symz3::state::sym_z3_pcode_executor_state::SymZ3PcodeExecutorState;
    use crate::pcode::emu::symz3::sym_z3_pcode_arithmetic::testing::EvalCtx;
    use crate::pcode::emu::symz3::sym_z3_pcode_executor_state_piece::testing::test_language;
    use crate::pcode::emu::symz3::sym_z3_records_execution::SymZ3RecordsExecution;
    use crate::pcode::emu::symz3::sym_z3_records_preconditions::SymZ3RecordsPreconditions;
    use crate::pcode::exec::bytes_pcode_executor_state_piece::BytesPcodeExecutorStatePiece;
    use crate::pcode::exec::pcode_executor_state::PcodeExecutorState;
    use crate::pcode::exec::pcode_executor_state_piece::{PcodeExecutorStatePiece, Reason};
    use crate::pcode::exec::pcode_state_callbacks::{NoPcodeStateCallbacks, NONE};
    use crate::pcode::exec::pcode_userop_library::nil;
    use crate::program::model::address::{Address, AddressSpace};
    use crate::program::model::lang::language::Language;
    use crate::program::model::pcode::{OpCode, SequenceNumber, Varnode};

    type State = SymZ3PcodeExecutorState<NoPcodeStateCallbacks>;

    fn sym_state(language: &Arc<dyn Language>) -> State {
        let concrete = BytesPcodeExecutorStatePiece::new(Arc::clone(language), Arc::new(NONE));
        SymZ3PcodeExecutorState::new(Arc::clone(language), concrete, Arc::new(NONE), Arc::new(EvalCtx))
    }

    fn space(language: &Arc<dyn Language>, name: &str) -> Arc<AddressSpace> {
        language
            .get_address_factory()
            .get_all_address_spaces()
            .into_iter()
            .find(|s| s.name() == name)
            .unwrap()
    }

    struct Fixture {
        exec: SymZ3PcodeThreadExecutor<State, State>,
        executor: PcodeExecutor<Pair>,
        state: Arc<Mutex<SymZ3ThreadState<State, State>>>,
        code: Vec<PcodeOp>,
        language: Arc<dyn Language>,
    }

    /// A `CBRANCH` (relative +2) on a symbolic condition `x <u y` whose concrete value is `taken`,
    /// followed by two `COPY` filler ops.
    fn fixture(taken: bool) -> Fixture {
        let language = test_language();
        let unique = space(&language, "unique");
        let constant = space(&language, "const");
        let ram = space(&language, "ram");

        let state = Arc::new(Mutex::new(ThreadPcodeExecutorState::new(
            SharedPcodeExecutorState::new(sym_state(&language)),
            sym_state(&language),
        )));
        let arithmetic = state.lock().unwrap().get_arithmetic();
        let executor_state: Arc<Mutex<dyn PcodeExecutorState<Pair>>> = state.clone();
        let executor =
            PcodeExecutor::new(Arc::clone(&language), arithmetic, executor_state, Reason::ExecuteRead);

        let ctx = EvalCtx;
        let x = ctx.mk_bv_const("x", 32);
        let y = ctx.mk_bv_const("y", 32);
        let sym_cond = ctx.mk_bvult(&*x, &*y);
        let cond = Varnode::new(Address::new(Arc::clone(&unique), 0x80), 1);
        let value = (
            vec![taken as u8],
            SymValueZ3::from_bit_vec_and_bool(&ctx, &*ctx.mk_bv(taken as i64, 8), &*sym_cond),
        );
        state.lock().unwrap().set_var_varnode(&cond, &value);

        let seq = SequenceNumber::new(Address::new(Arc::clone(&ram), 0x1000), 0);
        let target = Varnode::new(Address::new(Arc::clone(&constant), 2), 4);
        let filler = |i| {
            PcodeOp::new(
                OpCode::Copy,
                SequenceNumber::new(Address::new(Arc::clone(&ram), 0x1000), i),
                vec![Varnode::new(Address::new(Arc::clone(&constant), 0), 1)],
                Some(Varnode::new(Address::new(Arc::clone(&unique), 0x90), 1)),
            )
        };
        let code = vec![PcodeOp::new(OpCode::CBranch, seq, vec![target, cond], None), filler(1), filler(2)];
        let exec = SymZ3PcodeThreadExecutor::new(
            SymZ3ThreadId::new("Threads[0]"),
            Arc::clone(&state),
            Arc::new(EvalCtx),
        );
        Fixture { exec, executor, state, code, language }
    }

    impl Fixture {
        fn step(&mut self, frame: &mut PcodeFrame) {
            let op = frame.next_op().clone();
            self.executor
                .step_op_hooked(&op, frame, &nil(), &mut self.exec)
                .expect("the op executes");
        }

        fn preconditions(&self) -> Vec<String> {
            self.state.lock().unwrap().get_local_state().get_right().get_preconditions()
        }

        fn ops(&self) -> Vec<crate::pcode::emu::symz3::sym_z3_records_execution::RecOp> {
            self.state.lock().unwrap().get_shared_state().with_symbolic(|s| s.get_ops())
        }
    }

    #[test]
    fn taken_branch_records_the_condition_and_branches() {
        let mut f = fixture(true);
        let mut frame = PcodeFrame::new(Arc::clone(&f.language), f.code.clone(), HashMap::new());
        f.step(&mut frame);
        // index advanced to 1 by next_op, then branch(+2) lands at 2.
        assert_eq!(frame.index(), 2);
        assert_eq!(f.preconditions(), vec!["B:bool;s;(bvult x y)".to_string()]);
    }

    #[test]
    fn untaken_branch_records_the_negated_condition_and_falls_through() {
        let mut f = fixture(false);
        let mut frame = PcodeFrame::new(Arc::clone(&f.language), f.code.clone(), HashMap::new());
        f.step(&mut frame);
        assert_eq!(frame.index(), 1);
        assert_eq!(f.preconditions(), vec!["B:bool;s;(not (bvult x y))".to_string()]);
    }

    #[test]
    fn every_stepped_op_is_recorded_against_the_thread() {
        let mut f = fixture(true);
        let mut frame = PcodeFrame::new(Arc::clone(&f.language), f.code[1..].to_vec(), HashMap::new());
        f.step(&mut frame);
        let ops = f.ops();
        assert_eq!(ops.len(), 1);
        assert_eq!(ops[0].op.opcode, OpCode::Copy);
        // Java: KeyPath.parse(thread.getName()).index().
        assert_eq!(ops[0].get_thread_name(), Some("0".to_string()));
        // No precondition for a non-branch op.
        assert!(f.preconditions().is_empty());
    }

    #[test]
    fn get_thread_is_the_constructor_thread() {
        let f = fixture(true);
        assert_eq!(f.exec.get_thread().get_name(), "Threads[0]");
    }
}
