//! Port of `ghidra.app.decompiler.DecompilerHighlighter`.
//!
//! The highlighter interface passed to clients of the `DecompilerHighlightService`.
//!
//! The expected workflow is:
//! 1. Create the highlighter via `DecompilerHighlightService`
//! 2. Clients request highlights via `apply_highlights()`
//! 3. Clients clear highlights via `clear_highlights()`
//! 4. The highlighter may be removed via `dispose()`

/// Trait for highlighting tokens in the decompiler output.
///
/// This is a port of the Java interface `ghidra.app.decompiler.DecompilerHighlighter`.
/// It provides a way to manage highlighting lifecycle and state within the decompiler.
pub trait DecompilerHighlighter: Send + Sync {
    /// Apply highlights to the decompiler view.
    ///
    /// Call this method when you wish to apply your highlights.
    fn apply_highlights(&mut self);

    /// Clear highlights from the decompiler view.
    ///
    /// Call this method when you wish to remove your highlights.
    fn clear_highlights(&mut self);

    /// Remove this highlighter from the decompiler.
    ///
    /// Call this method to clean up and remove your highlighter from the Decompiler.
    fn dispose(&mut self);

    /// Get the ID used by this highlighter.
    ///
    /// This will either be generated by this API or supplied by the client.
    ///
    /// # Returns
    ///
    /// The unique identifier for this highlighter.
    fn get_id(&self) -> &str;
}

#[cfg(test)]
mod tests {
    use super::*;

    // A simple concrete test implementation
    struct TestHighlighter {
        id: String,
        highlights_applied: bool,
    }

    impl TestHighlighter {
        fn new(id: String) -> Self {
            Self {
                id,
                highlights_applied: false,
            }
        }
    }

    impl DecompilerHighlighter for TestHighlighter {
        fn apply_highlights(&mut self) {
            self.highlights_applied = true;
        }

        fn clear_highlights(&mut self) {
            self.highlights_applied = false;
        }

        fn dispose(&mut self) {
            self.highlights_applied = false;
        }

        fn get_id(&self) -> &str {
            &self.id
        }
    }

    #[test]
    fn test_highlighter_lifecycle() {
        let mut highlighter = TestHighlighter::new("test_highlighter_1".to_string());
        assert_eq!(highlighter.get_id(), "test_highlighter_1");
        assert!(!highlighter.highlights_applied);

        highlighter.apply_highlights();
        assert!(highlighter.highlights_applied);

        highlighter.clear_highlights();
        assert!(!highlighter.highlights_applied);

        highlighter.dispose();
        assert!(!highlighter.highlights_applied);
    }

    #[test]
    fn test_highlighter_id() {
        let h1 = TestHighlighter::new("highlighter_1".to_string());
        let h2 = TestHighlighter::new("highlighter_2".to_string());

        assert_eq!(h1.get_id(), "highlighter_1");
        assert_eq!(h2.get_id(), "highlighter_2");
        assert_ne!(h1.get_id(), h2.get_id());
    }

    #[test]
    fn test_highlighter_as_trait_object() {
        let mut highlighter: Box<dyn DecompilerHighlighter> =
            Box::new(TestHighlighter::new("boxed_highlighter".to_string()));

        assert_eq!(highlighter.get_id(), "boxed_highlighter");
        highlighter.apply_highlights();
        highlighter.clear_highlights();
        highlighter.dispose();
    }
}
