use std::io::{self, Write};

use crate::generic::lsh::vector::idf_lookup::IdfLookup;
use crate::generic::lsh::vector::weight_factory::WeightFactory;
use crate::util::xml::spec_xml_utils;
use crate::util::xml::xml_element::XmlElement;
use crate::util::xml::xml_exception::XmlException;
use crate::util::xml::xml_pull_parser::XmlPullParser;

/// A single hash/weight pair within a sparse LSH vector.
///
/// Port of `generic.lsh.vector.HashEntry`.
#[derive(Debug, Default, Clone, Copy)]
pub struct HashEntry {
    /// A specific hash.
    hash: i32,
    /// Associated hash (term) frequency (minus one) within the vector.
    tf: i16,
    /// Inverse Document Frequency (a lookup index for "information" in this hash).
    idf: i16,
    /// The actual weight of this hash as a coefficient.
    coeff: f64,
}

impl PartialEq for HashEntry {
    fn eq(&self, other: &Self) -> bool {
        self.hash == other.hash && self.tf == other.tf
    }
}

impl Eq for HashEntry {}

impl std::hash::Hash for HashEntry {
    fn hash<H: std::hash::Hasher>(&self, state: &mut H) {
        self.hash.hash(state);
        self.tf.hash(state);
    }
}

impl HashEntry {
    /// Creates a zeroed `HashEntry`, for use with [`Self::restore_xml`].
    pub fn new() -> Self {
        Self::default()
    }

    /// Creates a hash entry with an explicit weight.
    ///
    /// `h` is the 32-bit hash, `tcnt` is the (optional) term-frequency count (set to 1 if
    /// not using), and `weight` is the weight associated with the hash.
    pub fn with_weight(h: i32, tcnt: i32, weight: f64) -> Self {
        Self {
            hash: h,
            tf: if tcnt > 63 { 63 } else { (tcnt - 1) as i16 },
            idf: 1,
            coeff: weight,
        }
    }

    /// Creates a hash entry with a weight calculated from its term frequency and idf
    /// frequency.
    ///
    /// `h` is the 32-bit hash, `tcnt` is the term frequency count, `dcnt` is the
    /// (normalized) idf frequency (should be generated by an [`IdfLookup`]), and `w` is the
    /// factory used to generate the final weight.
    pub fn with_factory(h: i32, tcnt: i32, dcnt: i32, w: &WeightFactory) -> Self {
        let tf = if tcnt > 63 { 63 } else { (tcnt - 1) as i16 };
        let idf = if dcnt > 511 { 511 } else { dcnt as i16 };
        let coeff = w.get_coeff(idf as usize, tf as usize);
        Self { hash: h, tf, idf, coeff }
    }

    pub fn get_hash(&self) -> i32 {
        self.hash
    }

    pub fn get_tf(&self) -> i16 {
        self.tf + 1
    }

    pub fn get_idf(&self) -> i16 {
        self.idf
    }

    pub fn get_coeff(&self) -> f64 {
        self.coeff
    }

    /// Serializes this object as XML to a `Writer`.
    pub fn save_xml<W: Write>(&self, fwrite: &mut W) -> io::Result<()> {
        let mut buf = String::new();
        buf.push_str(" <hash");
        if self.tf != 0 {
            spec_xml_utils::encode_signed_integer_attribute(&mut buf, "tf", (self.tf + 1) as i64);
        }
        buf.push('>');
        buf.push_str(&spec_xml_utils::encode_unsigned_integer((self.hash as i64) & 0xffff_ffff));
        buf.push_str("</hash>\n");
        write!(fwrite, "{}", buf)
    }

    pub fn save_sql(&self, buf: &mut String) {
        buf.push_str(&format!("{:x}", self.tf + 1));
        buf.push(':');
        buf.push_str(&format!("{:x}", self.hash));
    }

    /// Builds (deserializes) this object from an XML stream.
    pub(crate) fn restore_xml<P: XmlPullParser>(
        &mut self,
        parser: &mut P,
        w: &WeightFactory,
    ) -> Result<(), XmlException> {
        self.tf = 0;
        self.idf = 0;
        let el = parser.start(&["hash"])?;
        if let Some(str_) = el.get_attribute("tf") {
            self.tf = spec_xml_utils::decode_int(Some(&str_)) as i16;
            self.tf -= 1;
        }
        if let Some(str_) = el.get_attribute("idf") {
            self.idf = spec_xml_utils::decode_int(Some(&str_)) as i16;
        }
        self.hash = spec_xml_utils::decode_int(Some(parser.end()?.get_text()));
        self.coeff = w.get_coeff(self.idf as usize, self.tf as usize);
        Ok(())
    }

    /// Restores entry but recalculates the idf.
    ///
    /// `parser` is the xml state, `w` is the weight factory used to calculate the
    /// coefficient with, and `lookup` recalculates the idf.
    pub(crate) fn restore_xml_with_lookup<P: XmlPullParser>(
        &mut self,
        parser: &mut P,
        w: &WeightFactory,
        lookup: &IdfLookup,
    ) -> Result<(), XmlException> {
        self.tf = 0;
        let el = parser.start(&["hash"])?;
        if let Some(str_) = el.get_attribute("tf") {
            self.tf = spec_xml_utils::decode_int(Some(&str_)) as i16;
            self.tf -= 1;
        }
        self.hash = spec_xml_utils::decode_int(Some(parser.end()?.get_text()));
        self.idf = lookup.get_count(self.hash) as i16;
        self.coeff = w.get_coeff(self.idf as usize, self.tf as usize);
        Ok(())
    }

    fn parse_hash(sql: &str, start: usize) -> io::Result<(i32, usize)> {
        let bytes = sql.as_bytes();
        let mut hash: i32 = 0;
        let mut pos = start;
        loop {
            if pos >= bytes.len() {
                return Err(io::Error::new(
                    io::ErrorKind::InvalidData,
                    "Parsing hashentry with no terminator",
                ));
            }
            let digit = match bytes[pos] {
                tok @ b'0'..=b'9' => tok - b'0',
                tok @ b'A'..=b'F' => tok - b'A' + 10,
                tok @ b'a'..=b'f' => tok - b'a' + 10,
                _ => break,
            };
            hash = (hash << 4) + digit as i32;
            pos += 1;
        }
        Ok((hash, pos))
    }

    pub fn restore_sql(
        &mut self,
        sql: &str,
        start: usize,
        w: &WeightFactory,
        lookup: &IdfLookup,
    ) -> io::Result<usize> {
        let (parsed, mut pos) = Self::parse_hash(sql, start)?;
        self.hash = parsed;
        if self.hash == 0 || sql.as_bytes().get(pos) != Some(&b':') {
            return Err(io::Error::new(io::ErrorKind::InvalidData, "Error parsing HashEntry"));
        }
        self.tf = (self.hash - 1) as i16;
        let (parsed, next_pos) = Self::parse_hash(sql, pos + 1)?;
        self.hash = parsed;
        pos = next_pos;
        self.idf = lookup.get_count(self.hash) as i16;
        self.coeff = w.get_coeff(self.idf as usize, self.tf as usize);
        Ok(pos)
    }

    pub fn restore_base64(
        &mut self,
        buffer: &[char],
        offset: usize,
        decoder: &[i32],
        w: &WeightFactory,
        lookup: &IdfLookup,
    ) -> bool {
        // Value between 0 and 63.
        self.tf = decoder[buffer[offset] as usize] as i16;
        if self.tf < 0 {
            return false; // Check for bad character
        }
        let mut val = decoder[buffer[offset + 1] as usize];
        val <<= 6;
        val |= decoder[buffer[offset + 2] as usize];
        val <<= 6;
        val |= decoder[buffer[offset + 3] as usize];
        val <<= 6;
        val |= decoder[buffer[offset + 4] as usize];
        val <<= 6;
        val |= decoder[buffer[offset + 5] as usize];
        if val < 0 {
            return false; // Only 30-bits read so far, should be positive
        }
        let rem1 = decoder[buffer[offset + 6] as usize];
        val <<= 2;
        self.hash = val | (rem1 & 3); // Final 2 bits of 32-bit hash
        if rem1 > 3 {
            return false; // Remaining 4-bits should be zero
        }
        self.idf = lookup.get_count(self.hash) as i16;
        self.coeff = w.get_coeff(self.idf as usize, self.tf as usize);
        true
    }

    pub fn save_base64(&self, buffer: &mut [char], offset: usize, encoder: &[char]) {
        buffer[offset] = encoder[self.tf as usize];
        let mut val = self.hash as u32;
        buffer[offset + 6] = encoder[(val & 3) as usize]; // Final 2 bits
        val >>= 2;
        buffer[offset + 5] = encoder[(val & 0x3f) as usize];
        val >>= 6;
        buffer[offset + 4] = encoder[(val & 0x3f) as usize];
        val >>= 6;
        buffer[offset + 3] = encoder[(val & 0x3f) as usize];
        val >>= 6;
        buffer[offset + 2] = encoder[(val & 0x3f) as usize];
        val >>= 6;
        buffer[offset + 1] = encoder[(val & 0x3f) as usize];
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const BASE64_ENCODER: &[char] = &[
        'A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M', 'N', 'O', 'P', 'Q', 'R',
        'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j',
        'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '0', '1',
        '2', '3', '4', '5', '6', '7', '8', '9', '+', '/',
    ];

    fn base64_decoder() -> [i32; 128] {
        let mut decoder = [-1i32; 128];
        for (i, &c) in BASE64_ENCODER.iter().enumerate() {
            decoder[c as usize] = i as i32;
        }
        decoder
    }

    #[test]
    fn with_weight_sets_fields() {
        let entry = HashEntry::with_weight(0x1234, 5, 2.5);
        assert_eq!(entry.get_hash(), 0x1234);
        assert_eq!(entry.get_tf(), 5);
        assert_eq!(entry.get_idf(), 1);
        assert_eq!(entry.get_coeff(), 2.5);
    }

    #[test]
    fn with_weight_clamps_term_frequency() {
        let entry = HashEntry::with_weight(1, 1000, 1.0);
        assert_eq!(entry.get_tf(), 64); // tf field clamped to 63, getter adds 1 back
    }

    #[test]
    fn with_factory_computes_coeff() {
        let mut w = WeightFactory::new();
        w.set_logarithmic_tf_weights();
        let entry = HashEntry::with_factory(7, 2, 600, &w);
        assert_eq!(entry.get_idf(), 511); // clamped
        assert_eq!(entry.get_tf(), 2);
        assert_eq!(entry.get_coeff(), w.get_coeff(511, 1));
    }

    #[test]
    fn equality_ignores_idf_and_coeff() {
        let a = HashEntry::with_weight(10, 3, 1.0);
        let b = HashEntry::with_weight(10, 3, 999.0);
        assert_eq!(a, b);
    }

    #[test]
    fn equality_differs_on_hash_or_tf() {
        let base = HashEntry::with_weight(10, 3, 1.0);
        assert_ne!(base, HashEntry::with_weight(11, 3, 1.0));
        assert_ne!(base, HashEntry::with_weight(10, 4, 1.0));
    }

    #[test]
    fn save_sql_round_trips_through_restore_sql() {
        let w = WeightFactory::new();
        let lookup = IdfLookup::new();
        let original = HashEntry::with_weight(0xdead, 4, 1.0);
        let mut buf = String::new();
        original.save_sql(&mut buf);
        assert_eq!(buf, "4:dead");

        // `restore_sql` requires a non-hex terminator after the hash (in the real
        // LSHCosineVector SQL format entries are separated by ',' and terminated by ')').
        // Append one so parsing has an end delimiter, mirroring the vector encoding.
        buf.push(')');

        let mut restored = HashEntry::new();
        let end = restored.restore_sql(&buf, 0, &w, &lookup).unwrap();
        assert_eq!(end, buf.len() - 1); // stops at the ')' terminator
        assert_eq!(restored.get_hash(), 0xdead);
        assert_eq!(restored.get_tf(), 4);
    }

    #[test]
    fn restore_sql_rejects_missing_terminator() {
        let w = WeightFactory::new();
        let lookup = IdfLookup::new();
        let mut entry = HashEntry::new();
        assert!(entry.restore_sql("dead", 0, &w, &lookup).is_err());
    }

    #[test]
    fn restore_sql_rejects_missing_colon() {
        let w = WeightFactory::new();
        let lookup = IdfLookup::new();
        let mut entry = HashEntry::new();
        assert!(entry.restore_sql("dead-beef", 0, &w, &lookup).is_err());
    }

    #[test]
    fn save_base64_round_trips_through_restore_base64() {
        let encoder = BASE64_ENCODER;
        let decoder = base64_decoder();
        let w = WeightFactory::new();
        let lookup = IdfLookup::new();

        let original = HashEntry::with_weight(0x1234_5678, 10, 1.0);
        let mut buffer = vec!['\0'; 7];
        original.save_base64(&mut buffer, 0, encoder);

        let mut restored = HashEntry::new();
        let ok = restored.restore_base64(&buffer, 0, &decoder, &w, &lookup);
        assert!(ok);
        assert_eq!(restored.get_hash(), 0x1234_5678);
        assert_eq!(restored.get_tf(), 10);
    }

    #[test]
    fn restore_base64_rejects_bad_tf_character() {
        let decoder = base64_decoder();
        let w = WeightFactory::new();
        let lookup = IdfLookup::new();
        let mut entry = HashEntry::new();
        let buffer = vec!['!', 'A', 'A', 'A', 'A', 'A', 'A'];
        assert!(!entry.restore_base64(&buffer, 0, &decoder, &w, &lookup));
    }

    #[test]
    fn save_xml_omits_tf_attribute_when_zero() {
        let entry = HashEntry::with_weight(5, 1, 1.0); // tcnt=1 -> tf field 0
        let mut buf = Vec::new();
        entry.save_xml(&mut buf).unwrap();
        let text = String::from_utf8(buf).unwrap();
        assert_eq!(text, " <hash>0x5</hash>\n");
    }

    #[test]
    fn save_xml_includes_tf_attribute_when_nonzero() {
        let entry = HashEntry::with_weight(5, 3, 1.0); // tcnt=3 -> tf field 2
        let mut buf = Vec::new();
        entry.save_xml(&mut buf).unwrap();
        let text = String::from_utf8(buf).unwrap();
        assert_eq!(text, " <hash tf=\"3\">0x5</hash>\n");
    }
}
